### ISSUE TITLE
Internal PTB error related to Screen text settings (OSX 10.8.5, Matlab2013a)

### ISSUE THREAD

**Issue by jbarredo** [Psychtoolbox-3/Psychtoolbox-3#180]
I updated both my OS and PTB yesterday and the screen function now crashes with the following message:

INTERNAL PSYCHTOOLBOX ERROR
    error:                PsychError_internal
    general description:  Unspecified error, probably a Psychtoolbox bug
    specific description: Failed to initialize the window record because the default font for DrawText, Geneva, was not found.
    module name:          Screen
    subfunction call:     OpenWindow
    file name:            OSX/Screen/PsychWindowTextGlue.c
    function name:        PsychInitTextRecordSettings
    line number:          66

I've double-checked that the font file exists, it does. This warning is also thrown before the crash:

PTB-INFO: Connection to Psychtoolbox kernel support driver instance #0 (Revision 0) established.
PTB-INFO: Disconnecting from kernel driver instance #0 for detected Intel GPU for safety reasons. setenv('PSYCH_ALLOW_DANGEROUS', '1') to override.

Thanks,
Jennifer

**Comment by montyhugh** [comment]
I'm having this same issue. Changing the default font doesn't work and reinstalling doesn't work. I didn't have this problem until I switched from a 2014 version of MATLAB to R2015b.

**Comment by kleinerm** [comment]
OSX versions older than 10.11 El Crapitan are no longer officially supported and i don't test against them anymore. Assuming you use the latest El Crapitan, and latest PTB beta from the v3.0.12 series, make sure to read "help DrawTextPlugin" for potential troubleshooting instructions. There are no other known problems with text rendering on OSX.
