### ISSUE TITLE
Psychtoolbox download problem

### ISSUE THREAD

**Issue by sudhasharma529** [Psychtoolbox-3/Psychtoolbox-3#220]
Dear Mario
I am trying to install Psychtoolbox -3 but each time it gives the following error..

svn: E730061: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox' 
svn: E730061: Error running context: No connection could be made because the target machine actively refused it.  
Sorry, the download command "CHECKOUT" failed with error code 1: 
svn: E730061: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox'
svn: E730061: Error running context: No connection could be made because the target machine actively refused it.

Can you please tell me how to sort this out as soon as possible.

Regards

**Comment by Threadman** [comment]
Hello, 

I have the same problem and I tried to find a solution but wasn't able to.
I wonder how you solved it as it is closed with no reply here.

**Comment by LornaUofT** [comment]
Hi, I am having a similar error today when I was trying to run the DownloadPsychtoolbox.m 
I instaled the last MacOs version (mojave). Is that an issue with the last version of Psychtoolbox.
this is the error that I have when trying to instal:
svn: E175002: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox'
svn: E175002: OPTIONS of 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox': SSL handshake failed: SSL error: tlsv1 alert protocol version (https://github.com)

Thanks in advance.

**Comment by kleinerm** [comment]
Get a new DownloadPsychtoolbox installer from our website. It will try to
pick a non-outdated version of the svn executable on your system. Whatever
your current DownloadPsychtoolbox.m picks is totally outdated and gets
rejected by GitHub for security reasons.

I should also mention that macOS Mojave is not officially supported with
the current or soon to be released PTB beta. Testing it on the only machine
i have left for testing with Mojave - a macMini 2012 - showed almost
catastrophically bad performance wrt. visual stimulation. Both PTB internal
timing and consistency checks by use of the PsychtoolboxKernelDriver and
external measurement equipment (a Datapixx) reported completely broken
visual timing on Intel graphics. There are currently no known workarounds
or fixes for these problems.

Upgrading to Linux is strongly recommended.
-mario
