### ISSUE TITLE
PsychtoolboxVersion fails

### ISSUE THREAD

**Issue by swilmet** [Psychtoolbox-3/Psychtoolbox-3#228]
I've just installed the Psychtoolbox beta, from SVN, and I get this error when running PsychtoolboxVersion:

??? Index exceeds matrix dimensions.

Error in ==> PsychtoolboxVersion at 144
                Psychtoolbox.version.revision=cvv(2);

There was no errors during the installation, except a problem with the libz.so.1 shipped with Matlab, saying that version information was not available.

My system:
Fedora 21, 64 bits
Matlab 7.6 (R2008a)

Maybe the Matlab version is too old?

**Comment by dcnieho** [comment]
How did you install psychtoolbox? Using the provided scripts? Your matlab
version is indeed too old, believe that 2010a is the oldest still supported
(if not even a newer one).

Best,
Dee

**Comment by swilmet** [comment]
Yes, the Subversion based Linux installation, with DownloadPsychtoolbox.m.

I'll try to get a newer Matlab version (Octave is unfortunately not used where I work).

**Comment by swilmet** [comment]
It works fine with Matlab R2011b, so I close the bug. Thanks.

**Comment by swilmet** [comment]
Note that on this page:
http://psychtoolbox.org/requirements/

the Matlab requirement is "7.4 R2007a or later", so it should be updated (at least for Linux).
