### ISSUE TITLE
Timing delay created by send TTL with pp

### ISSUE THREAD

**Issue by facelaboratory** [Psychtoolbox-3/Psychtoolbox-3#231]
Hello,

I am running Psychtoolbox on a Linux set up and am seeing timing delays of up to 200ms when sending a TTL signal with the pp function.  When the send TTL command is commented out the timing of the experiment is fine.  Does anyone know what could be causing this problem or if there would be a better alternative to the pp function?

Thank you.

**Comment by iandol** [comment]
PTB uses pnet -- Psychtoolbox/PsychHardware/iViewXToolbox/tcp_udp_ip/pnet which works as expected at least on OS X, no idea what the pp function is, I don't have it in my PTB install...

**Comment by facelaboratory** [comment]
Thanks for the suggestion but from what I have read pnet does not yet support sending data through the parallel port which is required for the set up I am using.  pp is one of the two functions that were recommended to use with a Linux setup.  I can not obtain the second option as the link is dead. (Old Psychtoolbox website).

**Comment by iandol** [comment]
Ah, sorry for my brain fart actually (TTL ~= TCP which was my augmented reality read in your issue). As I don't use Linux I don't know what the best options are currently (I assume your pp command is separate to PTB as I can't find it in my matlab path at least). Yes, I see the old forum links are dead from this page too:

http://old.psychtoolbox.org/OldPsychtoolbox/wikka.php?wakka=FaqTTLTriggerOSXLinux

That page at least suggests some other options (I've tried USB>serial, Labjack and Arduino for TTL triggers before settling on the DataPixx for the high fidelity timing). But I'm sure there are working parallel port interfaces still working of Linux, 

https://groups.yahoo.com/neo/groups/psychtoolbox/conversations/topics/17923

that thread has info on pp and mario's ParportTTL which uses a UDP packet to a little server running alongside matlab.

https://groups.yahoo.com/neo/groups/psychtoolbox/search/messages?query=parallel%20port%20linux

perhaps post to the forums?

**Comment by kleinerm** [comment]
Closing as it seems to have been resolved on the forum:

https://groups.yahoo.com/neo/groups/PSYCHTOOLBOX/conversations/messages/18650

To the original poster. Please give feedback on the forum if it was actually resolved for you.
