### ISSUE TITLE
Channel mapping in PsychPortAudio on MacOSX

### ISSUE THREAD

**Issue by PLu55** [Psychtoolbox-3/Psychtoolbox-3#232]
It could not select the proper channels I need to play a sound . When I try to select which audio channels to send signals to I get this strange message: "PTB-WARNING: Provided 'selectchannels' channel mapping is ignored because this is not MS-Windows running on an ASIO enabled sound device." It seams like I have to send empty signals to all channels starting with channel zero and up to the target channel. Now my sound card has 192 channels so it is not managable to do this, why can I not just use the channel mapping as in Windows?

Regads
Peter Lundén

**Comment by kleinerm** [comment]
What is strange about this message? It clearly says this is not supported on OSX. Channel mapping is not implemented in our PortAudio backend for OSX or Linux at the moment. It wasn't possible at the time 'selectchannels' was implemented for Windows. Now a couple of years later it would be possible to implement by rebasing our code to the latest versions of PortAudio and reapplying and retesting all the enhancements i made on top of it, but It would be a bit of work implementing this on OSX and Linux, and even more work revalidating the driver after the changes to make sure they don't break anything else.

However you can use PsychPortAudio slave devices to work around this, so your code works cross-platform. BasicAMAndMixScheduleDemo.m shows how to open a master device with in your case up to 192 channels and then attach as many  single- or multi-channel audio slave devices to the target channels of the master device you actually want to use - a sophisticated mixer essentially, with independent control over content, timing and schedule of each virtual slave device. Internally the driver will output zeros on all "unused" channels and only mix your slave device sound into the target channel. Not quite as efficient as the 'selectchannels' method on Windows + ASIO, but likely still efficient enough.

-mario

**Comment by kleinerm** [comment]
Poster doesn't respond in reasonable time, and workaround exists. Closing.
