### ISSUE TITLE
Window Rects with a Non-fullscreen Window on a HiDPI display

### ISSUE THREAD

**Issue by iandol** [Psychtoolbox-3/Psychtoolbox-3#237]
If we use MouseTraceDemo.m as an example:

https://github.com/kleinerm/Psychtoolbox-3/blob/master/Psychtoolbox/PsychDemos/MouseTraceDemo.m#L38

By default everything works fine, panelfitter returns the correct Rect on line 38 (on this rMBP it is [0 0 1440 900]) and mouse drawing occurs under the cursor as expected. But if we change the OpenWindow on line 38 to open a non-fullscreen window:

```matlab
 [theWindow,theRect] = Screen('OpenWindow', whichScreen, 0, [0 0 720 450]);
```
theRect returned is still [0 0 1440 900], and therefore the co-ordinates are now out and drawing occurs in the wrong place. The same happens with PsychImaging, and Screen('WindowSize') and Screen('Rect') also return the screen dimensions not the actual window dimensions. Note this is with kPsychNeedRetinaResolution disabled, just basic (scaled) drawing. I think non-fullscreen windows normally return rects the size of the window, rather than the screen?

**Comment by kleinerm** [comment]
I've committed a source code fix which may fix this, but no rebuilt Screen mex file - not booted on OSX atm.
Do you know how to build PTB from source? Otherwise it will have to wait until i feel masochistic enough for a trip into OSX. I can't test Retina displays for real, only in simulation, due to lack of hardware.

**Comment by kleinerm** [comment]
Actually there's a workaround that should have the same effect as the committed but untested fix:

If you specify the optional 'clientRect' parameter to Screen('OpenWindow') and set it identical to the 'rect' parameter, then i think that should have the same effect.

**Comment by iandol** [comment]
Yep, clientRect fixes this, will have a go at rebuilding (I haven't really been PTBing for a while so forgot how to, but sure I'll find the info) later today and will close this if the rebuilt screen also fixes this...

**Comment by kleinerm** [comment]
Ok, had to reboot, so i rebuilt Screen for OSX - in my master branch.

If you still have access to a AMD HD-5000 gpu it would be useful to test run this version of Screen on it as well and report if anything unusual happens.

**Comment by iandol** [comment]
Yes, rebuilt screen works too. I tried rebuilding, but suspect I need the GStreamer SDK, I got a failure to find gst/gst.h
