### ISSUE TITLE
obj file reader no longer works for some files

### ISSUE THREAD

**Issue by pjbh** [Psychtoolbox-3/Psychtoolbox-3#238]
Some changes made to LoadObjFile result in it no longer working for some of our obj files, it says index exceeds matrix dimension at line 196.  It makes an incorrect assumption about the number of entries for each face definition, probably because some of our objs are naughty!  
f 1271/674/ 601/769/ 293/727/

There used to be the following code:
                    if findstr(Lyn,'/ ') %cobbled obj, no normals given
                        f1=sscanf(Lyn,'%f/%f/');
                        f1=f1([1 3 5 2 4 6 1 3 5]);
                    else
When I add that back in, it falls over at what is then line 503, which I kludged by adding an if statement:
    if size(Normals,2)>0
        objobject{meshcount}.normals = Normals(:, 1:vnum);  %#ok<AGROW>
    end

**Comment by kleinerm** [comment]
If you think you found a proper fix for it, please send a GitHub pull request.

thanks,
-mario

**Comment by pjbh** [comment]
Hi Mario.  I’m not sure it is a proper fix, and I have no idea what a GitHub pull request is!  I think it needs something else to say that the normal list is null, at least, not sure what other effects there might be.

Sorry, Peter

**Comment by kleinerm** [comment]
You could just e-mail me your file if it is up to date with our latest 3.0.12 releases.
But have you tried setting the optional 'preparse' parameter to zero? Maybe that already fixes the problem?

**Comment by kleinerm** [comment]
Closing due to lack of response.
