### ISSUE TITLE
No Euro symbol (€) with Screen('DrawText')

### ISSUE THREAD

**Issue by Price-Lab** [Psychtoolbox-3/Psychtoolbox-3#242]
I have just upgraded from Psychtoolbox-2 to Psychtoolbox-3 and Euro symbol is no longer supported.
It has worked without any problem under Psychtoolbox-2 but no matter what I try under Psychtoolbox-3 the 'DrawText' subfunction won't draw €. It does not crash but just draws nothing instead of €. I have tried different ways of drawing the text string containing the symbol including changing the string to uint8 with no success. I have tried to draw randomly some other symbols from ASCII tables and they work just fine. 

My version of Psychtoolbox is: 
3.0.12 - Flavor: beta - Corresponds to SVN Revision 6001

Please help

Mark

**Comment by dcnieho** [comment]
Does the font you use include the euro symbol?

**Comment by kleinerm** [comment]
Works on Linux if i just insert unicodetext = hex2dec('20ac'); into DrawHIghQualityUnicodeTextDemo.m
If it doesn't work if you encode the text string as double()'s this way, as explained in help DrawTextEncodingLocaleSettings, then your font probably doesn't support the euro symbol.

**Comment by Price-Lab** [comment]
Yes it does include the euro symbol. I have tried to print it by supplying ascii code as well. Tried different fonts. I tried to print other symbols such as £ $ & ¥ + many others and they all display fine. The only symbol I can’t get to display is €. It always replaces € with nothing.

**Comment by danae1968** [comment]
For me it worked when I turned the whole string that I added in DrawText into double. For example:
    money=2;
    msgHard = double(sprintf('for €%.2f',money));
    Screen('DrawText',wPtr, msgHard)
