### ISSUE TITLE
KbWait "forWhat" bug

### ISSUE THREAD

**Issue by TaylorHanayik** [Psychtoolbox-3/Psychtoolbox-3#247]
I've found a small bug in KbWait that occurs when you pass KbWait an empty "forWhat" variable, such as when you wish to call it like so: 

```
deviceN = -1;
forWhat = [];
untilTime = GetSecs+1.25;
[secs, keycode] = KbWait(deviceN, forWhat, untilTime);
```

I know it's not a huge issue, but I wanted to throw it out there. I modified my copy of KbWait by putting in an isempty check after nargin checking (see code below)

```
if nargin < 2
    forWhat = 0;
end
if isempty(forWhat)
    forWhat = 0;
end
```

**Comment by kleinerm** [comment]
Thanks for the suggestion. Fixed in my master branch, will be part of the next PTB beta.
Unfortunately it just missed a minor beta update a few minutes ago, so may take a bit.
