### ISSUE TITLE
the psychtoolbox doesn't report the right number of dispalys

### ISSUE THREAD

**Issue by kirikouestpetit** [Psychtoolbox-3/Psychtoolbox-3#252]
Hello
I have an issue with the function Screen('Screens'), it returns 0 whereas I have 2 monitors connected, even if I use the physicalDisplays flag. Also if I try to force Screen('OpenWindow',1) I get a crash.
The only workaround I found is to use the 'rect' argument to fit my second monitor size but I am scared that it might mess with frame accuracy.
I get this problem on linux with PTB3
Does anyone knows how I can make the psychtoolbox understand there are actually 2 monitors connected please ?
thanks everyone

**Comment by kirikouestpetit** [comment]
Solved ! 
in fact it was a x11 problem, the two monitors have to be set as two different xwindows in order for the psychtoolbox to interpret them as different screens

**Comment by kleinerm** [comment]
You mean different X-Screens? Yes, you need to create a /etc/X11/xorg.conf file which uses the "ZaphodHeads" parameter to create two separate x-screens for the two monitors, then PTB will report and use them as separate screens - this provides proper timing. Depending on your graphics driver, e.g., NVidia proprietary driver, the setup GUI will allow you to do that with a few mouse clicks.

The Psychtoolbox/PsychHardware/LinuxX11ExampleXorgConfs/ folder contains example xorg.conf files for different display configurations, which can be used as templates for your specific setup. Searching the Psychtoolbox user forum for "ZaphodHeads" will also show a couple of relevant posts.
