### ISSUE TITLE
Rect functions cleanup

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#253]
Hi Mario, others,

I was just profiling some code in the critical path and found that some of the Rect functions are less efficient than they can be. Its partially because of all the RectTop etc calls in there. I see those four functions as convenient for users, but not needed for internal code as they'll never change.
Also calls to PsychNumel and such should just be replaced with numel and such by now, as all platforms currently supported have functions like numel (and assert). (NB: I'm not suggesting removing those functions from PTB, just replacing their internal use).

Also, further gains can be had by vectorizing more. E.g., in OffsetRect, 

        newRect(RectTop) = oldRect(RectTop) + y; 
        newRect(RectBottom) = oldRect(RectBottom) + y; 
        newRect(RectLeft) = oldRect(RectLeft) + x; 
        newRect(RectRight) = oldRect(RectRight) + x; 

can simply be replaced with

        newRect = oldRect + [x y x y]; 

I know this is all small speed ups and clean-ups, but when hit heavily in the draw loop, it can matter, it does for me right now.

Shall I do this in a series of pull requests?

All the best,
Dee

**Comment by kleinerm** [comment]
Sure. One pull request will be enough if it is well tested to not break anything, because i won't test this stuff. Especially make sure that both rects and transposed rects and already vectorized versions work.

**Comment by dcnieho** [comment]
Great! I think it is a good time to create some unit tests then. Then you
can test (I don't have any Octave around, given i'm on windows), and it
won't be more than a button press. I wouldn't want to burden you with more
than that ;)

**Comment by dcnieho** [comment]
Well on my way. I am also vectorizing the many Rect functions that aren't, meaning they'll work with Mx4 rect-array inputs. I am using Mx4 as the older function that do already accept rect arrays, with a few exceptions, take Mx4, not 4xM.

There a few exceptions, functions that take both Mx4 and 4xM. These are OffsetRect, RectCenter and RectCenterd. I have a small issue with these: when a 4x4 is passed, it is interpreted as a 4xM (which is compatible with only some of the functions), not an Mx4. I would like to change this so things are consistent throughout, even if this may lead to minor breakage of user code, I think the lack of surprises in the future is worth it.

For RectCenter and RectCenterd, I would also like to remove the check that it is called with two output arguments. Its more than annoying, as i sometimes want only the horizontal center, but am forced to take both outputs. Its also not consistent with other matlab functions that only give you more if you want it (and have a safeword :P). You mind if i remove this check? This doesn't break anyone's code.

**Comment by kleinerm** [comment]
Seems to be ok in minimal testing. Closing...

**Comment by dcnieho** [comment]
Great! (Did you try the unittest as well, which exercises all of them?) There was still some open questions/issues, see my last longer message above. You want to keep things as they are, or make the proposed changes?

**Comment by kleinerm** [comment]
Unit test worked. But now demos fail which are crucial for my own work :( -- GarboriumDemo, ProceduralGarboriumDemo for example.

**Comment by kleinerm** [comment]
I've reverted the pull of PsychRects enhancements for now.
Please make sure to run every single PsychDemo, PsychTest, PsychAlpha etc. and make sure none of them fails due to PsychRects changes. This stuff is subtle and it would be really bad if not even our own code survives the changes.

**Comment by dcnieho** [comment]
The problem is I failed to test for 4xM rects with those functions that
previously supported it (newly vectorized generally only do Mx4). Will go
over that and indeed run all such tests too.

**Comment by dcnieho** [comment]
Ok, there is only one solution here:
All vectorized functions should take both 4xM and Mx4 as both are
already used in the toolbox.

Sadly, historically, some took a 4x4 to be 4xM while other as Mx4.
There is only one way to deal with this: documentation. Furthermore,
we can consider a flag as last optional input argument, indicating
whether rects are concatenated in row direction (1: Mx4) or column
direction (2: 4xM). Then users can force consistent instead of
historical behavior. A persistent global is also an option so set
default orientation is also an option, but this might interfere with
internal code when the user sets it -> no-go.

Another thing to consider is functions such as OffsetRect than can
take rect-arrays and correspondingly sized vectors of, e.g., offsets.
Should we allow any orientation of the vector, or should it match the
orientation of the rect-array? Any orientation would be nice for
flexibility. I'll see how much extra code that is...

This is growing to be bigger than i expected, but i think its
necessary. Tedious, but i'll get it done.

**Comment by kleinerm** [comment]
Closing this for the moment due to lack of activity.
