### ISSUE TITLE
Windows text and the &

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#255]
Hi Mario,

On Windows, in DrawFormattedText, you have the special case for ampersands on Windows as a single one is interpreted as a switch to enable underlining. Using Screen('DrawText') directly, users will meet unexpected behavior.

The DrawTextW function in the GDI api has a flag DT_NOPREFIX to switch off this behaviour. Perhaps it is a good idea to add that in so that users are not surprised and behavior of drawtext is consistent across platforms.

Its lines 1138 and 1202, i think.

Cheers,
Dee

**Comment by kleinerm** [comment]
Thanks. Added it to my master branch. We'll see how it goes once i'm relaxed enough to fire up the Windows build VM again - which could take a couple of weeks.

**Comment by dcnieho** [comment]
Great! No worries and no rush of course!

**Comment by kleinerm** [comment]
Fixed.
