### ISSUE TITLE
Screen('TextColor') returns crap

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#261]
Hi Mario,

Screen('TextColor') is returning funky things for me. I have previously done some text drawing in my script, setting the color to an RGB input. However, the color i get back from Screen('TextColor') appears to have an uninitialized alpha value
```matlab
color = Screen('TextColor',win);
color(1:3)
ans =
    255     0     0
color
ans =
    1.0e+308 *
    0.0000         0         0    1.7977
```
Use this to replicate: https://gist.github.com/dcnieho/771e24032262494edfa8

I guess this is the ``DBL_MAX`` from ``PsychCoerceColorMode`` in PsychSourceGL\Source\Common\Screen\ScreenTypes.c that does not get converted

"Trace" done by reading source:
```C
// \PsychSourceGL\Source\Common\Screen\SCREENDrawText.c, lines 2072-2073:
PsychCopyInColorArg 	// if called with 3 element vector, mode should not be kPsychRGBColor
PsychSetTextColorInWindowRecord // -> calls PsychCoerceColorMode
PsychCoerceColorMode // stores [R G B DBL_MAX] and sets color mode to kPsychRGBAColor

// \PsychSourceGL\Source\Common\Screen\SCREENTextColor.c, lines 58-59
//Coerce the current color record to the correct type in case it has not been accessed yet.
PsychSetTextColorInWindowRecord // calls PsychCoerceColorMode. no-op as already done above
PsychCopyOutColorArg // will copy out the 4 element RGBA vector with alpha still set to DBL_MAX
//PsychCopyOutColorArg is in PsychSourceGL / Source / Common / Screen / ScreenArguments.c, line 344
```

I suppose one should convert any DBL_MAXes upon color output (that only occurs from the screen textcolor and textbackground color getter), but am not sure how to go about that as we need to know the range of color values in the current mode. You probably know where to find that ;)

Cheers!
Dee

**Comment by kleinerm** [comment]
Ok. Done.

**Comment by dcnieho** [comment]
Cool, thanks! I see you also rebuilt the mex file. Will test this and the & handling of DrawText tomorrow.

**Comment by kleinerm** [comment]
The & works now, just tested.

**Comment by dcnieho** [comment]
Grreat!
