### ISSUE TITLE
ComputeFSWSE missing

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#263]
I just ran FitGammaDemo, and it errored out on missing ComputeFSWSE.
David, notifying you of this as i believe this is the part of PTB you currently work on. Sorry if wrong about that.

**Comment by DavidBrainard** [comment]
I’ll look into this in the next day or so.  

DB

> On Jul 30, 2015, at 4:21 PM, Diederick C. Niehorster <notifications@github.com> wrote:
> 
> I just ran FitGammaDemo, and it errored out on missing ComputeFSWSE.
> David, notifying you of this as i believe this is the part of PTB you currently work on. Sorry if wrong about that.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/263>.
> 

David H. Brainard
Professor of Psychology
Director, Penn Vision Research Center
Director, Institute for Research in Cognitive Science
University of Pennsylvania
3401 Walnut Street, Suite 400A (mail address)
3401 Walnut Street, Room 315C (office location)
Philadelphia, PA, 19104
Phone: 215-573-7579
Email: brainard@psych.upenn.edu
Web: http://color.psych.upenn.edu/brainard

**Comment by DavidBrainard** [comment]
I fixed this (it was a typo) as well as dusted off a little cruft that had accumulated on some of the related routines.  See commit comment for details.

DB

**Comment by dcnieho** [comment]
great!
