### ISSUE TITLE
Windows taskbar sometimes popup when PTB window is busy

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#277]
Sometimes when PTB windows is busy, the windows taskbar might popup to the front. Meanwhile, the cursor which should have been hidden turned to be the busy style cursor.

This issue does not exist on other full screen applications. Any fix?

**Comment by dcnieho** [comment]
What you mean with "PTB windows is busy"? If you do a busy wait in your
code, you'll get this. The PTB window is also grayed out by windows, isn't
it?

**Comment by suxpert** [comment]
Perhaps it is a busy wait, some of those popups occur at WaitSecs, while some aren't.

The PTB window is not grayed though, the cursor is in busy style.

**Comment by kleinerm** [comment]
It's MS-Windows. It does weird shit for weird reasons, nobody knows why. Especially not why this happens on some machines with the taskbar and not on most others. You can use ShowHideTaskbar to hide the taskbar at the beginning of your experiment, or just manually set it to be hidden by default.

**Comment by suxpert** [comment]
The `busy style cursor` comes out mostly when an application do not response, that is, perhaps, the application do not deal with the message queue correctly.

**Comment by kleinerm** [comment]
Yes. But same problem. We run inside Matlab's process, we don't have control and access to the event loop/application message queue, so are mostly dependent on Matlab doing the right thing, which seems to be especially problematic on MS-Windows. Sometimes it helps to add drawnow; or similar commands to busy loops in the hope that this will kick event processing. A long WaitSecs would be problematic if Matlab doesn't deal with event processing during that time, while the user klicks a lot and generates many messages in the queue.
