### ISSUE TITLE
PTB window force quit will crash Matlab (Windows 8.1 x64, Maltab 2012b x64)

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#279]
After PTB window is opened, press Shift-@ will force quit this window.

How ever, this action will mostly crash Matlab, see details:

> PTB-INFO: Master-Abort key '@' pressed by user.
PTB-INFO: Enforcing script abortion and restoring desktop by executing Screen('CloseAll') now!
PTB-INFO: Please ignore the false error message (INTERNAL PSYCHTOOLBOX ERROR) caused by this...

> WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 1).
WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.

> ------------------------------------------------------------------------
       Segmentation violation detected at Sat Sep 05 15:34:13 2015
------------------------------------------------------------------------

> Configuration:
  Crash Decoding  : Disabled
  Default Encoding: GBK
  MATLAB Root     : D:\Apps\MATLAB\R2012b
  MATLAB Version  : 8.0.0.783 (R2012b)
  Operating System: Microsoft Windows 7
  Processor ID    : x86 Family 6 Model 60 Stepping 3, GenuineIntel
  Virtual Machine : Java 1.6.0_17-b04 with Sun Microsystems Inc. Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System   : Version 6.2 (Build 9200)

> Fault Count: 1

> Abnormal termination:
Segmentation violation

> Register State (from fault):
  RAX = 00007ffcc799d368  RBX = 0000000000000300
  RCX = 00007ffce609fc6a  RDX = 0000000000000000
  RSP = 0000000004c35cd0  RBP = 0000000000000000
  RSI = 0000000000000556  RDI = 000000000cf98900
 
>   R8 = 0000000004c35bd8   R9 = 0000000000000001
  R10 = 0000000000000000  R11 = 0000000000000000
  R12 = 0000000000000000  R13 = 0000000000000000
  R14 = 0000000000000000  R15 = 0000000000000400
 
>   RIP = 00007ffcc79434fd  EFL = 00010206
 
>    CS = 0033   FS = 0053   GS = 002b

> Stack Trace (from fault):
[  0] 0x00007ffcc79434fd D:\Apps\MATLAB\Toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00341245 ( mexFunction+293373 )
[  1] 0x00007ffcc7946e0b D:\Apps\MATLAB\Toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00355851 ( mexFunction+307979 )
[  2] 0x00007ffcc795e137 D:\Apps\MATLAB\Toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00450871 ( mexFunction+402999 )
[  3] 0x00007ffcc78fbebe D:\Apps\MATLAB\Toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64+00048830 ( mexFunction+000958 )
[  4] 0x0000000059be0f83         D:\Apps\MATLAB\R2012b\bin\win64\libmex.dll+00069507 ( mexRunMexFile+000131 )
[  5] 0x0000000059bdfce2         D:\Apps\MATLAB\R2012b\bin\win64\libmex.dll+00064738 ( inSwapMexfileReader+000226 )
[  6] 0x0000000059bdfe64         D:\Apps\MATLAB\R2012b\bin\win64\libmex.dll+00065124 ( inSwapMexfileReader+000612 )
[  7] 0x0000000074e8c80d   D:\Apps\MATLAB\R2012b\bin\win64\m_dispatcher.dll+00051213 ( Mfh_file::dispatch_fh+000509 )
[  8] 0x0000000074e8d0d6   D:\Apps\MATLAB\R2012b\bin\win64\m_dispatcher.dll+00053462 ( Mfunction_handle::dispatch+000854 )
[  9] 0x00007ffcc0f3210b  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00336139 ( inFunctionHandleInterface::DestroyWorkspace+148683 )
[ 10] 0x00007ffcc0f43edf  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00409311 ( inFunctionHandleInterface::DestroyWorkspace+221855 )
[ 11] 0x00007ffcc0f60ae8  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00527080 ( inFunctionHandleInterface::DestroyWorkspace+339624 )
[ 12] 0x00007ffcc0f48d94  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00429460 ( inFunctionHandleInterface::DestroyWorkspace+242004 )
[ 13] 0x00007ffcc0f52978  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00469368 ( inFunctionHandleInterface::DestroyWorkspace+281912 )
[ 14] 0x00007ffcc0f55a8b  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00481931 ( inFunctionHandleInterface::DestroyWorkspace+294475 )
[ 15] 0x00007ffcc0f3de1f  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00384543 ( inFunctionHandleInterface::DestroyWorkspace+197087 )
[ 16] 0x00007ffcc0f3dd80  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00384384 ( inFunctionHandleInterface::DestroyWorkspace+196928 )
[ 17] 0x00007ffcc0f6197d  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00530813 ( inFunctionHandleInterface::DestroyWorkspace+343357 )
[ 18] 0x00007ffcc0f60271  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00524913 ( inFunctionHandleInterface::DestroyWorkspace+337457 )
[ 19] 0x00007ffcc0f420e9  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00401641 ( inFunctionHandleInterface::DestroyWorkspace+214185 )
[ 20] 0x0000000074e8c80d   D:\Apps\MATLAB\R2012b\bin\win64\m_dispatcher.dll+00051213 ( Mfh_file::dispatch_fh+000509 )
[ 21] 0x0000000074e8d0d6   D:\Apps\MATLAB\R2012b\bin\win64\m_dispatcher.dll+00053462 ( Mfunction_handle::dispatch+000854 )
[ 22] 0x00007ffcc0f59482  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00496770 ( inFunctionHandleInterface::DestroyWorkspace+309314 )
[ 23] 0x00007ffcc0fe318f  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01061263 ( inEachVisibleName+014415 )
[ 24] 0x00007ffcc0f574ca  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00488650 ( inFunctionHandleInterface::DestroyWorkspace+301194 )
[ 25] 0x00007ffcc0f3de1f  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00384543 ( inFunctionHandleInterface::DestroyWorkspace+197087 )
[ 26] 0x00007ffcc0f3dd80  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00384384 ( inFunctionHandleInterface::DestroyWorkspace+196928 )
[ 27] 0x00007ffcc0f6197d  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00530813 ( inFunctionHandleInterface::DestroyWorkspace+343357 )
[ 28] 0x00007ffcc0f60271  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00524913 ( inFunctionHandleInterface::DestroyWorkspace+337457 )
[ 29] 0x00007ffcc0f420e9  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00401641 ( inFunctionHandleInterface::DestroyWorkspace+214185 )
[ 30] 0x0000000074e8c80d   D:\Apps\MATLAB\R2012b\bin\win64\m_dispatcher.dll+00051213 ( Mfh_file::dispatch_fh+000509 )
[ 31] 0x0000000074e8d0d6   D:\Apps\MATLAB\R2012b\bin\win64\m_dispatcher.dll+00053462 ( Mfunction_handle::dispatch+000854 )
[ 32] 0x00007ffcc0ff51e5  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01135077 ( inValidateLoadedObject+001893 )
[ 33] 0x00007ffcc1004595  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01197461 ( init_cleaner+015541 )
[ 34] 0x00007ffcc1007b75  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01211253 ( inSetMaxFrameCount+002261 )
[ 35] 0x00007ffcc1007b48  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01211208 ( inSetMaxFrameCount+002216 )
[ 36] 0x00007ffcc1007b07  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01211143 ( inSetMaxFrameCount+002151 )
[ 37] 0x00007ffcc0ef0213  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+00066067 ( inPathNotification::function_clear_notification+004019 )
[ 38] 0x00007ffcc0ffaed0  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01158864 ( inEvalCmdWithLocalReturn+000416 )
[ 39] 0x00007ffcc0ffae2c  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01158700 ( inEvalCmdWithLocalReturn+000252 )
[ 40] 0x00007ffcc0ffad71  D:\Apps\MATLAB\R2012b\bin\win64\m_interpreter.dll+01158513 ( inEvalCmdWithLocalReturn+000065 )
[ 41] 0x0000000079fbf90d    D:\Apps\MATLAB\R2012b\bin\win64\libmwbridge.dll+00063757 ( mnDebugPrompt+000109 )
[ 42] 0x0000000079fc0471    D:\Apps\MATLAB\R2012b\bin\win64\libmwbridge.dll+00066673 ( mnParser+000593 )
[ 43] 0x00000000749a64a4            D:\Apps\MATLAB\R2012b\bin\win64\mcr.dll+00222372 ( mcrInstance::mnParser_on_interpreter_thread+000036 )
[ 44] 0x000000007498681f            D:\Apps\MATLAB\R2012b\bin\win64\mcr.dll+00092191 ( mcr::setInterpreterThreadToCurrent+029887 )
[ 45] 0x0000000074986881            D:\Apps\MATLAB\R2012b\bin\win64\mcr.dll+00092289 ( mcr::setInterpreterThreadToCurrent+029985 )
[ 46] 0x000000001113e0b6            D:\Apps\MATLAB\R2012b\bin\win64\uiw.dll+00385206 ( UIW_IsUserMessage+000086 )
[ 47] 0x000000001113e7b9            D:\Apps\MATLAB\R2012b\bin\win64\uiw.dll+00387001 ( UIW_SetGLIMUserMsg+000153 )
[ 48] 0x00007ffce60f2a0f                     C:\Windows\system32\USER32.dll+00535055 ( BroadcastSystemMessageExA+000447 )
[ 49] 0x00007ffce608ce9f                     C:\Windows\system32\USER32.dll+00118431 ( SendMessageTimeoutW+000735 )
[ 50] 0x00007ffce608ce06                     C:\Windows\system32\USER32.dll+00118278 ( SendMessageTimeoutW+000582 )
[ 51] 0x00007ffce62b53e4                      C:\Windows\SYSTEM32\ntdll.dll+00611300 ( KiUserCallbackDispatcher+000036 )
[ 52] 0x00007ffce609fc6a                     C:\Windows\system32\USER32.dll+00195690 Ordinal2559+000074
[ 53] 0x00007ffce608a75c                     C:\Windows\system32\USER32.dll+00108380 ( PeekMessageW+000364 )
[ 54] 0x00007ffce608a5d3                     C:\Windows\system32\USER32.dll+00107987 ( PeekMessageA+000275 )
[ 55] 0x0000000011118f4b            D:\Apps\MATLAB\R2012b\bin\win64\uiw.dll+00233291 ( UIW_SetCurrentDialog+000731 )
[ 56] 0x000000001113fbe2            D:\Apps\MATLAB\R2012b\bin\win64\uiw.dll+00392162 ( ws_FreeSystemFont+000546 )
[ 57] 0x00000001800be6a3  D:\Apps\MATLAB\R2012b\bin\win64\libmwservices.dll+00779939 ( sysq::removeCommitDatabaseUpdatesHook+002131 )
[ 58] 0x00000001800bfe18  D:\Apps\MATLAB\R2012b\bin\win64\libmwservices.dll+00785944 ( sysq::removeCommitDatabaseUpdatesHook+008136 )
[ 59] 0x00000001800c1a20  D:\Apps\MATLAB\R2012b\bin\win64\libmwservices.dll+00793120 ( sysq::addProcessPendingEventsUnitTestHook+000240 )
[ 60] 0x00000001800c1ae8  D:\Apps\MATLAB\R2012b\bin\win64\libmwservices.dll+00793320 ( sysq::addProcessPendingEventsUnitTestHook+000440 )
[ 61] 0x00000001800c1ca3  D:\Apps\MATLAB\R2012b\bin\win64\libmwservices.dll+00793763 ( sysq::addProcessPendingEventsUnitTestHook+000883 )
[ 62] 0x00000001800c1d76  D:\Apps\MATLAB\R2012b\bin\win64\libmwservices.dll+00793974 ( sysq::addProcessPendingEventsUnitTestHook+001094 )
[ 63] 0x000000007498837e            D:\Apps\MATLAB\R2012b\bin\win64\mcr.dll+00099198 ( mcr::setInterpreterThreadToCurrent+036894 )
[ 64] 0x0000000074988665            D:\Apps\MATLAB\R2012b\bin\win64\mcr.dll+00099941 ( mcr::setInterpreterThreadToCurrent+037637 )
[ 65] 0x000000007497b166            D:\Apps\MATLAB\R2012b\bin\win64\mcr.dll+00045414 ( DepfunRules::postWarning+003430 )
[ 66] 0x00007ff7ebbc8a33         D:\Apps\MATLAB\R2012b\bin\win64\MATLAB.exe+00035379 ( ???+000000 )
[ 67] 0x00007ff7ebbc8c97         D:\Apps\MATLAB\R2012b\bin\win64\MATLAB.exe+00035991 ( ???+000000 )
[ 68] 0x00007ff7ebbc9163         D:\Apps\MATLAB\R2012b\bin\win64\MATLAB.exe+00037219 ( ???+000000 )
[ 69] 0x00007ffce4a82d92                   C:\Windows\system32\KERNEL32.DLL+00077202 ( BaseThreadInitThunk+000034 )
[ 70] 0x00007ffce6229f64                      C:\Windows\SYSTEM32\ntdll.dll+00040804 ( RtlUserThreadStart+000052 )

> This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

> If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

> A technical support engineer might contact you with further information.

> Thank you for your help.** This crash report has been saved to disk as C:\Users\Decision\AppData\Local\Temp\matlab_crash_dump.4656-1 **

> Caught MathWorks::System::FatalException
[Please exit and restart MATLAB]>>

**Comment by dcnieho** [comment]
I never knew of ths key. Try control-C

I just see in the output here that you are running matlab R2012b. This
means you must have an (years!) outdated PTB, as it hasn't been supported
for quite a while. Please upgrade to a newer Matlab version (R2013a or
later if i remember correctly), make sure its 64bit, get the newest PTB and
try and see if this and other problem's you're having are still there

**Comment by suxpert** [comment]
It is the `Master-Abort key '@' `, I found it in the C source code.

PTB claimed that I can use Matlab 2007a or later, and you know, upgrade Matlab need money, in my lab I have only 2012b available. :(

Ctrl-C will force quit Matlab's process, can not be catched, so no way to do the clean up jobs, which means that the PTB window is still in the front, busily doing some unknown jobs, I'll have to try again and again to execute an `sca` command to close it.

Although I can use the `onCleanup` class to do the cleanups, the question is, PTB provide such a key, it can't work correctly, so, ---I think this should be called as a bug or issue. :)

**Comment by kleinerm** [comment]
The reason that nobody knows about that key is because - who would have guessed that? - it doesn't work reliably on current versions of Windows. It did work in the far past on old Windows + Matlab versions. Maybe you should stick to the documentation instead of the source code.

I think CTRL+C works with onCleanup, but even if not, CTRL+C is the way you do it. Simply use ALT+TAB to make sure the Matlab window is selected before typing sca.

R2012b is ok. I develop and test with R2012a atm. R2007a probably still works, but i develop and test with whatever i can have in the lab, and that is R2012a. But if money is an issue i'd actually switch to Linux + Octave. That's not only cheap as in free, but Linux is also a much better choice of operating system for neuro-science.

So not a bug.

**Comment by suxpert** [comment]
There exist some other stimuli-related software, e.g., E-prime, which can use a special key-combination to force-quit the running experiment. I'm looking for such a function for a long time in Psychtoolbox, and finally found it in the source code.

Ctrl-C is not a good choice because the afterward operating is too tricky. Sometimes even after Alt-Tab to matlab, it doesn't got the focus, typing result to nothing. Also, because matlab is now hidden behind PTB's white window, it is hard to know what had happened to matlab, so I have to try again and again, pressing alt-tab, ctrl-c, sca<Enter>, that is not so comfortable comparing to a simple combined-key press.

If the `Shift-@` function can work correctly, I'll be very grateful.

**Comment by kleinerm** [comment]
e-Prime is a standalone application, not an add-on to an existing application. They are in full control of their event loop and other stuff, so it is easier for them.

Add this to the top of your scripts main function: canary = onCleanup(@sca);

Now on error, or if you press CTRL+C, your script will terminate, the 'canary' variable goes out of scope and gets deleted, and the cleanup function 'sca' gets executed and closes down the screen. I think that's an elegant solution. Obviously you can put more complex clenaup functions there than sca.
