### ISSUE TITLE
DrawText related function is buggy when the screen scale factor is not 1, i.e., HiDPI

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#282]
Hi there, I'm here again. I don't know if this bug exists on other system, but it can reproduce 100% on windows.

1. Open the control panel, change the scale factor to something like 150% or whatever.
2. Open the PTB window, draw multi-line text using `DrawFormattedText`, you can see that those lines are covering each other.
3. Try the `DrawHighQualityUnicodeTextDemo`, which set the `DefaultTextYPositionIsBaseline` option, you can see that those characters are cropped at the top.

I've tried using `TextBounds` command to find out the real bound for a string, the result seems correct (with HiDPI, the boundary became larger than without HiDPI), so this issue might be caused by an incorrect calculation on the bound box, perhaps e.g., [here](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/bfcc6d918e2c4d080dc408974e54abfbb1863cec/PsychSourceGL/Source/Common/Screen/SCREENDrawText.c#L1166)

**Comment by dcnieho** [comment]
Hi Litux,

The problem is much simpler, and that is that DrawFormattedText uses a
cheap way of estimating vertical font size, it doesn't use actual bounding
boxes.

Mario, you have used the actual bounding box method as a special case for
one line of text. In windows at least, the bounding box always takes
ascenders and descenders into account, so its always valid/constant, no
matter what text you want to print. Can we get the bounding box height once
and then use that as the text height instead of the current cheap way? It
would be a breaking change tho, as vspacing (even 1) would have a different
meaning.

Best,
Dee

**Comment by kleinerm** [comment]
Dee, simply send me a pull request with a properly modified DrawFormattedText.m, where the new hacks only apply to Windows (aka if IsWin ...hack... end), and some test case i can run on all OS'es, and we'll see...

thanks,
-mario

**Comment by suxpert** [comment]
Hi, I've tried the same setting on Ubuntu 14.04 (PTB from neuro debian), and perhaps found some useful things.

On windows, the `TextBounds` returned the same height for all characters of a font, for example, when I select Arial with size 40, the last number returned from TextBounds is 60 when scale factor is 1, and became 75 when scale factor is 1.25, this is the same for letter `M` or `-` or even space, see this list:

> TextBound on Windows, with scale factor 1.25, offset is 100, 100

Letter | normBoundsRect | offsetBoundsRect 0 | offsetBoundsRect 1
---------|-------------------------|---------------------------|---------------------------
M       |    [0 0 55 75]         | [100 99 155 174]     | [100 59 155 134]
-         |    [0 0 22 75]         | [100 99 122 174]     | [100 59 122 134]
space |   [0 0 19 75]       | [100 99 119 174]     | [100 59 119 134]

Comparing to without HiDPI, i.e., scale factor is 1:
> TextBound on Windows, with scale factor 1, offset is 100, 100

Letter | normBoundsRect | offsetBoundsRect 0 | offsetBoundsRect 1
---------|-------------------------|---------------------------|---------------------------
M       |    [0 0 43 60]         | [100 99 143 159]     | [100 59 143 119]
-         |    [0 0 18 60]         | [100 99 118 159]     | [100 59 118 119]
space |   [0 0 15 60]       | [100 99 115 159]     | [100 59 115 119]

So it seems that the bounding box on windows is not the traditional [glyph bounding box](http://www.freetype.org/freetype2/docs/glyphs/glyphs-3.html#section-5), but perhaps something like the **advance**. It seems to be OK because most of the time, typesetting do not consider about the glyph bounding box too much.

But this `outline box` is not correct either. With HiDPI, this box starts at an error y-position, thus the text is cropped at the top, see figs.
![Text Bound Issue on windows with HiDPI](https://cloud.githubusercontent.com/assets/1191414/10102579/c8c280d2-63d1-11e5-8efb-b90b3bcba4b4.png)
![Text Bound Issue on windows WITHOUT HiDPI](https://cloud.githubusercontent.com/assets/1191414/10103555/226d64da-63d7-11e5-9e41-d0db3db38eac.png)

These figures are obtained via:

```matlab
% First change the scale factor to 1.25, then
PsychDebugWindowConfiguration;
PsychDefaultSetup(2);
[w, rect] = PsychImaging('OpenWindow', 0, 0.5);
Screen('TextFont', w, 'Arial');
Screen('TextSize', w, 40);
Screen('DrawText', w, 'M', 100, 100, 1, 0, 0);
Screen('DrawText', w, 'M', 160, 100, 1, 0, 1);
Screen('Flip');
```


However, things became different on Linux. I select Arial with size 40 again, `TextBounds` of letter M became [0 0 27 29], and this box size do not change if I change the unity setting's scale factor (Which means that this scale factor does NOT apply to PTB window, or should I say this scale factor works incorrectly). See the following table.

> TextBound on Linux, offset is 100, 100

Letter | normBoundsRect | offsetBoundsRect 0 | offsetBoundsRect 1
--------|-------------------------|----------------------------|--------------------------
M       | [0 0 27 29]           |   [103 100 130 129]   |  [103 71 130 100]
-        | [0 0 11 3]             | [101 100 112 103]    | [101 88 112 91]
space |   [0 0 0 0]         | [100 100 100 100]    | [100 100 100 100]

I've tried to draw letter by letter without assign the position, so all those letters are closed together without any space, but draw multi letters do have spaces, see fig.
![Text Bound Issue On Linux](https://cloud.githubusercontent.com/assets/1191414/10102840/4e2143d4-63d3-11e5-8f28-ebb22318cafe.png)

For compare, here is when I change the scale factor, draw text without or with setting `baseline`:
![Text Bound on Linux when scale factor is not 1](https://cloud.githubusercontent.com/assets/1191414/10102883/94030928-63d3-11e5-86a3-abb1c2abd1fa.png)

I remember in somewhere, PTB is still using GDI for text render on windows, but a better choice should be DirectWrite, some other one suggested. What's more, there is a pango, which is cross platform. If the font render issue can not be fixed because of the limit of windows, how about move to pango or whatever?

**Comment by dcnieho** [comment]
The problem is that Screen('TextSize', win) is used as a proxy for the
lineheight, bounding boxes are not used at all in this function.
A simple, but not backward compatible fix would be to replace line 227

**Comment by dcnieho** [comment]
dammit, sent too early...
A simple, but not backward compatible fix would be to replace line 227 with:
theight = RectHeight(Screen('TextBounds', win, tstring)) * vSpacing;

Try that please and see if it works for you. Also try on ubuntu please.
If so, i'll implement it as an option (We need to stay backward compatible)

RE pango: yes, thats very much on the todo list, but will not happen
anytime soon (unless you volunteer). See the open issue from me from a few
months ago for a discussion.

**Comment by suxpert** [comment]
Oops, this won't work correctly. Seems that the returned height is already for multi-line text? I noticed that if I use this new code, the space between lines is larger for 3 lines than for 2 lines.

So I tried this line (in the thought that the character `|` should have the max height for most fonts):
```matlab
theight = RectHeight(Screen('TextBounds', win, '|')) * vSpacing;
```
It seems that for windows, the too narrow issue is gone.

For Linux, it seems that the height of `|` is still **smaller** than TextSize, and in all my tests, Linux does not seem to have the real equivalent to Windows' global scale factor, so the same issue might not exist on Linux.

### Issues still remain:
0. How to deal with the different TextBounds on Windows and Linux?
1. DrawText, because of the different concept of TextBounds, draw much different text on Linux and Windows, makes the code not portable.
2. TextBounds on Windows, if the `DefaultTextYPositionIsBaseline` option is on, is incorrect, no matter for HiDPI or not. (Much worse for HiDPI)
3. DrawText, because of the incorrect TextBounds, can not work correctly if `DefaultTextYPositionIsBaseline` option is on, for HiDPI screen when the scale factor is larger than 1.
4. The same TextSize gives a different real font size on windows and Linux, how to make them equal?

BTW, I've did a double check, the HiDPI with scale factor larger than 1 is not enough for reproduce these issues. So here is the details:

On windows, there is a global scale factor that applies to all application, for scaling the UI and the text drawn by the application, even if the application itself do not consider about doing such adaption (see MSDN: [DPI-aware](https://msdn.microsoft.com/library/dd464646.aspx) ). So if the application is not DPI-aware, when scale factor is not 1, the UI may be blur.

But there is still application-special settings, to disable such scale for certain application. To do that, right click on the application, click properties, on the compatibility tab, check the `Disable display scaling on high DPI settings` option and apply. Then Windows will not scale the UI even if scale factor is not 1.

I usually enlarge the scale factor for large screens, and disable the scaling for certain applications because they are not DPI aware. Matlab is on of them. So PTB Window inherit this property, keep away from blur. But the DrawText function still apply the scale factor, so text is larger than usual. Then the calculation on bounding box et al., became incorrect.

**Comment by dcnieho** [comment]
Thanks for the investigation. Indeed, a | or so ('Alaxgj' would also be an
option, something with ascenders and descenders) would be an option. Though
for windows, the bound always includes space for ascenders and descenders
in my testing, seems not to depend on actual letters used. May be different
on different OS.

Things are not portable indeed. Again, see the other issue i opened about
it.

On Sat, Sep 26, 2015 at 7:58 AM, LiTuX S. <notifications@github.com> wrote:

> - TextBounds on Windows, if the DefaultTextYPositionIsBaseline option is
> on, is incorrect, no matter for HiDPI or not. (Much worse for HiDPI)


One further question about this: what is incorrect? Do you have some
screenshot? See my other issue for some quick testing code that you way
want to try to run.

So changing to using actual textbound height makes things better for
Windows. It still works for Linux as well? Trying to see if this
change/extra option would actually be an improvement.

Note that Mario is working on DPI awareness settings, so lets see about
that first....

Best,
Dee

**Comment by suxpert** [comment]
Yep, most of the characters on windows give to the same `height` except two. I just find them minutes ago, and that seems to be another issue.

These two letter's are `Line Feed` and `Carriage Return`, ASCII 10 and 13. I found that if I pass them to `DrawText` or `TextBounds`, the result is incorrect on windows. It seems that `DrawText` use the Bbox returned by something the same as `TextBounds` to draw the background, then draw text inside this box, am I right? The result by
```matlab
Screen('DrawText', w, ['I can ', 10, 'eat glass'], 100, 100, 1, 0, 0);
```
is like this on windows:
![drawtext_issue](https://cloud.githubusercontent.com/assets/1191414/10116656/c79c3fbc-646d-11e5-87e5-ad427dcf697e.PNG)
So the text is no longer inside the bounding box.

On Linux, the LF or CR acted as they were eaten.

About the issue related to `DefaultTextYPositionIsBaseline`, I've post two screen shot in the previous comment, here again, is the screen shot without modifying scale factor. You can see that the bounding box of the right `M` is not the same as the left one, the bounding box, or the text itself, is shifted in the y axis.
![Bbox when scale factor is 1](https://cloud.githubusercontent.com/assets/1191414/10103555/226d64da-63d7-11e5-9e41-d0db3db38eac.png)

 This offset become larger if scale factor is larger than 1, so for the HiDPI setting, the right `M` is cropped at the top, leading to an incomplete letter.
![Bbox when scale factor is 1.25](https://cloud.githubusercontent.com/assets/1191414/10102579/c8c280d2-63d1-11e5-8efb-b90b3bcba4b4.png)

One more thing, what does the `TextSize` really mean? I've measured the drawn text, it seems that:
on windows, the height of the fake `bounding box` is around 1.5 times the `TextSize`;
while on Linux, the height of the bounding box of `|` is around the `TextSize` though, different fonts give different result. What's more, if there are texts using accent et al, the height of the bounding box is larger than the `TextSize` but never up to 1.5 times.

The real text size differs so much: (both were drawn using Arial at TextSize = 400):
![drawtext_test-windows](https://cloud.githubusercontent.com/assets/1191414/10116738/98165b1c-6470-11e5-9acc-d0227e4f6178.png)
![textsize_test](https://cloud.githubusercontent.com/assets/1191414/10116737/9811f91e-6470-11e5-92ba-7d2a87d565da.png)

**Comment by suxpert** [comment]
It seems that the windows' way is correct. I've tried on Linux with LibreOffice, Gvim, gedit, the M in arial at 400 are all the same as in PTB drawn under windows.
![m-in-arial-400](https://cloud.githubusercontent.com/assets/1191414/10116806/691862c6-6473-11e5-89ee-1e59485f9be6.png)

**Comment by suxpert** [comment]
Update:
I've found a magic number :laughing: 

Comparing to the actual size of `M` at size 400, I have to set the `TextSize` to 533 in PTB Linux version, to obtain the same display result.

I've tried again for `|M^W|` at size 300, the closest size on Linux is 400. (Some slightly differences exist in the space between letters.)

533 is almost **4/3** times of 400, and 400 is truly **4/3** times of 300.

So why 4/3?

**Comment by kleinerm** [comment]
The 4/3 is the ratio 96 / 72 DPI. The Linux (and new OSX) textrenderer assumes a display DPI of 72, whereas the stuff you've shown apparently assumes 96 DPI. The goal was to make point size in fonts match pixel size, so 1 pt = 1 pixel, because traditionally Screen TextSize expects font size in pixels. See 

http://www.freetype.org/freetype2/docs/glyphs/glyphs-2.html

So we tell Freetype to assume a 72 DPI display when building font glyphs, so we know the font has the nominal size in pixels that the use specified. Now if an application instead tries to scale font size based on display DPI then it will yield different results for any selected font size. Your examples work with an assumed 96 DPI for a "standard resolution" display. The internet is somewhat confused about what DPI for a standard display is, citing 72 and 96 as the most common ones, e.g.,:
https://forums.adobe.com/thread/780929?tstart=0

So in that sense the Linux text renderer does what it is supposed to do, obeying font size in pixels. Insofar it shouldn't have problems with HiDPI displays, nor should it behave differently for any set scaling factor. It is surprising though if you compare with other desktop apps, which probably use font point size as size spec, where 1 pt = 1/72 inch, and then the application or OS has to scale for given display DPI.

Screen('DrawText') is only supposed to handle single line text, so it will do weird things if you try to insert line feeds, carriage returns etc. DrawFormattedText.m is supposed to fix this good enough for typical use. But it is not a full blown text layout engine. Pango would be a good solution for that, but somebody would need to do the actual work of implementing that as a new drawtext plugin for all operating systems and make sure it is easily maintainable in the future. Also Pango as a layout engine would be likely much slower than our current speed optimized renderer, and speed is important for many vision science experiments, so a Pango renderer would not be a replacement, but only a selectable alternative for people which don't need speed but beauty in text layout.

**Comment by kleinerm** [comment]
The latest beta now provides the same FTGL plugin text renderer by default on Windows, as on OSX and Linux and this one does improve text positioning, calculates better bounding boxes and keeps the size of text in pixels constant, irrespective of DPI setting on Windows.

- Requires Octave-4 or
- when Matlab is used the installation of GStreamer 1.4 or later.

Both Octave-4 and GStreamer have the required libfontconfig and libfreetype dll's bundled to make our FTGL text renderer plugin work on Windows.
