### ISSUE TITLE
Octave 4 on (Arch) Linux Support?

### ISSUE THREAD

**Issue by nichdel** [Psychtoolbox-3/Psychtoolbox-3#293]
I notice that there's a folder/support for Octave 4 on OSX but none such for linux. Arch currently ships Octave 4. Presently, the install script fails on arch with octave 4. Could this be fixed, and is there a workaround until there's an official fix? Here's the problematic part of the install script:

    Running post-install routine...

    warning: savepath: current path saved to ~/.octaverc
    Octave major version 4 detected. Will prepend the following folder to your Octave path:
     /home/nichdel/psychtoolbox/Psychtoolbox/PsychBasic/Octave4LinuxFiles64...
    warning: addpath: /home/nichdel/psychtoolbox/Psychtoolbox/PsychBasic/Octave4LinuxFiles64: No such file or directory
    warning: savepath: current path saved to ~/.octaverc

    In place of the expected Octave .mex binary plugin file this placeholder file was executed:

      WaitSecs.m

    This MEX file seems to be missing or inaccessible on your Octave path or it is dysfunctional:

      WaitSecs.mex

    The following directory should be the *first one* on your Octave path:
     /home/nichdel/psychtoolbox/Psychtoolbox/PsychBasic/Octave3LinuxFiles64/

    If you have just installed Psychtoolbox, it worked properly and suddenly stopped working
    after you have restarted Octave, then you may encounter a bug present in Octave 3.2.0.
    Try the following at the Octave prompt: First type "savepath" + Enter to save the current Octave    path again.
    Then exit Octave and restart it. After that try again - It may work then, if the problem was caused by aforementioned bug.

    ERROR: WaitSecs-MEX does not work, most likely other MEX files will notwork either.
    ERROR: One reason might be that your version 4.0.0 of Octave is incompatible. We recommend
    ERROR: use of the latest stable version of Octave-3 as announced on thewww.octave.org website.
    ERROR: Another conceivable reason would be missing or incompatible required system libraries on your system.

    ERROR: After fixing the problem, restart this installation/update routine.

    Installation aborted. Fix the reported problem and retry.

**Comment by kleinerm** [comment]
Octave-4 support will be part of the next beta update, likely to happen before start of next week.
However, officially we only support recent Debian/Ubuntu atm., so there is always some risk of things being broken on other distros due to differences in shipped libraries etc.

**Comment by nichdel** [comment]
@kleinerm Thanks for the info. I'll be running it with Octave 3 on Debian for the time being, but look forward to seeing how it does with Octave 4.

**Comment by kleinerm** [comment]
Solved in current beta. NeuroDebian et al. will get updated later.
