### ISSUE TITLE
Using Psychtoolbox as C++ library

### ISSUE THREAD

**Issue by CarloNicolini** [Psychtoolbox-3/Psychtoolbox-3#302]
I see that, despite the most important Screen related functions in Psychtoolbox are written in C, everything is compiled in mex files that are hardly callable from any C++ without including matlab dependencies. I'm wondering if anyone ever tried to compile indepentently the Screen to create a c++ shared object (at least for Linux). I see for example that the linuxmakeit64.m contains everything to compile the mex files 

mex CFLAGS='$CFLAGS -fPIC -std=gnu99 -fexceptions' -v -outdir ../Projects/Linux/build/ -output Screen -largeArrayDims -DPTBMODULE_Screen -DPTB_USE_GSTREAMER -DPTBVIDEOCAPTURE_LIBDC -DPTB_USE_NVSTUSB -D_GNU_SOURCE -I/usr/X11R6/include -I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I../Cohorts/libnvstusb-code-32/include -ICommon/Base -ICommon/Screen -ILinux/Base -ILinux/Screen -L/usr/X11R6/lib "Linux/Base/_.c" "Linux/Screen/_.c" "Common/Screen/_.c" "Common/Base/_.c" -lc -lrt -ldl -lGL -lGLU -lX11 -lXext -lX11-xcb -lxcb -lxcb-dri3 -lgstreamer-1.0 -lgstbase-1.0 -lgstapp-1.0 -lgstvideo-1.0 -lgstpbutils-1.0 -lgobject-2.0 -lgmodule-2.0 -lxml2 -lgthread-2.0 -lglib-2.0 -lXxf86vm -ldc1394 -lusb-1.0 -lpciaccess -lXi -lXrandr -lXfixes

P.S.
Has someone ever thought about compiling all PTB with CMake?

**Comment by dcnieho** [comment]
Its not that simple as compiling directly instead of with the mex command. The code has many calls to the matlab api, and its entry point is as understood by the matlab code. A lot of glue would have to be rewritten. That said, it is of course interesting to bring PTB's excellent machinery to a larger audience. Just don't count on it happening anytime soon.
