### ISSUE TITLE
OffsetRect fails when adjusting 4 rects

### ISSUE THREAD

**Issue by mscain** [Psychtoolbox-3/Psychtoolbox-3#305]
OffsetRect expects a matrix of rects with 4 columns. However, it tries to be clever and deal with input that is actually formatted as 4 rows. This leads to a problem when a matrix with 4 rects is provided.

These two calls work:
```
OffsetRect(ones(3,4), [1; 2; 3], [6; 7; 8])
OffsetRect(ones(5,4), [1; 2; 3; 4; 5], [6; 7; 8; 9; 10])
```
This call gives `Error using +, Matrix dimensions must agree`:
```
OffsetRect(ones(4,4), [1; 2; 3; 4], [6; 7; 8; 9])
```

I think this can be fixed by changing line 54 to
```
if size(oldRect, 1)==4 && size(oldRect, 2)~=4
```

**Comment by kleinerm** [comment]
Applied your proposal, thanks.
