### ISSUE TITLE
Windows 10 OpenWindow issue

### ISSUE THREAD

**Issue by tombeesley** [Psychtoolbox-3/Psychtoolbox-3#309]
Hello,

Using Windows 10, latest PTB and Matlab 2015b, I have trouble opening a full resolution window.

The following fails:

MainWindow = Screen('OpenWindow',0,[50 50 50],[0 0 1920 1080]); 

But this works

MainWindow = Screen('OpenWindow',0,[50 50 50],[0 0 1919 1079]); 

Is this a known issue, and if so is there a solution? 

thanks

**Comment by dcnieho** [comment]
What is your screen's resolution? If that's fullscreen, does opening
fullscreen without the resolution argument (Effectively the same) work?

**Comment by tombeesley** [comment]
Hi – thanks for the reply. It suddenly started working at full resolution, without any clear indication of why! (seemingly nothing was changed in the code) I’ll report back if I have further issues.
