### ISSUE TITLE
Memory Leak Drawing to Screen

### ISSUE THREAD

**Issue by ljchang** [Psychtoolbox-3/Psychtoolbox-3#315]
We have recently observed a memory leak using DrawFormattedText() in a while loop (though other drawing functions might demonstrate same issue).  It seems to be worse when the text size is bigger.  

Matlab Version:  8.5.0.197613 (R2015a)
PTB Version: 3.0.12 - Flavor: beta - Corresponds to SVN Revision 7386
MacOS Version: 10.10.5
Hardware: MBP Retina 15-inch, Mid 2015

We haven't observed this behavior using older versions of Matlab (e.g., 8.0.0.783 (R2012b) on a mid-2012 MBA, OS 10.8.4.

See our example function for replicating issue.
```
function MemoryLeakExample()

Screen('Preference', 'SkipSyncTests', 1)
screens = Screen('Screens');
screenNumber = max(screens);

[window, rect] = Screen('OpenWindow', screenNumber, [0 0 0 ]);
Screen('TextSize', window, 100);
buttons=0;

while ~buttons
    DrawFormattedText(window,'Watch memory usage grow!','center','center', [255 255 255]);
    Screen('Flip',window);
end

sca;

end
```

**Comment by kleinerm** [comment]
Does this also happen with the latest year 2016 Psychtoolbox? With the new text renderer? Please post PTB's Matlab output. If it can't use the new text renderer ported from Linux it will print some warning wrt. DrawText not being able to load the text renderer plugin.

When testing the old legacy Apple CoreText text renderer last week on 10.11 "El Crapitan" i found horrendous memory leaks in the multi-dozen-gigabyte range just after running DrawHighQualityUnicodeTextDemo. These are definitely not PTB bugs, but OSX operating system bugs. Maybe those bugs already exist in 10.10 Yosemite and you found the same bug.

OSX is an utter disaster in quality. Never seen such a buggy operating system.

**Comment by ljchang** [comment]
This running the January 2016 release. It looks like the new text renderer fails to load, here's that output: 

```
PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.


PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.12 - Build date: Jan 14 2016).
PTB-INFO: Support status on this operating system release: OSX version 10.10 is not supported or tested anymore.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Installation of the PsychtoolboxKernelDriver is strongly recommended if you care about precise visual
PTB-INFO: onset timestamping or timing. See 'help PsychtoolboxKernelDriver' for installation instructions.


PTB-INFO: OpenGL-Renderer is ATI Technologies Inc. :: AMD Radeon R9 M370X OpenGL Engine :: 2.1 ATI-1.32.25
PTB-INFO: Renderer has 2048 MB of VRAM and a maximum 1928 MB of texture memory.
PTB-INFO: VBL startline = 1800 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.668863 ms [59.992096 Hz]. (50 valid samples taken, stddev=0.074196 ms.)
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: Psychtoolbox imaging pipeline starting up for window with requested imagingmode 33793 ...
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus drawing.
PTB-INFO: Enabling panel fitter. Providing virtual framebuffer of 1440 x 900 pixels size.
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus post-processing (if any).
PTB-WARNING: DrawText: Failed to load external drawtext plugin [dlopen(libptbdrawtext_ftgl64.dylib, 10): image not found]. Reverting to legacy text renderer.
PTB-WARNING: DrawText: Functionality of Screen('DrawText') and Screen('TextBounds') may be limited and text quality may be impaired.
PTB-WARNING: DrawText: Type 'help DrawTextPlugin' at the command prompt to receive instructions for troubleshooting.
```

Here's forcing the OS specific legacy renderer (which is happening above anyway), i.e. by using `Screen(‘Preference’,’TextRenderer’, 0)` 
```
PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.

PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.12 - Build date: Jan 14 2016).
PTB-INFO: Support status on this operating system release: OSX version 10.10 is not supported or tested anymore.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Installation of the PsychtoolboxKernelDriver is strongly recommended if you care about precise visual
PTB-INFO: onset timestamping or timing. See 'help PsychtoolboxKernelDriver' for installation instructions.


PTB-INFO: OpenGL-Renderer is ATI Technologies Inc. :: AMD Radeon R9 M370X OpenGL Engine :: 2.1 ATI-1.32.25
PTB-INFO: Renderer has 2048 MB of VRAM and a maximum 1928 MB of texture memory.
PTB-INFO: VBL startline = 1800 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback: Timestamps returned by Screen('Flip') will be less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.668663 ms [59.992813 Hz]. (50 valid samples taken, stddev=0.069763 ms.)
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: Psychtoolbox imaging pipeline starting up for window with requested imagingmode 33793 ...
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus drawing.
PTB-INFO: Enabling panel fitter. Providing virtual framebuffer of 1440 x 900 pixels size.
PTB-INFO: Will use 8 bits per color component framebuffer for stimulus post-processing (if any).
```

So what do you suggest as the best work-around/solution for this? Have you encountered any graphics/firmware update that helps the issue or a different way to handling drawing in PsychToolbox?

**Comment by dcnieho** [comment]
The solution is to get the new text rendered to load. Have you got all its
dependencies in place? Specifically, it needs some font handling libraries
that are by default not available on OSX. To quote selectively from the
release notes from the janurary release:

"The new text renderer on Windows works only if GStreamer is installed,
something that is normally optional if one doesn't want to play back or
write movie files or capture/record live video. If the requirements are not
met then PTB will fall back to the old legacy GDI text renderer. The same
happens btw. on OSX if the X11 X-Server isn't installed -- fallback to
Apples legacy CoreText renderer.
Another side effect of the new FTGL renderer is that the first invocation
of DrawText or TextBounds after updating to this beta will take very long -
possibly a minute or more - while FontConfig builds its initial font
database by scanning your system for fonts. So don't be surprised about
scripts hanging for a minute or so once. The same will happen after major
operating system upgrades which substantially change the set of installed
fonts."

Can you make sure X11 server is installed and then run, keeping in mind the
first drawing call can take a few minutes?

**Comment by kleinerm** [comment]
Seems that memory leak in Apples text rendering was already introduced before OSX 10.11, but after 10.8.

What Diederick says, just as following PTB's advice "Type 'help DrawTextPlugin' at the command prompt to receive instructions for troubleshooting." would have told you. Install the X11 X-Server XQuartz for OSX, that should make the new text renderer work. The first time you run a demo that draws text, the script will probably appear to hang for >= a minute as the new text renderer builds its font database.

The list of OSX bugs just doesn't end. It has far surpassed even bad versions of MS-Windows in buggyness by now. And almost none of them is fixable anymore with reasonable effort - or at all. I can only recommend getting rid of Apples toy operating system for this line of work.

**Comment by ljchang** [comment]
Yikes, this is pretty unbelievable.  Thanks @kleinerm and @dcnieho for your suggestions!  We'll report back soon.

**Comment by ejolly** [comment]
Hi @kleinerm @dcnieho I'm a graduate student with @ljchang actively trying to solve this issue. So I'm not quite sure how to explain this but something seems to have worked. Here's the current status:
On Friday I reinstalled PsychToolbox and XQuartz (as X11 is no longer officially distributed by Apple) and the memory issue did **not** get fixed, with the plugin unable to be loaded because the OS could not locate the plugin: 
`PTB-WARNING: DrawText: Failed to load external drawtext plugin 'libptbdrawtext_ftgl64.dylib' [dlopen(libptbdrawtext_ftgl64.dylib, 10): image not found].`

Moments ago I updated PsychToolbox again and now while the plugin is still claiming to fail at loading, the memory leak seems to have gone away! The behavior of DrawText is occurring as you described (first invocation takes a while).  Here's the latest output:
```
PTB-WARNING: DrawText: Failed to load external drawtext plugin [dlopen(/Applications/Psychtoolbox/PsychBasic/PsychPlugins/libptbdrawtext_ftgl64.dylib, 10): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Applications/Psychtoolbox/PsychBasic/PsychPlugins/libptbdrawtext_ftgl64.dylib
  Reason: Incompatible library version: libptbdrawtext_ftgl64.dylib requires version 19.0.0 or later, but libfreetype.6.dylib provides version 18.0.0]. Retrying under generic name [libptbdrawtext_ftgl64.dylib].
PTB-WARNING: DrawText: Failed to load external drawtext plugin 'libptbdrawtext_ftgl64.dylib' [dlopen(libptbdrawtext_ftgl64.dylib, 10): image not found]. Reverting to legacy text renderer.
```

I've also tried copying over the libptdrawtext_ftgl64.dylib file to /usr/lib and while that solves the "image not found" issue, it looks like there's version compatibility issue with libfreetype provided by the XQuartz release and what PsychToolbox expects
```
PTB-WARNING: DrawText: Failed to load external drawtext plugin [dlopen(/Applications/Psychtoolbox/PsychBasic/PsychPlugins/libptbdrawtext_ftgl64.dylib, 10): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Applications/Psychtoolbox/PsychBasic/PsychPlugins/libptbdrawtext_ftgl64.dylib
  Reason: Incompatible library version: libptbdrawtext_ftgl64.dylib requires version 19.0.0 or later, but libfreetype.6.dylib provides version 18.0.0]. Retrying under generic name [libptbdrawtext_ftgl64.dylib].
PTB-WARNING: DrawText: Failed to load external drawtext plugin 'libptbdrawtext_ftgl64.dylib' [dlopen(libptbdrawtext_ftgl64.dylib, 10): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /usr/lib/libptbdrawtext_ftgl64.dylib
  Reason: Incompatible library version: libptbdrawtext_ftgl64.dylib requires version 19.0.0 or later, but libfreetype.6.dylib provides version 18.0.0]. Reverting to legacy text renderer.
```

**Comment by kleinerm** [comment]
The memory leak is fixed in the latest "Nothing but the rain" PTB beta - i found a way around it. This time it was at least partially my fault, fixing other OSX text renderer bugs apparently introduced the memory leak under certain conditions.

The load failure is interesting. Are you using the latest version of XDarwin?
Do you have GStreamer installed, and if not, does installing it change anything?

**Comment by kleinerm** [comment]
Ok, see this PTB message for a solution for why the new text renderer isn't used on your setup:

https://groups.yahoo.com/neo/groups/PSYCHTOOLBOX/conversations/messages/20288

More OSX stupidity, mixed with some Matlab stupidity, it never fails to entertain...
