### ISSUE TITLE
Win64 64 bit Octave - DownloadPsychtoolbox, SetupPschtoolbox and UpdatePsychtoolbox - possible error?

### ISSUE THREAD

**Issue by galiloe** [Psychtoolbox-3/Psychtoolbox-3#316]
Hi,

I've just installed a 64 bit version of Octave (mingw, NOT cygwin) on Windows and when I tried to set up Psychtoolbox on this version it gave me a message that my version wasn't compatible.
Looking at the SetupPsychtoolbox.m  code I saw it was testing for

IsWin = ~isempty(strfind(computer, 'PCWIN')) || strcmp(computer, 'i686_64-w64-mingw32');

when i run computer() it returns x86_64-w64-mingw32

Should this test therefore also include a check for 'x86_64-w64-mingw32', as this was the value used by default on the build of the 64 bit windows version of Octave?  If so then this change is also needed in DownloadPsychtoolbox.m and UpdatePsychtoolbox.m

I made these changes to the scripts on my machine and the setup and update steps have now worked, and the Psychtoolbox functions I've tried using appear to be functioning without any problems.

**Comment by dcnieho** [comment]
In this case, i guess the check could become:
IsWin = ~isempty(strfind(computer, 'PCWIN')) || ~isempty(strfind(computer,
 '86_64-w64-mingw32'));

But unless it has changed very recently, right now 32bit octave, not 64bit
is supported on windows.

All the best,
Dee

**Comment by galiloe** [comment]
Thanks for the info - I wan't entirely clear on this point. If I  hit problems I'll revert to the 32 bit version, until the position changes.

**Comment by kleinerm** [comment]
64-Bit Octave is not really supported on Windows atm. I would support it if there would be an official upstream installer available for it, as is the case for 32-Bit. Maybe you can ask the Octave developers if they could consider providing such an official build.

The current PTB distro contains some test builds of mex files for 64-Bit Octave though, which i used with a cross-compiled 64-bit build of Octave for Windows to do the initial bringup. These are not maintained or updated atm., but the ones that are there will probably work fine. There isn't any technical reason, just that i don't want to maintain 32 Bit and 64-Bit, and my own cross-compiled mxe build, and all the required 3rd party 64-Bit dll's, so i'll wait until 64-Bit becomes available and then switch to 64-Bit, cancelling 32-Bit support again.
