### ISSUE TITLE
TextBounds: get advance as well

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#338]
Can we have an optional fourth output for Screen('TextBounds') that indicates the advance of the bounding box, i.e., how much further the cursor will be after the edge of the bounding box? I need this for a more advanced version of DrawFormattedText which also supports some HTML-like formatting commands. Those formatting commands mean that i can have multiple text segments on a single line, making the layouting impossible if i don't know how far the boxes should be apart and can't rely on this happening correctly automatically as it does in the simple left to right case. (This function is almost done by the way, just requires a bit of extension so it supports the same usage cases as the original DrawFormattedText).

I don't know if information about the advance is directly available from the BBox (the advance is a member variable of that class), but if not, here is the relevant bits of code that set the advance after a draw() call.

```
vector_scale_ = ( point_size_ * resolution_ ) / ( 72. * face->units_per_EM );

// Drawing a character always advances the MODELVIEW.
glTranslatef( face->glyph->advance.x / 64. * vector_scale_,
		     face->glyph->advance.y / 64. * vector_scale_,
		     0. );
```
To me, it is ok to only support this with the text plugin and not the other renders. My function will simply only be advised to use with the plugin renderer, which is necessary for other reasons too.

**Comment by kleinerm** [comment]
I have this implemented for 64-Bit Octave3/4 on LInux now. Don't know when i will rebuild for other platforms, but this will only affect PTB 3.0.13.

See this commit in my master branch:

https://github.com/kleinerm/Psychtoolbox-3/commit/21cde1a4e42ce9cb823915ef38013be8e1f5a0d9

**Comment by dcnieho** [comment]
Hi Mario,

That implementation looks beautiful. Thank you very much! I'll wait
patiently for the 3.0.13 series.

Thanks and all the best,
Dee

**Comment by kleinerm** [comment]
Ok, all platforms now updated in my own kleinerm repo master branch, if you want to try.
As this is v3.0.13 prep, 32-Bit Octave-4 on Windows is no longer supported/updated.

**Comment by dcnieho** [comment]
Cool! I've downloaded screen and the FTGL plugin, will give them a spin in the next few days :)

**Comment by dcnieho** [comment]
hmm, the advance does not seem to be completely reliable, sometimes being a pixel or two off.
I expect the left of the bounding box + the advance to be equal to where the drawing cursor ends up next (nx returned by DrawText). 
Some observations:

- ``nx`` is always 1 pixels less than left of next bounding box (well, i've seen 2 once...)
- left of drawn text's bounding box + advance is also sometimes one pixel more than ``nx``, that is good i guess. But i have seen it be 2 pixels more, and even 5 pixels once with a large font size.

This requires more investigation. I'll make an attempt to build the FGTL plugin myself, to see if i can attach the visual studio debugger (that works, have done it with other mex files before). I have VS2015 though, hope i wont run into version mixing problems... We'll see. More soon!

**Comment by dcnieho** [comment]
not sure if this is the right forum for this question, but might as well:

- i have installed newest gstreamer 1.8.1 (dev package)
- i got ftglplugin to compile with vs2015 (edited bat a bit). rendered text looks good, but advance returned is always 0. perhaps compatibility problem with screen, so:
- ran mex file compiler for Screen, also using vs2015 (this is windows 10, but using windows 8.1 sdk as is default, 64bit, newest matlab).

The generated mexfile can't be loaded by matlab. dependency walker shows nothing interesting, very similar output to mex files compiled by you.

Do you have an idea what should be my next step?

oh wait, i just see that also with your 3.0.13 compiled plugin file i have this problem. So perhaps its something with the newest gstreamer? Tmr i will try to attach a debugger and see if i can step through the code, see what's happening

**Comment by kleinerm** [comment]
There was some problem building with the latest GStreamer 1.8 SDK, because i think they screwed up delay loading. I reverted to 1.4 for building on Windows.

Wrt. the text advance: It doesn't measure from the left border of the bounding box, but from the previous text cursor position, which is usually not the same as the left bounding box. So if 'x' is the text position for drawing, nx = x + advance will be the new text cursor position - the one that would get returned by nx = Screen('DrawText'). See the commit message.

**Comment by dcnieho** [comment]
Hi Mario,

1st, you're right. the advance is from the active cursor position, such as passed into DrawText. All works beautifully now.

2nd, I didn't realize that i had to install both the devel and normal gstreamer lib as the two complement each other. That explained a lot about the sudden loading problems. I'm on 1.4 as well.

I've got an improvement to the FGTL plugin building bat file that gets rid of all the path management (VS has some batch files that do that for you). Interested?

**Comment by kleinerm** [comment]
Closing, as this is now part of 3.0.13.
