### ISSUE TITLE
Eyelink can not run on windows10 x64

### ISSUE THREAD

**Issue by gitforziio** [Psychtoolbox-3/Psychtoolbox-3#346]
```
>> Eyelink

In place of the expected mex file this placeholder file was executed:

  Eyelink

This mex file seems to be missing or inaccessible on your Matlab path or it is dysfunctional:

  Eyelink.mexw64

Hmm. I cannot find the file on your Matlab path?!?

One reason could be that your Matlab path is wrong or not up to date
for the current Psychtoolbox. You may want to run SetupPsychtoolbox to 
fix possible path problems.
```

`Eyelink.mexw64` is not found. But I found `Eyelink.mexa64`, `Eyelink.mexglx`, `Eyelink.mexmaci64` in `PsychBasic`.

It seems that Eyelink functions currently only support win32, osx, and linux64?

**Comment by dcnieho** [comment]
eyelink works on win64, though i have only tried windows 7. did you install
the sdk. does screen work?

**Comment by gitforziio** [comment]
Oh, it's strange. I can run `Screen` but just not `Eyelink`...

**Comment by dcnieho** [comment]
did you install the eyelink SDK and is it on the system path?

**Comment by gitforziio** [comment]
Oh, I see! That's why... Thank you!

**Comment by Yavar** [comment]
I am using PTB 3.0.13 on MATLAB 2016b 64 bit and Windows 10 x64. 

I've installed "vc_redist.x64" and "EyeLinkDevKit_win32_1.8.515" (as I did not find EyeLinkDevkit for win 64).

Although I've only found EyeLinkeDevKit... on this website:
http://www.cs.umb.edu/~marc/prexel/

and still I'm getting the same error while using "Eyelink" command.

"Screen" command is working well but the following commands also do not working:

Datapixx
PsychkinectCore
moalCore
moglCore

for each of the above commends am getting respected error with X.mexw64 ...

Any ideas? I would really appreciate it. :)

**Comment by tere93** [comment]
Hi there,
 Did you fix this problem? I am having exactly the same one. I have tried changing the compiler, reinstalling matlab, installing a SDK 7.1... but nothing works. It is driving me crazy!

Thanks!

Teresa

**Comment by iandol** [comment]
Teresa, what exact problem with which versions are you having exactly? I have run PTB with Eyelink on 64bit Windows 10 (though have now "upgraded" to Linux, as it is much better for Psychophysics with PTB), and although I initially had multiple path problems:

https://www.sr-support.com/showthread.php?5267-invalid-Eyelink-mexw64-file-eyelink-dll-missing

It does work. You certainly should be using the 32/64 dev kit from SR-Research and not anything else (as @Yavar seems to suggest). Sadly my solution involved multiple reboots and tweaking and I didn't clearly understand the precise steps to get it to work. But perhaps something in that thread will help?
