### ISSUE TITLE
EyeLink Toolbox demo offline possible

### ISSUE THREAD

**Issue by siyuanyin** [Psychtoolbox-3/Psychtoolbox-3#359]
Hi, I am wondering whether it would be possible that I run Eyelink toolbox demos without actually running the real Eyelink system. Any suggestions would be appreciated.
Thanks,
Siyuan

**Comment by dcnieho** [comment]
off the top of my head: EyelinkInit() has an option parameter to run it in
dummy mode. You'll need to have the eyelink sdk installed on your computer,
bu no actual connection with the eyelink is made

**Comment by siyuanyin** [comment]
Thanks for your reply. May I ask where I can find the eyelink sdk installation. Very much appreciate it!

**Comment by kleinerm** [comment]
From SR-Researchs support website, once you have a customer account with them.
