### ISSUE TITLE
NFO: PTB's Screen('Flip', 10) command seems to have missed the requested stimulus presentation deadline

### ISSUE THREAD

**Issue by vistamasiha** [Psychtoolbox-3/Psychtoolbox-3#360]
Dear All,

I'm having the same problem (below) running Psychtoolbox 3.0.13 (in Matlab 2015a) on Macbook Air with El Capitan. I was hoping if any one could help me to resolve it. 

INFO: PTB's Screen('Flip', 10) command seems to have missed the requested stimulus presentation deadline
INFO: a total of 630 times out of a total of 46286 flips during this session.

INFO: This number is fairly accurate (and indicative of real timing problems in your own code or your system)
INFO: if you provided requested stimulus onset times with the 'when' argument of Screen('Flip', window [, when]);
INFO: If you called Screen('Flip', window); without the 'when' argument, this count is more of a ''mild'' indicator
INFO: of timing behaviour than a hard reliable measurement. Large numbers may indicate problems and should at least
INFO: deserve your closer attention. Cfe. 'help SyncTrouble', the FAQ section at www.psychtoolbox.org and the
INFO: examples in the PDF presentation in PsychDocumentation/Psychtoolbox3-Slides.pdf for more info and timing tips.

My stimulus is running but the dots and the circle/oval are not well presented during motion, there is sort of a tail/sequence behind every dot/circle only when it's moving!

Any suggestions would be highly appreciated. 

Thanks,
vista

**Comment by dcnieho** [comment]
Tails have nothing to do with Screen flip missing deadlines. Tails are due
to ghosting, or your screen not being able to switch between light and dark
quick enough. Even if it could, some are generated in your eyes as well
(motion streak) with high contrast stimuli especially. Google for ghosting,
or display persistence.

Cheers,
Dee

**Comment by vistamasiha** [comment]
Dear Dee,

Thank you for the feedback. My visual paradigm is, in fact, a motion localiser (for 9.4t fMRI experiments) with high contrast. Someone suggested that I'd better off giving up the idea of running such stimulus on a laptop since the built-in graphic card can never keep up with the power required for executing the stimulus! In any case, thanks for making the time and suggesting something rather than giving up!

Best,
vista
