### ISSUE TITLE
"TTL triggers for OSX and Linux" FAQ links to pages without the necessary files

### ISSUE THREAD

**Issue by brittyazel** [Psychtoolbox-3/Psychtoolbox-3#364]
https://github.com/Psychtoolbox-3/Psychtoolbox-3/wiki/FAQ#ttl-triggers-for-os-x-or-linux-machines

Both Option 1 and 2 send to pages that seem to reference solutions with files that are no longer available. 

I am in great need of sending parallel port codes from within Matlab on Linux for recording EEG on our Biosemi system. Do you have a copy of the code that would have been on these pages? If so, can I have it? Further, it might be beneficial to update the FAQ with working links to the files + documentation. Perhaps hosted on Dropbox or the like, as long as the files are available.

**Comment by kleinerm** [comment]
Hi,

at the moment you could use this one (mex file included) if you want a simple solution that can only send triggers:

https://github.com/widmann/ppdev-mex

Or this one for a more complex solution that also can receive triggers (i think this was part of the original link):

https://github.com/nielllab/ratrix/tree/trunk/classes/util/parallelPort

**Comment by brittyazel** [comment]
Hi, that first link worked great and does everything I need. I only need to send triggers, not receive them
