### ISSUE TITLE
improve psychHID cookedKey on windows

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#373]
As it is now, the cookedKey ignores the state of capslock, as well as the right alt modifier as used in e.g. Swedish and German. As far as i can see, the state of these can be provided to ToAsciiEx, like is already done for shift. Shall I implement this? I see no backward compatibility problems, the cookedKey field will simply be correct in more cases (it is meant to provide a guess of the typed character after all, and it does a pretty good job usually).

Two further improvements i would like are:
- when ToAsciiEx puts more than one character into the buffer, provide the last in the cookedKey return instead of ignoring as is done now. The second of the two characters put in the buffer matches the key-press of the second keypress. Two keys are put in the buffer if there was a dead key pressed before, but the current keypress could not compose with it. This change should not have backward compatibility concerns, it again leads to correct output in more corner cases.
- still provide cookedKey if a dead key (e.g. a diacritic) is pressed. It would however be necessary to indicate somehow that this is a dead key. Since the cookedEventCode field is an int, perhaps this could be indicated by negating the returned cookedEventCode. This would of course have to be default-off, enabled by the user setting a preference.

I'd be happy to implement all four items a.s.a.p., go on all four?

**Comment by kleinerm** [comment]
Sounds all reasonable. Except for last point of returning dead keys like diacritic's. What would be the value of that?

**Comment by kleinerm** [comment]
I think this is done with latest PTB beta, so closing.
