### ISSUE TITLE
KbStrokeWait function is not available(freezing on Mac).

### ISSUE THREAD

**Issue by kimju7929** [Psychtoolbox-3/Psychtoolbox-3#376]
Hello!

I tried to run some tutorial provided by PTB website. 
I'm using the Matlab on my Mac os(2015 Macbook pro retina) with OSX 10.12.
But, in every project when I run it, my Mac doesn't respond to pressing any Key. 
Moreover, I can't escape from Key-input phase.
In this phase, my mac show me gray screen.
It's not completely freezing, because when I press Command+F5, I can hear the Voice Over function of Mac functioning.

I deleted the KbStrokeWait function line on script and ran it, there is no problem but I can't use Key-input function.
Please help me.

**Comment by kleinerm** [comment]
Do our demos like KbDemo work? KbStrokeWait at the command line? Psychtoolbox the latest version of the 3.0.13 series? Did it work on older OSX versions? Output of GetKeyboardIndices? Maybe there are multiple keyboards connected and you are waiting on the wrong one?

**Comment by kimju7929** [comment]
I copied and pasted the whole codes in “tutorial - (1) The bsics - Totally Minimal Demo.” to script window of my matlab .

Following your advice, I typed “KbStrokeWait” at command window, and this is the result.



And I don’t know what should I do from here…..

Psychotoolbox is the latest version(3.0.13).

I don’t have older OSX versions so that I couldn't test it.

I didn’t understand about “output of GetKeyboardIndices”. Is it about keyboard setting of the Psychtoolbox on the Mac?

I don’t use any other keyboard but only the keyboard of Macbook Pro.

**Comment by kimju7929** [comment]
I copied and pasted the whole codes in “tutorial - (1) The bsics - Totally Minimal Demo.” to script window of my matlab .

Following your advice, I typed “KbStrokeWait” at command window, and this is the result.



And I don’t know what should I do from here…..

Psychotoolbox is the latest version(3.0.13).

I don’t have older OSX versions so that I couldn't test it.

With “GetKeyboardIndices”, I got this result.



I don’t use any other keyboard but only the keyboard of Macbook Pro.

**Comment by kleinerm** [comment]
What do you mean with "this is the result"? KbStrokeWait should wait until you hit a key, then return to the Matlab prompt. Does it do that? Or does it hang?

If you type GetKeyboardIndices, what is its output in the Matlab window? It must output something, no?

**Comment by kimju7929** [comment]
I sent you email with some picture. 
When I run these codes, the gray screen come up at last.
I thought this wait for me pressing one key. 
But I doesn't respond to pressing any keys, showing the gray screen.
No return to the Matlab prompt. 
For "GetKeyboardIndices", this is the result.

ans =
         1      2      6

**Comment by kleinerm** [comment]
Ok, what is the output when you execute [keyboardIndices, productNames, allInfos] = GetKeyboardIndices
If you execute KbStrokeWait(-1) does that wait for a key press?

**Comment by kimju7929** [comment]
the result is,

keyboardIndices =
1  2  6

productNames =

1x3 cell array

'Keyboard'  'Deyboard'  'Apple Internal Keyboard / Tra...'

allInfos =

1x3 cell array

[1x1 struct]  [1x1 struct]  [1x1 struct]

And for KbstrokeWait(-1),

ans = 

6.7199e+04

I have checked "KbStrokeWait(-1)" on script Editor, It's working!!
You are amazing!!
How do you know it?! What was the problem?!

**Comment by kimju7929** [comment]
Should I always the "KbWait(-1), KbStrokeWait(-1), KbPressWait(-1)....."???
Is there a way to use like just "KbStrokeWait"??

**Comment by kleinerm** [comment]
For some reason your computer detected 3 keyboards instead of just the one which is built into it, so you need to tell the functions which keyboard to use, or you need to use the -1 parameter to tell them to check all keyboards.
I don't know where those extra keyboards come from if you really only have 1 keyboard on your machine. Do you have some keyboard via Bluetooth connected. Or do you know what a "Deyboard" is supposed to be?

**Comment by kimju7929** [comment]
I have no idea about what is the "Deyboard". 
I never have used any Bluetooth keyboard before, but only some Bluetooth speakers, headphones, a mouse.
The mouse could be the problem of my case?

**Comment by kleinerm** [comment]
I don't know. Your Mac thinks that some connected device (could be via USB or via Bluetooth) is a keyboard, so it treats it as such. That's all i can say. If you disconnect all USB devices and disable Bluetooth, maybe that helps to find out which device causes the trouble. Or maybe OSX 10.12 is just faulty on your Mac - macOS is a rather buggy system nowadays, and that causes misdetection of keyboards. Otherwise you'll have to specify that -1 flag all the time to tell Psychtoolbox to check all keyboards for key presses.

**Comment by kimju7929** [comment]
I see. 
Thanks for your kind advice so much.
Finally I can move to next stage :)
It was nice you were here this forum. 
I hope this issue can be resolved later.
