### ISSUE TITLE
Starting OpenGL > 3 context with moglcore. Possible?

### ISSUE THREAD

**Issue by CarloNicolini** [Psychtoolbox-3/Psychtoolbox-3#379]
I found problems in using all the commands that are available when a OpenGL context > 3 is needed, in particular, glGenBuffer was always returning 0 (and I saw that this is still an open issue).
Also I'd want to use geometry shaders in my code, and this seems not possible, since `#version 330` is needed for geometry shaders.
Any idea on how to modify the `InitializeMatlabOpenGL` function to start a OpenGL4 context?
I think in some way `glew` has to be used, that allows for a newer OpenGL context to start.

**Comment by kleinerm** [comment]
Have you tried Octave or a Matlab version before 2015b? glGenBuffers() should work on anything before R2015b or on Octave. That it doesn't work on later Matlab's is a known compatibility issue.

In general most of the OpenGL 3.1+/4 functionality is also available as ARB extensions, so you will need to use the glFooARB() variants of glFoo().

Creating an OpenGL context > 3 would need to be done by PTB's Screen command. This is not implemented at the moment. In principle we could request such a context for use with moglcore, but that context would not be backwards compatible with OpenGL <= 3 on at least Linux and OSX. Furthermore it is not clear if such a context could share things like framebuffer resources with Screen(), which would be highly problematic.

But as i said, OpenGL3/4 is also exposed to GL2 contexts via ARB extensions, so there isn't a loss in functionality.
