### ISSUE TITLE
Dead link on the citations page

### ISSUE THREAD

**Issue by danprec** [Psychtoolbox-3/Psychtoolbox-3#380]
The HTML link on "Kleiner M, Brainard D, Pelli D, 2007, “What’s new in Psychtoolbox-3?” Perception 36 ECVP Abstract Supplement. [HTML]" on the credits page is a dead link. 

Also, the "Credits" page can only be reached through an explicit search in google, not through the home website.

Editors have raised questions about the validity of such citations if they lead to dead links.

**Comment by kleinerm** [comment]
Ok thanks for letting us know. Updating the Wiki is unfortunately one of those things nobody has time much for. But then simply removing the dead link on the citation should solve that questions. The link is not part of the citation, just there for convenience, so people know what they are citing?
