### ISSUE TITLE
IOPort/OpenPort and high port numbers (Windows)

### ISSUE THREAD

**Issue by qx1147** [Psychtoolbox-3/Psychtoolbox-3#381]
IOPort('OpenSerialPort', ...) doesn't recognize ports above COM9. The workaround is easy, just specify '\\\\.\COM14' instead of 'COM14', for example. This notation is also valid for low port numbers (see https://support.microsoft.com/en-us/kb/115831).
It would be nice to have this fix added in IOPort.

**Comment by qx1147** [comment]
The current change (01.11.2016) would break Matlab code that uses the '\\\\.\' notation already. This is perfectly fine with me, so I just wanted to mention it.

**Comment by kleinerm** [comment]
I hope nobody uses that notation, because i only just read your comment after releasing the beta with the new behavior.

**Comment by kleinerm** [comment]
I implemented handling of the \. notation in IOPort for the next beta, currently in my master branch.
