### ISSUE TITLE
Psychotoolbox 3.0.9

### ISSUE THREAD

**Issue by yingzzzz** [Psychtoolbox-3/Psychtoolbox-3#386]
Hi! I am new to programming and I am trying to download Psychotoolbox 3.0.9 because my Windows is 32-bit. I downloaded the 3.0.9.zip file but the script for MATLAB did not work. Specifically, it told me to enter a savepath but when I entered the path, it always said that the script was wrong. I tried different sentences/formats to enter the savepath but still failed... Can anyone tell me how to download the 3.0.9 version? Thank you!

-Ying

**Comment by dcnieho** [comment]
I dont understand the problem you're seeing. But, you want 3.0.11, thats
the last version that supported 32bit matlab on windows.

Cheers,
Dee
