### ISSUE TITLE
Psychtoolbox 3.0.9 on 32 bit Windows 7 not installing

### ISSUE THREAD

**Issue by Legacy3424** [Psychtoolbox-3/Psychtoolbox-3#398]
We have download the subversion client: Slik-Subversion-1.9.5 32 bit and then tried installing Psychtoolbox. This is the error we keep receiving: 

svn: E170013: Unable to connect to a repository at URL 'https://psychtoolbox-3.googlecode.com/svn/beta/Psychtoolbox' 
svn: E160013: '/svn/beta/Psychtoolbox' path not found 
Sorry, the download command "CHECKOUT" failed with error code 1: 
svn: E170013: Unable to connect to a repository at URL 'https://psychtoolbox-3.googlecode.com/svn/beta/Psychtoolbox'
svn: E160013: '/svn/beta/Psychtoolbox' path not found

Please help!

**Comment by kleinerm** [comment]
Googlecode shut down its repositories. Get the final 3.0.9 zip file from this link:
https://github.com/Psychtoolbox-3/Psychtoolbox-3/archive/Psychtoolbox-3.0.9.zip
Unzip, In Matlab go into the Psychtoolbox folder, run SetupPsychtoolbox.
Needless to say these old versions are completely unsupported in case of any further problems.
