### ISSUE TITLE
Survey Psychtoolbox3

### ISSUE THREAD

**Issue by mtaranu** [Psychtoolbox-3/Psychtoolbox-3#399]
Hello, 
I am running a visual experiment using Matlab and Psychtoolbox. For each of the experimental blocks that I need to run (they are very many blocks) the white screen with a message to complete the Psychtoolbox experience survey appears on the screen. While I definitely understand the need for this survey to be distributed I was wondering if there is any way I can make it stop while running an experiment.
It distracts participants and takes very long time from the experiment.

Your feedback will be greatly appreciated!

Best regards, 
Mihaela

**Comment by dcnieho** [comment]
You probably should not close and reopen the screen for every block

**Comment by mtaranu** [comment]
Hi Diederick, 
Thank you for your response! I am not sure yet how this could solve the problem. Before every block I have to show instructions and give a break. There is no way this message can be made not to show up on the screen when Psychtoolbox launches?

**Comment by dcnieho** [comment]
It sounds like you are using someone else's code? Ask them for help. There
is no reason why you would need a fresh psychtoolbox sessions to be able to
show instructions. I think there is a way to make the startup screen
without message. search this forum and it should come up (I have a memory
of it).

**Comment by kleinerm** [comment]
Screen('Preference', 'VisualDebugLevel', level); for a low enough 'level' will replace it by a black screen.
But as Diederick said, if you reopen the window for each block of trials you are doing it wrong. Simply learn how to display some "Take a break" text on the screen and wait for a keystroke instead. There are enough demos and tutorials to show how to do it.

**Comment by mtaranu** [comment]
Thank you both for the responses. I understand what you are saying. Fair point. However, this doesn't really solve the problem with the message to complete the survey which appears when Psychtoolbox starts.  I have tried as well what Mario said with Screen('Preference', 'VisualDebugLevel', level), but that doesn't seem to affect the message you get on the screen, it's still there.  I haven't seen this message in any of the previous versions of psychtoolbox.

**Comment by dcnieho** [comment]
There has always been a startup message, before it was just different.

And not closing and reopening the screen all the time does solve your
problem i assume? Then subjects won't be confused by the message in the
middle of the experiment.

What visual debug level did you try?

**Comment by mtaranu** [comment]
Indeed, the startup message was always there but this time is a bit different. It has more text and red color. Anyway. I used Screen('Preference', 'VisualDebugLevel',0l).

**Comment by kleinerm** [comment]
VisualDebugLevel 0 will suppress the startup screen and show black only. Unless your script would do something like "clear all" and thereby undo the setting before opening the onscree window. I assume your Psychtoolbox is up to date?

**Comment by mtaranu** [comment]
Yes, I have the latest version of the Pychtoolbox. I was expecting as well
that VisualDebugLevel 0 will show black screen only, but doesn't happen.
Will need to investigate this further, thank you for you suggestion with
the "clear all".

**Comment by kleinerm** [comment]
I know that it works with the latest PTB beta, so something must be wrong with your code if it doesn't.

But again, closing and reopening the window for every block is the wrong/more unreliable approach, and it is trivially easy to show instructions like "Have a break!" and wait for a key press to advance to the next block. We have tons of demos to show how to do that, e.g., DrawSomeTextDemo.
