### ISSUE TITLE
legacy: Check PCI ID's for AMD Southern Islands gpu's etc. for updates

### ISSUE THREAD

**Issue by towolf** [Psychtoolbox-3/Psychtoolbox-3#40]
`original reporter: kleinerm`
`tags: medium priority`

May need to cross-check and add new pci id's for most recent AMD gpu's to make sure DCE display engines are correctly detected for latest hw.

**Comment by kleinerm** [comment]
Updated to state at end of March 2015 (last update commit October 2014-10-28). Would need updates for anything after start of April 2015.

**Comment by kleinerm** [comment]
Updated to state at end of June 2015 (last update commit 2015-05-12). Would need updates for anything after start of July 2015.

However, this only covers up to DCE-8. DCE-10/11 are completely missing atm.. PCI ids for the gpu's handled by amdgpu are now contained in this new location:
http://cgit.freedesktop.org/~airlied/linux/tree/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c?h=drm-next

Update for DCE10/11 "Volcanic Islands" pending.

**Comment by kleinerm** [comment]
Mappings up to date for end of October (last update commit 2015-10-21). Would need updates for anything after start of November 2015.

**Comment by kleinerm** [comment]
Mappings up to date as of 11 February 2016, no commits since 2015-10-21.

**Comment by kleinerm** [comment]
New address of driver (drm-next moved repos):
https://cgit.freedesktop.org/drm/drm/log/drivers/gpu/drm/amd/amdgpu/amdgpu_drv.c

**Comment by kleinerm** [comment]
Mappings up to date as of 26. June 2018, no relevant commits since 2018-5-18.
Includes VEGA12, VEGA20, VEGA-M, all mapping to DCE-12.

**Comment by kleinerm** [comment]
As all new (later than year 2018) AMD gpu's have an unsupported DCN engine, the current mapping is stable and this periodic task is no longer necessary.

Closing as done.
