### ISSUE TITLE
Master-Abort key '@'

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#403]
I believe this is only for Windows, and it is a little annoying to have the chance that when someone types, they may hit it without knowing. In my case, i am making a textbox, and found this key when trying to type it (of course :p). Do we need it, or can we remove it? If we do, can we make it a more complex key combination?

**Comment by kleinerm** [comment]
Ok, that one i removed for the next beta.

**Comment by dcnieho** [comment]
thanks!
