### ISSUE TITLE
FloatTextureDemo - frame buffer object creation error

### ISSUE THREAD

**Issue by TomSar** [Psychtoolbox-3/Psychtoolbox-3#405]
Hello,

I am trying to run the Matlab demo FloatTextureDemo which is in Psychtoolbox\PsychDemos\OpenGL4MatlabDemos 
but I am getting the following error:
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Error using moglcore
MOGL-Error: Your OpenGL command glFramebufferTexture2DEXT() caused the following OpenGL error: invalid operation. Aborted.

Error in glFramebufferTexture2DEXT (line 15)
moglcore( 'glFramebufferTexture2DEXT', target, attachment, textarget, texture, level );

Error in moglCreateFBO (line 116)
    glFramebufferTexture2DEXT(GL.FRAMEBUFFER_EXT, GL.COLOR_ATTACHMENT0_EXT + i - 1, GL.TEXTURE_RECTANGLE_EXT, texids(i), 0);

Error in FloatTextureDemo (line 63)
    [fbos(1), tex ]=moglCreateFBO(msize, msize, 2);
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

My understanding is that frame buffer object - FBO - cannot be created. I need this function to create a VR visual stimulus so any help or directions on how to create a FBO would be very much appreciated.

BTW, I am running Matlab 2016a in a Windows 7 machine with a NVS510 video card.

Thank you very much for your help.

**Comment by kleinerm** [comment]
I think you're not running Psychtoolbox 3.0.13 or later, so please update to the latest PTB. Mathworks introduced a bug into Matlab R2015b and later versions which might cause this error on your R2016a, unless you have a recent Psychtoolbox which has workarounds in place for said Matlab bug.

Btw. PTB allows you to create onscreen windows (see help PsychImaging for the 'PsychImaging('AddTask', 'General', 'FloatingPoint32Bit'); task), and offscreen windows (Screen('OpenOffscreenwindow', ...)) with floating point framebuffers, for floating point 2D drawing, but also for access as float textures via Screen('GetOpenGLTexture',...). Often that is way more convenient than dealing with low-level GL calls for FBO's, float textures etc. directly.
