### ISSUE TITLE
Specify custom IP address for EyeLink toolbox

### ISSUE THREAD

**Issue by Rnmcg** [Psychtoolbox-3/Psychtoolbox-3#414]
Hi,

I am using the Eyelink Toolbox on Matlab to run an experiment integrated the Eyelink 1000. There are lots of other people using the same lab who have manually changed the IP address (for reasons pertaining to their own research paradigms that involve EEG), so it is not the default Eyelink IP (100.1.1.1, 100.1.1.2). Would there any way of adding functionality for specifying custom IP addresses from the Eyelink Toolbox script?

Thanks

**Comment by sr-brian** [comment]
Hi Rnmcg, 

Please try:
`Eyelink('SetAddress', ipaddress);`

Brian
