### ISSUE TITLE
sampling rate on mcc 1208fs is lower than is said in the manual

### ISSUE THREAD

**Issue by lain112358** [Psychtoolbox-3/Psychtoolbox-3#419]
HI
I work from Windows XP in Matlab2008a and use MCC 1208fs board as analog ouput
The sampling rate according to the manual is 10000hz (http://www.mccdaq.com/pdfs/manuals/USB-1208FS.pdf), while through Psychtoolbox I get only 1000hz:

Display Summary of Analog Output (AO) Object Using 'USB-1208FS'.

       Output Parameters:  1000 samples per second on each channel.

Is there something wrong with the computer, software or there is a mistake in the manual?

**Comment by kleinerm** [comment]
The "help DaqAOutScan" help mentions that our routines can only achieve about 2000 Hz on that device on OSX for unknown reasons - at least unknown to Denis Pelli who wrote that code. Maybe it is just the same on Windows, in this case only achieving 1000 Hz.

You could try to pass in the optional 'options' parameter struct, set to 'options.getReports=0' and see if the function still works correctly (i have no idea) and if that improves performance or not. Or use the Matlab profiler to find out where lots of time is spent inside that M-File. I don't have such a device, so you are mostly on your own with this.

**Comment by kleinerm** [comment]
Ok, no response, so closing.

**Comment by lain112358** [comment]
Good afternoon

Sorry for being late in responding, I will certainly try to check what you
have suggested. Thanks for helping

пн, 26 июня 2017 г. в 21:32, Mario Kleiner <notifications@github.com>:
