### ISSUE TITLE
Screen('ConfigureDisplay','Brightness',...) is not reliable.

### ISSUE THREAD

**Issue by denispelli** [Psychtoolbox-3/Psychtoolbox-3#424]
dear mario
the Psychtoolbox command to set display brightness is flakey on my MacBook Air. (That's the only computer I tested.)
Screen('ConfigureDisplay','Brightness',screen,[],brightnessSetting)
I've tried single stepping through my MATLAB code while watching the display and the System Preferences Displays panel. (Incidentally, the AutoBrightness command does reliably turn autobrightness on and off.)
The Brightness command with a value of 1 usually (but not always) increases the screen brightness. But, weirdly, the brightness slider never moves. So the screen brightness becomes 1, while the slider remains, e.g. at 0.5. Any operation that brings focus back to the Displays panel brings brightness back down to whatever the slider is at. This is not what I remember. My recollection is that setting the brightness also moved the slider. My guess is that the behavior changed in one of the macOS releases. I realize that this may be beyond our reach. I'm just mentioning it to alert others and in the hope that perhaps there is a way to fix it.

best
denis

AutoBrightness(screen,0);
brightnessSetting=1;
brightnessReading = Screen('ConfigureDisplay','Brightness',screen,[],brightnessSetting)
brightnessReading = Screen('ConfigureDisplay','Brightness',screen,[])

**Comment by kleinerm** [comment]
Actually that's not our fault. It was implemented and tested and it worked fine in the past on different MacBooks. If it doesn't work properly now without me changing any related code then that's a macOS bug and should be filed to Apple:

https://developer.apple.com/bug-reporting/

Ideally with a copy to OpenRadar, so people can keep track if or how (or how poorly) Apple handles issues:

http://www.openradar.me/

Closing as invalid.

**Comment by kleinerm** [comment]
Still works fine on MBP 2010 with latest OSX 10.12, so not a general OSX bug.

**Comment by denispelli** [comment]
dear mario
thanks for checking what do you mean by "works". What I reported is that
it's unreliable. If you watch the preference panel while the  command acts
you see that the brightness changes, but the slider doesn't move. (it
should move, and used to under older OS versions.) The slider in the wrong
position bites you if the panel receives focus, and the brightness goes
back down. playing with it more reveals more weirdness, including
brightening that is much delayed. for experiments we need something
reliable.

the effect on brightness is unreliable and thus hard to test for. the
failure to move the slider is solid and easy to check for.
best
denis


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University
+1-646-258-7524 | denis.pelli@nyu.edu | http://psych.nyu.edu/pelli/ | Skype:
denispelli <#> | http://denispelli.com
<http://www.facebook.com/denispelli>
<http://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli>
