### ISSUE TITLE
Error in running SimpleMovieDemo

### ISSUE THREAD

**Issue by taliweiss** [Psychtoolbox-3/Psychtoolbox-3#427]
Hi all,
If someone has an idea and can help me...

when I tried to run SimpleMovieDemo I get an error
I am running with two screens, other Demos (like ImageMixingTutorial) do works...
----------------------------------------------------------------------------------------------------------
Error in SimpleMovieDemo (line 46)
    win = Screen('OpenWindow', screenid, 0, windowrect);

Running on Matlab for Microsoft Windows, with JVM enabled!
This may crash. See 'help GStreamer' for problem and workaround.

**Comment by iandol** [comment]
Have you followed all the instructions in `help GStreamer`?

**Comment by kleinerm** [comment]
No feedback, closing.
