### ISSUE TITLE
long delay at first use of textrenderer, each time

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#429]
I have recently installed a few professional fonts on my Windows 10 64 bit (up to date) system. I'm running the  master branch from here in Matlab R2017a.

After i installed the fonts, each time an form of text rendering is called for the first time for a new window, I have a 15 second delay until Screen returns. See below sample code and output from running it. Note that this code opens a window twice, 

I can't rule out this is coincidence of course. How would I go about investigating this, i.e., what are likely spots where this slowdown could happen and where i could thus put some time stamping stuff in the C code? High verbosity doesn't reveal anything that looks interesting to me, textrenderer just loads.

Thanks!
p.s. on an unrelated note, is there a way to get help for the specific preferences, like if i want to see the various options of Screen('Preference', 'TextRenderer')?

```
clc; clear all;

Screen('Preference', 'SkipSyncTests', 1);

try
    for p=1:2
        wpnt = Screen('OpenWindow', 0, 127);
        % Ensure the high quality text renderer is used
        Screen('Preference', 'TextRenderer', 1);
        
        t = Screen('Flip',wpnt);
        for q=1:20
            Screen('DrawText', wpnt, 'bla');
            t(end+1) = Screen('Flip',wpnt);
        end
        
        diff(t)
        
        sca;
    end
catch ME
    sca;
    rethrow(ME);
end
```

relevant output:
```
ans =

  Columns 1 through 7

   16.1802    0.0191    0.0061    0.0064    0.0176    0.0062    0.0062

  Columns 8 through 14

    0.0188    0.0063    0.0067    0.0062    0.0175    0.0074    0.0184

  Columns 15 through 20

    0.0062    0.0066    0.0187    0.0063    0.0066    0.0054



ans =

  Columns 1 through 7

   16.0723    0.0061    0.0156    0.0068    0.0062    0.0165    0.0082

  Columns 8 through 14

    0.0061    0.0157    0.0071    0.0063    0.0183    0.0066    0.0063

  Columns 15 through 20

    0.0180    0.0080    0.0063    0.0157    0.0072    0.0061
```

**Comment by kleinerm** [comment]
That's normal. Adding new fonts means the fontconfig cache needs to be rebuilt, and that takes time. This is triggered automatically by libfontconfig on first init (fc_init() iirc?) after the fonts on the machine have changed.

**Comment by dcnieho** [comment]
Hi Mario,

This happens every time i open a new window. There is always the 16 second delay. That wouldn't be normal?

Cheers,
Dee

**Comment by kleinerm** [comment]
Nope, it should be a one-time thing. The fc_init() in the plugin would still be the best starting point to investigate. Or maybe looking if something weird happens with Windows security features like filesystem virtualization or how was that hack called that allows to "install" stuff into system folders, while not actually installing there, but redirecting to a safe location. Just a hunch, no idea if that matters, but i assume it's some Windows related problem if it happens all the time.

**Comment by qx1147** [comment]
@dcnieho I cannot reproduce this on my Win10 test PC. It is a one-time thing, as Mario says. Is the HQ renderer actually used (smooth text)? What happens if you place the 'TextRenderer' call at the beginning of your script? Do you have the directory "C:\Users\account\AppData\Local\fontconfig\cache"? Your gstreamer version?

**Comment by dcnieho** [comment]
@qx1147 thanks for the suggestions! The HQ renderer is used, i dont see the slowdown if forcing the old GDI renderer. The slow down happens at the first drawtext call, not the TextRenderer call. i have the fontconfig directory and my gstreamer was freshly installed a few months ago, recommended version i think. I'm going to put some timing statements in the C code to see where the slowdown occurs. Thanks!

**Comment by dcnieho** [comment]
Hmm, turns out something was funky in fontconfig's cache files i guess. The slowdown was indeed caused by the FcInit() call. But upon deleting files in "C:\Users\account\AppData\Local\fontconfig\cache", after they were regenerated the first time i ran my script, all subsequent times now take a normal amount of time. Thanks for the help!
