### ISSUE TITLE
Get struck in text-related functions

### ISSUE THREAD

**Issue by Sunflow2** [Psychtoolbox-3/Psychtoolbox-3#436]
If I use text-related functions, such as Screen('DrawText') or DrawFormattedText, it always get struck(no response) and i have to quit matlab without any error information.
My OS is Windows 10, the verision of matlab is R2016a, and i have updated PTB to the latest version.

**Comment by dcnieho** [comment]
This is normal for the first time. It can take a few minutes. Let it run,
and it'll eventually come out of it. It's checking all the fonts you have.
Shouldn't occur after that, unless you add new fonts.

All the best,
Dee

**Comment by Sunflow2** [comment]
Yes, waiting for minutes does work, thank you!
But the waiting time does not reduce after that, seeming that it need the same time to check fonts.

**Comment by dcnieho** [comment]
I've had this problem too. Deleting the fontconfig cache files (Google to
find out where they are, not near a computer now) did the trick for me.

**Comment by kleinerm** [comment]
From issue #429 : But upon deleting files in "C:\Users\account\AppData\Local\fontconfig\cache", after they were regenerated the first time i ran my script, all subsequent times now take a normal amount of time. Thanks for the help!
