### ISSUE TITLE
 Problem with running real experiment 

### ISSUE THREAD

**Issue by AmDeh** [Psychtoolbox-3/Psychtoolbox-3#442]
Hi, I have a problem in windows 7, I want to show two images in screen and
 one of images is a plot which is updating during experiment, but the problem is the plot
 which was converted to images (and is updating) will not be shown, the following warning is showing:

 >PTB-ERROR: Screen('Flip'); beamposition timestamping computed an *impossible
> stimulus onset value* of 13025.295485 secs, which would indicate that
> PTB-ERROR: stimulus onset happened *before* it was actually requested!
> (Earliest theoretically possible 13025.298162 secs).
>
> PTB-ERROR: Some more diagnostic values (only for experts): rawTimestamp =
> 13025.302650, scanline = 322
> PTB-ERROR: Some more diagnostic values (only for experts):
> line_pre_swaprequest = 112, line_post_swaprequest = 118,
> time_post_swaprequest = 13025.298291
> PTB-ERROR: Some more diagnostic values (only for experts):
> preflip_vblcount = 0, preflip_vbltimestamp = -1.000000
> PTB-ERROR: Some more diagnostic values (only for experts):
> postflip_vblcount = 0, postflip_vbltimestamp = -1.000000,
> vbltimestampquery_retrycount = 0
>
> PTB-ERROR: This error can be due to either of the following causes (No way
> to discriminate):
> PTB-ERROR: Either something is broken in your systems beamposition
> timestamping. I've disabled high precision
> PTB-ERROR: timestamping for now. Returned timestamps will be less robust
> and accurate, but if that was the culprit it should be fixed.
>
> PTB-ERROR: An equally likely cause would be that Synchronization of
> stimulus onset (buffer swap) to the
> PTB-ERROR: vertical blank interval VBL is not working properly.
> PTB-ERROR: Please run the script PerceptualVBLSyncTest to check this. With
> non-working sync to VBL, all stimulus timing
> PTB-ERROR: becomes quite futile. Also read 'help SyncTrouble' !

 can anyone help me?

**Comment by dcnieho** [comment]
Again:
Please post to the mailing list, not to a closed github question. Also, you
do not really provide any information. the psychtoolbox website has good
info about how to ask questions.

Best,
Dee
