### ISSUE TITLE
Screen('DrawDots') wrong diameter when using dot_Type = 3

### ISSUE THREAD

**Issue by dumbly** [Psychtoolbox-3/Psychtoolbox-3#443]
Following code creates a circle with 100px diameter:
```
posXY_Centre = [screenXpixels*1/2 screenYpixels*1/2];
Screen('DrawDots', window, posXY_Centre , 100);
```
However when using dot_type 3 (anti-aliasing: uses a builtin shader-based implementation):
`Screen('DrawDots', window, posXY_Centre, 100, 1, [], 3);`
A circle is drawn with 50px diameter, whereas I would expect a circle with 100px diameter.
Further information & DxDiag available on request.

**Comment by kleinerm** [comment]
I can't reproduce this problem, works fine on my Linux machine with Intel HD Ironlake graphics. So likely not a PTB bug, but some graphics driver problem. What OS + graphics card + driver is this?

**Comment by dumbly** [comment]
Hi Kleinerm,

Sorry for the late reply, here is my setup:
- OS: Windows Server 2016 Standard
- Version: 1607
- OS Build: 14393.447
- CPU: Intel Xeon E5-2630 v3
- GPU: NVIDIA Quadro M2000
- DirextX 12
- GPU driver: 378.66 (http://www.nvidia.com/download/driverResults.aspx/115432/en-us)
- PsychtoolboxVersion: 3.0.14 - Flavor: beta - Corresponds to SVN Revision 8301

I've tried with an updated driver: 385.12 (http://www.nvidia.co.uk/download/driverResults.aspx/122185/en-uk) but the same problem occurs.

**Comment by kleinerm** [comment]
Thanks. Maybe it will help somebody else to avoid the problem. As i said, there's no solution here if a new NVidia driver doesn't fix it, apart from avoiding those shader-based dot types.
