### ISSUE TITLE
PsychtoolboxConfigDir fails if Windows username has special characters

### ISSUE THREAD

**Issue by puolival** [Psychtoolbox-3/Psychtoolbox-3#444]
I am having trouble running the latest version of the PsychToolbox. I get the following error message

> Error using PsychtoolboxConfigDir (line 115)
> I could not create a folder to store your preferences in

(using the script http://peterscarfe.com/totallyminimaldemo.html) which I think is caused by a special character in my Windows username.

**Comment by kleinerm** [comment]
Is that all the error output? On Octave it would print the folder and a system provided reason for failure.
If you edit PsychtoolboxConfigDir.m at line 115 and add some disp(DirMessage) statement, or remove the semicolon in line 109 from [DirMade, DirMessage] = mkdir(TheDir); we can see the error message.

**Comment by kleinerm** [comment]
No response in 9 days. Closing.
