### ISSUE TITLE
GetSecsTest fails, unable to disable 1khZ timer Interrupts

### ISSUE THREAD

**Issue by danielnjoo** [Psychtoolbox-3/Psychtoolbox-3#447]
I receive the following error on running GetSecsTest():

> The average duration of a low-res timer tick is 1.000000 milliseconds. The low-res timer still runs at 1msec resolution. That means that our test is not diagnostic. Please exit and restart Matlab, then retry. Make sure that any kind of multi-media applications are closed while the test is running.

Would greatly appreciate any tips! Am I meant to disregard this ([link to forum post ](https://groups.yahoo.com/neo/groups/psychtoolbox/conversations/topics/9457)where this advice is given)?

It appears deprecated? (2009, applies to W32 only, I'm using W64, but is definitely not performance related as am using i7-4610M). I'm running example code from SensoMotoric Instruments that calls iV_Calibrate() which presumably uses GetSecsTest().

**Comment by qx1147** [comment]
Don't know whether this is even relevant for GetSecs(), but some BIOS'es allow disabling the HPET (High Performance Event Timer).

**Comment by dcnieho** [comment]
On windows, the default timer interrupt is 16ms, but any app can request a
more frequent interrupt, which will then apply system wide. Also on 64bit.

What SMI sample code is this? Has it been officially released?

**Comment by danielnjoo** [comment]
It was `GazeContingent.m` (there were 3 other examples, none of which could pass callibration) in the Matlab SDK that came with the kit... I could get a copy of it to you? Relatively confident that it's official.

**Comment by dcnieho** [comment]
Hi Daniel,

I'd be happy to have a copy of that, see what it is you've got! I should
also be able to have a test of it then next week. In the meantime, I'd
simply remove the call to getsecstest in the smi code if you can find it.
You dont have to run that every time. To have check of your system, run
getsecstest without any smi software running (its likely the program
turning the interrupt clock to 1 ms), nor anything other than the bare
essentials.


On Oct 17, 2017 10:06 AM, "danielnjoo" <notifications@github.com> wrote:

It was GazeContingent.m (there were 3 other examples, none of which could
pass callibration) in the Matlab SDK that came with the kit... I could get
a copy of it to you? Relatively confident that it's official.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/447#issuecomment-337095763>,
or mute the thread

**Comment by danielnjoo** [comment]
So `GetSecsTest()` still fails even when nothing else is running... Will try to figure out how to disable it without ruining everything (is there a line somewhere in PTB?)

[link to code](pastebin.com/jVbKCtWt)

**Comment by dcnieho** [comment]
Thanks for sending the code. I see this is the code from SMI SDK release
from 1-2 years back (their last release). GetSecsTest is not called in
that. I've done a search for it and not found it anywhere in the code. Note
that a call to iView.iV_Calibrate calls directly into a C dll which isn't
able to call matlab functions again.

Is there a way you could figure out where the call to GetSecsTest occurs?
As that is an actual error, it should be accompanied by a call stack,
indicating the series of function calls until the location where the error
occurred. Could you provide that?

On the side, Mario, how relevant is this test still, given that i see its
10 years old?

**Comment by qx1147** [comment]
@danielnjoo: 
Sorry for my irrelevant post earlier. Now, that I've read your original post more carefully, I wonder what your problem really is. I guess, the SMI example program fails to calibrate for some reason and you suspected it was related to same timing problem. Then you saw the post in the forum which gave you the idea of running GetSecsTest(), which gave you the message. Right?

Anyway, unless the SMI code depends and the timer having a low resolution, the message given by GetSecsTest() is not relevant. As dcnieho pointed out, any Windows program or service or driver could crank up the resolution of that timer to 1ms, although it should do so only temporarily. But even if it is not the SMI code which requests 1ms, it is rather unlikely that this causes the calibration to fail.

So do you have any hint of why the calibration might fail? Is there any message in MATLAB? Which tracker are you using? Is there maybe any useful message in the tracker program?

**Comment by danielnjoo** [comment]
@dcnieho so turns out that iV_Calibrate was expecting manual input for fixation dots which we never proceeded to give it. Changing it to infer automatic input solved the entire problem (not quite sure how, but...)?
