### ISSUE TITLE
kPsychGUIWindow not working

### ISSUE THREAD

**Issue by TheoCloppenburg** [Psychtoolbox-3/Psychtoolbox-3#448]
Hello,
I am currently trying to use the special flag 'kPsychGUIWindow' with the Screen() function. 
I am using Windows 10 and the newest release of ptb.

[WIND2]=Screen('OpenWindow', 1, [], [], [], [], [], [], [],kPsychGUIWindow);

will open a standard fullscreen window, wich cannot be operated like a GUI in any way.
There is literally no difference if I pass the flag 'kPsychGUIWindow' or not.

Has anyone experienced a similar issue or has an idea how to fix this?

Thanks and kind regards,

Theo

**Comment by kleinerm** [comment]
This only works for windowed non-fullscreen windows. Also you never get a truly GUI window, there are aways limitations. But at least it is possible to e.g., minimize/maximimze/resize/move it iirc, and use things like Screen('Rect') or 'GlobalRect' to find out about the current size or position of such a window. i can't remember if the close button works or if it either does nothing or crash. Some limitations are unavoidable.

**Comment by TheoCloppenburg** [comment]
thanks for your answer! It works when I pass a window size to the function.
I am trying to get a uibutton to work in the window, but I think this is not possible. So I am going to have to work out a different approach.
Thank you,
Theo
