### ISSUE TITLE
case-sensitive typo in Eyelink demo

### ISSUE THREAD

**Issue by cjayb** [Psychtoolbox-3/Psychtoolbox-3#449]
Dear Devs,

My recent installation of Win 10 (MATLAB Version: 8.6.0.267246 (R2015b)) dies at line 354 due to a case-sensitive

https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/ff1898ec391334e46548bd7a8bec28fb7b0b77aa/Psychtoolbox/PsychHardware/EyelinkToolbox/EyelinkDemos/GazeContingentDemos/EyelinkGazeContingentDemo.m#L354

```matlab
Cannot find an exact (case-sensitive) match for 'EyeLink'

The closest match is: Eyelink in C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Eyelink.mexw64

Error in EyelinkGazeContingentDemo (line 354)
            EyeLink('Message', 'Key pressed')
```

Apparently Windows is feeling case-sensitive, who'd have thought? ;)

**Comment by kleinerm** [comment]
Will be fixed in next beta update. Thanks for reporting.
