### ISSUE TITLE
rethrowing exceptions

### ISSUE THREAD

**Issue by cjayb** [Psychtoolbox-3/Psychtoolbox-3#450]
Here's another proposal for a beta-update. Presumably due to the new focus on OOP,  exceptions are now represented as a class (tested on Win 10, ML2015b): `MException`

This leads to a difference in how exceptions should be rethrown, and breaks the logic starting here:

https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/ff1898ec391334e46548bd7a8bec28fb7b0b77aa/Psychtoolbox/PsychBasic/psychrethrow.m#L13

I found the following change will do the trick (`msg` is now a class, not a string):

```matlab
if isa(msg, 'MException')
   msg.rethrow
elseif exist('rethrow', 'builtin')==5
% continue as before
```

**Comment by kleinerm** [comment]
So psychrethrow fails on R2015b?

**Comment by cjayb** [comment]
Yeah it did! Now that I think about it, my proposed fix might fail on older versions where ‘isa’ presumably doesn’t exist...?

**Comment by kleinerm** [comment]
isa() is supported on all Octave and Matlab versions we support, so this should be fine.
Added it for next beta. Thanks.
