### ISSUE TITLE
DrawFormattedText displays the text in half ......

### ISSUE THREAD

**Issue by YUW349** [Psychtoolbox-3/Psychtoolbox-3#454]
see the image 
![334719728988424803](https://user-images.githubusercontent.com/34189844/33516778-5c525806-d72d-11e7-9975-89d0968262b3.jpg)

**Comment by dcnieho** [comment]
Please provide relevant information (google for how to make a proper help
request). also, check the output of your experiment run carefully for
anything related to drawing text.

**Comment by kleinerm** [comment]
No response in a month and almost certainly user error. Closing.
