### ISSUE TITLE
Online documentation of KbCheck and other KbXXX functions

### ISSUE THREAD

**Issue by qx1147** [Psychtoolbox-3/Psychtoolbox-3#456]
I am currently writing a how-to for the PTB-wiki on keyboard input processing and just realized that the online documentation of many KbXXX functions seems to be missing,  for example of KbCheck and KbQueueCheck. All I can link to is the documentation of the according PsychHID functions (http://docs.psychtoolbox.org/KbCheck, http://docs.psychtoolbox.org/KbQueueCheck). How come and can it be fixed?

**Comment by kleinerm** [comment]
A valid problem, but unfixable for the time being. Seems the documentation generator script doesn't like the fact that KbQueueCheck.m and the PsychHID('KbQueueCheck') subfunction have exactly the same name string. The way we generate help and store it on the documentation site would need to be changed, and Tobias who wrote all this online documentation magic is no longer involved, so we lack both the brains & brawns to fix it.
