### ISSUE TITLE
Failed to initialize the window record because the default font for DrawText was not found.

### ISSUE THREAD

**Issue by RussellACH** [Psychtoolbox-3/Psychtoolbox-3#461]
Using DrawFormattedTextDemo i get the below error. I'm using PTB Version 3.0.13 , OSx 10.11.6, and MatLab 2015a. I've tried reinstalling Psychtoolbox, following suggestions from 'help DrawTextPlugin' and deleting "libfreetype.6.dylib", as well as installing standard fonts using the Font App and validating all fonts which indicate they are safe to use. Additionally my default text font is Arial. 

Any suggestions? 

INTERNAL PSYCHTOOLBOX ERROR
	error:                PsychError_internal
	general description:  Unspecified error, probably a Psychtoolbox bug
	specific description: Failed to initialize the window record because the default font for DrawText was not found.
	module name:          Screen
	subfunction call:     OpenWindow
	file name:            OSX/Screen/PsychWindowTextGlue.c
	function name:        PsychInitTextRecordSettings
	line number:          66

**Comment by kleinerm** [comment]
Mac OSX of course.
Try to run the freely downloadable app "FontNuke" and restart Matlab and see if that helps.
Other than that run at Screen('Preference','Verbosity', 6) and post what PTB has to say.
