### ISSUE TITLE
PTB Sync Trouble Windows 7 

### ISSUE THREAD

**Issue by xavierjob** [Psychtoolbox-3/Psychtoolbox-3#462]
After carefully following the "help SyncTrouble" nothing seems to solve my "PTB - ERROR: SYNCHRONIZATION FAILURE" (error message/info pasted below) . 

So far I have tried installing different versions of psychtoolbox, using different screen resolutions, making sure that the configuration settings on my graphics card are correct (as stated in "help SyncTrouble"). I'm only running on one monitor (not dual displays). The drivers for the graphics card are updated. Can anyone advise me further?!?

My setup: PTB version 3.0.14 with Matlab 64 bit R2014b, running on Windows 7. Graphics card: ATI Radeon HD 4200. Monitor: Dell Trinitron P992 running at 85Hz refresh rate.  

**********************
PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.14 - Build date: Oct  3 2017).
PTB-INFO: Support status on this operating system release: Windows version 6.1 partially supported, but no longer tested at all.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Will disable DWM because a regular fullscreen onscreen window is opened -> We want best timing and performance.
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.

WARNING: VBL Calibration run No. 1 failed. Retrying...
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.

WARNING: VBL Calibration run No. 2 failed. Retrying...
WARNING: Will enable VBL busywait-workaround before trying final VBL Calibration run No. 3.
WARNING: This will hopefully work-around graphics driver bugs of the GPU sync-to-retrace mechanism. Cross your fingers!
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.

PTB-INFO: OpenGL-Renderer is ATI Technologies Inc. :: ATI Radeon HD 4200 :: 3.3.10151 Compatibility Profile Context
PTB-INFO: VBL startline = 768 , VBL Endline = 806
PTB-INFO: Measured monitor refresh interval from beamposition = 18.971991 ms [52.709280 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 0.000000 ms [1.#INF00 Hz]. (0 valid samples taken, stddev=10000000.000000 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 11.764706 ms [85.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

WARNING: Mismatch between measured monitor refresh interval and interval reported by operating system.
This indicates massive problems with VBL sync.

WARNING: Measured monitor refresh interval indicates a display refresh of less than 20 Hz or more than 250 Hz?!?
This indicates massive problems with VBL sync.

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

Error using Screen
See error message printed above.

Error in DrawFormattedTextDemo (line 20)
    w=Screen('OpenWindow', screenNumber);

**Comment by kleinerm** [comment]
This has been answered on the forum, with no response from you in 9 days. Good luck.
