### ISSUE TITLE
Screen( ) Mex File Issues

### ISSUE THREAD

**Issue by theBFG515** [Psychtoolbox-3/Psychtoolbox-3#463]
Not sure if I am doing something wrong, but have been picking up an error.

Last Error: could not find library or dependencies: C:\toolbox\Psychtoolbox\PsychBasic\Octave4WindowsFiles64\Screen.mex () in Octave 4.2.2, Windows 10, 64 bit.

GStreamer installed and is not detecting the Screen.mex when queried

>> Screen
error: could not find library or dependencies: C:\toolbox\Psychtoolbox\PsychBasic\Octave4WindowsFiles64\Screen.mex
>> Screen Screens?
error: could not find library or dependencies: C:\toolbox\Psychtoolbox\PsychBasic\Octave4WindowsFiles64\Screen.mex

Is this a known issue, and if so is there a known fix?

Kind Regards,

The BFG.

edit. 
>> PsychtoolboxVersion
ans = 3.0.14 - Flavor: beta - Corresponds to SVN Revision 8424
For more info visit:
https://github.com/Psychtoolbox-3/Psychtoolbox-3

**Comment by kleinerm** [comment]
Current mex files are built against Octave 4.2.0, so maybe they are incompatible with v4.2.1 or 4.2.2.
Installing 4.2.0 should work.
