### ISSUE TITLE
Ubuntu 16.04 LTS issue using default font

### ISSUE THREAD

**Issue by clhorien** [Psychtoolbox-3/Psychtoolbox-3#464]
I am having trouble using DrawText. I have tried reinstalling Matlab and PTB, and I have already tried the solutions offered here (https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/400  ; briefly, these solutions included renaming conflicting freetype libraries and running "sudo dpkg --reconfigure matlab-support" to rename certain libraries).

My system and setup:

OS: ubuntu 16.04 LTS
Matlab: 9.4.0.813654 (R2018a) 64 bit
PTB version: 3.0.14 (Downloaded from NeuroDebian for Matlab)

Here is my error:

Failed to load X11 font with name Helvetica.

Available X11 fonts are:

[very long list]

Failed to load X11 font with name -*-helvetica-regular-r-*--20-*-*-*.
Try a Screen('TextFont') name according to one of the listed available fonts above.

Any help would be much appreciated; thank you in advance!

**Comment by kleinerm** [comment]
Please provide the full output of PTB, maybe even setting verbosity higher via Screen('Preference','Verbosity', 10) before executing some text drawing demo like DrawSomeTextDemo.m.

**Comment by kleinerm** [comment]
No response in 11 days. Closing as invalid.
