### ISSUE TITLE
GetKbChar passes too many arguments to KbPressWait

### ISSUE THREAD

**Issue by moregev** [Psychtoolbox-3/Psychtoolbox-3#473]
According to `GetKbChar` documentation, it "accepts optionally all arguments that KbCheck accepts and passes those arguments to KbCheck", however when I try to pass a `scanList` vector, I get the following error:
```
Error using KbWait
Too many input arguments.

Error in KbPressWait (line 34)
[secs, keyCode, deltaSecs] = KbWait(deviceNumber, 2, varargin{:});

Error in GetKbChar (line 39)
when = KbPressWait(varargin{:});
```

It seems like `GetKbChar` also passes the optional arguments to `KbPressWait`, which in turn passes them to `KbWait`, which is not able to handle them. I'm not familiar with Psychtoolbox internals so I'm not able to suggest a solution, but your help would be appreciated!

**Comment by kleinerm** [comment]
All of these functions accept a deviceindex of the input device, and a untilTime, but KbCheck currently does not accept any additional arguments, especially not a scanList vector? So this error is correct.

While PsychHID('KbCheck') does accept a scanList, you should not use PsychHID directly, that is not a supported way of using it. Functions like RestrictKeysForKbCheck are probably what you want to use.
