### ISSUE TITLE
psychtoolbox svn 8424 and 8583 works differently, the latter gives a synch error for screen functions

### ISSUE THREAD

**Issue by baburerdem** [Psychtoolbox-3/Psychtoolbox-3#474]
Hello,
We are running a visual perception experiment where we present a rotating spiral on screen using Matlab and psychtoolbox.  We have to use two monitors in extended display mode, one for stimulus presentation and the other for experimenter's use.
The original script runs OK in a setup where we have windows 7 and psychtoolbox version 3.0.14 **SVN 8424**.  
However, the same script fails to run on a different computer where we use the "updated" versions of windows 7 and psychtoolbox 3.0.14 **SVN version 8583**.

The program terminates where we want to use PsychImaging ('OpenWindow', ) which calls 'PrepareConfiguration' in the PsychImaging script, where the problem seems to be with the termination of the active configuration.  

Please advise on where the incompatibility might arise from (which ultimately gives a synch problem) and how we might solve it.
Thank you.

**Comment by dcnieho** [comment]
please provide the full output on the console for a run where it failed,
directly after a clean start of matlab

**Comment by kleinerm** [comment]
In general, Intel graphics and also multi-display is problematic on Windows. We recommend Linux for most non-trivial use cases.
Closing this, as Windows-7 is no longer supported, and PTB 3.0.17 is the only supported PTB since a while.
