### ISSUE TITLE
PTB - ERROR: SYNCHRONIZATION FAILURE

### ISSUE THREAD

**Issue by KataTam** [Psychtoolbox-3/Psychtoolbox-3#475]
I have the same synchronization issue on two laptops. Below I included the MATLAB output for the various tests and options that I have tried. 
I disabled firewalls etc. while running and there is only one monitor connected to each laptop. 

Any help is much appreciated!

LAPTOP 1 (Dell Precision 3520 with Intel Core i7-7700HQ CPU @ 2.80 GHz, 16 GB RAM, 64-bit Windows 10 Pro, MATLAB 2018a, built-in display, 1920 x 1080 screen resolution): 
LAPTOP 2 (Dell Precision M3800 with Intel Core i7-4702HQ CPU @ 2.20 GHz, 8 GB RAM, 64-bit Windows 7 Pro, MATLAB 2016a, built-in display, 1920 x 1080 screen resolution): 

LAPTOP 1 error messages:

PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.14 - Build date: Apr  6 2018).
PTB-INFO: Support status on this operating system release: Windows version 10.0 supported and tested to some limited degree.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: Quadro M620/PCIe/SSE2 :: 4.5.0 NVIDIA 382.66
PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
PTB-INFO: Measured monitor refresh interval from beamposition = 16.659256 ms [60.026692 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.660248 ms [60.023115 Hz]. (50 valid samples taken, stddev=0.237873 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

Error using Screen
See error message printed above.

Error in runVisualSearchP (line 29)
[window1, rect] = Screen('Openwindow',whichScreen,backgroundColor,[],[],2);

Regarding GStreamer, I've reinstalled it by selecting all the components, as specified. I think it should not be issue because MATLAB opens up with the below message:

PsychStartup: Adding path of installed GStreamer runtime to library path. [C:\gstreamer\1.0\x86_64\bin] 

However, when I try to test GStreamer with SimpleMovieDemo, I receive another error: 

In SimpleMovieDemo (line 26) 

PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.14 - Build date: Apr  6 2018).
PTB-INFO: Support status on this operating system release: Windows version 10.0 supported and tested to some limited degree.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: Quadro M620/PCIe/SSE2 :: 4.5.0 NVIDIA 382.66
PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
PTB-INFO: Measured monitor refresh interval from beamposition = 16.659338 ms [60.026397 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.660781 ms [60.021196 Hz]. (50 valid samples taken, stddev=0.195317 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================

PTB-ERROR: Screen('Flip'); beamposition timestamping computed an *impossible stimulus onset value* of 1594.162097 secs, which would indicate that
PTB-ERROR: stimulus onset happened *before* it was actually requested! (Earliest theoretically possible 1594.164587 secs).

PTB-ERROR: Some more diagnostic values (only for experts): rawTimestamp = 1594.166170, scanline = 263
PTB-ERROR: Some more diagnostic values (only for experts): line_pre_swaprequest = 154, line_post_swaprequest = 205, time_post_swaprequest = 1594.165326
PTB-ERROR: Some more diagnostic values (only for experts): preflip_vblcount = 93, preflip_vbltimestamp = 1593.195266
PTB-ERROR: Some more diagnostic values (only for experts): postflip_vblcount = 0, postflip_vbltimestamp = -1.000000, vbltimestampquery_retrycount = 0

PTB-ERROR: This error can be due to either of the following causes:
PTB-ERROR: Very unlikely: Something is broken in your systems beamposition timestamping. I've disabled high precision
PTB-ERROR: timestamping for now. Returned timestamps will be less robust and accurate.

PTB-ERROR: The most likely cause would be that Synchronization of stimulus onset (buffer swap) to the
PTB-ERROR: vertical blank interval VBL is not working properly, or swap completion signalling to PTB is broken.
PTB-ERROR: Please run the script PerceptualVBLSyncTest to check this. With non-working sync to VBL, all stimulus timing
PTB-ERROR: is futile. Also run OSXCompositorIdiocyTest on macOS. Also read 'help SyncTrouble' !

PerceptualVBLSyncTest
  PerceptualVBLSyncTest(screen, stereomode, fullscreen, doublebuffer, maxduration, vblSync, testdualheadsync)
 
  Perceptual synchronization test for synchronization of Screen('Flip') and
  Screen('WaitBlanking') to the vertical retrace.
 
  Arguments:
  'screen' Either a single screen handle, or none (in which case the
  display with the maximum id will be used), or a vector of two handles in
  stereomode 10, e.g., [0 1] if you want to output to screens 0 and 1. You
  can also pass a vector of two screens when stereomode is not set to 10.
  In this case two separate (non-stereo) onscreen windows will be opened on
  both displays and they will get flipped in multiflip mode 2. That means
  that the first display (first element of 'screen') is synced to VBL, but
  the 2nd one is synced to bufferswaps of the first one. This is a
  straightforward test to check if two displays of a stereosetup run with a
  synchronized retrace cycle (good!) or if they are phase-shifted or
  drifting against each other (not good!).
 
  'stereomode' Which stereomode to use? Defaults to zero, ie. no stereo.
 
  'fullscreen' Fullscreen presentation? Defaults to 1 ie. yes. In
  non-fullscreen mode, no proper synchronization of bufferswaps can be
  expected.
 
  'doublebuffer' Single- or double-buffering (1). Defaults to 1. In single
  buffer mode there is no sync to retrace, so this is a good way to
  simulate the tearing artifacts that would happen on sync failure, just to
  get an impression.
 
  'maxduration' Maximum runtime of test: Runs until keypress or maxduration
  seconds have elapsed (Default is 10 seconds).
 
  'vblSync' If 1, synchronize bufferswaps to vertical retrace of monitor,
  otherwise (setting 0) swap immediately without sync, ie., usually with tearing.
 
  'testdualheadsync' If 1, and 'vblSync' is zero, manually wait until the video
  scanout position reaches half the height of the display, then swap. If this
  is done on a multi-display setup and the video scanout cycles of all the
  participating displays are properly synchronized, you should see a "static"
  crack line roughly at half the height of the display, maybe a bit lower. If
  you see a wandering crack line, at least on some displays, or you see vertical
  offsets of the position of the crack line between displays, then the displays
  are not properly synchronized, ie., not suitable for artifact free binocular
  stimulation. Caveat: This logic has been developed and tested specifically
  for testing on Linux with a single X-Screen spanning multiple displays. It may
  or may not be suitable to assess other operating systems or display configurations.
 
  After starting this test, you should see a flickering greyish background
  that flickers in a homogenous way - without cracks or weird moving patterns
  in the flickering area. If you see an imhogenous flicker, this means that
  synchronization of stimulus onset to the vertical retrace doesn't work due
  to some serious bug or limitation of your graphics hardware or its driver.
  If you don't know what this means, you can test this script with parameter
  doublebuffer == 0 to artificially create a synchronization failure.
 
  On many systems you should also see some emerging pattern of yellow horizontal lines.
  These lines should be tightly concentrated/clustered in the topmost area of
  the screen. Lots of yellow lines in the middle or bottom area or even
  randomly distributed lines indicate some bug in the driver of your graphics
  hardware. This is a common problem of all ATI graphics adapters on MacOS-X
  versions earlier than OS-X 10.4.3 when running a dual-display setup...
 
  A second reason for distributed yellow lines could be bad timing on your
  machine, e.g., due to background activity by virus scanners or the Spotlight
  indexing service on OS-X. Turn these off for conducting your studies!
 

Press ENTER key to start the test. The test will stop after 10 seconds
or any keypress...

PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.14 - Build date: Apr  6 2018).
PTB-INFO: Support status on this operating system release: Windows version 10.0 supported and tested to some limited degree.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: Quadro M620/PCIe/SSE2 :: 4.5.0 NVIDIA 382.66
PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
PTB-INFO: Measured monitor refresh interval from beamposition = 16.659189 ms [60.026933 Hz].
PTB-INFO: Beamposition queries are supported, but disabled. Using basic timestamping as fallback:
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.661714 ms [60.017833 Hz]. (50 valid samples taken, stddev=0.264443 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

>> VBLSyncTest()

ans =

     0

PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.14 - Build date: Apr  6 2018).
PTB-INFO: Support status on this operating system release: Windows version 10.0 supported and tested to some limited degree.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: Quadro M620/PCIe/SSE2 :: 4.5.0 NVIDIA 382.66
PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
PTB-INFO: Measured monitor refresh interval from beamposition = 16.659323 ms [60.026450 Hz].
PTB-INFO: Beamposition queries are supported, but disabled. Using basic timestamping as fallback:
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.655756 ms [60.039305 Hz]. (50 valid samples taken, stddev=0.354755 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

Error using Screen
See error message printed above.

Error in PsychImaging (line 2077)
            [win, winRect] = Screen('OpenWindow', screenid, clearcolor, winRect, pixelSize, numbuffers, stereomode, multiSample, imagingMode, specialFlags, clientRect,
            fbOverrideRect);

Error in VBLSyncTest (line 284)
        w=PsychImaging('OpenWindow',screenNumber, 0,[],[],[], stereo);

LAPTOP 2 error messages: 

when running SimpleMovieDemo, MATLAB freezes and I need to restart. 

On starting MATLAB:

PsychStartup: Adding path of installed GStreamer runtime to library path. [C:\gstreamer\1.0\x86_64\bin]

>> VBLSyncTest()

ans =

     0

PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.14 - Build date: Apr  6 2018).
PTB-INFO: Support status on this operating system release: Windows version 6.1 partially supported, but no longer tested at all.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Will disable DWM because a regular fullscreen onscreen window is opened -> We want best timing and performance.
PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: Quadro K1100M/PCIe/SSE2 :: 4.4.0
PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
PTB-INFO: Measured monitor refresh interval from beamposition = 16.652718 ms [60.050258 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.648788 ms [60.064433 Hz]. (50 valid samples taken, stddev=0.102557 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

PTB-ERROR: Screen('Flip'); beamposition timestamping computed an *impossible stimulus onset value* of 585.242596 secs, which would indicate that
PTB-ERROR: stimulus onset happened *before* it was actually requested! (Earliest theoretically possible 585.250511 secs).

PTB-ERROR: Some more diagnostic values (only for experts): rawTimestamp = 585.251845, scanline = 599
PTB-ERROR: Some more diagnostic values (only for experts): line_pre_swaprequest = 509, line_post_swaprequest = 548, time_post_swaprequest = 585.251080
PTB-ERROR: Some more diagnostic values (only for experts): preflip_vblcount = 0, preflip_vbltimestamp = -1.000000
PTB-ERROR: Some more diagnostic values (only for experts): postflip_vblcount = 0, postflip_vbltimestamp = -1.000000, vbltimestampquery_retrycount = 0

PTB-ERROR: This error can be due to either of the following causes:
PTB-ERROR: Very unlikely: Something is broken in your systems beamposition timestamping. I've disabled high precision
PTB-ERROR: timestamping for now. Returned timestamps will be less robust and accurate.

PTB-ERROR: The most likely cause would be that Synchronization of stimulus onset (buffer swap) to the
PTB-ERROR: vertical blank interval VBL is not working properly, or swap completion signalling to PTB is broken.
PTB-ERROR: Please run the script PerceptualVBLSyncTest to check this. With non-working sync to VBL, all stimulus timing
PTB-ERROR: is futile. Also run OSXCompositorIdiocyTest on macOS. Also read 'help SyncTrouble' !
The refresh interval reported by the operating system is 16.66667 ms.
Measured refresh interval, as reported by "GetFlipInterval" is 16.64879 ms. (nsamples = 0, stddev = 0.00000 ms)

ans =

     1

PTB missed 1 out of 600 stimulus presentation deadlines.
One missed deadline is ok and an artifact of the measurement.
PTB completed 0 stimulus presentations before the requested target time.
Have a look at the plots for more details...

>> PerceptualVBLSyncTest()
  PerceptualVBLSyncTest(screen, stereomode, fullscreen, doublebuffer, maxduration, vblSync, testdualheadsync)
 
  Perceptual synchronization test for synchronization of Screen('Flip') and
  Screen('WaitBlanking') to the vertical retrace.
 
  Arguments:
  'screen' Either a single screen handle, or none (in which case the
  display with the maximum id will be used), or a vector of two handles in
  stereomode 10, e.g., [0 1] if you want to output to screens 0 and 1. You
  can also pass a vector of two screens when stereomode is not set to 10.
  In this case two separate (non-stereo) onscreen windows will be opened on
  both displays and they will get flipped in multiflip mode 2. That means
  that the first display (first element of 'screen') is synced to VBL, but
  the 2nd one is synced to bufferswaps of the first one. This is a
  straightforward test to check if two displays of a stereosetup run with a
  synchronized retrace cycle (good!) or if they are phase-shifted or
  drifting against each other (not good!).
 
  'stereomode' Which stereomode to use? Defaults to zero, ie. no stereo.
 
  'fullscreen' Fullscreen presentation? Defaults to 1 ie. yes. In
  non-fullscreen mode, no proper synchronization of bufferswaps can be
  expected.
 
  'doublebuffer' Single- or double-buffering (1). Defaults to 1. In single
  buffer mode there is no sync to retrace, so this is a good way to
  simulate the tearing artifacts that would happen on sync failure, just to
  get an impression.
 
  'maxduration' Maximum runtime of test: Runs until keypress or maxduration
  seconds have elapsed (Default is 10 seconds).
 
  'vblSync' If 1, synchronize bufferswaps to vertical retrace of monitor,
  otherwise (setting 0) swap immediately without sync, ie., usually with tearing.
 
  'testdualheadsync' If 1, and 'vblSync' is zero, manually wait until the video
  scanout position reaches half the height of the display, then swap. If this
  is done on a multi-display setup and the video scanout cycles of all the
  participating displays are properly synchronized, you should see a "static"
  crack line roughly at half the height of the display, maybe a bit lower. If
  you see a wandering crack line, at least on some displays, or you see vertical
  offsets of the position of the crack line between displays, then the displays
  are not properly synchronized, ie., not suitable for artifact free binocular
  stimulation. Caveat: This logic has been developed and tested specifically
  for testing on Linux with a single X-Screen spanning multiple displays. It may
  or may not be suitable to assess other operating systems or display configurations.
 
  After starting this test, you should see a flickering greyish background
  that flickers in a homogenous way - without cracks or weird moving patterns
  in the flickering area. If you see an imhogenous flicker, this means that
  synchronization of stimulus onset to the vertical retrace doesn't work due
  to some serious bug or limitation of your graphics hardware or its driver.
  If you don't know what this means, you can test this script with parameter
  doublebuffer == 0 to artificially create a synchronization failure.
 
  On many systems you should also see some emerging pattern of yellow horizontal lines.
  These lines should be tightly concentrated/clustered in the topmost area of
  the screen. Lots of yellow lines in the middle or bottom area or even
  randomly distributed lines indicate some bug in the driver of your graphics
  hardware. This is a common problem of all ATI graphics adapters on MacOS-X
  versions earlier than OS-X 10.4.3 when running a dual-display setup...
 
  A second reason for distributed yellow lines could be bad timing on your
  machine, e.g., due to background activity by virus scanners or the Spotlight
  indexing service on OS-X. Turn these off for conducting your studies!
 

Press ENTER key to start the test. The test will stop after 10 seconds
or any keypress...

PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.14 - Build date: Apr  6 2018).
PTB-INFO: Support status on this operating system release: Windows version 6.1 partially supported, but no longer tested at all.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Will disable DWM because a regular fullscreen onscreen window is opened -> We want best timing and performance.
PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: Quadro K1100M/PCIe/SSE2 :: 4.4.0
PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
PTB-INFO: Measured monitor refresh interval from beamposition = 16.652575 ms [60.050773 Hz].
PTB-INFO: Beamposition queries are supported, but disabled. Using basic timestamping as fallback:
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.649142 ms [60.063154 Hz]. (50 valid samples taken, stddev=0.142310 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

runVisualSearchP('ke1');

PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.14 - Build date: Apr  6 2018).
PTB-INFO: Support status on this operating system release: Windows version 6.1 partially supported, but no longer tested at all.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Will disable DWM because a regular fullscreen onscreen window is opened -> We want best timing and performance.
PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: Quadro K1100M/PCIe/SSE2 :: 4.4.0
PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
PTB-INFO: Measured monitor refresh interval from beamposition = 16.652727 ms [60.050224 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.645569 ms [60.076048 Hz]. (301 valid samples taken, stddev=0.225670 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

Error using Screen
See error message printed above.

Error in runVisualSearchP (line 29)
[window1, rect] = Screen('Openwindow',whichScreen,backgroundColor,[],[],2);

**Comment by kleinerm** [comment]
Both of these Dell laptops seem to be "NVidia Optimus" laptops with Intel integrated graphics + NVidia discrete graphics. Those are known to generally not work at all with precise and trustworthy timing.

"help HybridGraphics" for details, but it boils down to this: Either you find some setting in the Laptops firmware menu to disable Optimus and always use the NVidia (unlikely), or to disable Optimus and always use the Intel (a bit more likely) which makes your NVidia graphics useless and exposes you to frequent Intel graphics driver bugs instead. The latter can also be set in Windows for Matlab alone somehow.

The only way to get good timing on Optimus is by switching to a modern Linux distribution, however if you want to use the NVidia at high performance under Optimus it will require a substantial amount of manual setup, as explained in help HybridGraphics.

Btw. that SimpleMovieDemo or anything else involving GStreamer often crashes under Matlab unless you use the -nojvm switch is a known Matlab on Windows bug. If you found that SimpleMovieDemo actually works reliably on Windows with R2018a (ignoring the timing problems that is, but at least not crashing Matlab but playing the movies), that would be an interesting bit of information.

**Comment by KataTam** [comment]
Thank you for your help!
