### ISSUE TITLE
changing colors with precise timing

### ISSUE THREAD

**Issue by jiwanna** [Psychtoolbox-3/Psychtoolbox-3#477]
Hello 

I have been trying to change colors with precise timing about ms unit.

For now, I got help from Accurate timing demo and Wait frame demo in http://peterscarfe.com/ptbtutorials.html 

And Finally I accomplished to shift color alternatively (red-green-red-green~~)

But  the problem is time delay.

I script my program to run during 5s.

The shorter shifting time is, the longer time duration is getting.

![image](https://user-images.githubusercontent.com/37168069/39794325-b06d1fec-5384-11e8-9c4f-f53813720a7e.png)

This is part of the program to shift colors. 

inum = 10ms 20ms ...100ms
freq = 5s/inum

Is there better ways to change colors with attenuating delay?

Or should I use function WaitSecs()?

Any comments and advice will be a great help to me.

Thanks

from Ji-Wan Kim

**Comment by kleinerm** [comment]
Same question asked at forum, which is the right place for such questions. Closing.
