### ISSUE TITLE
macOS: PTB - ERROR: SYNCHRONIZATION FAILURE

### ISSUE THREAD

**Issue by ybthakur** [Psychtoolbox-3/Psychtoolbox-3#480]
I am using Psychtoolbox on MacOS HighSierra 10.13.4. I am having trouble with the VBL. I am getting the following error. I don't want to skip the sync test as I need the timings to be accurate. Can somebody help me with this?
<img width="1236" alt="screen shot 2018-05-09 at 12 54 43 pm" src="https://user-images.githubusercontent.com/39136773/39836472-563d8e40-5388-11e8-9991-234861149bd0.png">

**Comment by dcnieho** [comment]
have you taken all the steps in help SyncTrouble as suggested by the text?

**Comment by vaib338** [comment]
No idea. I didn't change anything.

**Comment by iras** [comment]
I might be experiencing a similar problem.

```OSXCompositorIdiocyTest()```

```PTB-INFO: OpenGL-Renderer is Intel Inc. :: Intel HD Graphics 5000 OpenGL Engine :: 2.1 INTEL-10.32.48
PTB-INFO: Renderer has 1536 MB of VRAM and a maximum 1536 MB of texture memory.
PTB-INFO: VBL startline = 900 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback.
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 19.304703 ms [51.800848 Hz]. (259 valid samples taken, stddev=5.313051 ms.)
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?


----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.```

**Comment by courtcourtaney** [comment]
I am also currently experiencing this issue: I developed on a Mac using OS X 10.12 and had no issues, but now I'm having difficulty getting the program running on several machines I have to use for research, which are all on High Sierra 10.13. I haven't been able to find a workaround based on the SyncTrouble documentation. If there isn't a fix for this synchronization failure, is there some way to work around for this specific issue to at least get the program to run?

**Comment by jxj24** [comment]
Mario, is this fundamental to macOS  or just their graphics drivers? For instance, do NVidia's "web drivers" for Maxwell and Pascal cards, which are supposedly written outside of Apple, doomed as well?

I am strongly considering moving all my stimulus code to a separate Linux box (prob running Centos?) and using TCP/IP between the two.

**Comment by kateiyas** [comment]
I would like to have the option to develop on macOS instead of scripts (e.g. code that we intend to run on Linux systems as recommended) just crashing.

**Comment by kleinerm** [comment]
Ok, the latest PTB 3.0.15 BETA should fix or improve this, thanks to contract work done for Denis Pelli.
See #611 and linked from there a little essay with an - unfortunately incomplete - list about all the horrors that is Apples current trainwreck. Don't worry, macOS Catalina already brings various new trouble.

-> macOS: For entertainment and education use only!
