### ISSUE TITLE
Screen Close All Failure

### ISSUE THREAD

**Issue by AmitKhandhadia** [Psychtoolbox-3/Psychtoolbox-3#482]
For some reason, Screen('CloseAll') gets caught in a loop when I am running a GUI that uses it play short movie clips. It will run through the clips just fine but when I go to clear the screen, PTB just freezes. The matlab window still operates fine but it can't issue any commands or process anything. It doesn't even output any error. Trying to close the videos independently also results in a freeze. Any idea as to what might be causing these issues?

**Comment by dcnieho** [comment]
Can you provide a minimal (as short as possible) code example that we can
run?

**Comment by kleinerm** [comment]
No response within 14 days, closing.
