### ISSUE TITLE
Checkout Failure, unable to connect to a repository

### ISSUE THREAD

**Issue by ChaoticTacoTornado** [Psychtoolbox-3/Psychtoolbox-3#492]
I'm trying to download the psychtoolbox and keep getting a checkout failure with this output: 

svn: E175002: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox'
svn: E175002: OPTIONS of 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox': SSL handshake failed: SSL error: tlsv1 alert protocol version (https://github.com)

Does anyone know what this means/how I could fix it? I'm completely new with Matlab and programming in general and have tried to figure it out, but haven't had any luck. 
(ps. I'm using a mac with OS X 10.9.5)

**Comment by kleinerm** [comment]
Try this new DownloadPsychtoolbox.m.zip file, which might fix it for OSX:
https://github.com/Psychtoolbox-3/Psychtoolbox-3/raw/master/Psychtoolbox/DownloadPsychtoolbox.m.zip
If you want to use OSX 10.9 you will need to download the outdated and totally unsupported Psychtoolbox-3.0.12 though, not the current beta that gets downloaded by default.

**Comment by ChaoticTacoTornado** [comment]
I downloaded the new zip file you posted, and then tried using it with this command: DownloadPsychtoolbox('3', '0', '12')
It gave me the same checkout errors from above, but it was unable to connect to the new repository. 
svn: E175002: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/0/Psychtoolbox'
svn: E175002: OPTIONS of 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/0/Psychtoolbox': SSL handshake failed: SSL error: tlsv1 alert protocol version (https://github.com)

**Comment by kleinerm** [comment]
Ok, that wouldn't be the proper syntax to download v3.0.12, but it doesn't matter, as the error is the same here.
I think your OSX is too old. Its svn tool is so outdated it uses a transfer protocol that is no longer supported as it poses a security risk (tlsv1).

You can download it manually as a large zip file from this link:
https://github.com/Psychtoolbox-3/Psychtoolbox-3/archive/Psychtoolbox-3.0.12.zip

Then follow the instructions under: http://psychtoolbox.org/download/#without-download

This is probably more simple than upgrading your operating system.

**Comment by ChaoticTacoTornado** [comment]
okay, thank you so much for your help!! Ill go give that a try

**Comment by ChaoticTacoTornado** [comment]
got it, thank you again for your help!
