### ISSUE TITLE
Drawing of calibration targets in PsychEyelinkDispatchCallback.m inconsistent

### ISSUE THREAD

**Issue by widmann** [Psychtoolbox-3/Psychtoolbox-3#496]
PsychEyelinkDispatchCallback.m includes a nested function EyelinkDrawCalibrationTarget (close to the end) drawing targets for the Eyetracker calibration and validation routines. Targets are basically disks in foreground color containing a smaller disk in background color (shaping a ring).

Size of the target disk and the inset disk are defined by the calibrationtargetsize and calibrationtargetwidth fields of the Eyelink config structure relative to screen width. Depending on resulting target sizes in pixels different functions are used to plot the targets (DrawDots vs. FillOval).

Depending on the function used (depending on calibrationtargetsize), the inset pixel diameter is growing either with increasing calibrationtargetwidth or decreasing calibrationtargetwidth. I wrote a demo illustrating the resulting inset pixel diameter depending on calibrationtargetsize and calibrationtargetwidth.

The bug itself is trivial to fix by replacing
`Screen('DrawDots', eyewin, calxy, insetSize, el.backgroundcolour, [], 1);`
by
`Screen('DrawDots', eyewin, calxy, inset, el.backgroundcolour, [], 1);`

Problem is backward compatibility. Not sure how to fix the problem without breaking backward compatibility and existing experiments. What would be your approach to maintain backward compatibility?

Thank you! Best,
Andreas

[el_caltar_demo.m.zip](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/2297761/el_caltar_demo.m.zip)

**Comment by dcnieho** [comment]
forwarding this to SR support (I am not sure who is responsible for
maintaining the toolbox, its probably good to have them in the loop)

All the best,
Dee

**Comment by kleinerm** [comment]
I think we should just fix it as you proposed. Eyetracker calibration doesn't sound like its details are a critical part of a paradigm. And the whole idea of PsychEyelinkDispatchCallback is that it can be replaced by an arbitrary user-provided routine if customization etc. is needed.

Another question is why we continue to use DrawDots at all? Presentation of a single calibration target is not performance critical, so exclusive use of FillOval, which will be somewhat slower, shouldn't matter and simplify the code.

**Comment by kleinerm** [comment]
I've removed the DrawDots special case for PTB 3.0.15, so there's only one code-path via FillOval. That should provide consistency.

**Comment by widmann** [comment]
Sorry, for the delay. I was still testing. I stumbled across one special case. Frequently we do not use anti-aliasing. Without anti-aliasing and FillOval (and integer pixel coordinates as coming from the eye-tracker) the smallest inset (or target) size is 2x2 pixels. As the same actually also applies to dots FillOval is fine for now and solves the problem. We can change later if I come up with a better solution.

Thank you and sorry again for the delay.
Best,
Andreas

**Comment by sr-brian** [comment]
@kleinerm Brian from SR-Research here. I emailed you Aug 17th consequent to this submission, but haven't yet heard back. Would you be able to get in touch please to discuss more thorough collaboration on the EyeLink Toolbox? If you've not received the email, please reach out to me at brian@sr-research.com Thanks!
