### ISSUE TITLE
Current Wayland support status

### ISSUE THREAD

**Issue by yhz-1995** [Psychtoolbox-3/Psychtoolbox-3#502]
Hi,

What is the current support status for Psychtoolbox running on Linux with Wayland display server?

On my machine Screen('Flip',window) works under X but not under Wayland.

And does Wayland have stimulus timing problems?

**Comment by mirh** [comment]
Curious people can follow the "progress in the scene" at
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/103
(also, just a casual reminder that `tearing_control_v1` just landed)
