### ISSUE TITLE
doesn't work for latest version of Octave 4.4.1 on Mac OSX

### ISSUE THREAD

**Issue by christinesfkao** [Psychtoolbox-3/Psychtoolbox-3#506]
WARNING: Your version 4.4.1 of Octave is incompatible with this release. We strongly recommend
WARNING: using the latest stable version of the Octave 4.2.x series for use with Psychtoolbox.
WARNING: Stuff may not work at all or only suboptimal with other versions and we
WARNING: don't provide any support for such old versions.

But I can't find downloading scripts for Octave 4.2.x in Homebrew.
https://github.com/Homebrew/homebrew-core/blob/master/Formula/octave.rb
https://formulae.brew.sh/formula/octave

**Comment by christinesfkao** [comment]
I tried [this](https://wiki.octave.org/Octave_for_macOS#Octave_4.2.2_VM_installer_for_Mac_OS_X_10.10_Yosemite.2C_10.11_El_Capitan.2C_10.12_Sierra.2C_10.13_High_Sierra) as a VM installer (Vagrant and VirtualBox) to get Octave 4.2.2, but even by following the steps on the [download guide for Ubuntu 14.04](http://psychtoolbox.org/download.html#Linux) and installing NeuroDebian and etc., things don't seem to work either. 

I still get `octave exited with signal 6` as the GUI crashed. After changing the graphic toolkit from qt to gnuplot, I get `octave exited with signal 11` instead. 

Typing `help Psychtoolbox` in the Octave GUI console gets error messages indicating that I haven't installed Psychtoolbox at all... which isn't true...

**Comment by kleinerm** [comment]
Not quite sure how you try to fix a macOS problem by following a download guide for Ubuntu Linux?
Unfortunately, keeping stuff compatible across Octave versions on macOS or Windows is basically impossible, so a given PTB version is locked to a specific Octave version.
That said, Psychtoolbox 3.0.15 is not far from release, a couple of days. v3.0.15 will support Octave 4.4.1.

**Comment by christinesfkao** [comment]
Hi, thanks for letting me know there will be an update soon.

P.S. I followed a download guide for Ubuntu Linux because the alternative method I chose was to install a virtual machine for Octave 4.2.2.
