### ISSUE TITLE
HideCursor in Linux

### ISSUE THREAD

**Issue by anthonysali** [Psychtoolbox-3/Psychtoolbox-3#510]
I am a long-time Psychtoolbox user, but I just installed it for the first time on a linux machine. I'm running Ubuntu 18.04 and I installed Psychtoolbox through the neurodebian repository.  All seems to work well, except HideCursor is not actually hiding the cursor. Is this a known issue? If it is, is there a workaround or an update that I need to apply?

Thanks and let me know if I can provide any other info.

**Comment by kleinerm** [comment]
Do you call HideCursor() after 'OpenWindow'? I think that may be required.

**Comment by anthonysali** [comment]
Thanks for tip. I wasn't doing that and now it works exactly as expected!
