### ISSUE TITLE
Text functions ('DrawText', 'TextBounds') cause Matlab to hang

### ISSUE THREAD

**Issue by coriumgit** [Psychtoolbox-3/Psychtoolbox-3#511]
This issue started just out of the blue. One day an experiment works as usual, the next day Matlab was hanging, where a kill from process manager was required. We isolated the issue to the text functions above. We suspect that a windows update is the cause of this, as nothing else in the system changed...

**Comment by dcnieho** [comment]
Give it a few minutes, the text drawing functions need to refresh their
cache perhaps. If this happens on every new run of the code, you may need
to delete the fontconfig cache (I get stuck in this state myself every now
and then). See issue 429 for how to solve that

**Comment by coriumgit** [comment]
Yes, you were right, had to give it a few minutes run once and since then it works as usual. 
Thanks !
