### ISSUE TITLE
Error message Downloading Psychtoolbox

### ISSUE THREAD

**Issue by CarlosBB86** [Psychtoolbox-3/Psychtoolbox-3#516]
Hello,
I am trying to download Psychtoolbox-3 on a Mac OSX Yosemite 10.10.5 . I recently downloaded a new Matlab version (R2018_b) and the Psychotoolbox version I had did not work anymore. When I try to download Psychotoolbox-3 this message keeps showing up on Matlab: 

**svn: E175002: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox'
svn: E175002: OPTIONS of 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox': SSL handshake failed: SSL error: tlsv1 alert protocol version (https://github.com)
Sorry, the download command "CHECKOUT" failed with error code 1: 
For reason, see output above.
The download failure might be due to temporary network or server problems. You may want to try again in a few minutes. It could also be that the subversion client was not (properly) installed. On Microsoft
Windows you will need to exit and restart Matlab or Octave after installation of the Subversion client. If that does not help, you will need to reboot your machine before proceeding. Another reason for download failure could be if an old working copy - a Psychtoolbox folder - still exists.
In that case, it may help to manually delete that folder. Or maybe you do not have write permissions for the target folder?**

I followed all the message recommendations: I tried downloading the program several times across different days, I made sure the subversion client was installed and I deleted previous Psychtoolbox folders I had. Any thoughts on what might be going on?

Thanks in advance,
Carlos

**Comment by dcnieho** [comment]
you version of svn is too old and doesn't support the required SSL protocol. update it (if comes with XCode, see if updating xcode works. Check if there are any other svn executables on path also that are used instead. Failing that, just manually download a zip from the github page and run SetupPsychtoolbox

**Comment by CarlosBB86** [comment]
Hello,

Thanks for the advice. I was able to update my svn version (not without trouble) and the problem was solved. However, I had to download a previous version of Psychtoolbox too because my OSX was too old for Psychtoolbox-3. Many thanks for the advice!

Carlos
