### ISSUE TITLE
Let "DrawFormattedText2" be compatible with unicode text

### ISSUE THREAD

**Issue by psychelzh** [Psychtoolbox-3/Psychtoolbox-3#519]
The `DrawFormattedText` works well with unicode text if converting to numbers with function `double`. I wonder if it will be possible to do so with `DrawFormattedText2`, for currently, it reports error like this:

```matlab
Error using regexp
The 'STRING' input must be either a char row vector, a cell array of char row vectors, or a string array.

Error in DrawFormattedText2>getFormatting (line 841)
[tagis ,tagie ,tagt ] = regexp(tstring,'(?i)(?<!(?<!/)/)<(i|b|u)>','start','end','tokens');

Error in DrawFormattedText2 (line 336)
[tstring,fmtCombs,fmts,switches,previous] = getFormatting(win,tstring,baseColor,resetStyle);

Error in main (line 54)
DrawFormattedText2(double(instruction), 'win', window_ptr);
```

**Comment by dcnieho** [comment]
Hi! Can you send me your instruction string so i have some example text you
would like to be able to display? matlab's regexp works with unicode too,
but not when its encoded as a double().

Thanks for the report

**Comment by psychelzh** [comment]
My sample string would be:

```matlab
instruction = ['下面我们玩一个游戏', ...
    '\n屏幕上会一个一个地出现小动物', ...
    '\n你需要判断当前这个小动物是不是和<b>前一个<b><color=ff0000>一样<color>', ...
    '\n如果一样就按<b>左键<b>，不一样就按<b>右键<b>'];
```

**Comment by dcnieho** [comment]
I just fixed this. Should appear in next PTB update. See the change here in case you need it fixed now:
https://github.com/Psychtoolbox-3/Psychtoolbox-3/pull/520/commits/a49d0d1ee17a8fe6bf6c31cea216d56d21d807c4
