### ISSUE TITLE
PsychJavaTrouble

### ISSUE THREAD

**Issue by tiborauer** [Psychtoolbox-3/Psychtoolbox-3#521]
Lines 159 and 162 of [PsychJavaTrouble](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/Psychtoolbox/PsychJava/PsychJavaTrouble.m) fail to detect `'PsychJava'` in javaclasspath.txt even if it is there, because of the argumentation of strfind. 
Replacing the order of arguments solves the issue:
`strfind(fileContents{i},'PsychJava')`

**Comment by kleinerm** [comment]
Thanks for catching this! Fixed for next PTB beta.
