### ISSUE TITLE
PTB V3.0.15 problem with matlab crash

### ISSUE THREAD

**Issue by mwang67** [Psychtoolbox-3/Psychtoolbox-3#528]
I'm using Matlab 2018a and running the latest PTB with support for Oculus CV1 on Win10 PC.

However, when I tried the demos (e.g. VRHMDDemo etc.) matlab show a pop up window and crashes (see below) 
![capture](https://user-images.githubusercontent.com/36744044/51769831-e1632600-2098-11e9-81ac-bf8b54499cba.PNG)

The demo did display in the HMD but if I close the matlab crash window matlab quits.

**Comment by kleinerm** [comment]
Does this also happen if you install GStreamer? Shouldn't technically matter, but then that's one obvious difference between the machine on which Oculus VR1 support was developed and successfully tested, and yours. Also i need the content of that Matlab crash report, the popup window telling it crashes is useless.

**Comment by mwang67** [comment]
Just installed GStreamer and run into same crash.  Here's the report copied
below.
Thank you,

Assertion detected at Mon Jan 28 10:44:19 2019 -0800
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : windows-1252
  Deployed                 : false
  Graphics Driver          : Unknown software
  Graphics card 1          : Intel Corporation ( 0x8086 ) Intel(R) HD
Graphics 630 Version 21.20.16.4550 (2016-11-11)
  Graphics card 2          : NVIDIA ( 0x10de ) NVIDIA GeForce GTX 1070
Version 23.21.13.9125 (2018-3-16)
  Java Version             : Java 1.8.0_144-b01 with Oracle Corporation
Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 4808126
  MATLAB Root              : C:\Program Files\MATLAB\R2018a
  MATLAB Version           : 9.4.0.813654 (R2018a)
  OpenGL                   : software
  Operating System         : Microsoft Windows 10 Home
  Process ID               : 17112
  Processor ID             : x86 Family 6 Model 158 Stepping 9, GenuineIntel
  Session Key              : d8cfe37c-4638-4e32-89c3-297aa2c857dd
  Window System            : Version 10.0 (Build 17134)

Fault Count: 1


Assertion in foundation::usm::Detail<struct
foundation::usm::scope::Mvm>::find at
b:\matlab\foundation\usm\management.cpp line 671

Register State (captured):
  RAX = 0000000010d22ef8  RBX = 0000000000000000
  RCX = 00000001c803e350  RDX = 0000000000000000
  RSP = 00000001c803e2d0  RBP = 0000000012486b08
  RSI = 0000000010d22ef8  RDI = 0000000010d22ef8

   R8 = 00005009ac31b2ca   R9 = 00007ff94cd40000
  R10 = 0000000010c5a298  R11 = 0000000010d12efc
  R12 = 00000001c803e990  R13 = 0000000010d12e28
  R14 = 0000000010d22e78  R15 = 0000000012486b08

  RIP = 0000000010b1c44a  EFL = 00000202

   CS = 0033   FS = 0053   GS = 002b

Stack Trace (captured):
[  0] 0x0000000010b16063
bin\win64\libmwfl.dll+00155747
foundation::core::diag::thread_context::unspecified_bool+00000051
[  1] 0x0000000010b14658
bin\win64\libmwfl.dll+00149080
foundation::core::diag::stacktrace_base::capture+00000024
[  2] 0x0000000010b18925
bin\win64\libmwfl.dll+00166181
foundation::core::diag::symbols::getSymbolAddress+00009941
[  3] 0x0000000010b17aae
bin\win64\libmwfl.dll+00162478
foundation::core::diag::symbols::getSymbolAddress+00006238
[  4] 0x0000000010b1bd3b
bin\win64\libmwfl.dll+00179515 foundation::core::diag::terminate+00000059
[  5] 0x000000001246340c
bin\win64\libmwfoundation_usm.dll+00013324
foundation::usm::getErrorHandler+00000060
[  6] 0x0000000012477c29
bin\win64\libmwfoundation_usm.dll+00097321
foundation::usm::Detail<foundation::usm::scope::Mvm>::find+00000233
[  7] 0x00000000fb5f4f37
bin\win64\libmwbridge.dll+00020279 ioSetIoCallbacks+00001479
[  8] 0x00000000fb5f5f93
bin\win64\libmwbridge.dll+00024467 ioSetIoCallbacks+00005667
[  9] 0x00000000fe9d9efa
bin\win64\libut.dll+00237306 utVprintf+00000202
[ 10] 0x00000000fc60bb33
 bin\win64\libmex.dll+00178995 mexPrintf_800+00000035
[ 11] 0x00007ff91c1512d6
C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\PsychOculusVRCore1.mexw64+00004822
[ 12] 0x00007ff8fb700b1c C:\Program
Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll+00920348
ConfiguratorUnregisterC+00004796
[ 13] 0x00007ff8fb7007de C:\Program
Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll+00919518
ConfiguratorUnregisterC+00003966
[ 14] 0x00007ff951cd3034
 C:\WINDOWS\System32\KERNEL32.DLL+00077876 BaseThreadInitThunk+00000020
[ 15] 0x00007ff9527a3691
C:\WINDOWS\SYSTEM32\ntdll.dll+00472721 RtlUserThreadStart+00000033

**Comment by kleinerm** [comment]
Can you check if the crash goes away if you add a call:

PsychOculusVR1('Verbosity', 0);

before the Screen('Closeall') or sca; call in the VR demo?

My suspicion is that the Oculus runtime wants to print some status output
via our logging callback, and does so from a thread other than the Matlab
main thread, and that causes the crash. None of this happened with my
Matlab versions during testing, but those are way older than R2018a, so
maybe R2018a doesn't like such printing from non-main threads anymore.

**Comment by mwang67** [comment]
I added the line as such to the end of VRHMDDemo:

KbStrokeWait;
PsychOculusVR1('Verbosity', 0);
sca;
close all;
plot(1000 * diff(vbl));

and the log looks like the same.  So far I have tried on matlab 2018a and
b.  But I can try an earlier version.  Which matlab versions have worked
for you?



Assertion detected at Mon Jan 28 12:57:57 2019 -0800
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : windows-1252
  Deployed                 : false
  Graphics Driver          : Unknown software
  Graphics card 1          : Intel Corporation ( 0x8086 ) Intel(R) HD
Graphics 630 Version 21.20.16.4550 (2016-11-11)
  Graphics card 2          : NVIDIA ( 0x10de ) NVIDIA GeForce GTX 1070
Version 23.21.13.9125 (2018-3-16)
  Java Version             : Java 1.8.0_144-b01 with Oracle Corporation
Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : win64
  MATLAB Entitlement ID    : 4808126
  MATLAB Root              : C:\Program Files\MATLAB\R2018a
  MATLAB Version           : 9.4.0.813654 (R2018a)
  OpenGL                   : software
  Operating System         : Microsoft Windows 10 Home
  Process ID               : 1832
  Processor ID             : x86 Family 6 Model 158 Stepping 9, GenuineIntel
  Session Key              : 6eaaffc3-d0c5-4446-816e-d2efa2a35387
  Window System            : Version 10.0 (Build 17134)

Fault Count: 1


Assertion in foundation::usm::Detail<struct
foundation::usm::scope::Mvm>::find at
b:\matlab\foundation\usm\management.cpp line 671

Register State (captured):
  RAX = 0000000010aa2ef8  RBX = 0000000000000000
  RCX = 00000001a803e350  RDX = 0000000000000000
  RSP = 00000001a803e2d0  RBP = 0000000011746b08
  RSI = 0000000010aa2ef8  RDI = 0000000010aa2ef8

   R8 = 0000448b0d872bd9   R9 = 00007ff948850000
  R10 = 00000000109da298  R11 = 0000000010a92efc
  R12 = 00000001a803e990  R13 = 0000000010a92e28
  R14 = 0000000010aa2e78  R15 = 0000000011746b08

  RIP = 000000001089c44a  EFL = 00000202

   CS = 0033   FS = 0053   GS = 002b

Stack Trace (captured):
[  0] 0x0000000010896063
bin\win64\libmwfl.dll+00155747
foundation::core::diag::thread_context::unspecified_bool+00000051
[  1] 0x0000000010894658
bin\win64\libmwfl.dll+00149080
foundation::core::diag::stacktrace_base::capture+00000024
[  2] 0x0000000010898925
bin\win64\libmwfl.dll+00166181
foundation::core::diag::symbols::getSymbolAddress+00009941
[  3] 0x0000000010897aae
bin\win64\libmwfl.dll+00162478
foundation::core::diag::symbols::getSymbolAddress+00006238
[  4] 0x000000001089bd3b
bin\win64\libmwfl.dll+00179515 foundation::core::diag::terminate+00000059
[  5] 0x000000001172340c
bin\win64\libmwfoundation_usm.dll+00013324
foundation::usm::getErrorHandler+00000060
[  6] 0x0000000011737c29
bin\win64\libmwfoundation_usm.dll+00097321
foundation::usm::Detail<foundation::usm::scope::Mvm>::find+00000233
[  7] 0x00000000fb5f4f37
bin\win64\libmwbridge.dll+00020279 ioSetIoCallbacks+00001479
[  8] 0x00000000fb5f5f93
bin\win64\libmwbridge.dll+00024467 ioSetIoCallbacks+00005667
[  9] 0x00000000fe9d9efa
bin\win64\libut.dll+00237306 utVprintf+00000202
[ 10] 0x00000000fc60bb33
 bin\win64\libmex.dll+00178995 mexPrintf_800+00000035
[ 11] 0x00007ff91dd212d6
C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\PsychOculusVRCore1.mexw64+00004822
[ 12] 0x00007ff8dd940b1c C:\Program
Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll+00920348
ConfiguratorUnregisterC+00004796
[ 13] 0x00007ff8dd9407de C:\Program
Files\Oculus\Support\oculus-runtime\LibOVRRT64_1.dll+00919518
ConfiguratorUnregisterC+00003966
[ 14] 0x00007ff951cd3034
 C:\WINDOWS\System32\KERNEL32.DLL+00077876 BaseThreadInitThunk+00000020
[ 15] 0x00007ff9527a3691
C:\WINDOWS\SYSTEM32\ntdll.dll+00472721 RtlUserThreadStart+00000033

**Comment by kleinerm** [comment]
Don't remember from the top of my head, i'm not close to the test machine
atm. But probably some R2014'ish version, nothing more modern.

The crash log looks very much as if some logging output would cause it.
Maybe try PsychOculusVRCore1('Verbosity', 0); and try to find out with some
debug output if the crash is really in Screen('CloseAll')?

**Comment by mwang67** [comment]
I tried using "keyboard" to pause the VRHMDDemo script and see where the
crash happens.  And it seems that maybe something is wrong with PsychVRHMD
function?

PsychImaging('PrepareConfiguration');
keyboard     <<---up to this point in the code is fine

if ~stereoscopic
  % Setup the HMD to act as a regular "monoscopic" display monitor
  % by displaying the same image to both eyes:
  PsychVRHMD('AutoSetupHMD', 'Monoscopic', 'LowPersistence FastResponse
DebugDisplay', [], [], deviceindex);
else
  % Setup for stereoscopic presentation:
  PsychVRHMD('AutoSetupHMD', 'Stereoscopic', 'LowPersistence FastResponse',
[], [], deviceindex);
end

keyboard;      <<----here crashes

Then I tried:

PsychImaging('PrepareConfiguration');
if ~stereoscopic
  PsychVRHMD('AutoSetupHMD', 'Monoscopic', 'LowPersistence FastResponse
DebugDisplay', [], [], deviceindex);
else
  PsychVRHMD('AutoSetupHMD', 'Stereoscopic', 'LowPersistence FastResponse',
[], [], deviceindex);
end
PsychOculusVRCore1('Verbosity', 0)    <<-- added this, and shows the
following type of bug
keyboard;

Command window
>> VRHMDDemo
Tried to prepare a new configuration phase via
PsychImaging('PrepareConfiguration'), but did not finalize the previous
phase yet.
You must call the PsychImaging('OpenWindow', ...); command at least once to
open an onscreen
window according to the provided settings, before you can specify settings
for additional onscreen windows.

The most likely reason you see this error message is because your script
aborted with some error
before it managed to open the onscreen window. In that case it is best
practice to execute a 'clear all'
command at the Matlab/Octave prompt before you restart your script.

I will restart configuration now and forget the previously made
PsychImaging('AddTask', ...); settings.
Warning: Tried to prepare a new configuration phase, but you did not
finalize the
previous phase yet!
> In PsychImaging (line 1446)
  In VRHMDDemo (line 44)
PsychOculusVR1: Opening the first connected Oculus VR headset.
PsychOculusVRCore1-ERROR: Failed to connect to Oculus Rift with deviceIndex
0. This could mean that the device
PsychOculusVRCore1-ERROR: is already in use by another application or
driver.
Error in function Open: Usage error
Could not connect to Rift device with given 'deviceIndex'! [ovr_Create()
failed]
Error using PsychOculusVRCore1
Usage:

[oculusPtr, modelName, resolutionX, resolutionY, refreshHz,
controllerTypes]] =
PsychOculusVRCore1('Open' [, deviceIndex=0][, multiThreaded=0]);

Error in PsychOculusVR1 (line 1231)
  [handle, modelName, panelXRes, panelYRes, panelHz, controllerTypes] =
  PsychOculusVRCore1('Open', varargin{:});

Error in PsychOculusVR1 (line 1142)
      newhmd = PsychOculusVR1('Open', 0);

Error in PsychVRHMD (line 663)
    hmd = PsychOculusVR1('AutoSetupHMD', basicTask, basicRequirements,
basicQuality,
    deviceIndex);

Error in VRHMDDemo (line 52)
  PsychVRHMD('AutoSetupHMD', 'Stereoscopic', 'LowPersistence FastResponse',
[], [],
  deviceindex);

**Comment by kleinerm** [comment]
Those bugs are not bugs, but you had some regular error abort or manual
abort and didn't call "clear all" to reset everything.

Always call "clear all" before a new test-run to avoid such false errors.
Try what happens if you use the PsychOculusVRCore1('Verbosity', 0); call at
the very beginning of the demo, so all driver status output is suppressed.

**Comment by mwang67** [comment]
Matlab was able to run without crashing when that line is put at the very
beginning.
Thank you very much!

**Comment by kleinerm** [comment]
That means my suspicion wrt. recent Matlab's is probably correct. I'll add
a fix for the next PTB beta, but might need some feedback from you if it
works out, once i've done that. Please keep monitoring this issue.

**Comment by mwang67** [comment]
Yes, happy to help. Thank you.

**Comment by kleinerm** [comment]
Ok, new PTB beta is out. Try without the workaround. Hopefully it is fixed.

**Comment by mwang67** [comment]
Was able to do the demo without the workaround.  Thank you for the fix!

**Comment by kleinerm** [comment]
Good. Thanks for the feedback. Case closed.
