### ISSUE TITLE
Error PsychImaging

### ISSUE THREAD

**Issue by iiceyyy** [Psychtoolbox-3/Psychtoolbox-3#530]
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.

WARNING: VBL Calibration run No. 1 failed. Retrying...

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: GeForce GT 750M/PCIe/SSE2 :: 4.5.0 NVIDIA 369.09
PTB-INFO: VBL startline = 768 , VBL Endline = 768
PTB-INFO: Measured monitor refresh interval from beamposition = 16.666593 ms [60.000264 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 14.109421 ms [70.874631 Hz]. (10 valid samples taken, stddev=0.526672 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

WARNING: Mismatch between measured monitor refresh interval and interval reported by operating system.
This indicates massive problems with VBL sync.

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

Error use Screen
See error message printed above.

Error PsychImaging (line 2077)
            [win, winRect] = Screen('OpenWindow', screenid, clearcolor, winRect,
            pixelSize, numbuffers, stereomode, multiSample, imagingMode, specialFlags,
            clientRect, fbOverrideRect);

I have tried many times but didn't work ,how can I solve it?

**Comment by dcnieho** [comment]
Have you read help SyncTrouble as the error suggests?
