### ISSUE TITLE
Typing error in glmGetPixels

### ISSUE THREAD

**Issue by carlounimib** [Psychtoolbox-3/Psychtoolbox-3#534]
There is a typing error in glmGetPixels.m (PsychOpenGL\MOGL\wrap) at line 21
height=rect(4)-rect)2); 
instead of
height=rect(4)-rect(2);

**Comment by kleinerm** [comment]
Oh, i think we should remove those glm functions, as most of them only worked on very old Apple PowerPC hardware iirc. They don't serve any purpose since over a decade. I'll remove them for the next PTB update. The correct replacement for that function is simply Screen('GetImage',...).
