### ISSUE TITLE
Using Psychtoolbox as python library？？？

### ISSUE THREAD

**Issue by plumewind** [Psychtoolbox-3/Psychtoolbox-3#535]
Hello ,

I want to apply the visual stimulation system to the actual system, which is used here. But most of the system is written in C++ or Python. I know how this toolbox is used in matlab. I want to ask now: Can he be used as a python library?
thank you very much.

**Comment by kleinerm** [comment]
Not the visual stimulus system yet. I was contracted by the PsychoPy project to port over our GetSecs, WaitSecs, IOPort, PsychHID and PsychPortAudio drivers so far. The PsychoPy people now work on writing more Pythonic wrapper classes around these ported mex files and to integrate them into PsychoPy.

Porting Screen for visual stimulation would be possible and certainly highly beneficial, but it is a chunk of work for which i would need to get contracted to do. Probably around 10.000 Euros (+ VAT if applicable) would probably be an appropriate amount. So lets see what the future brings...
