### ISSUE TITLE
Problem with graphics driver and Mesa OpenGL

### ISSUE THREAD

**Issue by JacopoTurini** [Psychtoolbox-3/Psychtoolbox-3#536]
Hello, I'm running PTB-3 on Linux (Ubuntu 18.04.2 LTS) in the R2018b Matlab version. I just moved to this setting and when I run my code I get this error:

> PTB-INFO: This is Psychtoolbox-3 for GNU/Linux X11, under Matlab 64-Bit (Version 3.0.15 - Build date: Feb  6 2019).
> PTB-INFO: Support status on this operating system release: Linux 4.18.0-16-generic Supported.
> PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
> PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
> PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.
> 
> PTB-INFO: NVIDIA Corporation - GP104 [GeForce GTX 1080] GPU found. Trying to establish low-level access...
> PTB-INFO: Connected to NVidia GP104 [GeForce GTX 1080] GPU of NV-130 family with 4 display heads.
> PTB-WARNING: Your graphics driver doesn't allow me to control syncing wrt. vertical retrace!
> PTB-WARNING: Please update your display graphics driver as soon as possible to fix this.
> PTB-WARNING: Until then, you can manually enable syncing to VBL somehow in a manner that is
> PTB-WARNING: dependent on the type of gfx-card and driver. Google is your friend...
> 
> 
> 
> 
> PTB-WARNING: Seems that a Mesa OpenGL software renderer is active! This will likely cause miserable
> PTB-WARNING: performance, lack of functionality and severe timing and synchronization problems.
> PTB-WARNING: Most likely you are running Psychtoolbox on a Matlab version 8.4 (R2014b) or later and
> PTB-WARNING: Matlab is causing this problem by overriding your operating systems OpenGL library with
> PTB-WARNING: its own outdated software library. Please run the setup script PsychLinuxConfiguration()
> PTB-WARNING: now from your Matlab command window and then quit and restart Matlab to fix this problem.
> 
> 
> PTB-WARNING: Actually, it is pointless to continue with the software renderer, as that will cause more trouble than good.
> PTB-WARNING: I will abort now. Read the troubleshooting tips above to fix the problem. You can override this if you add the following
> PTB-WARNING: command: Screen('Preference', 'ConserveVRAM', 64); to get a functional, but close to useless window up and running.
> 
> 
> Error using Screen
> See error message printed above.

I ran successfully PsychLinuxConfiguration() as suggested by the warnings and the PTB website, closed Matlab, restarted and still got the same message.

Thanks for the support!

**Comment by kleinerm** [comment]
Assuming you didn't use the PTB from NeuroDebian, but directly from us via DownloadPsychtoolbox? Have you called 'sudo apt install matlab-support' and answered YES when it asks if it should fix your Matlab installation for incompatibilities?

**Comment by kleinerm** [comment]
Also, a GeForce 1000 series gpu will run very slowly under the open-source drivers. If you want more than 10% of the graphics performance of your gpu you'd unfortunately need to install NVidia's proprietary graphics driver. This is one of the reasons i recommend against use of NVidia gpu's for visual stimulation. NVidia is rather unfriendly to open-source drivers, so you lose part of the open-source advantage of Linux if you want to use a modern NVidia gpu at high performance.

**Comment by kleinerm** [comment]
No user response in over 2 months, closing.
