### ISSUE TITLE
"SetupPsychtoolbox.m" breaks Matlab startup procedure on a multi-user Windows machine

### ISSUE THREAD

**Issue by yhz-1995** [Psychtoolbox-3/Psychtoolbox-3#539]
Hello, I am trying to install Psychtoolbox on a multi-user Windows 10 machine. I am the administrator of the computer, but I hope to install the toolbox for one particular standard account (i.e. does not affect Matlab path for other user account).

After downloading the zip file from Github, I logged in to that standard account, open Matlab and ran "SetupPsychtoolbox". Then Matlab asked for administrator privileges, I felt a bit wired but still granted it. The installation finished with no error. However, I immediately found that Matlab startup procedure was broken on all other accounts (including the administrator account). It gave a lot of errors:

```
An error occurred while trying to determine whether "pathdef" is a function
name.
 
Undefined function 'usejava' for input arguments of type 'char'.
Warning: MATLAB did not appear to successfully set the search path. To recover
for this session of MATLAB, type "restoredefaultpath;matlabrc". To find out how
to avoid this warning the next time you start MATLAB, type "docsearch problem
path" after recovering for this session. 
Warning: Initializing Java preferences failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:
MATLAB:UndefinedFunction
Undefined function 'usejava' for input arguments of type 'char'. 
> In matlabrc (line 66) 
Warning: Initializing MATLAB Graphics failed.
This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:
MATLAB:UndefinedFunction
Undefined function or variable 'ismac'. 
> In hgrc (line 163)
  In matlabrc (line 72) 
Warning: Failed to add default profiler filters. 
> In matlabrc (line 81) 
Warning: Executing startup failed in matlabrc.
This indicates a potentially serious problem in your MATLAB setup, which should
be resolved as soon as possible.  Error detected was:
MATLAB:UndefinedFunction
Undefined function 'addpath' for input arguments of type 'char'. 
Undefined function or variable 'rmiml.getAll'. 
Undefined function or variable 'rmiml.visibleInToolstrip'. 
Undefined function or variable
'internal.matlab.desktop.editor.getSystemObjectInfo'. 
Undefined function or variable
'matlab.unittest.internal.ui.toolstrip.getFileInfoForToolstrip'. 
Undefined function or variable 'rmiml.getAll'. 
Undefined function or variable
'matlab.unittest.internal.ui.toolstrip.getFileInfoForToolstrip'. 
Undefined function or variable
'internal.matlab.desktop.editor.getSystemObjectInfo'. 
Undefined function or variable 'rmiml.visibleInToolstrip'. 
Undefined function or variable 'rmiml.getAll'. 
Undefined function or variable
'matlab.unittest.internal.ui.toolstrip.getFileInfoForToolstrip'. 
Undefined function or variable
'internal.matlab.desktop.editor.getSystemObjectInfo'. 
Undefined function or variable 'rmiml.visibleInToolstrip'. 
Undefined function or variable 'rmiml.getAll'. 
Undefined function or variable
'matlab.unittest.internal.ui.toolstrip.getFileInfoForToolstrip'. 
Undefined function or variable
'internal.matlab.desktop.editor.getSystemObjectInfo'. 
Undefined function or variable 'rmiml.visibleInToolstrip'. 
Undefined function or variable 'rmiml.visibleInToolstrip'. 
Undefined function or variable 'connector.ensureServiceOn'. 
Undefined function or variable 'connector.ensureServiceOn'. 
Undefined function or variable 'connector.ensureServiceOn'. 
Undefined function or variable 'mls.internal.FevalService.init'. 
java.lang.NoClassDefFoundError: Could not initialize class com.mathworks.services.editordataservice.EditorDataServiceManager$SingletonHolder
	at com.mathworks.services.editordataservice.EditorDataServiceManager.getInstance(EditorDataServiceManager.java:118)
	at com.mathworks.connector.standalone_host.impl.StandaloneHostImpl.startEditor(StandaloneHostImpl.java:244)
	at com.mathworks.connector.standalone_host.impl.StandaloneHostImpl.doStart(StandaloneHostImpl.java:101)
	at com.mathworks.connector.standalone_host.StandaloneHost.start(StandaloneHost.java:60)
Undefined function or variable 'connector.internal.lifecycle.callConnectorStarted'. 
Undefined function or variable 'matlab.supportpackagemanagement.internal.getInstalledSupportPackagesInfo'. 
Undefined function or variable 'rmiml.visibleInToolstrip'. 
```

We are using Matlab R2018b here. I hope to know what is the possible cause of this problem?

**Comment by kleinerm** [comment]
Sorry, no idea why that would happen? The script just adds the Psychtoolbox folder to the search path with addpath() and then uses savepath() to save the new path. Nothing special there. PTB itself doesn't ask for your password, i assume Matlab did, maybe for savepath()?

**Comment by yhz-1995** [comment]
Yes, it is the savepath() function that needs administrative permission. I have found the cause of the problem: after saving Matlab path from a standard account, the permission of "pathdef.m" file is somehow corrupt: only that standard can read it, and all other accounts, including the administrator account do not have read access to it. Therefore Matlab startup procedure fails on other accounts. I guess it is a Matlab or Windows bug.

However, is it mandatory for Psychtoolbox to savepath during installation? On a multi-user machine, I guess it would be better to use a "startup.m" to load user-specific Matlab search path for each account, which has already been implemented in Psychtoolbox currenlty.

**Comment by kleinerm** [comment]
You'd have the same problem when putting that into a startup.m file, because then we'd have to add the location of that startup.m file inside the Psychtoolbox folder to Matlab's path, no?

It's a bit weird you encounter this problem, as i'd assume other Windows users also have multiple non-admin accounts with Matlab, and this is the first time ever i heard about such a problem.

Could there be something wrong with the filesystem permissions etc. on your specific Matlab installation?

**Comment by lcnature** [comment]
Hello, this seems to occur to linux (Ubuntu 18.04) as well. I had the error mentioned in this [thread](https://www.mathworks.com/matlabcentral/answers/390813-why-s-getfileinfofortoolstrip-missing-after-update-to-r2018a), after following the suggestion, the error of `Undefined function or variable 'matlab.unittest.internal.ui.toolstrip.getFileInfoForToolstrip'` was gone, but so was psychtoolbox. When I re-install psychtoolbox using `sudo apt-get install matlab-psychtoolbox-3 ` and `ptb3-matlab`, the error did not show up, but another error said it cannot save path to the default pathfile. After restarting matlab, the error of `Undefined function or variable 'matlab.unittest.internal.ui.toolstrip.getFileInfoForToolstrip'` occurs again.
