### ISSUE TITLE
Screen OpenVideoCapture memory leak

### ISSUE THREAD

**Issue by brittyazel** [Psychtoolbox-3/Psychtoolbox-3#545]
I'm having an issue when using "SetNextCaptureBinSpec" when opening my webcam device for video capture. First, I need to open the webcam device using image/jpeg rather than video/x-raw, but I could not find a way to do it with the built in options provided (please point me in the right direction if there is this option). My solution to this was to use the SetNextCaptureBinSpec to create the GStreamer pipeline myself, and after a bunch of time figuring it out I came up with this:

`Screen('SetVideoCaptureParameter', -1, 'SetNextCaptureBinSpec=v4l2src device=/dev/video0 ! image/jpeg ! jpegdec');
`
Now, this works amazing, and for about 2 min my video works like a charm, however this method leaks memory like crazy, on the order of 200MB/sec and my whole RAM supply is filled in just a couple of minutes. I've tried to add in options like "fakesink" or manually specifying a save path, but if I do so the psychtoolbox script stalls on that line and doesn't go any further. However, an important note is that even though the script stalls waiting for the GStreamer sink to finish, the memory leak goes away.

So I think the issue is that I'm not manually specifying a sink and all of the video is being stored to memory. I'd also like to note that adding a targetmoviename to the OpenVideoCapture also doesn't fix this, even though the file starts being written once the video recording is started.

OS: Archlinux (and Ubuntu 18.04)
Psychtoolbox Version: PTB_Beta-2019-02-07_V3.0.15
GStreamer version: 1.14.4

**Comment by kleinerm** [comment]
Hi,

i can't reproduce such a memory leak if i modify VideoIPWebcamCaptureDemo.m by inserting this
capturebinspec = 'v4l2src device=/dev/video0 ! videoconvert'
into line 163. My cams don't do jpeg, so this is the closest i can do to your example.

This suggests the memory leak is not caused by Psychtoolbox.

GStreamer docs list this as an example pipeline for your case:
gst-launch-1.0 v4l2src ! jpegdec ! xvimagesink

So in your case that would translate to:
gst-launch-1.0 v4l2src device=/dev/video0 ! jpegdec

Given that i can't observe any memory leaks on Ubuntu 18.04.2 LTS with my closest example, i wonder if your script maybe forgets to Screen('Close', tex) the texture retrieved from Screen('GetCapturedImage',...)? That would be the most simple explanation.

**Comment by brittyazel** [comment]
Sadly it's not as simple as forgetting a Screen("close"). The issue begins immediately after starting video playback, not after requesting a frame. Even having the video running in the background causes the leak. 

I think I'm closer to figuring it out though, with using "image/jpeg ! jpegdec" in my SetNextCaptureBinSpec I cannot write the recording to file. Setting a file path to save as something like "test.mov" results in the file being created when starting recording, but it being 0bytes at the end. Something is breaking recording. However, when I default to "video/x-raw format=yuy2" recording works fine.

Oddly when I envoke the same command for gstreamer from the command line with a filesink, recording works great with image/jpeg. So something weird is happing internally with the Psychtoolbox gstreamer call that I can't rectify

**Comment by kleinerm** [comment]
So you get the memory leak if you modify the VideoIPWebcamCaptureDemo.m to set line 163 as
capturebinspec = 'v4l2src device=/dev/video0 ! jpegdec' ?
Does the following make any difference?
capturebinspec = 'v4l2src device=/dev/video0 ! jpegdec ! videoconvert'

PTB's engine uses the camerabin element internally, ie. it feeds the output of capturebinspec as video-source into that element. But then my capturebinspec didn't cause any memory leaks, so i don't know what peculiarity of jpegdec would cause a memory leak when used with the camerabin element.

**Comment by kleinerm** [comment]
No response in over a month, closing.

**Comment by brittyazel** [comment]
Sorry I got sidetracked with travel and other projects. I'll respond to this ticket sometime early next week and try out what you all recommended. I was also waiting for the release of GStreamer 1.16 to see if that would help the problem. Should I leave the ticket closed?
