### ISSUE TITLE
support octave 5.1.0

### ISSUE THREAD

**Issue by eflister** [Psychtoolbox-3/Psychtoolbox-3#547]

**Comment by kleinerm** [comment]
On the todo list for the next PTB version bump to 3.0.16, probably soonish. We can only do such backwards compat breaking changes with a version bump, as at least Octave for Windows and Apple's trainwreck are not compatible wrt. mex files across different Octave minor versions. It's not a priority for the Octave developers, so the fact it worked on Linux was more a mixture of trickery on my side and some luck. Even there 4.2 -> 4.4 finally breaks that.

**Comment by kleinerm** [comment]
Done. Octave 5.1.0 it is on Windows and macOS. Octave 3.8 and later for Linux.
Now one must install GStreamer 1.16.0 or later in the MSVC version for Octave 5.1 to work.
