### ISSUE TITLE
Successfully building PsychPython on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by biogeo** [Psychtoolbox-3/Psychtoolbox-3#552]
I saw the note that PsychPython was not building on Ubuntu 18.04 LTS. After trying setup.py on my system and iterating through package installations to clear errors, I got a successful build, and I can import psychtoolbox and get a correct-looking result from psychtoolbox.GetSecs().

I had to do the following:

```
sudo apt install libusb-1.0-0-dev libxi-dev libasound2-dev portaudio19-dev
python setup.py build
```

I didn't start from a totally clean install, so of course it's possible I had already installed some requirements beyond the base, but I thought I'd share this in case it helps.

I'm really excited to see PsychToolbox come to Python and am willing to help out with testing. I assume Screen is going to require a lot more work before it's ready?

**Comment by biogeo** [comment]
Oh, this was with Python 3.6.7, also.

**Comment by kleinerm** [comment]
The most easy on Ubuntu/Debian and related - with Universe repo enabled - should be a

sudo apt build-dep psychtoolbox-3

That pulls all build dependencies of the octave-psychtoolbox-3, so probably a tad more than what you'd need, given it will pull in GNU/Octave development libs/headers, but at least not too little.
