### ISSUE TITLE
PlayMoviesWithoutGapDemo2 skipping frames at the end of video

### ISSUE THREAD

**Issue by josefaffourtit** [Psychtoolbox-3/Psychtoolbox-3#553]
Running the script as provided on the tutorial subpage of the psychtoolbox website, and the videos (which are identical except for content and length) are not being played until completion. I have an array which contains all the "counts" of the number of textures in each video, which I determine using:
 
     

```
for i=1:numMovFiles
      
       moviepath{i} = fullfile(stimDir,movieFiles{i});

       [movie, ~, ~, ~, ~, count] = Screen('OpenMovie', wPtr, moviepath{i});

       counts{i} = count;

       Screen('CloseMovie', movie);

    end
```

Then using the script provided on the website only 90% of the total textures are shown.

` [tex, pts] = Screen('GetMovieImage', wPtr, movie, 1);`

The script switches to the next video because pts < lastpts, but this is happening prematurely.

**Comment by kleinerm** [comment]
Hmm. It worked fine a few years ago on Linux with whatever GStreamer version i used at that time.

If it doesn't work, then that is out of our control, it would be some GStreamer issue. What OS and GStreamer version is this? We ususally recommend a modern Ubuntu Linux for best results.

The performance will probably also vary with the format/encoding of the movie file, so reencoding in another format might help. I think H264 generally worked well, but ymmv.

There's also PlayMoviesDemoWithoutGap1.m which uses a different mechanism to achieve similar/same results. Maybe worth a try.

Closing, as there ain't nothing we could do about this problem anyway - not a Psychtoolbox bug.
