### ISSUE TITLE
Problem with Psychtoolbox and Dell Xps15

### ISSUE THREAD

**Issue by LucaGuido** [Psychtoolbox-3/Psychtoolbox-3#554]
Hello. When I try to run scripts, I always get the message reported below. I am using a Dell XPS15 9560 with Nvidia GTX 1050 GPU. May you kindly help me with this? Thank you in advance!
Luca

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

WARNING: Mismatch between measured monitor refresh interval and interval reported by operating system.
This indicates massive problems with VBL sync.

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

**Comment by dcnieho** [comment]
Have you followed the suggestions in the message itself?

**Comment by LucaGuido** [comment]
Thank you for your reply. Yes, I did so but unfortunately the problem persists.

**Comment by dcnieho** [comment]
Do you want to use this machine for data collection or just development?
What screen resolution? Using internal or external screen? And i assume it
has both intel and nvidia gpu?

**Comment by LucaGuido** [comment]
Yes, I'd like to use the machine for data collection.
Screen resolution: 1920 x 1080
Using internal screen.
Yes, it has both intel and nvidia gpu.

**Comment by kleinerm** [comment]
Using the NVidia will most likely not work, as this is an Optimus laptop, and as explained on our webpage and in "help HybridGraphics", multi-gpu laptops are almost always broken wrt. visual timing. Linux docs for your laptop model suggest there is no way to fix this on your machine, as all video outputs are only connected to the Intel integrated chip.

You can try disabling the NVidia gpu when running Matlab/Octave. There's some choice if you right-click on the Matlab icon to run Matlab with integrated graphics only, iirc. Maybe also some way in NVidia driver settings panel to prevent use of the NVidia for Matlab/Octave.

This leaves you with Intel gpu, which statistically speaking, seems to be broken timing-wise on at least half all computers as well. Hence our strong recommendation to avoid Optimus laptops under Windows. Try it and see if PTB works or not, verify with external measurement equipment if PTB doesn't complain.

If you have a HiDPI display, ie. screen scaling other than 100% or 96 dpi, also check "help RetinaDisplays" for more trouble on Windows.

Your best bet if you need trustworthy timing on this laptop is to install Linux, e.g., as a dual-boot. At least Intel graphics should work very well timing-wise etc. under Linux. Use of the NVidia is in theory possible, as explained in help HybridGraphics, but not trivial at all on GeForce 800 series and later, not for beginners and far from plug & play or without limitations. E.g., if you wanted to use the NVidia efficiently, you'd be restricted to Ubuntu 18.04.1 LTS, no distribution with anything else than X-Server 1.19 atm., as PTB doesn't yet support high performance GeForce 800+ on X-Server 1.10 / Ubuntu 18.04.2 LTS or later.

The ArchLinux wiki gives some guidance, but sticking to a well working Intel onboard chip and the latest Ubuntu 18.04.2 LTS would probably be the way to go.

Good luck!

If you need precise visual timing you'll h

**Comment by LucaGuido** [comment]
Thank you very much. I will try what you suggested.
