### ISSUE TITLE
Sending triggers to BIOPAC System and FLIR camera

### ISSUE THREAD

**Issue by LucaGuido** [Psychtoolbox-3/Psychtoolbox-3#555]
Hello everyone.
I am trying to create a code for sending triggers to a BIOPAC system used for registering the skin conductance level (I would just need a timestamp on the representation of the signal and this should be done via Matlab) and to a FLIR thermograhic camera in order to start/stop the recording.
I have read that "IOPort" should be useful at this regard. Does anyone have suggestions on how to use it for the purpose mentioned above or alternatively may you suggest other methods?
I thank you very much in advance!

**Comment by kleinerm** [comment]
Already answered on forum. Please don't post everything twice in two locations.
