### ISSUE TITLE
Can we compile the c-mex files for Matlab by ourselves ? 

### ISSUE THREAD

**Issue by FrankYinXF** [Psychtoolbox-3/Psychtoolbox-3#559]
If the source file can release out so that we can compile the c-mex files, it will be great.

**Comment by dcnieho** [comment]
There in this repository, thats kinda the point

**Comment by kleinerm** [comment]
"help UseTheSource"

And the various build scripts in Psychtoolbox-3/PsychSourceGL/Source/ e.g., linuxmakeitoctave for Octave on Linux, or linuxmakeit64 for 64-Bit Matlab on Linux etc. Currently compiled against R2012a and Octave 4.2. You'll also need the various dependencies installed. Most easily on Debian, Ubuntu Linux via "sudo apt build-dep psychtoolbox-3"
