### ISSUE TITLE
Invalid MEX file for InitializePsychSound

### ISSUE THREAD

**Issue by aernesto** [Psychtoolbox-3/Psychtoolbox-3#560]
Greetings,

I am using MATLAB_R2016a on Mac OS X 10.10.5. I downloaded the [master branch](https://github.com/Psychtoolbox-3/Psychtoolbox-3/tree/895436d3a6a05e2608b316bfe78e6c869ee5a6df) from Psychtoolbox-3 and added it to my path. Then I called `InitializePsychSound` and got the following error:
```
>> InitializePsychSound
Failed to load PsychPortAudio driver!

The exact error message of the linker was: Invalid MEX-file '/Users/adrian/Documents/MATLAB/toolboxes/Psychtoolbox-3/Psychtoolbox/PsychBasic/PsychPortAudio.mexmaci64': dlopen(/Users/adrian/Documents/MATLAB/toolboxes/Psychtoolbox-3/Psychtoolbox/PsychBasic/PsychPortAudio.mexmaci64, 6): Symbol not found: _AudioOutputUnitStart
  Referenced from: /Users/adrian/Documents/MATLAB/toolboxes/Psychtoolbox-3/Psychtoolbox/PsychBasic/PsychPortAudio.mexmaci64 (which was built for Mac OS X 10.11)
  Expected in: /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
 in /Users/adrian/Documents/MATLAB/toolboxes/Psychtoolbox-3/Psychtoolbox/PsychBasic/PsychPortAudio.mexmaci64


Error using InitializePsychSound (line 106)
Failed to load PsychPortAudio driver.
```

What am I doing wrong? Could you please help me?

**Comment by dcnieho** [comment]
I don't know, but:
- use the beta branch, not the master branch (use install instructions on
psychtoolbox.org)
- "(which was built for Mac OS X 10.11)" seems like a good clue, your OSX
is too old. In general only a pretty recent OSX is supported. See again the
psychtoolbox.org website

**Comment by aernesto** [comment]
Thank you. The Beta branch didn't resolve the issue, so it's probably my old OS.
