### ISSUE TITLE
Controlling focus of PTB screen

### ISSUE THREAD

**Issue by jaib1** [Psychtoolbox-3/Psychtoolbox-3#561]
A very simple question that I'm sure has been answered before somewhere, but unfortunately I could not find the answer in the documentation: is there a way to control the focus of a PTB Window opened with the `Screen` command. Typically it can only be viewed in the foreground in front of all other applications, but I would like a way to be able to move it between background and foreground.

**Comment by dcnieho** [comment]
Google for windowshieldinglevel

**Comment by jaib1** [comment]
Cheers!
