### ISSUE TITLE
Python source distributions on PyPI

### ISSUE THREAD

**Issue by hoechenberger** [Psychtoolbox-3/Psychtoolbox-3#563]
Hello, currently, there are no source distributions (`sdist`s) of the Python library on PyPI. Would it be possible to please add those? Thank you!

**Comment by kleinerm** [comment]
So far the PsychoPy maintainer Jon Peirce does all the work wrt. building wheels etc., as i'm not familiar with the PyPI eco system and its rules and requirements. Also totally overloaded atm. with other stuff, so not time to get into this atm.

You seem to be part of the PsychoPy team, so if you want to create a pull request that adds whatever needs to be done to the setup.py or manifest for this, i'm happy to accept that. I can only do very superficial review though, so somebody else or you should make sure it is well working on all supported operating systems. I'll mostly just trust you know what you're doing unless proven oterhwise.

**Comment by hoechenberger** [comment]
Thanks for the response. I'll get in touch with Jon then. :)

**Comment by peircej** [comment]
Yes, no worries. I can push sdist versions too on release

**Comment by hoechenberger** [comment]
Great, thanks!

**Comment by peircej** [comment]
Incidentally @kleinerm what's the plan for 3.0.16? I've got a couple of tweaks for the pythonic version of the lib (notably adding a new class for Slave streams) but I've also run into an issue there that on windows (only) I'm getting nonsense when 2 slaves play together. I'll try and get a MWE over to you to check if it's "me" or "you" :wink: (or maybe just the hardware).

> You seem to be part of the PsychoPy team....I'll mostly just trust you know what you're doing unless proven oterhwise.

Richard is very capable and very careful (more so than me in both aspects!) but I'll also run my eyes over any PsychPython contributions
