### ISSUE TITLE
Matlab crashes on OpenMovie

### ISSUE THREAD

**Issue by coriumgit** [Psychtoolbox-3/Psychtoolbox-3#571]
Hello,
I'm trying to work with the movie playing functions, but it seems that OpenMovie is highly unreliable - it crashes Matlab on 95% of the times.
I'm calling OpenMovie on many different systems, be it windows xp, 7 or 10 (64bit) on Matlabs 2014 through 2018, on many different computers I got here. I tried OpenMovie with all sorts of video formats - .mkv, wmv, mpg, avi, mov - but with the same results ( I have Windows 7 Codec Pack installed on all systems). In contrast to these varieties, I consistently make sure I have gstreamer 1.14.4 installed on the system. 
One thing that helped getting OpenMovie to work was resetting the computer and opening Matlab and running the script  right after the startup. This worked quite randomly - it worked only for some movies in some formats, but those files for which OpenMovie worked after a reset, it worked every time...
[matlab crash.pdf](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/3439017/matlab.crash.pdf)

**Comment by kleinerm** [comment]
This has been reported so often and answered and workarounds explained on our webpage that i'm baffled how you could have missed it?

Anyway, today Psychtoolbox 3.0.16 was released, which may fix these issues. Read the announcement carefully, and make sure you have the GStreamer versions etc. installed which are mentioned in the release announcement:

http://psychtoolbox.org/news.html
