### ISSUE TITLE
General CIE chromaticity plotter?

### ISSUE THREAD

**Issue by da5nsy** [Psychtoolbox-3/Psychtoolbox-3#576]
Probably FAO @DavidBrainard 

Does PTB have a general chromaticity diagram plotter?
I've written and been using one and wondered if it would be valuable within PTB.

https://github.com/da5nsy/General-Purpose-Functions/blob/master/drawChromaticity.m

Would need cleaning up to suit general purposes of course, happy to do so if it doesn't already exist and would be useful.

**Comment by DavidBrainard** [comment]
I don't recall something like this in PTB as a separate function.  There are various tutorials I've written that make chromaticity plots, but I can see that a separate function in the toolbox could be quite useful.  The PTB Colorimetry routines tend to use (e.g.) DrawChromaticity as their function naming convention, so I'd prefer to make that switch, as well as other clean up (such as header comments explaining what it does and what the inputs are.  Thanks!

**Comment by da5nsy** [comment]
Sure, sounds good. 
I've got a thesis to write but I'll come back to this in a few weeks once that's done and neaten it up.

Any preference between DrawChromaticity and PlotChromaticity? (Or other suggestion?)

**Comment by da5nsy** [comment]
Hi David,
Finally having a crack at this. 
Found a slight issue - since T_xyz1931.mat is only to 4 decimal places, the ends of the spectral locus get pretty wild (see screenshot below, or [code](https://github.com/da5nsy/General-Purpose-Functions/blob/ca2d523d98603c5cf1f2bc8407c20a3062f775f5/Compare1931PTBvsCIE.m)). For my own work, I've hard-coded it so that it ignores the first and last few values, but this seems inappropriate for public code. 
The comparison above uses the [data from the CIE website](http://files.cie.co.at/204.xls) which goes down to 6dp (though interestingly - only at the extremes).
The only real solution I can see would be to increase the precision of the underlying data. How would you feel about that?

![image](https://user-images.githubusercontent.com/3739866/67051980-ae842500-f134-11e9-838a-a637348b5d52.png)

![image](https://user-images.githubusercontent.com/3739866/67051997-bf349b00-f134-11e9-86b1-d96e29b0f906.png)

![image](https://user-images.githubusercontent.com/3739866/67051946-990efb00-f134-11e9-9e93-8fcfd1549053.png)

**Comment by DavidBrainard** [comment]
I don't have any objection to matching the CIE specification in terms of the precision to which these are entered.   If you create a new version of T_xyz1931 and send it to me, I'll fold it in.

**Comment by da5nsy** [comment]
Hi David, Please find [here](https://github.com/da5nsy/General-Purpose-Functions/blob/b664c5ea5cae466d44c5ef54c0ec2104d8aff87e/DrawChromaticity.m) my chromaticity plotter. I've added a few extra options, neatened it up and written some comments. If you're happy with it, please roll it into PTB.

**Comment by DavidBrainard** [comment]
Will try to review these PR's by this coming weekend.

**Comment by DavidBrainard** [comment]
Sorry to be slow to get to this.  Haven't lost track of it.

**Comment by DavidBrainard** [comment]
The new XYZ data and drawChromaticity now merged into PTB master.

**Comment by da5nsy** [comment]
Missed this development, thanks @DavidBrainard !
