### ISSUE TITLE
Bug in PsychDrawSprites2D with Matlab R2019a

### ISSUE THREAD

**Issue by rdiggelmann** [Psychtoolbox-3/Psychtoolbox-3#577]
PsychDrawSprites2D throws an error when you try to show exactly 4 objects. The error appears in line 147 in 'PsychDrawSprites2D' or in line 17 in 'CenterRectOnPointd' respectively:

```
Unable to perform assignment because the indices on the left side are not compatible with the size of the right side.

Error in OffsetRect (line 63)
        newRect(:, RectTop) = oldRect(:, RectTop) + y;

Error in CenterRectOnPointd (line 18)
newRect=OffsetRect(rect,x-cX,y-cY);

Error in PsychDrawSprites2D (line 147)
dstRects = CenterRectOnPointd(brects', xy(1,:)', xy(2,:)')';
```

What causes the error is unclear to me, but it happens only when the input to 'RectCenterd' is a 4x4 matrix (thus it only appears when showing 4 objects). The output of RectCenterd is then in a wrong format that causes the subsequent function call to fail.

My workaround for this error is to duplicate one objects whenever there should be 4. This is a very ugly hack, but it for for now until this issue is taken care of.

**Comment by kleinerm** [comment]
Yep, there's an ambiguity in rect processing inside CenterRectOnPointd() for 4x4 input matrices, wrt. if these are 4 rects as one rect per row, or one rect per column.

Fixed for next beta update. Until then you can get a fixed CenterRectOnPointd() from here:

https://raw.githubusercontent.com/kleinerm/Psychtoolbox-3/master/Psychtoolbox/PsychRects/CenterRectOnPointd.m

**Comment by rdiggelmann** [comment]
Thanks!
