### ISSUE TITLE
PsychPortAudio &  Screen('GetMovieImage') simultaneos times out waiting for a new frame

### ISSUE THREAD

**Issue by marcelfarres** [Psychtoolbox-3/Psychtoolbox-3#581]
I want to present a movie and then different sounds independently of that video. 

When I try to do it the `tex = Screen('GetMovieImage', win, movie);` only is able to pull the first frame and then always return `tex = 0`.

Anyone has a workaround or knows why this happens. 

I attach some example code, if you set `isAudioActive=true` the video will stop playing with this error

`PTB-ERROR: In Screen('GetMovieImage') for movie 0: Timed out while waiting for new frame after 5 seconds!`

Thanks in advance. 

Test Code
```

AssertOpenGL;
moviename = [PsychtoolboxRoot 'PsychDemos/MovieDemos/DualDiscs.mov'];
isAudioActive = true;
windowrect = [200, 250, 1100, 850];
% Wait until user releases keys on keyboard:
KbReleaseWait;

% Select screen for display of movie:
screenid = max(Screen('Screens'));

try
    if isAudioActive
        InitializePsychSound(1);
        pahandle = PsychPortAudio('Open', [], [], 2, [], 1, 0); 
    end
    % Open 'windowrect' sized window on screen, with black [0] background color:
    win = Screen('OpenWindow', screenid, 0, windowrect);
    
    % Open movie file:
    movie = Screen('OpenMovie', win, moviename);
    
    % Start playback engine:
    Screen('PlayMovie', movie, 1);
    
    % Playback loop: Runs until end of movie or keypress:
    while ~KbCheck
        % Wait for next movie frame, retrieve texture handle to it
        tex = Screen('GetMovieImage', win, movie);
        
        % Valid texture returned? A negative value means end of movie reached:
        if tex<=0
            % We're done, break out of loop:
            break;
        end
        
        % Draw the new texture immediately to screen:
        Screen('DrawTexture', win, tex);
        
        % Update display:
        Screen('Flip', win);
        
        % Release texture:
        Screen('Close', tex);
    end
    
    % Stop playback:
    Screen('PlayMovie', movie, 0);
    
    % Close movie:
    Screen('CloseMovie', movie);
    
    % Close Screen, we're done:
    sca;
    
catch %#ok<CTCH>
    sca;
    PsychPortAudio('Close')
    psychrethrow(psychlasterror);
end 
```

**Comment by kleinerm** [comment]
Look at the optional specialflags parameter for Screen('Openmovie', ...). There's a flag to tell PTB that no audio should be played back from the movie. That should do the trick. Without that flag GStreamer will try to open a connection to the sound card even for movies without sound track. If PsychPortAudio grabs exclusive control of the soundcard, that would go wrong, as the movie playback would block until the sound card becomes available, but the soundcard is blocked by PsychPortAudio.

Happens at least on Linux by default, as PsychPortAudio will grab a low-level ALSA device and block Pulseaudio during that time, whereas GStreamer then blocks on the blocked Pulseaudio server. May also happen on Windows with the WASAPI sound backend in exclusive mode.

**Comment by marcelfarres** [comment]
Thank you very much for the super-fast response. 
After reviewing again my original code (not the example one) I realize that I was using specialFlags1 = 2 but in the wrong position in the function call. After changing it everything runs smooth :) 

I edited the original code so it helps other people in the same situation.
