### ISSUE TITLE
KbQueue/KbEvent and ListenChar/GetChar interfering with one another

### ISSUE THREAD

**Issue by cdvignali** [Psychtoolbox-3/Psychtoolbox-3#582]
I am trying to test the timing of a script that I will eventually run within the scanner. I have created a macro that will present a "t", which is acting as a trigger for the next stimulus to flip, but every time a "t" is presented from the macro I get the error on line 315 of the GetChar.m function. Is there a way I can work around this so both GetChar and KbQueue can function independently of one another? This isn't a problem when running these scripts within a fMRI scanner, so must be related to testing this behaviorally (perhaps because there are two OS in use when at the scanner).

```
if ~KbQueueReserve(1,1,[])
      error('Keyboard queue for default keyboard device already in use by KbQueue/KbEvent functions et al. Use of ListenChar/GetChar etc. and keyboard queues is mutually exclusive!');
end
```

**Comment by kleinerm** [comment]
Depends on operating system and scripting environment. On Linux and macOS you select a specific plugged in "keyboard device" (= as whatever special "keyboard" your USB scanner triggerbox shows up -- see GetKeyboardIndices for how to select). You'd use KbQueueCreate/Start/Stop/etc.(devindex) with the proper devindex from GetKeyboardIndices() for the scanner. And GetChar for the default keyboard.

On Windows you can't select a specific keyboard device and GetChar() will reserve the keyboard queue for deviceIndex=0 for its own exclusive use.

Do you need GetChar? There's also KbEventAvail, KbEventGet, KbEventFlush which return similar info as CharAvail, GetChar, FlushEvents, but with precise timestamps, and the character code (like in GetChar) in the CookedKey field. This way you could replace GetChar with something that is more precise and provides the same or more detailed info and is compatible with other use of the same KbQueue.

What also works is ListenChar(-1) to just suppress typed characters from showing up in the Matlab window, and ListenChar(0) to go back to normal - wouldn't collect actual keystrokes for GetChar/CharAvail, but doesn't clash with keyboard queues.
