### ISSUE TITLE
Invalid MEX-file???

### ISSUE THREAD

**Issue by arutherford7** [Psychtoolbox-3/Psychtoolbox-3#584]
trying to run a task in MATLAB and have the 64 bit psychtoolbox installed for my 64 bit windows. Gstreamer for 64 bit is also installed... any idea why this might be occurring?

Invalid MEX-file 'C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64': The specified module could not be
found.

Error in ShowCursor (line 161)
Screen('ShowCursorHelper', screenid, type, mouseid);

Error in Tasktraining (line 341)
    ShowCursor

**Comment by dcnieho** [comment]
What matlab version are you using?

**Comment by kleinerm** [comment]
Did you follow the installation instructions to the point? GStreamer 1.16.0 MSVC version -- just click the download link on your website. Maybe the need to install the vcredist... MSVC runtime if it isn't already on your system. Psychtoolbox 3.0.16 in its current state -- if in doubt, run UpdatePsychtoolbox to be sure.

Current Screen() mex file for PTB 3.0.16 will not work with any older GStreamer version than 3.0.16 64-Bit and only with the msvc version, not with the mingw64 version.

This is more strict requirements than in the past, and GStreamer is not mandatory, but in exchange the serious movie playback/video capture/video recording/movie writing compatibility crash-bugs with Matlab seem to be fixed as far as my testing goes. This version has been tested with R2014a, R2014b, R2019a and is expected but not yet tested to likely still work with R2012a.
