### ISSUE TITLE
Buying a stimulus laptop for the lab. What is the most reliable hardware/OS?

### ISSUE THREAD

**Issue by dangom** [Psychtoolbox-3/Psychtoolbox-3#586]
Most researchers here in our lab use Psychtoolbox 3 for running their experiments. 
Given that we're looking to buy a new stimulus laptop, I wondered what the most reliable, timing-accurate and user friendly option hardware + OS would be.

We've been looking into system76, which purports to sell decent GNU/Linux compatible hardware. Otherwise what other laptops would you recommend? And should we just go for Neurodebian as an OS?

**Comment by iandol** [comment]
I think the major issue is to make sure if you go for a discrete GPU, it is an AMD not NVidia GPU. Hybrid graphics (discrete + integrated) is still apparently problematic, and so there is an argument to get whatever is the latest iGPU on an Intel CPU without a dGPU. System76 laptops look great.

I think you should be able to install Neurodebian into PopOS (system76). I prefer to maintain my own Github fork of PTB (I can keep up-to-date more easily), but Neurodebian does make things easier (1 command install, though slightly older version of PTB normally).

**Comment by kleinerm** [comment]
Yes, what Ian says. If you need the performance or feature set of a discrete gpu, prefer AMD over NVidia for best support and ease of use. If you don't need high performance or special features - depends on your paradigms - Intel onboard graphics is also a good choice wrt. quality and ease of use on Linux. If you have to use a NVidia card for some good reason, avoid hybrid graphics laptops (e.g. "NVidia Optimus") or be prepared for various limitations and extra pain in setting up and maintaining and much less support from us in case of trouble.

It is quite unfortunate that System76's doesn't offer any Laptops with AMD discrete gpu for high demands, only NVidia gpu's, but they do have good offerings with Intel gpu, and at least they seem to avoid Optimus for their NVidia offerings.

In the end it all depends on the type of paradigms you intend to run with these laptops if Intel onboard will do.

**Comment by dangom** [comment]
Hi all,

thanks for your comments. We did get a System 76 back in late 2019. it works OK but I noticed a couple of times that it does lag on very demanding visual stimuli.
So a question for the devs, could you share a link of any laptop computer you know will be able to run demanding visual stimuli reliably using Psychtoolbox?

The system requirements described under http://psychtoolbox.org/requirements.html suggest an AMD graphics card, but that's somewhat of a rare find nowadays, and goes against my intuition of having an NVIDIA card that could also be used for CUDA.

I am asking this again because we are looking to buy a second stimulus computer. Any help would be highly appreciated.

**Comment by iandol** [comment]
@dangom — what GPU does the System76 have? Most Macbooks have AMD GPUs but don't easily run Linux. My grant restrictions force me to buy only Dell or Lenovo workstation laptops (grrr!!!) and they invariably come with NVidia cards (as you noted CUDA dominates ML and advanced graphics workflows). I ended up with a Dell 5540 with a T1000 which sucks for PTB (well display appears smooth but sync tests fail after the first run). Possible solutions are eGPUs via thunderbolt, not sure how Linux/PTB would handle those? Or some small form factor PCs can hold cards up to 75W which would allow an AMD solution in something that was nominally portable?

**Comment by dangom** [comment]
System76 has an integrated GPU - Intel UHD Graphics.

This Lenovo looks like a good candidate - ships with Linux, runs an intel CPU and AMD discrete card: https://www.amazon.com/Lenovo-Thinkbook-Business-Ultrabook-1920x1080/dp/B084ZYVQQ8/ref=psdc_13896615011_t1_B084ZX9XGF
