### ISSUE TITLE
BUG: pip install -e does not work

### ISSUE THREAD

**Issue by larsoner** [Psychtoolbox-3/Psychtoolbox-3#588]
I'm not a Python packaging expert, but my sense is that doing `pip install -e .` should "just work" for most Python code bases nowadays. However, the organization of Psychtoolbox / PsychPython makes this not work, because ideally the code would reside in a folder named `psychtoolbox` (the package name) not `PsychPython`. Currently `pip install -e .` works, but when you try to import it fails because the egg link points to the PTB `git` root, which does not have a `psychtoolbox` directory beneath it (it has PsychPython, Psychtoolbox, otc.).

One way around this would be to take the files currently in `PsychPython` and nest them under `PsychPython/psychtoolbox/*`. Then `PsychPython` can act like the root in any other standard Python package, including having `PsychPython/setup.py` (rather than in the PTB root).

@peircej @kleinerm @hoechenberger thoughts?

**Comment by peircej** [comment]
I think @kleinerm was having difficulties getting the files to be found at one point. If you can find a way to do it and keep the setup.py file together with only-Python related code then I'm sure he'd appreciate a PR for that. No promises, but my guess is that he'd appreciate it!

**Comment by kleinerm** [comment]
Yes. I do remember various weird limitations about where setup.py wanted to have things, especially to be included DLL libraries under Windows iirc. Can't remember the details though.

If you can make it work as you propose, i don't have any objections to such a change.

**Comment by larsoner** [comment]
Done, changes in #590
