### ISSUE TITLE
Matlab PsychPortAudio - cant use sample rate other than default on audio devices

### ISSUE THREAD

**Issue by afgenovese** [Psychtoolbox-3/Psychtoolbox-3#596]
When I set the device to -1 and simultaneous, my default interface can playback any sample rate. 

However, when I separate playback from capturing, I am getting an error when trying to use a sample rate which is not the default (48k). This is odd because I am sure both devices should support 96kHz. 

PTB-ERROR: Desired audio parameters for device 6 unsupported by audio device: Invalid sample rate 
PTB-ERROR: Seems the requested audio sample rate 96000.000000 Hz is not supported by this combo of hardware and sound driver.
Error in function Open: 	Usage error
Failed to open PortAudio audio device due to unsupported combination of audio parameters.
Error using PsychPortAudio
Usage:

pahandle = PsychPortAudio('Open' [, deviceid][, mode][, reqlatencyclass][, freq][, channels][, buffersize][, suggestedLatency][,
selectchannels][, specialFlags=0]);

Error in TEST (line 87)
out_pahandle = PsychPortAudio('Open', 6, 1, 1, srate, 2);

**Comment by dcnieho** [comment]
Is it specific to this sample rate 96K? What if you request 44.1K? Asking because that shows if its any non-default or that specific one. Also, please ask your question again, with this additional information, if still actual, on our [new forum](https://psychtoolbox.discourse.group/)
