### ISSUE TITLE
Error using imread -- Help needed ASAP

### ISSUE THREAD

**Issue by mccoffigny** [Psychtoolbox-3/Psychtoolbox-3#600]
<img width="983" alt="Screen Shot 2019-11-02 at 6 37 17 PM" src="https://user-images.githubusercontent.com/52081017/68077760-cd72f000-fd9f-11e9-876a-efd287a059b4.png">

**Comment by dcnieho** [comment]
This is not a PsychToolbox issue, you are not in the right place here. Hint: read the error message, the file does not exist or is not found in the location matlab looks for it.
