### ISSUE TITLE
Psychtoolbox is not showing Chinese characters. Can anyone tell me how I can display Chinese characters?

### ISSUE THREAD

**Issue by daniyalrajput** [Psychtoolbox-3/Psychtoolbox-3#603]
Psychtoolbox is not showing Chinese characters. Can anyone tell me how I can display Chinese characters? I am using window 10.

**Comment by dcnieho** [comment]
It does, see DrawHighQualityUnicodeTextDemo

**Comment by denispelli** [comment]
try putting "double( )" around the text string when you pass it to Screen.


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University

+1-646-258-7524 | denis.pelli@nyu.edu

http://psych.nyu.edu/pelli/ | Skype: denispelli <#>
| http://denispelli.com
<http://www.facebook.com/denispelli>
<http://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli>

**Comment by daniyalrajput** [comment]
> try putting "double( )" around the text string when you pass it to Screen. [image: photo] *Denis Pelli* Professor of Psychology & Neural Science, New York University +1-646-258-7524 | denis.pelli@nyu.edu http://psych.nyu.edu/pelli/ | Skype: denispelli <#> | http://denispelli.com <http://www.facebook.com/denispelli> <http://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli>
> […](#)
> On Thu, Nov 7, 2019 at 2:18 AM daniyalrajput ***@***.***> wrote: Psychtoolbox does not showing Chinese characters. Can anyone tell me how I can display Chinese characters? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Psychtoolbox-2D3_Psychtoolbox-2D3_issues_603-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DADKWX643PCY6HUNI76FNTTLQSO6LTA5CNFSM4JKCP5U2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HXQUSNA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=bW5Hp78zkNEcwgR7YQ4UMV99SN3fvgstm_n-s4kBe-A&s=OJ79B8zf-Ksgph-QwSS7699qo_ssGTVJYGdvUBS090c&e=>, or unsubscribe <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADKWX63XVEKA32T4BPKECNLQSO6LTANCNFSM4JKCP5UQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=7X-NKAXavKeKD9gIvst_RX6MqmtP6wERm4LVB5ZkcI4&m=bW5Hp78zkNEcwgR7YQ4UMV99SN3fvgstm_n-s4kBe-A&s=lr_yUAdaqtqSV2HSz4dpC4O7amckKwG35YJIz5t2G6o&e=> .

Thank very much for your reply. I already tried double() but it is not working.

**Comment by dcnieho** [comment]
again, see the DrawHighQualityUnicodeTextDemo, run that, does it work? if so, read how its done there and do the same

**Comment by daniyalrajput** [comment]
> again, see the DrawHighQualityUnicodeTextDemo, run that, does it work? if so, read how its done there and do the same

Thank you for the reply. I am trying DrawHighQualityUnicodeTextDemo.

**Comment by daniyalrajput** [comment]
> again, see the DrawHighQualityUnicodeTextDemo, run that, does it work? if so, read how its done there and do the same

Respected Sir:
I tried DrawHighQualityUnicodeTextDemo to display chinese character, but I do not know how I can get unicodetext(mentioned below). Could you plase tell me how I can get the value of unicodetext for Chinese characters?

unicodetext = [26085, 26412, 35486, 12391, 12354, 12426, 12364, 12392, 12358, 12372, 12374, 12356,...,12414, 12375, 12383, 12290, 13, 10];

**Comment by dcnieho** [comment]
go to https://unicodelookup.com/, copy your text (as far as it fits)
into the field, which will tell you what the unicode code point is for
each character. You want the numbers in the decimal (Dec) field there.
Also, make sure you use a font that has the characters that you want to show.

**Comment by daniyalrajput** [comment]
> go to https://unicodelookup.com/, copy your text (as far as it fits) into the field, which will tell you what the unicode code point is for each character. You want the numbers in the decimal (Dec) field there. Also, make sure you use a font that has the characters that you want to show.
> […](#)
> On Mon, Nov 18, 2019 at 6:19 AM daniyalrajput ***@***.***> wrote: again, see the DrawHighQualityUnicodeTextDemo, run that, does it work? if so, read how its done there and do the same Respected Sir: I tried DrawHighQualityUnicodeTextDemo to display chinese character, but I do not know how I can get unicodetext(mentioned below). Could you plase tell me how I can get the value of unicodetext for Chinese characters? unicodetext = [26085, 26412, 35486, 12391, 12354, 12426, 12364, 12392, 12358, 12372, 12374, 12356,...,12414, 12375, 12383, 12290, 13, 10]; — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much,Diederick C. Niehorster, for your help. I have solved the problem. Now, my code can show Chinese characters.
