### ISSUE TITLE
PsychImaging Error Message

### ISSUE THREAD

**Issue by efkccc** [Psychtoolbox-3/Psychtoolbox-3#604]
Hello!
This error message keeps coming up showing an error in one of the lines in 'PsychImaging'. 
Tried to re-install Psychtoolbox and still showing the same message. 
(I was trying the demos in Psychtool tutorial).

<img width="1059" alt="Screenshot 2019-11-06 at 23 48 07" src="https://user-images.githubusercontent.com/57488005/68387848-2f907400-0157-11ea-97c9-2ae34f74dd2f.png">
Does anyone know what went wrong/should I do?

Thanks!

**Comment by kleinerm** [comment]
Without knowing anything about your hardware+OS+software setup, nobody can help you. Can't read minds.

**Comment by efkccc** [comment]
> Without knowing anything about your hardware+OS+software setup, nobody can help you. Can't read minds.
Didn't realise that---first-time poster here!
So I was using Matlab_R2019b and 3.0.16 beta Psychtoolbox on MacbookPro 2018(macOS Mojave)
Thanks for pointing this out!

**Comment by kleinerm** [comment]
Ah, one of Apples awful operating systems. Due to bugs in Mojave and later, maybe also earlier versions of macOS, R2019b currently doesn't work at all with PTB, R2019a is the last one that does. Stay tuned for future PTB betas to fix the broken mess for R2019b that Apples incompetent work has left us with.

**Comment by efkccc** [comment]
Okay good to know---both annoying and reassuring (I was a bit worried it's because I did something wrong)
Thanks a lot!

**Comment by kleinerm** [comment]
Fixed by PTB BETA update from 27th November 2019.

Fixed by #611
