### ISSUE TITLE
PTB Screen 'OpenWindow' issue on MacOS Mojave

### ISSUE THREAD

**Issue by smithsm11** [Psychtoolbox-3/Psychtoolbox-3#607]
I'm running Matlab 2019b, PTB 3.0.16 on a Mac running Mojave 10.14.6. (I know that there are issues with visual presentation/timing/etc. when running PTB on a Mac - I won't actually be running experiments on my Mac, but I'd really like to be able to test my code on it anyway.)

When I try to run any of the demos (e.g. ArcDemo, MouseTraceDemo), I get the following output/error message:

> PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.
> 
> INTERNAL PSYCHTOOLBOX ERROR
> 	error:                PsychError_InvalidWindowRecord
> 	general description:  An Invalid window record was referenced.
> 	module name:          Screen
> 	subfunction call:     WindowKind
> 	file name:            /Users/kleinerm/projects/OpenGLPsychtoolbox/Psychtoolbox-3/PsychSourceGL/Source/Common/Screen/WindowHelpers.c
> 	function name:        PsychCheckIfWindowRecordIsValid
> 	line number:          61
> Error using Screen
> See error message printed above.
> 
> Error in sca (line 22)
>     if Screen('WindowKind', win) == 1
> 
> Error in ArcDemo (line 103)
>     `sca;`

Other notes:
- I have manually skipped the sync test with `Screen('Preference', 'SkipSyncTests', skipSync);`
- I get the same output regardless of whether or not I have a second display - in fact, PTB doesn't recognize the second display (it returns 0 as output for the Screen('Screens') command) even when I have it plugged in via VGA.
- I've also tried some of my own code - which worked perfectly well a couple of months ago on my Mac running 10.11 (maybe it was 10.13?) and Matlab 2014b. I get a similar error with this code when I try to open a window with the `Screen('OpenWindow')` command, except I also get a weird MEX error: 

> Unexpected unknown exception from MEX file..

> Error in e6test (line 261)
>     [onScreen, screenRect] = Screen('OpenWindow',whichScreen); 

PTB tries to open the window (my screen goes black, but nothing happens after that). And then, after I force close out (with `sca`), I get this message/error:

> INTERNAL PSYCHTOOLBOX ERROR
> 	error:                PsychError_InvalidWindowRecord
> 	general description:  An Invalid window record was referenced.
> 	module name:          Screen
> 	subfunction call:     WindowKind
> 	file name:            /Users/kleinerm/projects/OpenGLPsychtoolbox/Psychtoolbox-3/PsychSourceGL/Source/Common/Screen/WindowHelpers.c
> 	function name:        PsychCheckIfWindowRecordIsValid
> 	line number:          61

Or this one: 

> PTB-CRITICAL: Maximum recursion level 5 for recursive calls into module 'Screen' exceeded!
> PTB-CRITICAL: Aborting call sequence. Check code for recursion bugs!
> INTERNAL PSYCHTOOLBOX ERROR
> 	error:                PsychError_internal
> 	general description:  Unspecified error, probably a Psychtoolbox bug
> 	specific description: Module call recursion limit exceeded
> 	module name:          Screen
> 	subfunction call:     OpenWindow
> 	file name:            /Users/kleinerm/projects/OpenGLPsychtoolbox/Psychtoolbox-3/PsychSourceGL/Source/Common/Base/PsychScriptingGlueMatlab.c
> 	function name:        mexFunction
> 	line number:          254

Any and all help to resolve this issue (and enable me to open the window so that I can test my code) would be much appreciated.

**Comment by dcnieho** [comment]
See #604

**Comment by smithsm11** [comment]
Thanks a bunch! I'll try Matlab 2019a instead.
