### ISSUE TITLE
PTB Forum migration

### ISSUE THREAD

**Issue by czuba** [Psychtoolbox-3/Psychtoolbox-3#609]
Ran into a PTB error the other day that I'd normally head to the forums to solve, but they are no more.
I was happy to quickly find [a solution](https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/604) in the github issues in the interim, but reminded me of the many times I've circled back to old forum posts to solve problems (...sometimes _my own_ previously posted & forgotten solutions/workarounds).
### Has there been any progress on moving the forum to groups.io?
I relayed Diederick's groups.io suggestion to my [HOA] other yahoo group. They didn't migrate existing posts, but the overall layout & features seem decent (messages, threads, tag/labeling, wiki, etc)

If we hope/are able to migrate the data from Yahoo, I'd guess the sooner the better given Yahoo's blase shuttering of the old forum.

**Comment by kleinerm** [comment]
We have this now on Discourse, after some group decisions. I've pinged Allen Ingling a week ago if we can announce it and set proper links, but so far no response. So far no response. I think i'll just go ahead and announce the new forum location.

https://psychtoolbox.discourse.group

**Comment by kleinerm** [comment]
Ok, we'll give it until next week, as Allen Ingling tries to migrate the old forum into the new one over thanksgiving weekend. But the problem you tried to solve has been fixed by the latest PTB BETA.
