### ISSUE TITLE
Error while executing a compiled stand-alone Psych3 app

### ISSUE THREAD

**Issue by SebastianMoguilner** [Psychtoolbox-3/Psychtoolbox-3#613]
Dear all,

First of all, is it possible to do it at all?
If so, here is the issue:

After successfully compiling my app using the "application compiler" from MATLAB R2018a and installing it I get an error pointing to the following line

init_psych();

And it's related to a missing directory.

Is there an additional step that I'm missing in order to produce a shareable stand-alone app without having Matlab installed? 

Regards

**Comment by dcnieho** [comment]
init_psych() is not a function from psychtoolbox. The matlab compiler is
probably failing to identify all functions it should include. manually add
missing functions or directories or whatever to the compiler and then it
may work. So far this does not seem like a PTB specific problem, so google
for general matlab compiler support
