### ISSUE TITLE
Error while installing psychtoolbox

### ISSUE THREAD

**Issue by AgneseU** [Psychtoolbox-3/Psychtoolbox-3#617]
Hi all,

I am trying to install psychtoolbox on Matlab R2019b, but it keeps giving me the following error message:

Error using DownloadPsychtoolbox (line 818)
Download failed.

Can anyone offer a helping hand with this issue?

**Comment by dcnieho** [comment]
What is the rest of the output you get (above this error)?

**Comment by AgneseU** [comment]
This is the only output I’m getting. There is nothing above it.

**Comment by dcnieho** [comment]
please make sure you're using the newest version of this script, i don't
have that error on that line. Also, the code prints plenty of information
around where this error does occur, so that is strange you don't see it.
Perhaps the new version of the script is more helpful

**Comment by AgneseU** [comment]
Hi Diederick,
I'm attaching the whole message that is printing before the error message.
Can you recognise the problem?
I am using the latest version, so that shouldn't be the issue here.

>> cd C:\toolbox
DownloadPsychtoolbox('C:\toolbox')
DownloadPsychtoolbox('C:\toolbox','beta','')
Requested flavor is: beta
Requested location for the Psychtoolbox folder is inside: C:\toolbox

Good. Your privileges suffice for the requested installation into folder
C:\toolbox.

I will now download the latest Psychtoolbox for Windows.
Requested flavor is: beta
Target folder for installation: C:\toolbox
The following CHECKOUT command asks the Subversion client to
download the Psychtoolbox:
svn checkout
https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox/
"C:\toolbox\Psychtoolbox"
Downloading. It's nearly 100 MB, which can take many minutes.
Alas there may be no output to this window to indicate progress until the
download is complete.
Please be patient ...
If you see some message asking something like "accept certificate
(p)ermanently, (t)emporarily? etc."
then please press the p key on your keyboard, possibly followed by pressing
the ENTER key.

'svn' is not recognized as an internal or external command,
operable program or batch file.
Sorry, the download command "CHECKOUT" failed with error code 1:
'svn' is not recognized as an internal or external command,
operable program or batch file.

The download failure might also be due to temporary network or server
problems. You may want to try again in a
few minutes. It could also be that the subversion client was not (properly)
installed. On Microsoft
Windows you will need to exit and restart Matlab or Octave after
installation of the Subversion client. If that
does not help, you will need to reboot your machine before proceeding.
Another reason for download failure could be if an old working copy - a
Psychtoolbox folder - still exists.
In that case, it may help to manually delete that folder. Or maybe you do
not have write permissions for the target folder?

Error using DownloadPsychtoolbox (line 818)
Download failed.

**Comment by dcnieho** [comment]
This is key:
'svn' is not recognized as an internal or external command,
operable program or batch file.

So install svn (e.g. sliksvn)

**Comment by AgneseU** [comment]
Thank you ever so much. It works now.
There is, however, another issue. The screen is repeatedly freezing when I
try to run my tasks. Is that normal?

**Comment by dcnieho** [comment]
The first time it'll be stuck for up to minutes, just let it continue

**Comment by AgneseU** [comment]
Okay, great. Thanks again for your help.
