### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by manoharvhr** [Psychtoolbox-3/Psychtoolbox-3#618]
Whenever I start my MATLAB, the scripts execute. How do I stop that? I no longer want the toolbox

**Comment by dcnieho** [comment]
Just delete it

**Comment by manoharvhr** [comment]
Once you delete it, make sure you remove the associated path defines in
C:\Program Files\MATLAB\R2018a\toolbox\local\pathdef.m

Otherwise you get warnings each time you open MATLAB.
