### ISSUE TITLE
Multiple screens not recognized

### ISSUE THREAD

**Issue by gekaufman** [Psychtoolbox-3/Psychtoolbox-3#625]
New to Psychtoolbox, trying to use it to run a projector with Matlab.

I checked to see what screens I have available (with the projector on and detected as a second screen in Windows settings) using 
>>[screens]=Screen('Screens')

The response I get is
screens =

     0

Any ideas why Psychtoolbox isn't recognizing the projector screen even though Windows is?

**Comment by dcnieho** [comment]
have you cleared screen (or restarted matlab) after switching on the
projector? i think it only redetects screens the first time you call screen

**Comment by gekaufman** [comment]
That works, thank you!! 

Looks like I have to turn on the projector before opening Matlab.
