### ISSUE TITLE
Matlab r2019b and 'Screen'

### ISSUE THREAD

**Issue by scdakin** [Psychtoolbox-3/Psychtoolbox-3#629]
Hi
I upgraded Matlab (with an operational PTB) from r2019a to r2019b and now Screen doesn't work.
Error is:
'Invalid MEX-file 'C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64': The specified module could not be found.

I reinstalled PTB, reinstalled GStreamer, reinstalled runtime library, no go.

(I see some other posters have struggled with getting PTB going after a r2019b upgrade too. None of their fixes - reordering the path, or just waiting - have worked for me.)

**Comment by scdakin** [comment]
Installing Matlab r2019a and reinstalling PTB doesn't fix things.
The r2019b installation seems to introduce compatibility issues...

**Comment by kleinerm** [comment]
Proper MSVC GStreamer installed? That's what the other people did wrong, despite clear statements that one must use the MSVC versions, not the MinGW versions.

**Comment by scdakin** [comment]
Yep that was it, all fixed once I switched to the MSVC version of GStreamer.
Thanks Mario.
