### ISSUE TITLE
Screen('Screens',physicalDisplays=1) does not work as expected

### ISSUE THREAD

**Issue by denispelli** [Psychtoolbox-3/Psychtoolbox-3#630]
Yesterday I discovered the "physicalDisplays" option in Screen('screens',1), but I was disappointed to find that it always gives an array of the same size as Screen('screens'). When I have the LG external monitor connected and I enable mirroring, Screen('screens') and Screen('screens',1) both return one integer (0 and 1, respectively). When I disable mirroring, both calls return two integers ([0 1] and [1 2] respectively). Thus Screen('screens',1) seems useless.

Is this a bug?

**Comment by denispelli** [comment]
P.s. Is there a way to discover that the user has enabled mirroring? We have been warned that it severely worsens timing, so I'd like my programs to detect it, since my students won't necessarily notice. I thought that I could detect mirroring by comparing the lengths of arrays returned by Screen('screens') and Screen('screens',1), but, as noted above, I find they are equal, regardless of whether I enable mirroring.

**Comment by kleinerm** [comment]
I'm disappointed in Apples poor software quality as well, almost each time i have to use macOS, so i'm with you on this. 'physicalDisplays' = 1 returns the list provided via CGGetOnlineDisplayList(), which is described in Apples docs as "Provides a list of displays that are online (active, mirrored, or sleeping)." and "If the framebuffer hardware is connected, a display is considered connected or online. When hardware mirroring is used, a display can be online but not active or drawable. Programs that manipulate display settings (such as gamma tables) need access to all displays, including hardware mirrors, which are not drawable."

The normal Screen list comes from CGGetActiveDisplayList() "Provides a list of displays that are active (or drawable)." with this note: "The first entry in the list of active displays is the main display. In case of mirroring, the first entry is the largest drawable display or, if all are the same size, the display with the greatest pixel depth. Note that when hardware mirroring is being used between displays, only the primary display is active and appears in the list. When software mirroring is being used, all the mirrored displays are active and appear in the list."

I guess macOS doesn't use hardware mirroring then and the lists are the same.

There isn't a programmatic way to detect if a display is mirrored via some PTB api, but PTB prints a warning iff mirroring is enabled on a display, so those with the gift or reading should be able to read the warning - or for that matter it should be quite obvious if two monitors are connected and showing the same picture? Probably it will also cause other warnings like sync failures, as consequence of timing problems.
