### ISSUE TITLE
PTB incorrectly triggered DPI scaling on windows 10 laptop when duplicate to external monitor

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#633]
Background:
For some modern windows 10 laptops with a higher resolution, for example, 1920x1080 @ 14 inches,  windows 10 will use a higher DPI scaling by default, for example, at 150% in display settings. 

If an external monitor is attached in extend mode, the DPI of the external monitor might be different, for example, a 1920x1080 @ 24 inches monitor will have a default DPI scaling factor 100%.
This is a very useful feature of windows 10. If we use PTB in such a setting, the screen 1 and 2 works normally (perhaps).

If we change to duplicate mode, the DPI scaling factor of the internal monitor is used by default, thus, the external monitor will also have DPI scaling at 150%. That is OK for some scenario, and PTB can work with such settings (although might have sync problems), but when I change the DPI scaling to 100%, this issue happens.

How to reproduce:
A laptop with default DPI scaling larger than 100%, attached with a monitor with default DPI scaling at 100%, change project to duplicate mode, and then change DPI scaling to 100%.

Run VBLSyncTest for example, and pay attention to the taskbar, it shows that PTB window triggered DPI scaling, the taskbar enlarged before PTB window covered it. And after PTB window is closed, the DPI scaling will restore to the previous setting.

And it seems that even for the previous scenario where DPI scaling is 150% on the duplicate mode, there also exist some modifications on display setting (which might cause the monitor show some OSD information), which is not happening on a single display setting or extend mode.

**Comment by dcnieho** [comment]
Do you start matlab after you engaged duplicate mode and set scaling to
100%, or before? If before, please test with starting after all the other
steps

**Comment by suxpert** [comment]
Actually, I did all the tests after reboot the entire system, when I change any of the monitor settings, to confirm that this is an issue before I post here, and my steps to reproduce are truly reproducible, at least for the laptops in our lab.

**Comment by kleinerm** [comment]
Well, there's nothing we could do. This is a Windows limitation, not a PTB bug or such. In general i recommend against using mirror/clone/duplicate modes because they will cause timing/sync problems and degraded performance. Sorry. Maybe you can try to go into the Matlab properties tab (right click on Matlab icon), and in the compatibility settings tab iirc, use the buttons to set custom DPI HiDPI settings -- disable scaling completely for Matlab. Maybe that helps, maybe not.

**Comment by suxpert** [comment]
In windows 10 newer than 1709 (or so), the application-wise compatibility setting is changed, and there is no option to 'disable scaling completely', just three options:

- Application
- System
- System (enhanced)

And none of the four choices affect the behaviour of PTB I mentioned above (but affect the behaviour of MATLAB. That is why I thought it should be an issue of PTB).
