### ISSUE TITLE
ERROR Using Screen

### ISSUE THREAD

**Issue by skyaakash** [Psychtoolbox-3/Psychtoolbox-3#634]
Hello everyone,
         I have been getting 'Error Using Screen' message while trying to use screen function in PsychToolbox.
         I have been using Screen function to make texture with an image and display continuously on the screen for about 30 minutes. While the function runs well for the first 7 or 8 minutes without any error, the function crashes and throws 'Error using Screen' message on the MATLAB console. Is this an internal bug within the 'Screen' function? Is there any timeout as such within the 'Screen' function which is causing it?

       Following is the exact error copied from my MATLAB console:
Error using Screen
Usage:

textureIndex=Screen('MakeTexture', WindowIndex, imageMatrix [,
optimizeForDrawAngle=0] [, specialFlags=0] [, floatprecision=0] [,
textureOrientation=0] [, textureShader=0]);

Error in DARK_ADAPTATION/LandoltCFunction (line 583)
                        imageTexture = Screen('MakeTexture',
                        window, theImage);

Many thanks for your help.

**Comment by dcnieho** [comment]
Is there any more text above it?
First guess: you are out of texture memory. Do you Screen('Close') textures
you no longer need?

**Comment by skyaakash** [comment]
Hi dcnieho,
                    Thanks very much for your comment. It was running out of texture memory. After adding Screen('Close') line, I didn't see such a problem. 
                    Much appreciated.
