### ISSUE TITLE
Ubuntu 19.10 Wrong default KbQueue keyboard is detected.

### ISSUE THREAD

**Issue by marcelfarres** [Psychtoolbox-3/Psychtoolbox-3#635]
I upgrade from 18.XX (no problem to detect input devices) to 19.10 and after that I was not able to get any keyboard input using the routines KbQueueCreate, KbQueueStart, KbQueueStop, KbQueueCheck, KbQueueWait, KbQueueFlush and KbQueueRelease

Running 'Devices' I get empty struct array
`devices=PsychHID(‘Devices’ [, deviceClass])`
And running 'NumDevices' I get zero
`numberOfDevices=PsychHID(‘NumDevices’)`

Any idea how to debug it further or fix it? 

I am running: 
> Distributor ID:	Ubuntu
> Description:	Ubuntu 19.10
> Release:	19.10
> Codename:	eoan

**Comment by kleinerm** [comment]
Hmm, i did test 19.10 on a whole bunch of machines last year and none showed any such problems.
Are you using the latest PTB? Octave or Matlab etc.?

**Comment by marcelfarres** [comment]
I tested in 2 different machines, PTB last version both. One machine clean install 19, the other upgrade from 18 and they exhibit the same problem. 

They are running Matlab 2019a and 2019b.

I tested my own experiments and the demo and either of them is able to get keyboard responses...

What other info do you need? I would like to avoid rolling back to 18 and solve the bug

**Comment by kleinerm** [comment]
All works here, tested on many machines with fresh Ubuntu 19.10 installs last year. But you'd call GetKeyboardIndices, not the PsychHID('Devices') like you do? Does that make a difference? Does KbCheck etc. work if you don't specify any deviceIndex?

**Comment by marcelfarres** [comment]
I got it working again. Thanks for the help. 

Calling `[keyIsDown, secs, keyCode, deltaSecs] = KbCheck();` detect keyboard events without any problem. 

Using `KbQueueCreate(); KbQueueStart();[pressed, firstPress, firstRelease, lastPress, lastRelease] = KbQueueCheck();` without specific deviceIndex did not capture/report any key press. 

Calling the same function using the `deviceIndex` reported by `GetKeyboardIndices` was able to capture the keyboard events. 

I am using a Bluetooth keyboard. Is it normal that default does not work for `KbQueueCreate(); KbQueueStart(); KbQueueCheck();` but works for `KbCheck()`?

I want to understand because I need to implement an experiment that should be able to run in multiple computers and it will be compile, so I had to expose `deviceIndex` to the configuration file if necessary.

**Comment by kleinerm** [comment]
Not specifying a deviceIndex means to select the default keyboard, according to an **operating system specific** method.

On Linux:

KbCheck will use a function that leaves the choice of default keyboard to what the OS (X-Server) finds appropriate, the so called core keyboard. This likely will collect input from *any* connected keyboard, so also from your Bluetooth keyboard.

KbQueue's can only query exactly one specific keyboard, and there isn't any thing like a default keyboard. So Psychtoolbox uses its own heuristic to guess the right default keyboard. The fact that KbQueueCreate() without specific deviceIndex does not work, suggests that our heuristic selects the wrong keyboard.

So use GetKeyboardIndices, and select on the names reported by that command, to make sure you get the index of the keyboard you actually want.

If you give me the full output of [a,b,c] = GetKeyboardIndices(), and of the terminal command "xinput", i may be able to adapt our heuristic for a future PTB release.

**Comment by marcelfarres** [comment]
Thanks for the precise information, now I understand why it did not work before. 
I update my code forcing specify the device name where responses will be registered.   

Here is the info from the specific device. Please don't hesitate if you need any other information. Thanks!

**GetKeyboardIndices** 
keyboardIndices : `[3 4 5 6 7 8 10 11 12]`
productNames: 
`'Virtual core XTEST keyboard'	'Power Button'	'Video Bus'	'Power Button'	'Sleep Button'	'M720 Triathlon Keyboard'	'Keyboard K380 Keyboard'	'Keyboard K380 Consumer Control'	'Keyboard K380 System Control'`
allInfos:  
```|---------- product : 'Virtual core XTEST keyboard'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 3
   |----------- inputs : 248
   |------ interfaceID : 5
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
   |    
   |---------- product : 'Power Button'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 4
   |----------- inputs : 248
   |------ interfaceID : 6
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
   |    
   |---------- product : 'Video Bus'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 5
   |----------- inputs : 248
   |------ interfaceID : 7
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
   |    
   |---------- product : 'Power Button'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 6
   |----------- inputs : 248
   |------ interfaceID : 8
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
   |    
   |---------- product : 'Sleep Button'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 7
   |----------- inputs : 248
   |------ interfaceID : 9
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
   |    
   |---------- product : 'M720 Triathlon Keyboard'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 8
   |----------- inputs : 248
   |------ interfaceID : 10
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
   |    
   |---------- product : 'Keyboard K380 Keyboard'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 10
   |----------- inputs : 248
   |------ interfaceID : 12
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
   |    
   |---------- product : 'Keyboard K380 Consumer Control'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 11
   |----------- inputs : 248
   |------ interfaceID : 13
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
   |    
   |---------- product : 'Keyboard K380 System Control'
   |-------- transport : 'enabled'
   |-------- usageName : 'slave keyboard'
   |----- manufacturer : [ ]
   |-------- productID : [ ]
   |----- serialNumber : [ ]
   |--------- vendorID : [ ]
   |---------- version : [ ]
   |------------- axes : 0
   |---------- buttons : 248
   |------ collections : 0
   |------------ dials : 0
   |--------- features : 1
   |------------- hats : 0
   |------------ index : 12
   |----------- inputs : 248
   |------ interfaceID : 14
   |------- locationID : 3
   |--- maxTouchpoints : -1
   |---------- outputs : 0
   |---------- sliders : 0
   |---- totalElements : 248
   |-- touchDeviceType : -1
   |--- usagePageValue : 1
   |------- usageValue : 6
   |----------- wheels : 0
```

**xinput**:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ M720 Triathlon Mouse                    	id=11	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]
    ↳ M720 Triathlon Keyboard                 	id=10	[slave  keyboard (3)]
    ↳ Keyboard K380 Keyboard                  	id=12	[slave  keyboard (3)]
    ↳ Keyboard K380 Consumer Control          	id=13	[slave  keyboard (3)]
    ↳ Keyboard K380 System Control            	id=14	[slave  keyboard (3)]
```

**Comment by kleinerm** [comment]
In this case, the heuristic would have selected the "M720 Triathlon Keyboard" keyboard as default keyboard for KbQueueCreate(), because it is the first real, physical keyboard in the list. With that unplugged, it would have the K380 Keyboard - which i assume is your Bluetooth keyboard?

A PsychHID('Devices', -1) will btw. tell you which deviceIndex it considers the default keyboard.

So it basically worked as designed, just not as expected by you :)

**Comment by marcelfarres** [comment]
M720 is a Bluetooth mouse, not a keyboard. And yep, K380 is the Bluetooth Keyboard I expected to get the responses. 

Thanks again for the information, happy it was just me missing information about the behaviour and not a bug :)

**Comment by kleinerm** [comment]
Actually, could you try the attached zip file with a PsychHID.mexa64 file as replacement for the one in Psychtoolbox/PsychBasic ? This should fix default keyboard selection to ignore the M720.

[PsychHID.mexa64.zip](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/4069089/PsychHID.mexa64.zip)

**Comment by marcelfarres** [comment]
I think that the reason it shows as both is that the mouse has extra buttons (4 extra). 

I don't know if you can add to the ignore list all the multi-button Logitech mouses.

- MX MASTER 3

- MX ERGO

- M585

- MX ANYWHERE 2S

- M500

- M720 

- M510

- M705

- TRIATHLON

Thanks, override the file but it did not solve the problem for default selection.

**Comment by marcelfarres** [comment]
Now is selecting 4, when the correct output is 11 
The same keyboard shows up as 3 separate slave keyboards

- 'Keyboard K380 Consumer Control' -->keyboardIndices =4
- 'Keyboard K380 System Control'-->keyboardIndices=8
- 'Keyboard K380 Keyboard'-->keyboardIndices=11

If it is too specific maybe it is not worth implementing.

**Comment by kleinerm** [comment]
Hmm. The order of devices changed, apparently the 'Keyboard K380 Keyboard' doesn't always come first. Annoying but solvable. But not now. I'll see if i can do something about it for a future beta update one of the next days. I'll leave this issue open as a remainder to myself. Thanks.

**Comment by kleinerm** [comment]
I reworked it and rebuilt PsychHID mex files are in my kleinerm master branch for testing.
