### ISSUE TITLE
Screen OpenWindow failed, falsely claiming no PsychtoolboxKernelDriver

### ISSUE THREAD

**Issue by denispelli** [Psychtoolbox-3/Psychtoolbox-3#636]
Hi. Not sure if this is a bug, or my ignorance of what to expect. I thought the PsychtoolboxKernelDriver was important for good timing, but optional. I just encountered a fatal error, preventing Screen and PsychImaging from opening a window, because of claimed absence of the PsychtoolboxKernelDriver. See message below. Is this considered normal behavior?
In fact the PsychtoolboxKernelDriver is present, see output from IdentifyComputer below.

Doing "clear all" and running it again gives the same result. GratingDemo runs fine. My program gives the same error message whether I call Screen or PsychImaging to OpenWIndow. I've been using my program for many years, so I'm surprised and confused. I've never seen this error message before. Any advice on tracking this down?
Best
Denis
**CALLING: SCREEN** 
PTB-INFO: Installation of the PsychtoolboxKernelDriver is strongly recommended if you care about precise visual
PTB-INFO: onset timestamping or timing. See 'help PsychtoolboxKernelDriver' for installation instructions.
Error using Screen
See error message printed above.

Error in OpenWindow (line 30)
    [window,r]=Screen('OpenWindow',o.screen,white,screenBufferRect);

Error in CriticalSpacing (line 1002)
        window=OpenWindow(oo(1));

Error in runWordLengthEffect_Ziyi (line 114)
oo=CriticalSpacing(oo);

**CALLING PSYCHIMAGING:**
PTB-INFO: Installation of the PsychtoolboxKernelDriver is strongly recommended if you care about precise visual
PTB-INFO: onset timestamping or timing. See 'help PsychtoolboxKernelDriver' for installation instructions.
Error using Screen
See error message printed above.

Error in PsychImaging (line 2210)
            [win, winRect] = Screen('OpenWindow', screenid, clearcolor, winRect, pixelSize, numbuffers, stereomode, multiSample, imagingMode, specialFlags, clientRect,
            fbOverrideRect, vrrParams);

Error in OpenWindow (line 23)
        [window,r]=PsychImaging('OpenWindow',o.screen,white);

Error in CriticalSpacing (line 1002)
        window=OpenWindow(oo(1));

Error in runWordLengthEffect_Ziyi (line 114)
oo=CriticalSpacing(oo);
 

*** From IdentifyComputer **

          model: 'MacBookPro14,3'
            modelDescription: 'MacBook Pro (15-inch, 2017)'
                manufacturer: 'Apple Inc.'
                psychtoolbox: 'Psychtoolbox 3.0.16'
                      matlab: 'MATLAB 9.6 (R2019a)'
                      system: 'macOS 10.14.6'
                   screenMex: 'Screen.mexmaci64 Dec 16 2019'
                     screens: 0
                      screen: {[0]}
                        size: {[3360 2100]}
                  nativeSize: {[3360 2100]}
                          mm: {[330 206]}
              openGLRenderer: {'AMD Radeon Pro 560 OpenGL Engine'}
                openGLVendor: {'ATI Technologies Inc.'}
               openGLVersion: {'2.1 ATI-2.11.21'}
    psychtoolboxKernelDriver: 'PsychtoolboxKernelDriver 1.1'
              drawTextPlugin: 1
              psychPortAudio: 1
                     summary: 'MacBookPro14,3-macOS-10.14.6-PTB-3.0.16'`

**Comment by denispelli** [comment]
NEVER MIND. The problem disappeared after I rebooted my computer. I'm still surprised that lacking the PsychtoolboxKernelDriver is considered a fatal error, but since I can no longer replicate this error message, the issue is now moot.
Denis

**Comment by kleinerm** [comment]
It's not considered a fatal error at all, just a bad idea triggering that reminder. I can only assume something else was screwed up badly in the OS, which got fixed by the reboot.
