### ISSUE TITLE
MacBookPro 2019 16 inch: macOS Catalina Screen('Openwindow') fails.

### ISSUE THREAD

**Issue by solenef** [Psychtoolbox-3/Psychtoolbox-3#644]
Hello,

I meet exactly the same message as the one you described in your code : 

PTB-ERROR [Low-Level setup of window failed]:The specified gpu + display + gfx-driver combo may not support some requested feature.

when I try to initialize the screen on a macOS Catalina.

Here is the code to initialize : 

`function [w, r] = initializeScreen

screenNumber = 0; % 0 = main display

%PsychDebugWindowConfiguration(0, 0.5)
[w,r] = Screen('OpenWindow',screenNumber, 127); % open the window

% Set fonts
%Screen('TextFont',Window,'Times');
Screen('TextSize',w,48);
Screen('FillRect', w, 0);  % 0 = black background

HideCursor; % Remember to type ShowCursor later
`

and here are the error messages : 

`PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.

PTB-INFO: This is Psychtoolbox-3 for Apple OS X, under Matlab 64-Bit (Version 3.0.16 - Build date: Dec 16 2019).
PTB-INFO: OS support status: OSX version 10.15 is not officially supported or tested at all for this release.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-ERROR[CGLSetFullScreenOnDisplay failed: invalid drawable]. Main Screen() context

PTB-ERROR[Low-Level setup of window failed]:The specified gpu + display + gfx-driver combo may not support some requested feature.

Error using Screen
See error message printed above.

Error in initializeScreen (line 6)
[w,r] = Screen('OpenWindow',screenNumber, 127); % open the window

Error in FoodHealth (line 24)`

What do you suggest ?

Thanks a lot

**Comment by kleinerm** [comment]
Catalina is not really supported, as it is known to be especially buggy. What i really recommend is upgrading to Linux if possible.

UpdatePsychtoolbox.
What macOS version? Matlab version? What machine? What graphics card, display setup and display type, what resolution etc.? Does rebooting make a difference?

**Comment by solenef** [comment]
Thanks a lot for your answer.
Here are the details

MacOs Catalina 10.15.2
Matlab 2018b
Macbook Pro (16 inches, 3072 x 1920, 2019)
Retina Screen
Processor 2,6 Ghz Intel Core i7 6
Memory 16 Go 2667 MHz DDR4
Graphics AMD Radeon Pro 5300M 4 Go - Intel UHD Graphics 630 1536 Mo
Resolution 1792 x 1120
Psychtoolbox 3

Thanks in advance.
Best,

Solène

**Comment by kleinerm** [comment]
Oh hell, it's a MBP 16 inch 2019 with the new AMD Navi graphics. This is not supported at all by our PsychtoolboxKernelDriver, which means all high precision visual timing and most of PTB's diagnostics and workarounds for operating system bugs are dead. This makes the machine very untrustworthy for precise timing. You are essentially on your own here.

The error message you got is not something i've ever seen on any graphics card on macOS, and it shouldn't happen. The best you can try is upgrading to macOS 10.15.3 and hope that the problem goes away. Or try different video resolutions in the unlikely hope that that does something.

Do you need any timing precision for visual stimulation?

**Comment by solenef** [comment]
Thanks a lot for your explanations, it is very helpful. We are going to
install a virtual machine with linux then. I will also try upgrading, and
different video resolutions.

I think it is ok for the timing for now, I will let you know if I need some
help.

Thanks again and have a great day,

Solèn

**Comment by kleinerm** [comment]
A virtual machine will almost certainly not work, you need to run Linux on the actual machine for benefits. Unfortunately that is will likely be difficult as well, given how incompatible the 2019 models are so far with Linux. I have a 2017 model working ok'ish for my needs, after a full day of work. Current Apple Macs might be the most Linux hostile machines - and generally the least suitable machines for neuroscience. So Linux is unlikely to be an option for you atm.

Try upgrading Catalina to 10.15.3 first. Then try if switching to a different resolution helps. It could be that the specific bug you observe is specific to the new MBP 16 inch 2019.

If it doesn't work and if you don't care about precise/trustworthy visual timing/timestamping at all, you can try to add Screen('preference','Conservevram', 8192); to use the NO timing precision fallback path and see if that gives you at least a picture, albeit with wrong timing.

Or you try a Windows-10 installation. It likely won't be good, but it probably can't be worse than using macOS.

**Comment by kleinerm** [comment]
For what it's worth, a similar machine performed a bit better - but still unusable wrt. visual stimulation timing/timestamping - with macOS 11.5. See here:

https://psychtoolbox.discourse.group/t/trouble-running-pst-on-my-macbook-pro/3939
