### ISSUE TITLE
Beamposition synch problems with Nvidia gpu and Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by armengol** [Psychtoolbox-3/Psychtoolbox-3#645]
Hello, 
I used to use PTB-3 with MS Windows but now I am in need of high timing precision, and as I read in the PTB documentation, Linux is the best option for that, so I'm transitioning to Ubuntu 18.04 LTS.
Matlab version R2019b and using Nvidia GeForce GTX 1070 Ti with proprietary driver. I installed PTB-3 via Neuro Debian. I successfully ran PsychLinuxConfiguration().
However, the following WARNINGS and errors appear when I run PTB code (such as BeampositionTest.m).

```
PTB-INFO: This is Psychtoolbox-3 for GNU/Linux X11, under Matlab 64-Bit (Version 3.0.15 - Build date: Jul 17 2019).
PTB-INFO: Support status on this operating system release: Linux 5.3.0-28-generic Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: NVIDIA Corporation - GP104 [GeForce GTX 1070 Ti] GPU found. Trying to establish low-level access...
PTB-INFO: Connected to NVidia GP104 [GeForce GTX 1070 Ti] GPU of NV-130 family with 4 display heads.
PTB-WARNING: Hang in beamposition query detected! Seems my mapping of screen numbers to GPU's and display outputs is wrong?
PTB-WARNING: In a single GPU system you can resolve this by plugging in your monitors in a different order, changing the
PTB-WARNING: display arrangement in the control panel, or using the Screen('Preference', 'ScreenToHead', ...);
PTB-WARNING: command at the top of your scripts to set the mapping manually. See 'help DisplayOutputMappings' for more info.
PTB-WARNING: 
PTB-WARNING: I am not yet able to handle multi-GPU systems reliably at all. If you have such a system it may work if
PTB-WARNING: you plug your monitor(s) into one of the other GPU's output connectors, trying different combinations.
PTB-WARNING: Or you simply live without high precision stimulus onset timestamping for now. Or you use the free and open-source
PTB-WARNING: graphics drivers (intel, radeon, or nouveau) instead of the proprietary Catalyst or NVidia binary drivers.
PTB-WARNING: I've disabled high precision timestamping for this screen for the remainder of the session.

WARNING: Measured a negative beam position value after VBL onset!?! Broken display driver!!

PTB-WARNING: Couldn't determine end-line of vertical blanking interval for your display! Trouble with beamposition queries?!?
PTB-WARNING: Detected end-line is -1, which is either lower or more than 1.250000 times higher than vbl startline 1080 --> Out of sane range!


PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: GeForce GTX 1070 Ti/PCIe/SSE2 :: 4.6.0 NVIDIA 435.21
PTB-INFO: VBL startline = 1080 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback.
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 4.182363 ms [239.099310 Hz]. (50 valid samples taken, stddev=0.075391 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 4.166667 ms [240.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.


----- ! PTB - WARNING: SYNCHRONIZATION TROUBLE ! ----

One or more internal checks (see Warnings above) indicate that
queries of rasterbeam position are not properly working for your setup.

Psychtoolbox will work around this by using a different timing algorithm, 
but it will cause Screen('Flip') to report less accurate/robust timestamps
for stimulus timing.
Read 'help BeampositionQueries' for more info and troubleshooting tips.


WARNING: Beamposition queries broken or disabled or unsupported on your setup!
```

I went through the 'DisplayOutputMappings' and 'BeampositionQueries' help but I couldn't solve my problem. I am only using one display and a single GPU. Tried to replug the display into different video output connectors too.

Thanks for your help.

**Comment by kleinerm** [comment]
In general we recommend against NVidia gpu's, because they need the proprietary drivers, which make everything just a tad more painful. The open-source driver would solve this problem automatically, but i guess is not an option if you want to run a modern NVidia gpu at 240 Hz. Ideally you'd have an AMD gpu for an easier life.

Anyway, normally this means the display engine is misdetected by the heuristic, and the help in DisplayOutputMappings should help:

clear all; Screen('Preference', 'ScreenToHead', 0, 0, n); for a n of 0, 1, 2, or 3 should do the trick, depending on which of the 4 display engines 0, 1, 2 or 3 is used for your display. The "clear all" might be crucial between each failed trial.

**Comment by armengol** [comment]
Thank you for your quick response.
Yes, I read about the problems with NVidia but that is the gpu I have available right now...
I tried with the open-source nouveau driver to see if the performance was reduced (my PTB code is not very demanding, just 4 squares flickering, but I need the 240Hz refresh rate), however I got the warnings ````PTB-WARNING: Your graphics driver doesn't allow me to control syncing wrt. vertical retrace!
PTB-WARNING: Please update your display graphics driver as soon as possible to fix this.```` so I discarded the option of the open-source driver for now.

Going back to the current error, yes I tried already the Screen('Preference', 'ScreenToHead', 0, 0, n);
For some 'n', the bottom part of the errors in my previous comment (starting at ----- ! PTB - WARNING: SYNCHRONIZATION TROUBLE ! ----) don't show up anymore, but the first part of the warnings regarding the Hang in beamposition query still appear for all 'n'.

Thanks for our help.

**Comment by kleinerm** [comment]
Hmm. G-Sync is not enabled by any chance? What happens if you also use DownloadPsychtoolbox from our website to get the latest 3.0.16 beta?
The GTX 1070 is a gpu i tested under 18.04, i think with the 445 series drivers, and it worked just fine, at least with the current PTB beta release.

**Comment by armengol** [comment]
Oh that was it, G-sync was enabled. No more Beamposition errors. Thanks so much. However, now I get the following warnings: 
````
PTB-WARNING: OpenGL driver seems to use 1-buffering instead of the required double-buffering for Screen('Flip').
PTB-WARNING: This could be a false positive in which case there is no reason to worry, but it could also indicate some problem
PTB-WARNING: with visual stimulus onset timing on your setup, which would impair visual timing and timestamps of Screen('Flip').
PTB-WARNING: If timing matters, I'd recommend performing further diagnosis and potential troubleshooting (read 'help SyncTrouble').
PTB-WARNING: One potential cause for this is that some kind of desktop compositor is active and interfering.
PTB-WARNING: This is a one-time warning which will not repeat, even if the problem persists during this session.
````
Also, I don't think my system passes the PerceptualVBLSyncTest since the flickering is not homogeneous at all, with cracks and weird moving patterns. Is it related to the 1-buffering Warning I got?

**Comment by kleinerm** [comment]
That shouldn't happen either. What desktop GUI do you use? This is only one display, right?

**Comment by armengol** [comment]
GNOME 3.28.2
Yes, just one display and single gpu.

**Comment by kleinerm** [comment]
Hmm. Don't know. We just installed a fresh Ubuntu 18.04.4 LTS on a new machine, with a NVidia Quadro P1000 gpu similar to your GeForce and proprietary driver, and GNOME 3.28.2, even dual-display. It gave that 1-buffering warning once, but then on successive runs the warning was gone.

So it doesn't seem to be a general problem on a hardware + OS setup similar to yours.

**Comment by kleinerm** [comment]
Obviously one thing you could try if the warning happens regularly is installing different proprietary NVidia drivers for Linux from NVidia's website itself. Other than that, i don't think there is anything i could do. These are proprietary drivers, either they work or they don't, only NVidia can fix them.

**Comment by armengol** [comment]
I see. One thing I noticed is that no error or warning shows up when I run a ptb test the first time after I open Matlab. Then, even after running a 'close all' command, the following tests end up with warnings/errors.

**Comment by kleinerm** [comment]
There should be a more recent GNOME version available for Ubuntu 18.04, do an update might make sense. Also since today, NeuroDebian ships the latest PTB 3.0.16 beta.

Peculiar. So you get the 1-buffering warning every time you run your script, even after a "clear all" inbetween, except the 1st time after you started Matlab? What happens if you use GNU/Octave, or matlab -nodesktop ? Does moving/renaming the file PsychJavaSwingCleanup.m help in any way, if you restart Matlab afterwards and retry?

I don't have any test machine with proprietary NVidia graphics to conveniently reproduce such a problem, and on the one machine i can occassionally test, it didn't happen like that. But that machine probably also has a different Matlab version, in case this is some bad interaction between two proprietary pieces of software, Matlab and NVidia driver.

**Comment by armengol** [comment]
Okay, thanks for your comments. I keep struggling to run a clean experiment without getting warnings and errors, so I am considering acquiring a new AMD gpu. Could you recommend one that should work with Ubuntu 18.04 LTS and Matlab R2019b? Thanks!

**Comment by iandol** [comment]
@armengol -- the radeon pro WX range work well, the GPU chipset is not too new so gets good support by PTB. I use WX4100 and WX5100 cards and they are rock solid with PTB, never get sync errors unlike my RTX 2070 CUDA card or my T1000 based laptop which continually give sync errors with PTB...

**Comment by armengol** [comment]
@iandol -- thank you!
