### ISSUE TITLE
VBLSyncTest reports wrong refreshing rates.

### ISSUE THREAD

**Issue by mikelgg93** [Psychtoolbox-3/Psychtoolbox-3#647]
### Scenario ###

When you have 2 monitors with different refreshing rates, and run _VBLSyncTest_ in the one with the highest refreshing rate, the test would give you the measured rate as the highest, even though in Windows at least, the monitor with lower refreshing rate would do a bottleneck, and the stimulus would be displayed at lower rates.

---
### Problem ###

Although Psychotoolbox reports errors in timestamps with multiple monitors at the beginning, the user, still could run this test and believe that the screen is working at proper refreshing rates.

---
### Solution ###

In VBLSyncTest.m, check whether there is more than one monitor and if they do run at different refreshing rates. In that case, throw an error, rather than the alleged refreshing rate that is showing now.
Perhaps, as PBT INFO throws many lines, and in order to keep the user aware, use 
`fprintf(2, 'Error...'),`
 which would be displayed in red in the command line.

**Comment by kleinerm** [comment]
I don't understand the scenario you are describing? Why would somebody open a window spanning more than one monitor, e.g., for binocular stimulation, but run them at different video modes and expect anything meaningful to happen?

But if you think this is a problem worth solving, pull requests welcome. Must work on all supported operating systems though to be considered an improvement.

**Comment by mikelgg93** [comment]
Hmm, I probably did not describe it properly. The scenario would be having a screen(144Hz for ex.) where stimuli are presented and a secondary monitor(normal 60Hz) is used as control station, with, for example, the command window of Matlab. 
Then if you run this test, the test reports that the "main screen" is working fine, at maximum refreshing rates (144Hz), but in fact, is deploying the stimulus at the speed of the secondary monitor(60Hz) which is lower.
I will work on it when I have a bit of time and open again when I get it, meanwhile, I close this.

**Comment by kleinerm** [comment]
Hm. That's not what should happen on Windows if you have a multi-display setup and present on screen 1, 2, ... Sounds like a graphics driver bug to me.
