### ISSUE TITLE
Raster Bitmaps of Characters Display as Boxes on Some Configurations of MacBook Air

### ISSUE THREAD

**Issue by cewrightUCI** [Psychtoolbox-3/Psychtoolbox-3#649]
I am trying to help a student port a working script to her MacBook Air running OS X, Matlab R2019b (Update 4 - 9.7.0.1296695) and PsychToolbox 3.0.16 - Beta. This is an experiment that runs well on Windows and on a much older Mac setup. When run on the student's machine WITH an attached monitor, it works fine. However, when run on the same machine WITHOUT a second monitor, the characters stored as Bitmaps display just as white rectangles.

I have attached the full functions that creates these bitmaps. but the critical snippet of code to create these bitmaps is
    cc = StimSpecs.Characters(iStim);
    color = StimSpecs.Color(iStim, 1:3);

    % Generate an image of the character
    Screen('TextSize', w, charSize);
    [~, offsetBoundsRect]= Screen('TextBounds', w, cc, 100, 100);
    Screen('FillRect', w, bkgrnd);
    Screen('DrawText', w, cc, 100, 100, color, bkgrnd);
    % Be sure that there is enough padding in the recovered image
    offsetBoundsRect = offsetBoundsRect + [-ssTL -ssTL ssBR ssBR];
    imageArray=Screen('GetImage', w, offsetBoundsRect, 'backBuffer');

The resulting small bitmaps are later copied into a larger bitmap for the entire stimulus regions, converted to a texture with 
    Screen MakeTexture
then displayed with 
    Screen DrawTexture

We have downloaded and loaded the XQuartz software and cannot think of anything else that might resolve this issue. Thank you for your help.

Ted Wright
[MakeStimTemplates_Characters.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/4330902/MakeStimTemplates_Characters.txt)

**Comment by kleinerm** [comment]
Hello, this is a simple one: It works fine on Linux according to my testing, and fine on Windows and a much older (== less badly broken by Apple) macOS setup. Also there is nothing in PTB's text rendering that would in any way depend on the number of active monitors.

Conclusion: It is an Intel graphics driver bug in your version of macOS. Nothing we could do about it. Have you tried rebooting again to see if the problem goes away? Other than that, i'd suggest upgrading your macOS to the latest stable version, in the hope it will fix the bug. Or better, given that the more recent the macOS, the more badly broken it is in my experience, downgrade to an older version.

I assume there isn't any specific error message wrt. text rendering in the cases it behaves weird, which could shed some light on this.

Or you try Screen('Preference','TextRenderer', 0) to use the legacy macOS text renderer. Maybe that will sidestep the macOS bug, maybe not. However, that renderer will show text appearance and behaviour deviating from the normal renderer and from other operating systems. Also, in case of trouble, the legacy renderer is not supported in any way wrt. troubleshooting.

**Comment by cewrightUCI** [comment]
Thanks for your analysis Mario.

Charles Wright
