### ISSUE TITLE
old code in sca?

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#650]
Hi Mario,

On a Windows 10 machine with two monitors connected running up to date beta PTB on MATLAB R2019b, i ran into an issue. In a script, I accidentally called sca twice nearly in a row. The second time crashed on the `SetMouse(x,y,0);` call on line 40. Should the if-block guarding this code gain an `IsLinux()`? Or is it old and can be removed (since the comment mentions Ubuntu 16.04)?

I'll post the error tomorrow when i'm at the machine again, but wanted to post this already.

**Comment by dcnieho** [comment]
Hmm, can't reproduce the crash now. It was something thrown from SetMouseHelper. Ah well.

Still, if this is Linux only, would it be good to add an IsLinux() to the if? I don't enjoy my mouse cursor being moved all the time :p

**Comment by dcnieho** [comment]
Ah, here ya go, the error popped up again (and this when calling sca just once):
```
INTERNAL PSYCHTOOLBOX ERROR
	error:                PsychError_internal
	general description:  Unspecified error, probably a Psychtoolbox bug
	specific description: Couldn't position the mouse cursor! (SetCursorPos() failed).
	module name:          Screen
	subfunction call:     SetMouseHelper
	file name:            C:\Users\Mario Kleiner\Documents\GitHub\Psychtoolbox-3\PsychSourceGL\Source\Windows\Screen\PsychScreenGlue.c
	function name:        PsychPositionCursor
	line number:          1134
Error using Screen
See error message printed above.

Error in SetMouse (line 69)
Screen('SetMouseHelper', windowPtrOrScreenNumber, round(x), round(y), mouseid,
detachFromMouse);

Error in sca (line 58)
    SetMouse(x,y,0);

Error in record2camWithStim (line 669)
        sca
```

**Comment by kleinerm** [comment]
Ok, it's not a crash, but an error abort. Weird, i haven't ever seen SetCursorPos() failing, also not on multi-display? Is something special about your setup otherwise?

We can add a IsLinux && check to that if statement to work around the weirdness.

**Comment by dcnieho** [comment]
Its something specific about this setup i think yes, i have not ever seen
this fail on other dual screen setups with Windows 10 etc. Would be good to
have that check, thanks!

**Comment by kleinerm** [comment]
Ok. Done in my master branch. This issue should auto-close once the next beta is released.

**Comment by dcnieho** [comment]
thanks!

**Comment by kleinerm** [comment]
Fixed.
