### ISSUE TITLE
Multiple window flip: slave windows not cleared etc

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#655]
On multi-screen setups, i sometimes use the functionality to flip multiple windows at once (set last parameter of screen 'flip' to 1). I have come to realize that the window whose window pointer is not mentioned in this flip call, but which is flipped also, does not seem to receive full processing.
Specifically what i have seen is that i need to clear it manually by drawing a fullscreen rect, and also that if a panelfitter is applied, it is not computer (nothing appears on this window).
Is this expected?

As always, this is on Windows 10, latest PTB and R2019b

**Comment by kleinerm** [comment]
What's the purpose of this use of multiflip? I don't think i implemented clearing and such and don't intend to. The purpose of the whole thing was a cheap dual-window stereo implementation, but this is now properly handled by using stereomode 10 iirc., so the multiflip flag is kind of an ancient thing, just here for backwards compatibility.

**Comment by dcnieho** [comment]
The purpose is to flip multiple windows at the same time. I have a main
screen for the participant and a second screen for the operator, both
fullscreen. Hmm, stereomode 10 (or so) would also allow me to draw the two
screens separately and would thus work for my purposes. So your advice is
to use that instead? If so, i'll test that out and if it works submit a doc
patch for screen flip, pointing people to this solution.

**Comment by kleinerm** [comment]
There are two PsychImaging tasks for that type of mirroring, in "help PsychImaging":
MirrorDisplayTo2ndOutputHead and MirrorDisplayToSingleSplitWindow
depending on your specific use case.

**Comment by dcnieho** [comment]
Ah sorry, i wasn't clear enough. The second display is different, and thus
drawn separately. E.g. During an eye tracking experiment, it would show a
live view of the data on top of the stimulus to the operator, and during
eye tracker setup, it would show the interface for controlling the eye
tracker. So its not mirroring, but a separately addressable display i am
looking for. I understood you as suggesting that a stereomode along with
Screen('SelectStereoDrawBuffer') would be a better option than the old
multiflip. Or is there yet another better way for this?

Cheers and thanks,
Dee

**Comment by kleinerm** [comment]
Ok, so it is just about using two separate onscreen windows. In that case you could abuse stereomodes for dual-display stereo like 4 or 10 iirc iff both displays are identical models at identical resolution/refresh etc. I think one window spanning both monitors, ie. screenId 0, and stereomode 4 would be the most efficient in that case. Timing would only be fine if the displays are synchronized in their refresh cycles, ie. same monitor model, same video settings, Windows-10 + graphics drivers not screwing up something. Might be neccessary to use SLS (SingleLargeSurface) mode on AMD gpu's or some Mosaic thingy on NVidia gpu's. I know that used to work on AMD (last tested in 2010 or 2012?), i never got to test the Mosaic thingy. I also remember Windows-10 having bugs that caused system hangs iff one tried to do it without SLS or such?

Or you just draw conventionally and issue two separate Screen('Flip') commands. And maybe set the Screen('Flip', ...dontsync) flag to 1 or even 2 for the operator monitor to avoid blocking script execution on the completion of flips on the operator monitor. Given that timing is sort of important for eye tracking, you'll probably want to do what's best for precise timing on the stimulation display.
