### ISSUE TITLE
text underline not working with FTGL plugin

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#656]
This i have actually noticed for at least over a year, that underlining text does not work with the FTGL plugin (TextRenderer 1). I finally played with settings like text antialiasing, but they don't affect the result. It happens with multiple fonts

Example code:
```
clear screen
[wpnt,wrect]=Screen('OpenWindow', 0, 128);
Screen('TextStyle', wpnt, 4);
Screen('TextSize', wpnt, 40);
Screen('Preference', 'TextRenderer', 1);

Screen('drawtext',wpnt,'test',200,200);

Screen('Flip',wpnt);

WaitSecs(2);
sca
```

Windows 10, up to date PTB, MATLAB R2019b

**Comment by dcnieho** [comment]
Ah, i see that the FTGL plugin doesn't do underlining. I'll try and look into this, but definitely no promises

**Comment by dcnieho** [comment]
I made a start, see this branch:
https://github.com/dcnieho/Psychtoolbox-3/tree/FTGL_underline

I think it is probably not working completely right, even for standard built in fonts i always get 0. when querying underline_position from the face. I have found an ok-ish fallback in that case.

Well, this isn't perfect, but better than not having underlines at all.

some testing code:
```
clear screen
Screen('Preference', 'SkipSyncTests', 2);
[wpnt,wrect]=Screen('OpenWindow', 0, 128);

Screen('BlendFunction', wpnt, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);   % has no effect on text rendering, used below for semi-transparent bounding boxes
Screen('Preference', 'TextAntiAliasing', 2);

Screen('TextFont', wpnt, 'Arial');
Screen('TextStyle', wpnt, 1+4);
Screen('TextSize', wpnt, 100);
Screen('Preference', 'TextRenderer', 1);
Screen('drawtext',wpnt,'testg',200,200);

Screen('TextStyle', wpnt, 4);
Screen('drawtext',wpnt,'testg',200,300);

Screen('drawtext',wpnt,'test',200,400);


Screen('TextFont', wpnt, 'Helvetica');
Screen('TextStyle', wpnt, 4);
Screen('TextSize', wpnt, 50);
Screen('drawtext',wpnt,'test',200,500);

Screen('TextFont', wpnt, 'Helvetica');
Screen('TextStyle', wpnt, 1);
Screen('TextSize', wpnt, 50);
Screen('drawtext',wpnt,'test',200,600);


Screen('TextFont', wpnt, 'Helvetica');
Screen('TextStyle', wpnt, 4);
Screen('TextSize', wpnt, 50);
Screen('drawtext',wpnt,'test',200,700);

Screen('Flip',wpnt);
WaitSecs(2);
sca
```

**Comment by kleinerm** [comment]
I have a few nitpicks wrt. code style not quite matching the style there already. Small bug fixes.
Some suggestions for possibly improving performance when switching between underline/no-underline text. If you send a pull request i can add review comments. Apparently i can't do that if it isn't in a pull request.
I haven't tested this, but assuming it works, the general approach seems reasonable. Main question would be, does it still compute correct bounding boxes for Screen('TextBounds'), given that you don't have new code in the Texture::measure ( const QChar c ) method?

**Comment by kleinerm** [comment]
Ok, maybe you are offline atm., i can't comment inline without a pull request from you, and given that i looked at your code almost two weeks ago, and my memories of what to do differently are fading, i sent myself a pull request that contains inline comments of required changes/fixes and proposed performance optimizations:

https://github.com/kleinerm/Psychtoolbox-3/pull/172/files

**Comment by dcnieho** [comment]
Sorry for the inaction! Let me reply to what i can already and then work on the rest.

**Comment by kleinerm** [comment]
No worries, i don't think there are deadlines for volunteers ;)

Was just about to forget what i thought about, so thought better write it down.

**Comment by kleinerm** [comment]
Done in latest PTB beta "Crowning achievement".
