### ISSUE TITLE
CRT display vs LCD display

### ISSUE THREAD

**Issue by tourist-C** [Psychtoolbox-3/Psychtoolbox-3#658]
Hi, I got the spec that specifically asked to use CRT monitors instead of LCD display.
From my understanding from the sync error doc (http://psychtoolbox.org/docs/SyncTrouble), it seems CRT monitors are not a must.

Is it mandatory to use CRT monitors for test subjects?
Or I could use a laptop + external LCD monitor setup?

I am very new to this, so please bare with me.

**Comment by dcnieho** [comment]
please post this on our forum: https://psychtoolbox.discourse.group/
