### ISSUE TITLE
Different 'fontconfig' folder location on my system, but same happy fix

### ISSUE THREAD

**Issue by sr-brian** [Psychtoolbox-3/Psychtoolbox-3#659]
Fresh local install of Windows 1909, MATLAB 2019b and all things PTB this past week.

For whatever reason I was getting the "The external text renderer plugin failed to render the text string for some reason" when imposing on related functionality.

In documentation at: http://psychtoolbox.org/docs/DrawTextPlugin and other Issues tracked on GitHub (e.g. [#579](https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/579) the information indicates to clear the cached contents of the related fontconfig folder: 

> e.g., if your user
name would be “paul”, you’d likely need to delete the following file:
“C:\Users\paul[AppData](AppData)\Local\fontconfig\cache”

However, on my system the folder was instead created in a differet location, 
“C:\Users\paul\\.cache\fontconfig\”

There was no 'cache' subfolder, and the files therein were
-a----       2020-03-29  12:05 AM    204 CACHEDIR.TAG
-a----       2020-03-29  12:05 AM    1350200 d031bbba323fd9e5b47e0ee5a0353f11-x86_64.cache-7

I've removed those files from that folder, and no longer receive the aforementioned error on subsequent tests. However, I don't see any new files in that folder since the working tests, so I'm not sure if there is any down side to removing those files.

Hope this helps someone, and perhaps might be useful in documentation updates.

**Comment by kleinerm** [comment]
Thanks for the report. I added a snippet to the docs for the next PTB beta with your findings.
