### ISSUE TITLE
GetMouse ERROR

### ISSUE THREAD

**Issue by ALONELUR** [Psychtoolbox-3/Psychtoolbox-3#665]
I call GetMouse() in tutorial way: 
[x, y, buttons, focus, valuators, valinfo] = GetMouse(window);

This caused an error :
One or more output parameters were not assigned when screen was called.

Error GetMouse (line 219)
[globalX, globalY, rawButtons, focus, valuators,valinfo] = Screen('GetMouseHelper', numMouseButtons,windowPtrOrScreenNumber, mouseDev);

OS: ubuntu 18.04 LTS

**Comment by dcnieho** [comment]
Please post support questions to the forum: https://psychtoolbox.discourse.group/
When you do so, post a complete minimal (as few lines as possible) example that reproduces the error
