### ISSUE TITLE
Execution of arbitrary system commands via GetEchoString

### ISSUE THREAD

**Issue by bytebutcher** [Psychtoolbox-3/Psychtoolbox-3#666]
The GetEchoString method is used to let users enter text on the screen interactively.

I discovered a small quirk, that the entered text is also executed in the command window.
As a result the user is able to execute arbitrary system commands.

```
    % Setup screen
    screens = Screen('Screens');
    screenNumber = max(screens);
    white = WhiteIndex(screenNumber);
    [window, windowRect] = PsychImaging('OpenWindow', screenNumber, white);
    Screen('BlendFunction', window, 'GL_SRC_ALPHA', 'GL_ONE_MINUS_SRC_ALPHA');
    
    black = BlackIndex(screenNumber);
    Screen('TextSize', window, 24);
    Screen('TextFont', window, 'Arial');
    GetEchoString(window, 'Execute code: ', 0, 0, black, white);
    WaitSecs(5);   
    
    % Clear the screen
    sca;
```

When the user enters ```!notepad.exe``` (windows) the Windows Notepad application will be opened shortly after the screen is cleared.

**Comment by kleinerm** [comment]
I don't think that has anything to do with GetEchoString(), but simply with the fact that by default everything you type also ends in the Matlab command window.

The fix is to use ListenChar(-1) in your script to suppress forwarding of typed keystrokes to Matlab while the script is running.

**Comment by bytebutcher** [comment]
Thanks for your answer and the  suggestion of using ListenChar(-1). I was not aware of this function. While this does fix the issue for me and those who are aware of that, my guess is that most people will not bother using this function cause they do not know that this would allow participants to execute arbitrary commands. Even if they do know they might forget to use this function. 

Would it be possible to set ListenChar(-1) as default?

**Comment by kleinerm** [comment]
That function is mentioned and recommended in the help texts for the most commonly used keyboard input functions. If you find some help texts lacking with regard to this, a pull request with help text updates is welcome.

I don't know what you mean with setting ListenChar as default? There aren't defaults that get applied when starting a PTB script? And changing this behaviour after 15 years would break and confuse all existing scripts and users. So the answer would be no.

That said, this behaviour that typed text shows up in Matlab's or Octave's command window and could contain commands, is just standard Matlab/Octave UI behaviour, and everybody who ever typed during execution of a script would notice this. If anything it would be a security issue for Matlab or Octave to solve. I also think your scenario is a bit far fetched as a threat scenario. Subjects have access to all of Matlab while they are seated in front of the computer, so if they wanted to do nasty things they wouldn't need to go through such trouble. They could abort the script and type commands. Or they could even ALT+TAB away from PTB and Matlab and open a terminal and type commands. Always with the risk of getting discovered, more so if they type in Matlab and everything gets recorded into a command history or diary log file or the key response data also collected by PTB if a script takes keyboard input. Also what's the motivation of a subject to do that? It's not like data collection machines store data that is of much value to criminals?

**Comment by bytebutcher** [comment]
Thank you very much for your answer and your opinion about that matter.

> I don't know what you mean with setting ListenChar as default?
My Idea was to set ```ListenChar``` to ```-1``` during ```PsychImaging('OpenWindow', ...);``` and reset it when the window is closed. If this breaks existing scripts they might be adjusted by configuring ```PsychImaging``` accordingly. However i do understand your reasoning - if this kind of behavioural change does break and confuse a lot of existing scripts and users this will not be an ideal situation.  

I get your point that this seems like a far fetched threat. I was just a bit surprised when executing the above script and seeing that my input (10 lines of arbitrary characters) which i entered during the session was interpreted by matlab after the window was closed. My train of thought was "What if i tampered with a variable by accident" and after that i just checked the worst-case scenario and discovered that all it would take was a ```!``` at the beginning of a line to mess with my system. While the chances of this happening might be quite low, the chance alone is making me feel quite itchy. And your quite right about subjects with malicious intent. That threat seems to me far fetched, too.  

Thanks again for your answer. I really appreciate the work you put into this tool and really love using it during my experiments.
