### ISSUE TITLE
Why my texts take wrong position after change a PC ？

### ISSUE THREAD

**Issue by iuype** [Psychtoolbox-3/Psychtoolbox-3#668]
I wrote some texts presentations on my computer. In order for my program to run on screens of different sizes, I considered the change in resolution. But I still get confusing results.Everything goes well on my own PC and second man‘s PC ，but the third man’s PC ，where all texts has a fixed shift。

what shold I do？here is my matlab script。
[demo.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/4746648/demo.txt)

**Comment by dcnieho** [comment]
"help DrawTextPlugin", please make sure all the prerequisites for the high
quality text renderer are present at the machine thats different. If they
are not, PTB falls back to the legacy text renderer, which may render text
at different positions.
