### ISSUE TITLE
psychtoolbox Screen.mexw64 issue

### ISSUE THREAD

**Issue by yunshufan** [Psychtoolbox-3/Psychtoolbox-3#669]
I just installed psychtoolbox today. I followed the instructions, installed the 64-Bit GStreamer-1.16.0 MSVC, and corrected the path order so that C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\ is be before the folder C:\toolbox\Psychtoolbox\PsychBasic\. However, when I call the function Screen, I still receives error message saying "Invalid MEX-file
'C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64':
The specified module could not be found." Could someone help me out? thanks!

**Comment by dcnieho** [comment]
Did you install the visual c++ runtime as well?

**Comment by yunshufan** [comment]
No, I didn't see instructions for that. Could you provide more detailed info/instruction on that? Thanks!

**Comment by yunshufan** [comment]
Is it the "vcredist_x64_2015-2019"?

**Comment by yunshufan** [comment]
I tried to install it, but it failed with the following message:
![Capture](https://user-images.githubusercontent.com/32801111/85182787-b95cff80-b257-11ea-8087-97d2d4c7d771.PNG)

**Comment by yunshufan** [comment]
I also tried to install "VC_redist.x64" from the microsoft website. It is installed successfully, but I'm still having the same issue...

**Comment by dcnieho** [comment]
Its point 8 here:  http://psychtoolbox.org/download.html#Windows, which
provides a direct link. You may have tried the right installer already. If
that doesn't do it (make sure to restart after install), and you're sure
you have the right GStreamer version, then i am not sure what it could be.

**Comment by kleinerm** [comment]
The already installed vc_redist2015-2019 and GStreamer is all we need, so i guess something must go wrong maybe with setup of the GStreamer path. cd(PsychtoolboxRoot) and run SetupPsychtoolbox to make sure the current installation is sane enough. Post the full output in Matlab's command window from the moment you start Matlab by clicking its icon. I wonder if PsychStartup doesn't run for some reason at Matlab launch, or can't find GStreamer?

**Comment by yunshufan** [comment]
I uninstall all visual c++ on my computer (turned out there had been many
other versions already installed) and only install the vc_redist2015-2019.
Then I run the SetupPsychtoolbox as administrator. Then this issue was
gone. However, every time I restart Matlab, this issue comes back until I
re-run SetupPsychtoolbox. Basically, I have to run SetupPsychtoolbox every
time to avoid this issue. Is that normal?

**Comment by yunshufan** [comment]
This is the screen output when I run SetupPsychotoolbox:
>> SetupPsychtoolbox
Will setup working copy of the Psychtoolbox folder inside:
C:\toolbox\Psychtoolbox

Your old Psychtoolbox appears in the MATLAB/OCTAVE path:
Your old Psychtoolbox appears 1072 times in the MATLAB/OCTAVE path.
Before you decide to delete the paths, do you want to see them (yes or no)?
no
You didn't say "yes", so I'm taking it as no.
Shall I delete all those instances from the MATLAB/OCTAVE path (yes or no)?
yes
Success.

Now adding the new Psychtoolbox folder (and all its subfolders) to your
MATLAB/OCTAVE path.
Success.



Running post-install routine...


PsychStartup: Adding path of installed GStreamer runtime to library path.
[C:\gstreamer\1.0\x86_64\bin]
Matlab release 2007a or later detected. Will prepend the following
folder to your Matlab path:
C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\ ...

ans =

   1.4743e+05


Done with post-installation. Psychtoolbox is ready for use.


GENERAL LICENSING CONDITIONS AND TERMS OF USE:
----------------------------------------------

Almost all of the material contained in the Psychtoolbox-3 distribution
is free-software and/or open-source software under a OSI (
http://www.opensource.org/)
approved license. Most material is covered by the MIT license or a MIT
compatible license.

A few internal libraries and components are covered by other free software
licenses which we understand to be compatible with the MIT license, e.g.,
the GNU LGPL
license, or BSD and Apache-2.0 licenses, or they are in the public domain.

3rd-party components which are freely useable and redistributable for
non-commercial
research use, due to the authors permissions, but are not neccessarily free
/ open-source
software, can be found in the "PsychContributed" subfolder of the
Psychtoolbox distribution,
accompanied by their respective licenses.

A few components are licensed under the GNU GPL v2 license with a special
linking
exception for use with Mathworks proprietary Matlab application. A very few
components,
e.g., the PsychCV() function are currently covered by the standard GPL v2
license and
cannot be used with Matlab. These are only available for use with
GNU/Octave.

Please read the license text and copyright info in the Psychtoolbox file
License.txt carefully before you use or redistribute Psychtoolbox-3.
Use of Psychtoolbox-3 components implies that you have read, understood and
accepted
the licensing conditions.

However, in a nutshell, if you just use Psychtoolbox for your research, our
licenses
don't restrict you in any practically relevant way. Commercial users,
developers or
redistributors should make sure they understood the licenses for the
components they use.
If in doubt, contact one of the Psychtoolbox developers, or the original
authors of the
components you want to use, modify, merge or redistribute with other
software.

Your standard Psychtoolbox distribution comes without the source code for
the binary plugins (the MEX files). If you want to access the corresponding
source code, please type "help UseTheSource" for specific download
instructions.

BEGINNERS READ THIS:
--------------------

If you are new to the Psychtoolbox, you might try this:
help Psychtoolbox

Psychtoolbox website, which also links to a tutorial for basic use cases:
web http://www.psychtoolbox.org -browser

Please make sure that you have a look at the detailed ECVP 2013 tutorial
slides
in the PDF file PTBTutorial-ECVP2013.pdf
in the Psychtoolbox/PsychDocumentation subfolder for an overview of
differences
between Psychtoolbox-2 and Psychtoolbox-3 and proper use of basic features.
That
folder contains various additional helpful information for use of
Psychtoolbox.


Please also familiarize yourself with the demos contained in the PsychDemos
subfolder
and its subfolders. They show best practices for many common tasks and are
generally
well documented.



Enjoy!

Press RETURN or ENTER to confirm you read and understood the above message.

**Comment by kleinerm** [comment]
No, that's not normal. Either PsychStartup is not called at each startup of Matlab - You should see a message "PsychStartup: Adding path of installed GStreamer runtime to library path.
[C:\gstreamer\1.0\x86_64\bin]" every time you launch Matlab. Or the updated Matlab path with PTB folders added doesn't get properly saved.

In both cases it likely would be due to a permission problem on your machine.

PsychStartup gets called by the Matlab startup.m file.

**Comment by kleinerm** [comment]
No reaction in 10 days. closing.

**Comment by andrew-yian-sun** [comment]
Hello,

I have a similar issue: 

`Invalid MEX-file 'C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Datapixx.mexw64': The specified module could not be found.`

I have running a 64 bit Windows computer.

I have 64-Bit GStreamer-1.18.0 MSVC
I also downloaded the c++ runtime: vcredist_x64_2015-2019

However, unlike OP, I am still running into the issue.

**Comment by kleinerm** [comment]
@andrew-yian-sun To get support for issues like the one you posted here, read ``help PsychPaidSupportAndServices`` how to do that. Or under the following links:
https://www.psychtoolbox.net
http://psychtoolbox.org/prioritysupport.html

**Comment by HuwSwan** [comment]
I have a solve for any future folk.

Just ran into the same issue where it couldn't find the file despite it existing. When you run SetupPsychtoolbox or PsychStartup (which is also called by setup), at line 50 in psychstartup is: sdkroot = getenv('GSTREAMER_1_0_ROOT_MSVC_X86_64');

Depending on factors known only to god, on some systems and installs this returns 'C:\Program Files\gstreamer\1.0\msvc_x86_64' (with a trailing slash, I can't write it on here cos markup deletes it) and others it can return 'C:\Program Files\gstreamer\1.0\msvc_x86_64' without the trailing slash) 

Following in the script is the section %probe standard install location on drives C,D,E,F,G where 'bin' is appended to the path returned for sdkroot, however it's appended as:

sdkroot = [sdkroot 'bin'], meaning that you will get an incorrect path of 'gstreamer\1.0\msvc_x86_64bin' rather than 'gstreamer\1.0\msvc_x86_64\bin'

Changing the script to "fullfile(sdkroot,bin)" guarantees that it will always return the valid path, regardless of the original pathing problem, this resolves the issue provided all else is install correctly.

**Comment by kleinerm** [comment]
@HuwSwan Excellent find! I've committed your proposed fix for release in the next PTB update. Thanks!
