### ISSUE TITLE
! PTB - ERROR: SYNCHRONIZATION FAILURE ! on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by DBermudez0** [Psychtoolbox-3/Psychtoolbox-3#671]
PTB-INFO: This is Psychtoolbox-3 for GNU/Linux X11, under Matlab 64-Bit (Version 3.0.16 - Build date: Apr 25 2020).
PTB-INFO: OS support status: Linux 5.3.0-59-generic Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Hybrid graphics setup with support for "NVidia Optimus" DRI PRIME-Sync output slaving detected - or so i think?
PTB-INFO: If you are displaying on a video output directly connected to the NVidia gpu, then my thinking here
PTB-INFO: might be wrong. In that case use PsychTweak('UseGPUIndex') to fix me! Otherwise timing might be wrong.
PTB-INFO: If i'm right, then the following assessments hold for your Optimus setup with NVidia's proprietary driver:
PTB-WARNING: Optimus GPU synchronization seems to be disabled. Maybe the nvidia-modesetting driver is not enabled?
PTB-WARNING: Both visual timing and timestamping will likely be highly unreliable. Please read 'help HybridGraphics'
PTB-WARNING: on how to enable nvidia-modesetting, and then reboot once to improve quality of visual stimulation.
PTB-INFO: Failed to enable realtime-scheduling [Operation not permitted]!
PTB-INFO: You need to run Matlab or Octave with root-privileges, or run the script PsychLinuxConfiguration once for this to work.
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.
PTB-WARNING: Couldn't collect valid flip interval samples! Fatal VBL sync failure!
PTB-WARNING: Either synchronization of doublebuffer swapping to the vertical retrace signal of your display is broken,
PTB-WARNING: or the mechanism for detection of swap completion is broken. In any case, this is an operating system or gfx-driver bug!

WARNING: VBL Calibration run No. 1 failed. Retrying...
PTB-INFO: Failed to enable realtime-scheduling [Operation not permitted]!
PTB-INFO: You need to run Matlab or Octave with root-privileges, or run the script PsychLinuxConfiguration once for this to work.
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.
PTB-WARNING: Couldn't collect valid flip interval samples! Fatal VBL sync failure!
PTB-WARNING: Either synchronization of doublebuffer swapping to the vertical retrace signal of your display is broken,
PTB-WARNING: or the mechanism for detection of swap completion is broken. In any case, this is an operating system or gfx-driver bug!

WARNING: VBL Calibration run No. 2 failed. Retrying...
WARNING: Will enable VBL busywait-workaround before trying final VBL Calibration run No. 3.
WARNING: This will hopefully work-around graphics driver bugs of the GPU sync-to-retrace mechanism. Cross your fingers!
PTB-INFO: Failed to enable realtime-scheduling [Operation not permitted]!
PTB-INFO: You need to run Matlab or Octave with root-privileges, or run the script PsychLinuxConfiguration once for this to work.
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.
PTB-WARNING: Couldn't collect valid flip interval samples! Fatal VBL sync failure!
PTB-WARNING: Either synchronization of doublebuffer swapping to the vertical retrace signal of your display is broken,
PTB-WARNING: or the mechanism for detection of swap completion is broken. In any case, this is an operating system or gfx-driver bug!

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: GeForce GTX 960M/PCIe/SSE2 :: 4.6.0 NVIDIA 430.26
PTB-INFO: VBL startline = 1080 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback.
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 0.000000 ms [inf Hz]. (0 valid samples taken, stddev=1000000000.000000 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.685299 ms [59.932999 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

WARNING: Mismatch between measured monitor refresh interval and interval reported by operating system.
This indicates massive problems with VBL sync.

PTB-WARNING: Unable to measure monitor refresh interval! Using a fake value of 16.685299 milliseconds.

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! -----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

PTB-INFO: Psychtoolbox imaging pipeline starting up for window with requested imagingmode 1061 ...
PTB-INFO: Will use 32 bits per color component floating point framebuffer for stimulus drawing. Alpha blending should work correctly.
PTB-INFO: Will use 32 bits per color component floating point framebuffer for stimulus post-processing (if any).
PTB-WARNING: OpenGL driver seems to use 1-buffering instead of the required double-buffering for Screen('Flip').
PTB-WARNING: This could be a false positive in which case there is no reason to worry, but it could also indicate some problem
PTB-WARNING: with visual stimulus onset timing on your setup, which would impair visual timing and timestamps of Screen('Flip').
PTB-WARNING: If timing matters, I'd recommend performing further diagnosis and potential troubleshooting (read 'help SyncTrouble').
PTB-WARNING: One potential cause for this is that some kind of desktop compositor is active and interfering.
PTB-WARNING: The most likely cause on this NVidia Optimus setup is the use of the proprietary driver, which will massively impair proper timing!
PTB-WARNING: Use the open-source nouveau graphics driver, or install the enhanced modesetting ddx, or do not use the NVidia gpu at all, if you
PTB-WARNING: care about research grade timing. See 'help HybridGraphics' for more info.
PTB-WARNING: This is a one-time warning which will not repeat, even if the problem persists during this session.

WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 1).
WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.
Invalid MEX-file '/home/dbermudez/Documents/MATLAB/Psychtoolbox-3/Psychtoolbox/PsychBasic/moglcore.mexa64':
libglut.so.3: cannot open shared object file: No such file or directory

Error in InitializeMatlabOpenGL (line 186)
moglcore('DEBUGLEVEL', debuglevel);

Error in PsychImaging>PostConfiguration (line 3393)
    InitializeMatlabOpenGL([], [], 1);

Error in PsychImaging (line 2373)
    PostConfiguration(reqs, win, clearcolor, slavewin);

Error in ContrastPsychometricFunction (line 33)
[windowPtr p.ScreenRect] = PsychImaging( 'OpenWindow' , whichScreen, p.ScreenBackground);

**Comment by dcnieho** [comment]
For both your posts,
1) please post them on the forum
2) before doing so, please read the post instructions there. you need to
provide information
