### ISSUE TITLE
Psychophysics installation problem using DownloadPsychtoolbox

### ISSUE THREAD

**Issue by AmritaMukherjee2011** [Psychtoolbox-3/Psychtoolbox-3#673]
While installing Psychophysics toolbox in Windows, I am getting the following error:
Machine specification:
Windows 10, 64 bit OS, 16 GB RAM, 3.41 GHz CPU
>> DownloadPsychtoolbox('C:\toolbox')
DownloadPsychtoolbox('C:\toolbox','beta','')
Requested flavor is: beta
Requested location for the Psychtoolbox folder is inside: C:\toolbox

Good. Your privileges suffice for the requested installation into folder C:\toolbox.

I will now download the latest Psychtoolbox for Windows.
Requested flavor is: beta
Target folder for installation: C:\toolbox
The following CHECKOUT command asks the Subversion client to
download the Psychtoolbox:
svn checkout  https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox/ "C:\toolbox\Psychtoolbox"
Downloading. It's nearly 100 MB, which can take many minutes.
Alas there may be no output to this window to indicate progress until the download is complete.
Please be patient ...
If you see some message asking something like "accept certificate (p)ermanently, (t)emporarily? etc."
then please press the p key on your keyboard, possibly followed by pressing the ENTER key.

svn: E170013: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox'
svn: E120112: Error running context: APR does not understand this error code
Sorry, the download command "CHECKOUT" failed with error code 1:
svn: E170013: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox'
svn: E120112: Error running context: APR does not understand this error code

The download failure might also be due to temporary network or server problems. You may want to try again in a
few minutes. It could also be that the subversion client was not (properly) installed. On Microsoft
Windows you will need to exit and restart Matlab or Octave after installation of the Subversion client. If that
does not help, you will need to reboot your machine before proceeding.
Another reason for download failure could be if an old working copy - a Psychtoolbox folder - still exists.
In that case, it may help to manually delete that folder. Or maybe you do not have write permissions for the target folder?

Error using DownloadPsychtoolbox (line 818)
Download failed.

**Comment by kleinerm** [comment]
As the message says: "The download failure might also be due to temporary network or server problems. You may want to try again in a few minutes."

Other than that, follow the troubleshooting instructions on our Websites download page, or dowload it as a zip file, as described there.
