### ISSUE TITLE
PTB - ERROR: SYNCHRONIZATION FAILURE !  in Windows 

### ISSUE THREAD

**Issue by alexpavel2** [Psychtoolbox-3/Psychtoolbox-3#674]
Hi - I am having trouble running code in Matlab because the error "PTB - ERROR: SYNCHRONIZATION FAILURE ! .... Error using Screen,  [visible_window,windowRect]= Screen(screens, 'OpenWindow', 1, [ ], pixelsize)" keeps coming up. I have had this problem before but I fixed it by changing the graphics settings in my laptop , however now the problem is happening again and I'm not sure what else I can do. 

Any help is greatly appreciated ,

Alex

**Comment by dcnieho** [comment]
Have you followed the steps suggested by help SyncTrouble? If none of those
help, please post more info (OS, graphics card, laptop model, matlab
version, PTB version). Make sure you are fully up to date with PTB

**Comment by kleinerm** [comment]
Also check our user forum for suitable answers and discussions, and the list of closed issues here. This is always a misconfiguration of your system, an operating-system/graphics-driver bug, or simply a low performing system, and the topic has been treated endlessly here and on the forum.
