### ISSUE TITLE
How can I make the window bars disappear?

### ISSUE THREAD

**Issue by SimpierZhang** [Psychtoolbox-3/Psychtoolbox-3#676]
I want to draw a rect window without the tip bar, what can i do?Is there any parameter on Screen('OpenWindow') can achieve  implement this function?

![TNEVW4908CA3N0 %YK~I4 X](https://user-images.githubusercontent.com/63383702/95568486-e0358080-0a56-11eb-9268-eedc6ca91dc6.png)

Hope to get your answer！

**Comment by kleinerm** [comment]
This bar doesn't show, ie. the window is fullscreen, if you leave the 'rect' parameter of 'OpenWindow' out, or empty.
E.g., ``win = Screen('OpenWindow', screenId, backgroundcolor);``

None of our demos would show a window with a bar by default, so it actually takes extra effort to make it show the title bar.

**Comment by SimpierZhang** [comment]
Sorry, maybe my description is not clear. My requirement is that when I use the 'rect' parameter to create a non fullscreen window, I want to cancel this bar. What should I do？

**Comment by suxpert** [comment]
I'm not very sure about this, but perhaps the following line have missing parentheses? (Otherwise the `if` never reached)
https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/42872ae6d8aa9d175dc613dc2cafedbc6d1a23ac/PsychSourceGL/Source/Windows/Screen/PsychWindowGlue.c#L1024

should be
```C
        if (!(windowRecord->specialflags & kPsychGUIWindow)) {
```

Then only if `specialFlags = bitor(someotherflag, kPsychGUIWindow)` when OpenWindow, the window would have the border and title bar.

**Comment by kleinerm** [comment]
This commit will fix it for the upcoming PTB beta release (probably sometime this week, maybe next week):
https://github.com/kleinerm/Psychtoolbox-3/commit/aa9184f15d0717a81681320106585700a0960312
@suxpert You're right, that was it, thanks! Weirdly this worked fine for many years, so i don't know if the compiler
introduced some changes at some point, ...

**Comment by SimpierZhang** [comment]
@suxpert I also noticed the parameter "specialflags", but I found that this parameter only has the option of "kpsychguiwindow"? So is there any other way you can help me to fulfill my requirements?

**Comment by suxpert** [comment]
@SimpierZhang, @kleinerm has fixed this, so you may wait until the next release, or compile screen yourself. Then the window created by `Screen('OpenWindow')` will have no border and title bar by default, unless you set the specialFlags as I wrote in the previous comment.

Until then, there's no easy way to remove the title bar under windows. But for Linux, some window manager have options to remove them (for all windows).

**Comment by SimpierZhang** [comment]
Ok, thanks for your help, i may be know what i should do
