### ISSUE TITLE
Failed to initialize the window record because the default font for DrawText was not found.

### ISSUE THREAD

**Issue by anasioulas** [Psychtoolbox-3/Psychtoolbox-3#678]
Hello,

I get the following error on macOS Catalina.

INTERNAL PSYCHTOOLBOX ERROR
	error:                PsychError_internal
	general description:  Unspecified error, probably a Psychtoolbox bug
	specific description: Failed to initialize the window record because the default font for DrawText was not found.
	module name:          Screen
	subfunction call:     OpenWindow
	file name:            /Users/kleinerm/projects/OpenGLPsychtoolbox/Psychtoolbox-3/PsychSourceGL/Source/OSX/Screen/PsychWindowTextGlue.c
	function name:        PsychInitTextRecordSettings
	line number:          66

I tried the solutions I found in two other posts, but it still does not work. 

If I run
Screen('Preference','DefaultFontName')
Screen('Preference','DefaultFontStyle')
Screen('Preference','Verbosity', 6)
I get
    'Arial'
     0
     3

Thank you very much in advance

**Comment by kleinerm** [comment]
Is this all you get after a "clear all" and rerun? PTB on macOS can detect most problems with the macOS font database or fonts, so this failing without any helpful warning message is weird.

What's the output of ``numFonts=FontInfo('NumFonts')`` ?

What's the output of ``fontInfoStructArray=FontInfo('Fonts')``? Does that array actually contain a font with the name Arial? I'm not sure how your system could lose a default font, unless the font would be damaged or got disabled or deleted.

**Comment by anasioulas** [comment]
The whole message I get after a "clear all" and rerun is the following:

```
INTERNAL PSYCHTOOLBOX ERROR
	error:                PsychError_internal
	general description:  Unspecified error, probably a Psychtoolbox bug
	specific description: Failed to initialize the window record because the default font for DrawText was not found.
	module name:          Screen
	subfunction call:     OpenWindow
	file name:            /Users/kleinerm/projects/OpenGLPsychtoolbox/Psychtoolbox-3/PsychSourceGL/Source/OSX/Screen/PsychWindowTextGlue.c
	function name:        PsychInitTextRecordSettings
	line number:          66
Error using Screen
See error message printed above.

Error in PsychImaging (line 2232)
            [win, winRect] = Screen('OpenWindow', screenid, clearcolor, winRect, pixelSize, numbuffers, stereomode, multiSample, imagingMode, specialFlags, clientRect, fbOverrideRect, vrrParams);

Error in run_expe (line 143)
    video.h = PsychImaging('OpenWindow',video.i,0);
```
Also, regarding the second part, I get
```
>> numFonts=FontInfo('NumFonts')
numFonts =
   580
>> fontInfoStructArray=FontInfo('Fonts')
fontInfoStructArray = 
  1×580 struct array with fields:
```
and indeed if in the fontInfoStructArray.name there is one called 'Arial'.

**Comment by kleinerm** [comment]
Hm. There should be one where fontInfoStructArray.familyName has 'Arial' in it, with a styleCode field == 0.
If no entry has familyName == 'Arial' then that font does not exist from Screen()'s perspective. That would suggest some defect in the set of fonts on your system.

**Comment by anasioulas** [comment]
Hello, thanks again.

```
>> fontInfoStructArray(282)
ans = 
  struct with fields:
            number: 282
              name: 'Arial'
     QuickDrawName: ''
    PostScriptName: 'ArialMT'
        familyName: 'Arial'
         styleCode: 0
        styleNames: {'normal'}
              file: '/System/Library/Fonts/Supplemental/Arial.ttf'
           metrics: [1×1 struct]
            locale: [1×1 struct]
```
There is indeed one with the properties you mentioned. 
What does that mean?

**Comment by kleinerm** [comment]
This should work perfectly then, but apparently  doesn't. And it works just fine on my Catalina test system.

What macOS version, Octave/Matlab version is this? I assume this is the very latest PTB 3.0.16 beta release, right?

**Comment by anasioulas** [comment]
I am using the latest version of Matlab, namely matlab_R2020b_maci64.
I also tried with matlab_R2019a_maci64, but without uninstalling the 2020b first, so I am not sure how useful that was.
Regarding the PTB version, I get this 
`3.0.16 - Flavor: beta - Corresponds to SVN Revision 10582 but is *locally modified* !`

Would it be of any use to uninstall everything (Matlab, PTB) and try it again?
Do you have any other suggestion?

**Comment by suxpert** [comment]
@anasioulas  Perhaps you can check if changing the default font to some others (e.g., Helvetica) works or not.

Also, perhaps try to open the Arial font in Font Book, or try the PTB demo functions (DrawSomeTextDemo et. al.), might give further information (I guess).

**Comment by kleinerm** [comment]
Maybe reinstall PTB from a fresh download, to rule out some file corruption causing this. Sounds unlikely, but not impossible.
I just retested on maOS 10.15.7 fully up to date, and R2019b Update 7, and all is good.

**Comment by anasioulas** [comment]
Hello,

Actually, it was the other way around from suxpert's suggestion.
In the code they handed me at some they were changing the font to Helvetica. I changed it back to Arial and it finally worked.

Sorry for the inconvenience and thank you very much for your help and support

**Comment by kleinerm** [comment]
So the problem didn't exist?

**Comment by anasioulas** [comment]
Essentially, it didn't.
It was failing to run with Helvetica, but I can do my job with Arial.

**Comment by kleinerm** [comment]
Does the machine have Helvetica in the requested style, or not? If the font doesn't exist, it obviously won't work.

**Comment by anasioulas** [comment]
Yes, it has Helvetica with the requested style.
I don't know what is going wrong. But I am happy to work with Arial, it's not an issue.
