### ISSUE TITLE
Brightness setting via PTB

### ISSUE THREAD

**Issue by GLManenti** [Psychtoolbox-3/Psychtoolbox-3#683]
Hi! Not sure if this could be considered an "issue"...   I'm wondering if there is a Windows solution to force the graphic card to change the brightness values. Something like "[AutoBrightness"](http://psychtoolbox.org/docs/AutoBrightness). Thanks !

**Comment by dcnieho** [comment]
You mean the brightness setting of the monitor (don't think graphics cards
have one)? No, we do not have such a function

**Comment by qx1147** [comment]
You can use the ControlMyMonitor utility (https://www.nirsoft.net/utils/control_my_monitor.html). 
For example, for setting the Brightness to 70% on the primary monitor (Brightness has the VCR code 10hex), you would run (from MATLAB):
```
system('ControlMyMonitor.exe /SetValueIfNeeded Primary 10 70');
```
The utility has to be located in the current directory or somewhere in the Windows search path (not the MATLAB search path), or you have to specify its full pathname.
Running the tool without parameters opens a GUI which allows exploring the monitor parameters interactively.

**Comment by GLManenti** [comment]
Thank you very much for your answers. Yes I meant the brightness setting of the monitor (in my case PROPixx projector) and i checked how to get it done via PTB or Matlab. 
qx1147 solution is a good solution, Thanks. At the end we decided to command through the project's utility software externally from Matlab.
