### ISSUE TITLE
issue with compilation of a script using PTB function

### ISSUE THREAD

**Issue by tib-sim** [Psychtoolbox-3/Psychtoolbox-3#689]
Hi,
Until now, I compiled my PTB scripts with deploytool. This worked very well and I could use my compiled scripts on different computers ! I tried to do the same compilation on a new computer, this works fine again, once I launched the compiled script on this new computer. However, this did not work once I launched this compiled script on another computer. The compiled script gave me the following error "Invalid MEX-File" (Screen), with the path for this file and then sometimes the message "The specified module could not be found". I noticed a small difference for the size of mex64 files between my two computer. I also noticed that a different version of PTB was installed on my two computers (3.0.14 on my computer whose the compilation script worked everywhere AND 3.0.16 on my second and new computer). Thus I decided to copy the older mex64 files contained in the folder MatlabWindowsFilesR2007a from one computer to the other (the new one). I performed again the compilation on my new computer and then tested it on the the two computers and this time it seems  to work for both ! Why do I get this error with the more recent mex64 files? 
Best,
Simon

**Comment by dcnieho** [comment]
You probably haven't installed some required other tool (e.g. GStreamer, or
the right version of the VS runtime) on the computer where you try to run.
I would not suggest mixing the mex files of one ptb version with the
scripts of another

**Comment by tib-sim** [comment]
You are right, MVC 2015 2019 has not been installed on my older computer. This installation has been done few years ago and it is possible that I probably did not follow exatcly the instructions. I will update that and test it again. Thanks.
