### ISSUE TITLE
Sync works first time but subsequent tests fail...

### ISSUE THREAD

**Issue by saumilpatel** [Psychtoolbox-3/Psychtoolbox-3#710]
**[For commercial priority support for bug reports, click this link](http://psychtoolbox.org/prioritysupport.html)

**Describe the bug**
I just run DriftDemo and the first time it runs after a fresh matlab launch, the sync test passes but subsequent runs of DriftDemo reports Sync errors. The standard deviation in first run is about 0.03 msec whereas for subsequent runs they are like 0.3 msec and sometimes even 0.5 msec.

**To Reproduce**
Just run DriftDemo

**Expected behavior**
DriftDemo runs by displaying a drifting grating, nice and smooth, and there are no sync troubles reported at the end

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Runtime: Matlab 2020b
 - Hardware: Nvidia GeForce GTX 1060
 - Version: 3.0.12

**Additional context**

**Comment by saumilpatel** [comment]
Tried the latest beta version, it does the same thing

**Comment by dcnieho** [comment]
This is unlikely to be a bug, but instead a system configuration or hardware problem. Please post on the forum instead: https://psychtoolbox.discourse.group/
