### ISSUE TITLE
documentation contrast

### ISSUE THREAD

**Issue by michaelf500** [Psychtoolbox-3/Psychtoolbox-3#719]
**[For commercial priority support for bug reports, click this link](http://psychtoolbox.org/prioritysupport.html)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 20.04.1 LTS, macOS 10.15.7, Windows-10 (20H2)]
 - Runtime: [e.g. Matlab R2020b, Octave 5.2]
 - Hardware [e.g., AMD Radeon Pro W4100, Onboard sound chip]
 - Version [e.g. Psychtoolbox 3.0.17 - the output of the PsychtoolboxVersion() command]

**Additional context**

**Comment by michaelf500** [comment]
The documentation for PTB-3 functions, eg http://psychtoolbox.org/docs/KbQueueCheck has light grey text on a white background, giving a rather low visual contrast, and making it harder to read. The web accessibility evaluation tool https://wave.webaim.org/ rates the text as "very low contrast". 

Can the text be made a darker shade please?

Michael

**Comment by kleinerm** [comment]
Ok, that tinkering of myself seems to have done the trick. Now a AAA contrast score.
