### ISSUE TITLE
How to suppress screen startup and sync warning images?

### ISSUE THREAD

**Issue by nmtimme** [Psychtoolbox-3/Psychtoolbox-3#722]
Hello

I'm running Psychtoolbox-3 on Windows 10 in Matlab 2021a. When I execute the following commands:

global psych_default_colormode
psych_default_colormode = 1; % Default colormode to use: 0 = clamped, 0-255 range. 1 = unclamped 0-1 range.
AssertOpenGL;
PsychImaging('PrepareConfiguration');
PsychImaging('AddTask', 'General', 'FloatingPoint16Bit'); % Create the imaging pipeline
[win,winRect] = PsychImaging('OpenWindow', S.ScreenID, 0.5); % Open the screen (gray background)

I get the warnings below about synchronization after PsychImaging('OpenWindow'... is called. Based on my review of the website and github, this isn't particularly surprising. 

PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.17 - Build date: Apr 13 2021).
PTB-INFO: OS support status: Windows 10 (Version 10.0) supported and tested to some limited degree.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: For information about paid priority support, community membership and commercial services, please type
PTB-INFO: 'PsychPaidSupportAndServices'.

PTB-WARNING: Couldn't determine end-line of vertical blanking interval for your display! Trouble with beamposition queries?!?
PTB-WARNING: Detected end-line is 1535, which is either lower or more than 1.250000 times higher than vbl startline 768 --> Out of sane range!

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: Quadro P620/PCIe/SSE2 :: 4.6.0 NVIDIA 390.77
PTB-INFO: VBL startline = 768 , VBL Endline = 1535
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback.
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.666658 ms [60.000031 Hz]. (50 valid samples taken, stddev=0.020077 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================

----- ! PTB - WARNING: SYNCHRONIZATION TROUBLE ! -----

One or more internal checks (see Warnings above) indicate that
queries of rasterbeam position are not properly working for your setup.

Psychtoolbox will work around this by using a different timing algorithm, 
but it will cause Screen('Flip') to report less accurate/robust timestamps
for stimulus timing.
Read 'help BeampositionQueries' for more info and troubleshooting tips.

PTB-INFO: Psychtoolbox imaging pipeline starting up for window with requested imagingmode 1089 ...
PTB-INFO: Will use 16 bits per color component floating point framebuffer for stimulus drawing. Alpha blending should work correctly.
PTB-INFO: Will use 16 bits per color component floating point framebuffer for stimulus post-processing (if any).

I'm not particularly worried about these warnings since the system says it is working around the problem (though I'd appreciate any suggestions people could provide about how to fix them, beyond simply reading BeampositionsQueries or SyncTrouble). 

My real question is about how to suppress the screen output (the purple/pink screen with a frog and the red screen with the big exclamation point in a yellow triangle). I don't want these to be displayed when I call PsychImaging('OpenWindow',...). I looked through the website and the github issues, but I couldn't find anything about this. If I simply missed it, I'm sorry, and I'd appreciate it if you could direct me to the information. 

Thanks and have a good day!

~Nick

**Comment by kleinerm** [comment]
``Screen('Preference','VisualDebugLevel', 0);`` would switch to a black screen instead.
``PsychDefaultSetup(2)`` would be better than that ``psych_default_colormode`` you have there.

The beamposition failure is a weird one. What's your display setup? Monitors / resolution settings etc.?

See ``help PsychPaidSupportAndServices`` on how to give back something for the upkeep of PTB. Financial contributions are appreciated and needed.

**Comment by nmtimme** [comment]
Hi @kleinerm,

Thanks for your response! Your suggestions for suppressing the warning screen and purple info screen worked! Now a brief black screen appears. As a suggestion for future improvements, perhaps this could even be removed? Our task runs with a gray background, so the black screen still changes the visual stimulus. In any case, the black screen is a definite improvement, so thank you for that!

Regarding our monitors, we are using dual monitors. The first monitor is not visible to the subject and is a 1366x768 Dell monitor. We do not use PsychImaging('OpenWindow', on that monitor. The second monitor that displays stimuli for the subject is a 2048x1536 retina display (monitor: https://www.adafruit.com/product/1751, driver board: https://www.adafruit.com/product/1716). We use PsychImaging('OpenWindow', on that monitor. Let me know if there is additional information you need about the monitors. I'd appreciate any suggestions to remove the beamposition failure. 

Thank you for the suggestions about financial contributions to PTB. We will definitely consider this!

Thanks!

~Nick

**Comment by kleinerm** [comment]
Ok, that makes sense, so not a PTB bug. It was a coincidence that your Dell monitor has exactly half the vertical resolution of your Retina display, which confused me. Probably the timestamping problem is because of the use of multi-display on Windows (bad) and Retina (bad). In general, Linux would be a better choice for multi-display / Retina + precise timing, and for many other things...

If you need further assistance, feel free to follow...
PTB-INFO: For information about paid priority support, community membership and commercial services, please type
PTB-INFO: 'PsychPaidSupportAndServices'.
...to buy 1 hour of paid priority support, as a starter. More if one hour won't be enough.

Wrt. leaving the black screen out, that is not technically possible. What one could add is the option to select a different color than black. If you'd want that in a future PTB release, feel free to contract us to do that.

**Comment by nmtimme** [comment]
Sounds good! Thank you so much for your help!
