### ISSUE TITLE
Setting windowHandle=0 for PsychHID('KbQueueCreate') gives an error on win10

### ISSUE THREAD

**Issue by peircej** [Psychtoolbox-3/Psychtoolbox-3#723]
Setting windowHandle=0 for PsychHID('KbQueueCreate') gives an error on win10

**Describe the bug**

On win10, from a Python terminal run:
```
import psychtoolbox as ptb
q = ptb.PsychHID('KbQueueCreate', [], None, 0, 1000, 0, 0)
```
results in the error below, whereas the following works fine (but isn't in line with the documentation).
```
import psychtoolbox as ptb
q = ptb.PsychHID('KbQueueCreate', [], None, 0, 1000, 0, None)
```
The documentation for KbQueueCreate indicates that the default value for winHandle is 0
http://psychtoolbox.org/docs/KbQueueCreate

The bug also propogates to PsychPython/psychtoolbox/hid.py (and therefore to PsychoPy) because the keyboard hid.py uses 0 as the default, as in the docs

```
Error in function KbQueueCreate:     Incorrect argument type supplied
    Discrepancy between a specified and supplied argument:
        Specified Argument Description:
            direction: Input
            position: 6
            presence:
            formats allowed:
                unclassified
            minimum M: 1
            maximum M: 1
            minimum N: 1
            maximum N: 1
            minimum P: 1
            maximum P: 1
        Provided Argument Description:
            direction: Input
            position: 6
            presence: present
            format: int32
            number of dimensions: 0
                 M: 1
                 N: 1
                 P: 1
PsychHID:KbQueueCreate: Usage:

PsychHID('KbQueueCreate', [deviceNumber][, keyFlags=all][, numValuators=0][, numSlots=10000][, flags=0][, windowHandle=0])
1.6945     WARNING     We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
Traceback (most recent call last):
  File "C:\GITHUB\psychopy\psychojs_testing\tests\wdio_calibration\wdio_calibration_lastrun.py", line 78, in <module>
    defaultKeyboard = keyboard.Keyboard()
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\hardware\keyboard.py", line 182, in __init__
    buffer = _keyBuffers.getBuffer(devId, bufferSize)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\hardware\keyboard.py", line 400, in getBuffer
    kb_id=kb_id)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychopy\hardware\keyboard.py", line 439, in __init__
    self.dev = hid.Keyboard()  # a PTB keyboard object
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychtoolbox\hid.py", line 137, in __init__
    self._create_queue(buffer_size)
  File "C:\Program Files\PsychoPy3\lib\site-packages\psychtoolbox\hid.py", line 145, in _create_queue
    None, 0, num_slots, flags, win_handle)
TypeError: Incorrect argument type supplied
```

**To Reproduce**
On win10, from a Python terminal run:
```
import psychtoolbox as ptb
q = ptb.PsychHID('KbQueueCreate', [], None, 0, 1000, 0, 0)
```
The above works fine on macOS. On windows this works:
```
q = ptb.PsychHID('KbQueueCreate', [], None, 0, 1000, 0, None)
```

**Desktop (please complete the following information):**
 - OS: Windows 10 (10.0.15063)
 - Runtime: Python3.6 from python.org
 - Version: Psychtoolbox 3.0.17. There was no problem in 3.0.16

**Additional context**
winHandle=0 worked fine on 3.0.16 and still works on macOS (and ubuntu?)

**Comment by peircej** [comment]
Confirmed that ubuntu and macOS are both happy with either of
`q = ptb.PsychHID('KbQueueCreate', [], None, 0, 1000, 0, 0)`
or
`q = ptb.PsychHID('KbQueueCreate', [], None, 0, 1000, 0, None)`

so the bug is purely a windows thing

**Comment by 104H** [comment]
This bug persists on my system of the following specifications:
Ubuntu 20.04 LTS
python3.9
psychtoolbox 3.0.17.8

`q = ptb.PsychHID('KbQueueCreate', 11.0, None, 0, 1000, 0, 0)`
produces the following error
```
Error in function KbQueueCreate: 	Incorrect argument type supplied
	Discrepancy between a specified and supplied argument:
		Specified Argument Description:
			direction: Input
			position: 6
			presence:
			formats allowed:
				unclassified
			minimum M: 1
			maximum M: 1
			minimum N: 1
			maximum N: 1
			minimum P: 1
			maximum P: 1
		Provided Argument Description:
			direction: Input
			position: 6
			presence: present
			format: int64
			number of dimensions: 0
				 M: 1
				 N: 1
				 P: 1
PsychHID:KbQueueCreate: Usage:

PsychHID('KbQueueCreate', [deviceNumber][, keyFlags=all][, numValuators=0][, numSlots=10000][, flags=0][, windowHandle=0])
```

`q = ptb.PsychHID('KbQueueCreate', [], None, 0, 1000, 0, None)`
Produces no error.

**Comment by kleinerm** [comment]
Explanation in the commit. Computers are weird, and there might be something funky going on with Python interpreters on different OS'es, given that the same code executes on all OS'es in this case. Not sure if it is better to leave the parameter out or default it to 'None', for now i went or 'None'. It is not really a meaningful parameter as long as Screen() doesn't exist for Python, as it mostly relates to touchscreen input on Linux/X11 + Screen onscreen windows atm.

**Comment by peircej** [comment]
If the number is a number from the operating system then we might be able to make use of it one day, but just fetching global keys is good for now. Thanks for looking into it
