### ISSUE TITLE
How to identify hidden video capture devices?

### ISSUE THREAD

**Issue by nmtimme** [Psychtoolbox-3/Psychtoolbox-3#724]
Hello

I'm interested in using PTB to perform video capture from a FLIR Chameleon 3 camera. It is connected via USB 3 and I am running Windows 10. When I execute Screen(‘VideoCaptureDevices’), the camera is not found. The website (http://psychtoolbox.org/docs/Screen-OpenVideoCapture) explains that this can happen with some devices and it provides information about how to pass information to PTB about hidden devices so video capture can proceed. However, I can't find any information about how to identify the camera. How do I determine the camera's name or ID? I'd appreciate any suggestions on how to do this or if you could point me to the resource that describes this process. I looked around on the website and the github issues, but I couldn't find anything. If I missed it, I'm sorry. Thank you so much for your time and have a good day!

~Nick

**Comment by kleinerm** [comment]
For user questions we have a user forum. If you need further assistance from myself, feel free to follow...
PTB-INFO: For information about paid priority support, community membership and commercial services, please type
PTB-INFO: 'PsychPaidSupportAndServices'.
...to buy 1 hour of paid priority support, as a starter. More if one hour won't be enough.
