### ISSUE TITLE
Packages can not be authenticated from Ubuntu 20.04 repository

### ISSUE THREAD

**Issue by cornicis** [Psychtoolbox-3/Psychtoolbox-3#725]
**[For commercial priority support for bug reports, click this link](http://psychtoolbox.org/prioritysupport.html)

**Describe the bug**
The packages in the Ubuntu repository don't seem to be correctly authenticated

**To Reproduce**
`sudo apt-get install psychtoolbox-3`

produces following output:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'octave-psychtoolbox-3' instead of 'psychtoolbox-3'
The following additional packages will be installed:
  psychtoolbox-3-common
Recommended packages:
  octave-pkg-dev
The following NEW packages will be installed:
  octave-psychtoolbox-3 psychtoolbox-3-common
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 33,6 MB of archives.
After this operation, 679 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  psychtoolbox-3-common octave-psychtoolbox-3
Install these packages without verification? [y/N]
```

**Expected behavior**
Expected would be that no authentication error is raised and I don't need to proceed without verification.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS

**Additional context**
I also tried updating keys and repo with
```
sudo apt-key update
sudo apt-get update
```
but to no awail

**Comment by kleinerm** [comment]
That would be an issue to raise with Ubuntu upstream, as we are not packaging these packages.
