### ISSUE TITLE
Cannot Run Packaged Project because of Screen.mexw64 Not Found

### ISSUE THREAD

**Issue by Chaoyi-1230** [Psychtoolbox-3/Psychtoolbox-3#726]
Greetings!

**Describe the bug**

I was trying to package a project written in Matlab and Psychtoolbox with the Application Compiler of Matlab.

I added the main .m file as normal, the compiler detected all the related file including Screen.mexw64 automatically so I did not do anything before click 'Package'. The compilation did not have errors or exceptions, but the output .exe file in the 'for_testing' directory cannot run. It reported:

'C:\......\mcrCache9.10\test1_2\Psychtoolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Screen.mexw64' Invalid: The specified module could not be found. Error in => test1.m at line 6 (where the "Screen" function was called for the first time in the file.).

The project can run correctly if not packaged.

**Desktop (please complete the following information):**
 - OS: Windows-10 for Home, 10.0.19042
 - Runtime: Matlab 9.10.0.1602886 (R2021a)
 - Hardware: Intel(R) Core(TM) i7-10870H CPU
 - Version: 3.0.17 - Flavor: beta - Corresponds to SVN Revision 12153
 - GStreamer: Typical installed with 'gstreamer-1.0-msvc-x86_64-1.18.1.msi'
 - Nothing else installed.

**Comment by dcnieho** [comment]
That indicates some dependency of ptb was not found on the computer where
you run. See the install instructions,you need both the exactly right
version of gstreamer and an msvc runtime.

**Comment by Chaoyi-1230** [comment]
Thanks for your reply!

Do you mean that the incompatible version of gstreamer and msvc runtime
leads to that the packaged project cannot find the Screen.mexw64? Or do you
mean that some other dependencies were not configured correctly?


Diederick C. Niehorster ***@***.***> 于 2021年7月1日周四 上午12:30写道：

> That indicates some dependency of ptb was not found on the computer where
> you run. See the install instructions,you need both the exactly right
> version of gstreamer and an msvc runtime.
>

**Comment by dcnieho** [comment]
Screen is found but can't be loaded. A vommon reason for that is that the
right dlls can't be found. So make sure you have all it beeds installed. To
be sure, make sure any dll in the ptb folders is also included in your
compiled app, may or may not help.

Note that this standalone use of ptb is not supported by us, so we don't
really know when it works and how to get it to work. Its better to post on
our support forum, where other users may chime in.

**Comment by Chaoyi-1230** [comment]
When I tried to package my project with the whole PTB, I met these two problems: [727](https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/727) and [728](https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/728).

For [727](https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/727), the problem in the code has been kindly solved.

For [728](https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/728), I tried not involving the [GetOctlibDir.m](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/Psychtoolbox/PsychOneliners/GetOctlibDir.m) in the compiler and the packaging was ok. However, the packaged program cannot run still.

For anyone else who wants to package a Matlab+PTB project, you may refer to [this only one potentially useful video](https://www.youtube.com/watch?v=FZWwqFgzO9w&t=612s). I will also keep working on this.

Thanks again for your help! @dcnieho @DavidBrainard
