### ISSUE TITLE
Is GetOctlibDir.m execuable?

### ISSUE THREAD

**Issue by Chaoyi-1230** [Psychtoolbox-3/Psychtoolbox-3#728]
**Describe the bug**
This problem is about the file in [GetOctlibDir.m](https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/Psychtoolbox/PsychOneliners/GetOctlibDir.m)

I opened the file in Matlab R2020b and the first "__" in Line 6 was labeled as an error with message "invalid character(s)" as the screenshot below. I tried running the file and got error message:

```
PsychStartup: Adding path of installed GStreamer runtime to library path. [C:\gstreamer\1.0\msvc_x86_64\bin]
>> GetOctlibDir
Error: File: GetOctlibDir.m Line: 6 Column: 17
Invalid text character. Check for unsupported symbol, invisible character, or pasting of non-ASCII characters.
```

Was it because I did not have Octave installed on my PC? Please kindly let me know the solution.

**To Reproduce**
1. Open the file directly in Matlab R2020b.
2. Run it.

**Screenshots**
![image](https://user-images.githubusercontent.com/70335610/124162987-b1be7080-dad1-11eb-9ee7-7cb403df8fa9.png)

**Comment by dcnieho** [comment]
You should only call this function in Octave, not matlab

**Comment by Chaoyi-1230** [comment]
Got it. @dcnieho Thanks!
