### ISSUE TITLE
Invalid MEX-file

### ISSUE THREAD

**Issue by AilurusStyani** [Psychtoolbox-3/Psychtoolbox-3#731]
Command window pasted as following:
![PTB](https://user-images.githubusercontent.com/23051644/129051936-77a30a80-23aa-49ca-9fd5-5449ed5b599f.png)

I download and reinstalled the GStreamer and PTB several times. I can also confirm the GStreamer install file is 'gstreamer-1.0-msvc-x86_64-1.18.2' which is recommended by `help GStreamer`

> The following GStreamer runtime packages have been tested for good compatibility
  with Psychtoolbox 3.0.17 as of December 2020:
  For MS-Windows: 64-Bit Intel MSVC runtime v1.18.2 for use with 64-Bit Matlab/Octave.
  <https://gstreamer.freedesktop.org/data/pkg/windows/1.18.2/msvc/gstreamer-1.0-msvc-x86_64-1.18.2.msi>

I also tried to copy the file 'icudt61.dll' into 'C:\Windows\System32' but it still cannot work properly. 

- Win10 20H2
- PTB-3.0.17, 
- AMD Ryzen 9 4900H with Radeon Graphics,
- NVIDIA GeForce RTX 3060 Laptop GPU,
- MATLAB R2019a, 
- GStreamer msvc-x86_64-1.18.2

What should I do to make it work? Is it caused by the laptop GPU? Thanks in advance.

**Comment by kleinerm** [comment]
According to both...
https://www.dll4free.com/icudt61.dll.html
and
https://www.mathworks.com/matlabcentral/answers/488651-need-icudt61-dll-when-using-vlfeat-in-matlab-2019a

icudt61.dll is a 32-Bit DLL, so it can't work with a 64-Bit Application like 64-Bit Matlab. To me this looks like a Matlab R2019a
bug, that they would ship a icuuc61.dll which depends on a 32-Bit dll.

Not sure why only some mex files trigger it, or why our current Screen mexw64 file triggers it, given that PTB 3.0.17.0 was intensely tested in on R2019a + Windows 10 + GStreamer 1.18.0 in November 2020.

Maybe upgrade Matlab to a more recent version?
