### ISSUE TITLE
The tutorial page dosen't working 

### ISSUE THREAD

**Issue by JaYoonChoi** [Psychtoolbox-3/Psychtoolbox-3#734]
I tried to go to the tutorial page by searching the domain at google and the matlab homepage. But it doesn't working. 
There is an 404 error. Please check your tutorial homepage. 
And I wonder how long it takes time to restore ?

**Comment by dcnieho** [comment]
What page are you referring to? Whats the address?

**Comment by JaYoonChoi** [comment]
This one. https://peterscarfe.com/ptbtutorials.html

**Comment by kleinerm** [comment]
Whatever it was, it works now, just tested. Closing.
