### ISSUE TITLE
Screen( ) not working 

### ISSUE THREAD

**Issue by bgb2123** [Psychtoolbox-3/Psychtoolbox-3#740]
Hi, 

I downloaded Psychtoolbox on my MacBook Air (Mojave 10.14.3) without an issue but the Screen() command is not working. I'm running it on MATLAB R2020a and I receive the following error: 

Invalid MEX-file '/Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64':
dlopen(/Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64, 6): Symbol not found:
_objc_alloc_init
  Referenced from: /Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64 (which was built for
  Mac OS X 10.15)
  Expected in: /usr/lib/libobjc.A.dylib
 in /Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64

Does anyone know a solution to this issue?

**Comment by kleinerm** [comment]
That shouldn't happen. It could be incompatible with R2020a, but it should still work with 10.11 - 10.14, although i do no longer test for it or guarantee it. If you want me to investigate, get your lab to buy priority support: ``help PsychPaidSupportAndServices``
