### ISSUE TITLE
HP laptop with AMD 5700U had "SYNCHRONIZATION FAILURE" in win10

### ISSUE THREAD

**Issue by Roger1219** [Psychtoolbox-3/Psychtoolbox-3#746]
I am trying to study PTB in Matlab 2018b for neuroscience study. And my main stimuli is about different animation with pricise time interval. 
However, when i try your basic demo(https://peterscarfe.com/insertedCode/TotallyMinimalDemo.html), there is always a warning about "SYNCHRONIZATION FAILURE". I searched this topic and find some tips, including "ScreenTest", "VBLSyncTest" and "Help SyncTrouble". And I checked related settings in my computer, such as "Synchronize bufferswaps to the vertical retrace", "Triple buffering". But they are not work for me.
My  laptop has AMD Ryzen 7 5800U with Radeon Graphics 1.90 GHz, without independent display card. I didn't use multi-display.
Here are the full warning information:

For ScreenTest

> 
> >> ScreenTest
> 
> ***** ScreenTest: Testing Screen 0 *****
> 
> 
> PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.17 - Build date: Apr 13 2021).
> PTB-INFO: OS support status: Windows 10 (Version 10.0) supported and tested to some limited degree.
> PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
> PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
> PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.
> 
> PTB-INFO: For information about paid priority support, community membership and commercial services, please type
> PTB-INFO: 'PsychPaidSupportAndServices'.
> 
> 
> 
> PTB-INFO: OpenGL-Renderer is ATI Technologies Inc. :: AMD Radeon(TM) Graphics :: 4.6.14756 Compatibility Profile Context 20.40.22.06 27.20.14022.6001
> PTB-INFO: VBL startline = 1080 , VBL Endline = 1112
> PTB-INFO: Measured monitor refresh interval from beamposition = 16.652769 ms [60.050072 Hz].
> PTB-INFO: Will use beamposition query for accurate Flip time stamping.
> PTB-INFO: Measured monitor refresh interval from VBLsync = 16.664526 ms [60.007707 Hz]. (50 valid samples taken, stddev=0.755998 ms.)
> PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
> PTB-INFO: Small deviations between reported values are normal and no reason to worry.
> PTB-INFO: ==============================================================================================================================
> PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
> PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
> PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
> PTB-INFO: ==============================================================================================================================
> 
> WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?
> 
> 
> ----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! -----
> 
> One or more internal checks (see Warnings above) indicate that synchronization
> of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.
> 
> This will seriously impair proper stimulus presentation and stimulus presentation timing!
> Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
> You can force Psychtoolbox to continue, despite the severe problems, by adding the command
> Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.
> 
> 
> 错误使用 Screen
> See error message printed above.
> 
> 出错 ScreenTest (line 15)
>     w = Screen('OpenWindow',screen);
>  
> >> 

For VBLSyncTest

> >> VBLSyncTest
> Tried to prepare a new configuration phase via PsychImaging('PrepareConfiguration'), but did not finalize the previous phase yet.
> You must call the PsychImaging('OpenWindow', ...); command at least once to open an onscreen
> window according to the provided settings, before you can specify settings for additional onscreen windows.
> 
> The most likely reason you see this error message is because your script aborted with some error
> before it managed to open the onscreen window. In that case it is best practice to execute a 'clear all'
> command at the Matlab/Octave prompt before you restart your script.
> 
> I will restart configuration now and forget the previously made PsychImaging('AddTask', ...); settings.
> 警告: Tried to prepare a new configuration phase, but you did not finalize the previous phase yet! 
> > In PsychImaging (line 1660)
>   In VBLSyncTest (line 281) 
> 
> ans =
> 
>      0
> 
> 
> 
> PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.17 - Build date: Apr 13 2021).
> PTB-INFO: OS support status: Windows 10 (Version 10.0) supported and tested to some limited degree.
> PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
> PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
> PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.
> 
> PTB-INFO: For information about paid priority support, community membership and commercial services, please type
> PTB-INFO: 'PsychPaidSupportAndServices'.
> 
> 
> 
> PTB-INFO: OpenGL-Renderer is ATI Technologies Inc. :: AMD Radeon(TM) Graphics :: 4.6.14756 Compatibility Profile Context 20.40.22.06 27.20.14022.6001
> PTB-INFO: VBL startline = 1080 , VBL Endline = 1112
> PTB-INFO: Measured monitor refresh interval from beamposition = 16.652822 ms [60.049881 Hz].
> PTB-INFO: Will use beamposition query for accurate Flip time stamping.
> PTB-INFO: Measured monitor refresh interval from VBLsync = 16.635116 ms [60.113798 Hz]. (50 valid samples taken, stddev=0.799572 ms.)
> PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
> PTB-INFO: Small deviations between reported values are normal and no reason to worry.
> PTB-INFO: ==============================================================================================================================
> PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
> PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
> PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
> PTB-INFO: ==============================================================================================================================
> 
> WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?
> 
> 
> ----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! -----
> 
> One or more internal checks (see Warnings above) indicate that synchronization
> of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.
> 
> This will seriously impair proper stimulus presentation and stimulus presentation timing!
> Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
> You can force Psychtoolbox to continue, despite the severe problems, by adding the command
> Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.
> 
> 
> 错误使用 Screen
> See error message printed above.
> 
> 出错 PsychImaging (line 2330)
>             [win, winRect] = Screen('OpenWindow', screenid, clearcolor, winRect, pixelSize, numbuffers, stereomode, multiSample, imagingMode, specialFlags, clientRect, fbOverrideRect, vrrParams);
> 
> 出错 VBLSyncTest (line 295)
>     w = PsychImaging('OpenWindow',screenNumber, 0, [], [], [], stereo);
>  
> >>

**Comment by kleinerm** [comment]
Yes, that looks bad. If vsync is on, triple-buffering is off, freesync / vrr is off/unsupported, your display is not a HiDPI display (1920 x 1080 suggests it is not) and it is a single-display setup with  a single graphics chip, then your probably have everything set up right and this is a graphics driver bug.

I strongly recommend upgrading to Ubuntu Linux for best timing and reliability. AMD gpu's usually have excellent timing and reliability. As this seems to be a rather new machine, it might be a good idea to use the latest Ubuntu 21.10, normally we recommend the lastest stable LTS release, ie. Ubuntu 20.04.3-LTS atm.

For any further support: ``help PsychPaidSupportAndServices`` but upgrading to Linux is the best choice of action.
