### ISSUE TITLE
Is it possible to use PTB to present live videos?

### ISSUE THREAD

**Issue by WeichengLian** [Psychtoolbox-3/Psychtoolbox-3#755]
Dear someone,

Much appreciate your time. I'm now performing an experiment with the hyperscanning method, which would use two cameras to trans video on some specific stage during the experiment. For example, on each trial of the experiment, when both of them receive an electric stimulus, then they can see their partner's live face for 4 seconds. I don't know is it possible to perform such manipulation by PTB? On the user tutorial, it tells PTB could present videos. But how about the live videos?

Much appreciate your help!

Bests.

**Comment by dcnieho** [comment]
It can. PTB can show anything GStreamer can handle. So do some research
into how you can display your video feed with gstreamer, and you're pretty
much there.

**Comment by WeichengLian** [comment]
> 

Thanks for your reply. I'll try to figure some of the functions out of the GStreamer, even though I haven't used it before.

**Comment by kleinerm** [comment]
You usually don't need to know GStreamer itself, that is only needed for very special configurations.

We have various demos for it, e.g., under `help PsychDemos`, usually starting with ``Video...`` in the name. Also some more demos under `PsychDemos/PsychTutorials` and more fancy stuff involving image processing like BlurredMipmapDemo        BlurredVideoCaptureDemo.

A basic test would be ``VideoCaptureDemo``.

However, best support with highest performance, precision etc. for complex scenarios is provided for Linux only. There you have a very high performance/precision capture engine for IIDC compliant Firewire or USB-3 machine vision cameras and the GStreamer based engine for more standard consumer stuff like webcams. On macOS you have GStreamer and limited Firewire support which hasn't been tested in years as all recent Macs don't have firewire anymore. On Windows you only have basic support for stuff supported by GStreamer, e.g., webcams. Often reliability on Windows and macOS is lower or needs tweaking of the demo code.

For further support by myself, ``help PsychPaidSupportAndServices``.

**Comment by WeichengLian** [comment]
> 

Thanks for your clear and detailed reply. I'll take your article as a reference for my research.
Actually, we here often use Windows, which may partly limit the flexibility of codes. But I'll take a try!
Best,
