### ISSUE TITLE
Failed to load hgbuiltins issue

### ISSUE THREAD

**Issue by bsureshkrishna** [Psychtoolbox-3/Psychtoolbox-3#767]
First installation of GStreamer and Psychtoolbox with preexisting vcredist_x64 proceeds smoothly except that libfreetype.dll had to be renamed. 

Windows 11 Home, MATLAB R2022a, Psychtoolbox '3.0.18 - Flavor: beta - Corresponds to SVN Revision 12803, GStreamer 1.18.5 (the tested and recommended version for Windows).

When I restart Matlab, I get this error:

PsychStartup: Adding path of installed GStreamer runtime to library path. [C:\gstreamer\1.0\msvc_x86_64\bin]
Caught "std::exception" Exception message is:
Failed to load bundle #421: C:\Program Files\MATLAB\R2022a\bin\win64\hgbuiltins.dll
Caught "std::exception" Exception message is:
Failed to load bundle #420: C:\Program Files\MATLAB\R2022a\bin\win64\hg.dll
Error occurred during background graphics initialization: Failed to load bundle #420: C:\Program Files\MATLAB\R2022a\bin\win64\hg.dll
 
hgbuiltins.dll exists in that directory, and so does hg.dll

Any suggestions ? Thank you !

**Comment by bsureshkrishna** [comment]
ok, this does not happen when i change the name of libfreetype.dll back to its original.

so it seems that matlab, or rather hgbuiltins.dll and hg.dll expect a libfreetype.dll in its path.

**Comment by kleinerm** [comment]
Tested this on my Windows-10 21H2 system, GStreamer 1.18.5, Matlab R2022a - update 1 on the latest PTB 3,0.18.9.
No problem with either Matlab nor the text renderer, iow. can't reproduce your problem. The freetype dll from Matlab and the one from GStreamer needed by us have different filenames and seem to co-exist happily on my machine, so that's likely not it.

Maybe following the other advice about fontconfig caches helps? Or checking issue #579 or the user forum?

**Comment by dcnieho** [comment]
You say "except that libfreetype.dll had to be renamed", why did it _have_
to be renamed, what happened if you didn't?

**Comment by kleinerm** [comment]
@dcnieho That's one of the troubleshooting tips in help DrawTextPlugin, but seems to be not needed with R2022a.

**Comment by bsureshkrishna** [comment]
Deleting the fontconfig cache solved the problem. Perhaps help DrawTextPlugin can be slightly rewritten to indicate that this could be useful even if one does not see repeated long pauses at each invocation of text drawing. 

Thank you for your accurate, precise and quick advice !
