### ISSUE TITLE
issues with detecting keyboard input

### ISSUE THREAD

**Issue by avamadesousa** [Psychtoolbox-3/Psychtoolbox-3#770]
hi there,

we have an issue with detecting keyboard input. when we launched the experiment, the task didn't respond to the key press but the keyboard input did go into the command line when we exited the program. not sure if it has trouble recognizing the correct keyboard, any thoughts or suggestions on how to fix this would be highly appreciated. 

matlab version: 2022a
ptb version: 9.12.0.1956245 (R2022a) Update 2
os version: Ubuntu 20.04.3 LTS

thanks in advance!

**Comment by dcnieho** [comment]
Please send help requests to our forum instead: https://psychtoolbox.discourse.group/
(also, the PTB version is not the PTB version, thats a matlab version. Use PsychtoolboxVersion in matlab to get that info)
