### ISSUE TITLE
Screen.mexmaci64 does not work. Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#774]
**Describe the bug**
I'm still using macOS 10.13 (high Sierra), and was using an old version of Psychtoolbox.
Today I tried upgrade PTB to the latest version using `UpdatePsychtoolbox`, after it fetched the latest version
> 3.0.18 - Flavor: beta - Corresponds to SVN Revision 12862

The issue occurred. Then I tried re-install from scratch, still not work. Here is the output:
```
A very simple test call to the Screen() MEX file failed in AssertOpenGL, indicating
that either Screen is totally dysfunctional, or you are trying to run your script on
a system without Psychtoolbox-3 properly installed - or not installed at all.

Screen() does not work. Read all preceeding and following output as well as "help AssertOpenGL" for more info.
A first diagnostic test would be to simply type 'Screen' in your Matlab/Octave console and check what its output is.

The returned error message by Matlab/Octave was:
Last Error: MEX file '/Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64' is invalid:
dlopen(/Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Psychtoolbox/PsychBasic/Screen.mexmaci64 (MATLAB:mex:ErrInvalidMEXFile)
    /Applications/Psychtoolbox/PsychOneliners/AssertOpenGL.m,100
    /Applications/Psychtoolbox/PsychtoolboxPostInstallRoutine.m,675
    /Users/user/Downloads/DownloadPsychtoolbox.m,785
```

**To Reproduce**
1. Some apple machine that runs macOS 10.13 (or running inside a virtual machine)
2. Install MATLAB and install PTB3
3. Try `AssertOpenGL`

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Runtime: Matlab R2019b, the latest version that works with macOS 10.13.6
 - Hardware: not related
 - Version: 3.0.18 - Flavor: beta - Corresponds to SVN Revision 12862

**Additional context**
I've tried searching on the web and found that the symbol `____chkstk_darwin` might be introduced in a newer version of macOS. So does Screen really require this symbol to work properly? Or we can re-compile screen such that it is compatible with earlier version of macOS?

**Comment by kleinerm** [comment]
Bummer, but also for a not officially supported macOS version anymore. I only officially support and test for macOS 10.15.7. If you want me to investigate this problem anyway, please post your paid support token for up to 30 minutes of my work time.

-> `'help PsychPaidSupportAndServices`'.

**Comment by suxpert** [comment]
Oh, I understand.
Then I'll roll back to a previous working copy, or try to build against an earlier version of SDK and test if it works.

I'll close this issue then. Thank you.

**Comment by kleinerm** [comment]
Made some changes, might work now with 3.0.18.12 release. If not, I don't care.
