### ISSUE TITLE
Curiosity about the screen coordination in PTB Draw commands

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#780]
Firstly, the questions I'd like to share here might not be viewed as issue, but more like a misunderstanding of *features* or something like that. So, personally, I would like to know the specific logic in PTB, or why it will do things like this.

We know that PTB defines the whole screen (or window) using rectangle like [0, 0, 1920, 1080], since we know that the screen have actually 1920 pixels along the x axis, and 1080 pixels along the y axis, the rectangle *MUST* be half open and half close, i.e., either the starting point 0 do not corresponding to a real pixel, or the ending point 1920/1080 be out of screen.

If we draw the rectangle:
```matlab
Screen('FrameRect', win, [255, 0, 0], [0, 0, 1920, 1080], 1)
```
we can see that the thin frame is at the very edge of the screen, which should be `x=1, x=1920, y=1, y=1080`, if we say the top-left pixel is `(1,1)`.

As a result, if we draw some rectangle that *seem* to be a rectangle:
```matlab
Screen('FrameRect', win, [255, 0, 0], [10, 10, 11, 11], 1)
Screen('FrameRect', win, [255, 0, 0], [10, 10, 12, 12], 1)
```
we'll get one red pixel located at `(11,11)`, 4 pixels as a square respectively. This does not seem intuitive.

If we want to draw the rectangle manually:
```matlab
Screen('FrameRect', win, [255, 0, 0], [10, 10, 20, 20], 1)
Screen('DrawLine', win, [0, 255, 0], 10, 10, 10, 20, 1)
Screen('DrawLine', win, [0, 255, 0], 10, 10, 20, 10, 1)
Screen('DrawLine', win, [0, 255, 0], 20, 10, 20, 20, 1)
Screen('DrawLine', win, [0, 255, 0], 10, 20, 20, 20, 1)
```
we can see that they are not overlapped, the "manually" drawn rectangle *MUST* have additional adjustment to match the location of each side of the rectangle like this:
```matlab
Screen('DrawLine', win, [0, 255, 0], 11, 10, 11, 20, 1)
Screen('DrawLine', win, [0, 255, 0], 10, 11, 20, 11, 1)
Screen('DrawLine', win, [0, 255, 0], 20, 10, 20, 20, 1)
Screen('DrawLine', win, [0, 255, 0], 10, 20, 20, 20, 1)
```
And also, the `DrawLine` command seems to *skip* the top/left point, hence the starting point `(11, 10)` or `(10, 11)` were shown at `(11,11)`.

Then let's try to cut the square into two triangles:
```matlab
Screen('FrameRect', win, [255, 0, 0], [10, 10, 20, 20], 1)
Screen('FramePoly', win, [0 255 0], [10, 10; 10, 20; 20, 10], 1)
Screen('FramePoly', win, [0 255 0], [20, 20; 10, 20; 20, 10], 1)
```
or
```matlab
Screen('FrameRect', win, [255 0 0], [10, 10, 20, 20], 1)
Screen('FramePoly', win, [0 255 0], [10, 10; 10, 20; 20, 20], 1)
Screen('FramePoly', win, [0 255 0], [10, 10; 20, 10; 20, 20], 1)
```
Again, they are not overlapped. And unfortunately, I didn't find any way to adjust the points to make the triangles completely overlap with the rectangle. The best result I can get is:
```matlab
Screen('FrameRect', win, [255 0 0], [10, 10, 20, 20], 1)
Screen('FramePoly', win, [0 255 0], [11, 11; 11, 20; 20, 11], 1)
Screen('FramePoly', win, [0 255 0], [20, 20; 11, 20; 20, 11], 1)
```
which makes the second triangle smaller, but still have the top-left pixel missed. Or
```Matlab
Screen('FrameRect', win, [255 0 0], [10, 10, 20, 20], 1)
Screen('FramePoly', win, [0 255 0], [11, 11; 10, 20; 20, 10], 1)
Screen('FramePoly', win, [0 255 0], [20, 20; 10, 20; 20, 10], 1)
```
which does not seem to have sides parallel to x/y axis according to the coordinates, and still have the top-left pixel missed.

So, **can anybody explain about the screen coordinate system in PTB, and the logic of screen draw command?** Why are they so counterintuitive?

----
P.S.,
I've also tried to treat the coordinates as the boundaries between pixels, but also failed in understanding the logic, and the *symmetry axis* along lines with different width do not support this explanation.

**Comment by dcnieho** [comment]
Please post this on the discourse forum instead

**Comment by dcnieho** [comment]
Also, make sure to provide details of OS, graphics card and driver version, it may affect this
