### ISSUE TITLE
PsychToolbox failed to load DrawText Plugin

### ISSUE THREAD

**Issue by fly-xcf** [Psychtoolbox-3/Psychtoolbox-3#781]
I use a Windows system. After I installed the latest version of the plugin for GStreamer, I set the path to the plugin in Matlab. Then I went to the PsychToolbox website and downloaded the latest version of PsychToolbox package and unzipped it, "Something went wrong with high-quality text renderer setup.Read 'Help DrawTextPlugin' for PsychToolbox Troubleshooting. "After I've read everything in' Help DrawTextPlugin' and have resolved the problems mentioned in' Troubleshooting. 'It still" Failed to Load DrawTextPlugin."

![image](https://user-images.githubusercontent.com/75713626/184411849-c479b3b7-0a54-4cfe-a597-a72b05b077e7.png)

**Comment by dcnieho** [comment]
You shouldn't install the latest gstreamer, but the exact right version.
See help gstreamer
