### ISSUE TITLE
Error using ==> Screen Usage: textureIndex=Screen('MakeTexture',

### ISSUE THREAD

**Issue by ldaumail** [Psychtoolbox-3/Psychtoolbox-3#782]
**[For commercial support for bug reports, click this link](https://www.psychtoolbox.net/license-key)

**Describe the bug**
Hello, 
I am currently trying to run a visual task with Psychtoolbox (3.0.10 - Flavor: Psychtoolbox-3.0.10 - Corresponds to SVN Revision 4037)

In this task I have to create a lot of different 2D frames of sinusoidal gratings in order to make it "drift" on the screen.  For this, I use Screen 'MakeTexture'. I make all the different frames ahead of time before launching the task, so I can make sure the timing is right. 

The task works perfectly well. 

However, when I add the code I need to initialize my eye tracking system (Eyelink 1000) using the code "EyelinkSetup(0)"; , I get the error:

"
??? Error using ==> Screen
Usage:

textureIndex=Screen('MakeTexture', WindowIndex, imageMatrix [, optimizeForDrawAngle=0] [,
specialFlags=0] [, floatprecision=0] [, textureOrientation=0] [, textureShader=0]);

Error in ==> LD_fillingin_RSVP_hor_vert_V4 at 240
        tmptopWaveID(f,o) = Screen('MakeTexture', w, squeeze(exp.topWave(f,:,:,o)));
"
Is this a texture overload issue? 
I only draw the textures later on when my task is launched... and I do use "Screen('Close', exp.bottomWaveID(n+1,ori));"
This seems more like an interaction issue with the Eyelink code...?

**Desktop (please complete the following information):**
 - OS: Mac OS X version 10.6.8 [e.g. Ubuntu Linux 20.04.1 LTS, macOS 10.15.7, Windows-10 (20H2)]
 - Runtime: Matlab 7.9.0 2009 b 
 - Hardware: 2x2.8 GHz Quad Core Intel Xeon [e.g., AMD Radeon Pro W4100, Onboard sound chip]
 - Version:  3.0.10 - Flavor: Psychtoolbox-3.0.10 - Corresponds to SVN Revision 4037
Any help would be much appreciated!
Thanks,

**Comment by dcnieho** [comment]
Please post on the forum instead of github for support. That said, this is
likely not am overload issue. See the command window, above that usage
message is probably more info about the error

**Comment by kleinerm** [comment]
Psychtoolbox 3.0.10 is end-of-life and unsupported since many years, as is OSX 10.6. Also, EyelinkSetup is not a Psychtoolbox or Eyelinktoolbox command, but some own code of yours, which seems to be broken.

Closing as invalid.
