### ISSUE TITLE
How can I fix this error in the text?

### ISSUE THREAD

**Issue by Sameul182** [Psychtoolbox-3/Psychtoolbox-3#784]
How can I fix this error in the text?
It is cut off at the top of the line of text

**To Reproduce**

         Screen('TextSize', window, 30)
        DrawFormattedText(window, 'Se presentará una secuencia de\n\n adiciones y sustracciones con resultado.\n\n\n\n Por ejemplo:  2+?=3  o  ?-2=5 \n\n\n\n Cuando sepas la respuesta de cada operación, \n\n deberás decir en VOZ ALTA el resultado \n\n\nProcura no corregir tu respuesta',...
            'center', 'center', white);
        Screen('Flip', window);
        KbStrokeWait;

![20220915_195124](https://user-images.githubusercontent.com/113647231/190533640-f42b43e6-cc11-4cbc-8ce2-fe27852c60e6.jpg)
![20220915_195131](https://user-images.githubusercontent.com/113647231/190533644-4f8f2d63-e845-43b2-a120-9655f47e5ee9.jpg)

**Comment by dcnieho** [comment]
Post support requests on the forum, not here. that said, googling )or reading error messages) would've helped you: https://psychtoolbox.discourse.group/t/persistent-clipping-with-drawformattedtext/4578/1
