### ISSUE TITLE
Simplify download process

### ISSUE THREAD

**Issue by mirh** [Psychtoolbox-3/Psychtoolbox-3#787]
Aka drop (somewhat mandatory to install outside of matlab) subversion. 
I see why that could provide some small benefit over a normal download, as seen in *UpdatePsychtoolbox* (you once download twice as much data than strictly needed, but then the next version will be about half in size to fetch)

But AFAICT there's no essential usage of that in *DownloadPsychtoolbox*, given you seem to be always working with whole checkouts
(and specific revision/branch handling could be approximated for http downloads with just a few extra lines)
Of course if you dispense with versioning in this step, then you loose its possible advantages for those afterwards.. but I think the average joe (and [sometimes](https://savannah.gnu.org/bugs/index.php?63265#comment12) even way more than that) is probably more bothered by extra dependencies than saving bandwidth. 

And so IMHO, you should:
- [ ] switch `downloadmethod==1` to just use the built-in urlwrite/unzip functions (or something along that)
- [ ] have `isempty(downloadmethod)` fallback to that if no svn client is found (or have it be the default, if predictability is totally sacred)

**Comment by kleinerm** [comment]
That's what `SetupPsychtoolbox` is for, and all this is explained in our Downloads section of our webpage. Closing.

**Comment by mirh** [comment]
*SetupPsychtoolbox* defers the task of downloading the PTB copy to something/somebody else (and rightly so? I suppose that targets offline systems where you would not have any other choice). 
I'm talking about an improvement for *DownloadPsychtoolbox*. 
Not that it's in any way critical or even anywhere important (it's mostly a light nuisance on "pure" systems wanting to use octave), but simply put it seems a pointless complication.
