### ISSUE TITLE
Erratic reporting of key presses by KbCheck;

### ISSUE THREAD

**Issue by bradleygreger** [Psychtoolbox-3/Psychtoolbox-3#790]
When calling KbCheck (Windows 10, Matlab 2022b) pressing the left-Shift key randomly returns keyCode 16 (Shift) or keyCode 160 (LeftShift).

Pressing the right-Shift key returns keyCode 16 (Shift) or keyCode 161 (RightShift).
The right-Ctrl and left-Ctrl keys exhibit similar behavior.

Output from calling KbCheck while pressing left-Shift, right-Shift, right-Ctrl and left-Ctrl 10 times each:

You pressed key 160 which is LeftShift
You pressed key 160 which is LeftShift
You pressed key 16 which is Shift
You pressed key 16 which is Shift
You pressed key 16 which is Shift
You pressed key 160 which is LeftShift
You pressed key 160 which is LeftShift
You pressed key 160 which is LeftShift
You pressed key 16 which is Shift
You pressed key 16 which is Shift

You pressed key 16 which is Shift
You pressed key 16 which is Shift
You pressed key 16 which is Shift
You pressed key 161 which is RightShift
You pressed key 161 which is RightShift
You pressed key 16 which is Shift
You pressed key 16 which is Shift
You pressed key 16 which is Shift
You pressed key 161 which is RightShift
You pressed key 16 which is Shift

You pressed key 162 which is LeftControl
You pressed key 17 which is control
You pressed key 17 which is control
You pressed key 17 which is control
You pressed key 162 which is LeftControl
You pressed key 162 which is LeftControl
You pressed key 162 which is LeftControl
You pressed key 17 which is control
You pressed key 17 which is control
You pressed key 162 which is LeftControl

You pressed key 163 which is RightControl
You pressed key 163 which is RightControl
You pressed key 17 which is control
You pressed key 163 which is RightControl
You pressed key 163 which is RightControl
You pressed key 17 which is control
You pressed key 17 which is control
You pressed key 163 which is RightControl
You pressed key 17 which is control
You pressed key 163 which is RightControl

**Comment by kleinerm** [comment]
Peculiar! Please provide your paid support authentication token, so I can spend up to 30 minutes of time looking into this.
[`help PsychPaidSupportAndServices`. Also see this link for more information about our current christmas sale and survey: ](https://psychtoolbox.discourse.group/t/get-support-memberships-for-99-euros-tax-only-limited-offer/4712)

**Comment by kleinerm** [comment]
Closing, as user doesn't care.
