### ISSUE TITLE
Just want to make sure the improper settings can be skipped

### ISSUE THREAD

**Issue by CHIAANsGitHub** [Psychtoolbox-3/Psychtoolbox-3#791]
Dear all,

I'm new to here trying to use psychtollbox under matlab to design simple VR HMD experiments. Before I start the implement, I' ve read documents on the website and want to get it more clear about the system requirements:

I would like use windows, andaccording to what I read from the website, better use win10 because it seems win11 might not be supported yet.
Then, initially I would tyr to run a HTC vive pro2 HMD, but it is the same situation that it is likely a uncertainly support to run with PsychVRHMD.

I'm so sorry for my immature issues. Thanks for any help!

**Comment by dcnieho** [comment]
please post your question on https://psychtoolbox.discourse.group/, this
place is for bugs.
Also, I did not see a question in your message, so when you post there,
please improve it and people know what to help you with.
