### ISSUE TITLE
Poor Windows sync precision analysis and solutions 

### ISSUE THREAD

**Issue by mirh** [Psychtoolbox-3/Psychtoolbox-3#793]
After nearly two months of stupid registry "tweaks", disabling software and services from my laptop, adjusting whatever timers resolution, bothering people to let me test their PC and purposefully trying to slow down my desktop.. I think I have finally nailed down why refresh rate variability can suck so much on many Windows devices. 
The problem is [C-states](https://metebalci.com/blog/a-minimum-complete-tutorial-of-cpu-power-management-c-states-and-p-states/#c-states). 

This can explain why laptops are more affected (OEMs even disable some if they know battery anxiety won't ever be a concern), this is why results can be so flaky and all over the place, and above all this is why legend says the first run tends to be luckier than the others (being closer to the start of the main application, which may temporarily bias the CPU into a higher power state). 

| Deepest available | VBLsync stdev |
| ------------- | ------------- |
| C0        | 0.01-0.05 ms |
| C1        | 0.01-0.05 ms |
| C1E      | 0.06-0.10 ms |
| C7 (PKG off) | 0.13 ms |
| C7        | 0.16-0.19 ms |
| C8        | 0.19-0.23 ms |

I collected these numbers from both a 6600K (where I could manually control individual states from the firmware) and my 6500U (which I could spend the most time with, and where the problem was first and most noticeable).
Of course they are more of a baseline and many other [hardware](https://www.mouser.com/pdfdocs/desktop-6th-gen-core-family-spec-update.pdf#page=48) [and](https://github.com/torvalds/linux/commit/d7ef76717322c8e2df7d4360b33faa9466cb1a0d) [software](https://maxedtech.com/the-case-of-dpc-latency/) factors could compound them (indeed this last benchmarking run that I'm reporting isn't as consistent as some of the best ones I had), but to be sure when you have a 20x difference with just the toggle of a single bit you do know you have a big culprit. 

The effect doesn't seem to be as prominent when you use a dedicated gpu (well, provided that's where the currently in-use monitor is connected to begin with), but forcing C1 could still save a few ms even on my 2080 to reliably enter single-digits-microsecond territory. 

---
So, what could PTB do then?
Well.. not much AFAICT (besides the obvious telling the user the whole story, and to check their BIOS for relevant settings).
Windows doesn't have any application-specific interface like PM QoS, and even after looking for interesting strings inside intelppm.sys and the registry I couldn't *really* spot anything to suggest they are aware of CPU states existing for anything more than power-saving purposes. There are [also](https://web.archive.org/web/20060610221015/http://216.55.183.13/pdc2005/slides/FUN319_Stemen_Miller.ppt) [certain](https://web.archive.org/web/20101106145838/http://software.intel.com/en-us/blogs/2007/12/09/how-to-write-energy-efficient-apps/) "idle spoiling" techniques but their precise effectiveness is dubious. 
(and sure.. there is MMCSS, but as we know that's more about priority with respect to other processes, rather than power management per se - even though they did [actually expand](https://learn.microsoft.com/en-us/windows-hardware/customize/power-settings/configure-processor-power-management-options#quality-of-service) some of its capabilities as of lately, which I didn't test because it would have required actual programming).

The only userspace half-way "specific" method to influence them that I know is using power plans (and for as much as uncouth such a global solution may sound, their access and manipulation by individual programs is somewhat officially [precedented](https://learn.microsoft.com/en-us/previous-versions/windows/hardware/design/dn613884(v=vs.85))). 
And the good news for once is that it would even be [fairly](https://stackoverflow.com/a/9721763/5994170) easy to code in. 
After XP there's like a thousand and one caveats to ponder with its implementation though.

Setting IDLEDISABLE is actually the pinnacle of performance over power concerns, and by always forcing C0 it would even be able to address the "C1E problem" (i.e. the OS is completely clueless about it, and the absolute only way to disable it is through a [MSR](https://www.intel.com/content/dam/develop/external/us/en/documents/335592-sdm-vol-4.pdf#page=283)). But the other side of the coin is that, duh, indeed you'll always be using C0 for the entire run of the script. 
I guess it would be nice to have as a last resort optional override for when researchers are banging their heads against the gods of computer latency, but I'm squirming at the thought of some poor undergrad running even the most computationally simple visual experiment in a dark room to isolate the subject.. and then their old pentium 4 has the fan spinning like a jet turbine because it's stuck at [maximum](https://www.researchgate.net/figure/C-states-available-on-the-Intel-Skylake-server-SKX-core-7-together-with-AWs-new-C6A_tbl1_359080452) usage. 
Adjusting IDLESTATEMAX would then be the second best thing, except it doesn't work at all in my testing ([allegedly](https://social.msdn.microsoft.com/forums/windowshardware/en-US/39534389-a249-444d-9791-5d39bf68a2e5/disabling-cpu-idle-cstates-lowers-cpu-clock-frequency?forum=wdk) it was broken with W10 1803, though I couldn't countercheck).
But thankfully, last but not least, it was found that having both IDLEPROMOTE and IDLEDEMOTE set to 100 could still achieve the result of locking you to C1(E). This cheap workaround isn't going to guarantee any record number, but at least an average of 100 usec is enough to comfortably pass the sync tests the great majority of times (as opposed to almost never when my laptop was running out of the box). 

Though once a dedicated power plan is created (either from scratch, or by duplicating some of the hidden presets that are shipped with the OS) I wouldn't be sure on the best course of action. Should it be a "permanent" thing (meaning that it will stick even after we quit, also appearing in the Windows control panel) or should we delete it every time?

**Comment by dcnieho** [comment]
Would software like throttlestop give you the required control?

**Comment by mirh** [comment]
Yes. 
That's actually what turned me in the right direction, and what I spent like 30% of the time experimenting with. 
Getting down to ~C1 (and for that locking "Package C states" is not enough, you need the dedicated "C states AC: off" option that essentially adjusts the power plan in the ways I just explained above), and then also disabling C1E is the only way I can get my laptop to truly shine. 

Alas I don't think you could be expected to tinker with privileged cpu registers yourself (even though I guess there are many tools with such capabilities, that supports scripting)... and so everything else in my post is what remains.

**Comment by mirh** [comment]
Ok, so.. you may or may not have noticed some edits I did in the last days. 
Even after grasping at straws to find ifs and buts, what I wrote above still looks quite good and fitting for my CPU. 
Unfortunately it just came to me that of course not everybody is going to be into the same situation. 
And so complexity continues to pile up more and more, if you want to do everything with the utmost care.

First, 50% higher C1E times have been observed in certain odd/old/cheap Atom/Celeron/Pentium SoCs. That's still not enough to ruin the game, but the margin becomes very thin (fun fact: conversely the very latest *Cores* have basically made it a non-issue). 
And if you are short on manpower and time, I guess you could still be excused to put such marginal concern in the backburner.. but then the elephant in the room hit me. 

What about AMD?
There's offensively way less documentation on the matter, and they are quite [different](https://link.springer.com/article/10.1007/s00450-014-0270-z) architecturally (and that would be key when you suspect the poor results are caused more by power gating creeping into other parts of the package to affect the integrated display controller, rather than the cpu cores themselves being lethargic).
But the [potential](https://d-nb.info/1144299985/34#page=67) for even worse latency (if more stochastic) is there, and in a very hasty and unreliable test with a 4700U laptop I managed to score I was getting like the worst results I have ever seen. 
I'd still expect IDLEDISABLE to be able to get around any possible shortcoming now, but for the same reasons I still feel like that cannot be considered a solution (and in fact even C1 may [already](https://arxiv.org/pdf/2108.00808.pdf#page=7) be excessive power-wise). 

So micro-management may go from a handy quality of life feature, to a necessity... But I'm speculating here. 
(though it would also really help people with OEM computer with a bios too crippled to have C-states control exposed).
Something external like Throttlestop may still hold water for enterprise-managed (read: admin-restricted) systems that cannot be expected to give you much access once deployed, but otherwise I think the bother of having to manually adjust settings every time you want to switch between "experiment" and "daily" modes could justify having instead something built-in.

**Comment by kleinerm** [comment]
@mirh Any test results with the new mex files?

**Comment by kleinerm** [comment]
Improvement in v3.0.19.4, closing.
