### ISSUE TITLE
How to change PSYCH_MAX_MOVIES?

### ISSUE THREAD

**Issue by FelixAntonSchneider** [Psychtoolbox-3/Psychtoolbox-3#794]
Hi,

I try to run a stimulus composed of about 300 small movie snippets. When I try to present them I run into the following error:

`Error in function OpenMovie: Usage error
Allowed maximum number of simultaneously open movies exceeded!`

I tracked this down to the PSYCH_MAX_MOVIES Variable which is defined in PsychSourceGL/Source/Common/Screen/PsychMovieSupportGStreamer.c
Since it is a C-file, I guess it is not possible to edit this variable without recompiling the code?

I was wondering whether it would be possible to just compile this single file with mex and leave everything else untouched?

What is the simplest way to solve this?

Thanks for any help!

**Comment by kleinerm** [comment]
- Increasing PSYCH_MAX_MOVIES would only be possible with a full recompile of the Screen mex file.
- Also, using so many open movies in parallel could cause large performance degradation, each open movie needs memory, lots of parallel GStreamer threads, and possibly hw video decode resources.

I assume you are doing something in a wrong or highly suboptimal way. `help PsychPaidSupportAndServices` for paid further advice on this issue. Up to 30 minutes of my time, our special 99 Euro + tax christmas discount is still available.

**Comment by kleinerm** [comment]
On the off-chance you just want to play many small movies in sequence, look at the ``PlayMoviesWithoutGap....Demo.m`` demos. End of free advice.

**Comment by kleinerm** [comment]
Closing, user doesn't care.
