### ISSUE TITLE
ERROR     Support for the `sounddevice` audio backend is not available this session. Please install `psychopy-sounddevice` and restart the session to enable support.

### ISSUE THREAD

**Issue by romasiugzdaite** [Psychtoolbox-3/Psychtoolbox-3#806]
hi, 

we are trying to run EEG experiment with word repetition. it repeats one time only... the error is the following that we cant go around.

ERROR     Support for the `sounddevice` audio backend is not available this session. Please install `psychopy-sounddevice` and restart the session to enable support.

we installed it, but the error is the same.

any advice will be very helpful.

**Comment by dcnieho** [comment]
This seems to be a question regarding psychopy functionality, please direct
your query to the psychopy forums.
