### ISSUE TITLE
Psychtoolbox compatibility with Magic toolbox

### ISSUE THREAD

**Issue by Stefanatuurlijk** [Psychtoolbox-3/Psychtoolbox-3#812]
Hi all,

I am having some issues regarding the compatibility with the Psychtoolbox. I am currently trying to set up an experiment where a visual stimulus is presented to the subject, whereafter a particular time a TMS train of pulses needs to be given. I first wrote two separate scripts for the Magic Toolbox and the Psychtoolbox, and those work wonderfully, but when I combine the two the TMS gets disconnected from my PC. I know this because the TMS gets disarmed when I open a screen using the Psychtoolbox, but Matlab thinks it is still connected and armed. Is there something hidden in the code that overwrites the communication with the TMS device that I don't know of and is there something I can do to prevent this disconnection while using the Psychtoolbox and make it so that I can trigger the TMS during the visual stimuli? the TMS disconnects the moment I run the code below, after setting up the parameters earlier.

[window, windowRect] = PsychImaging('OpenWindow', screenNumber, white, [startXpix startYpix startXpix + dimX startYpix + dimY]);

Kind Regards,
Stefan.

**Comment by kleinerm** [comment]
Don't know what the Magic toolbox is, and generally there is insufficient info here, but can't see how PTB opening a window could interfere with a connection to a TMS stimulator unless it is somehow connected to the video output of the graphics card? `help PsychPaidSupportAndServices' for paid advice.

**Comment by Stefanatuurlijk** [comment]
Hi All, 

I have as of now solve the issue, It was not the screens flipping but the 'waitsecs' function that disconnected the TMS from matlab, by using the matlab 'pause' function I was able to resolve the issue. 

Best

**Comment by kleinerm** [comment]
For reference: https://github.com/nigelrogasch/MAGIC/issues/18

Weird that a proper wait on a thread on Windows would cause a serial port to disconnect. I see this toolbox uses Matlabs deprecated `serial()` function for serial i/o, probably a limitation of that function. Might be worth switching to Psychtoolbox `IOPort()` function which is optimized for neuroscience use cases and also has been found to have better timing / lower latency, e.g., for trigger emission.
