### ISSUE TITLE
`DrawFormattedText` with `sx = 0` (default) doesn't respect left `winRect` bound

### ISSUE THREAD

**Issue by SVNKoch** [Psychtoolbox-3/Psychtoolbox-3#817]
**Describe the bug**
When drawing formatted text inside an offset rect, its left bound is not respected.
for right aligned text the right bound is respected.

**To Reproduce**
take a look at this minimal, reproducible example:
[reproduce.m.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/12810246/reproduce.m.txt) (extension changed to .txt because of GitHub limitation)

**Expected behavior**
text should be correcty placed inside given rect when text is "left aligned" (`sx = 0`)

**Screenshots**
`DrawFormattedText` with `sx = 0` and a grey `winRect` offset to the right:
![0](https://github.com/Psychtoolbox-3/Psychtoolbox-3/assets/39488412/8ee99384-22fb-41f1-ab61-641cb7e26f72)
`DrawFormattedText` with `sx = 'right'` and a grey `winRect` offset to the left:
![right](https://github.com/Psychtoolbox-3/Psychtoolbox-3/assets/39488412/651b3d19-2306-4ce2-b2ee-0f84c72e64e4)

**Desktop (please complete the following information):**
 - OS: Windows-10 (21H2)
 - Runtime: Matlab R2023a
 - Version: 3.0.19 - Flavor: beta - Corresponds to SVN Revision 13692

**Comment by dcnieho** [comment]
I see that you already found it was not implemented functionality, and have implemented it in #818. Thanks!
Also have a look at DrawFormattedText2, which does support this, but is (probably) slower due to more extensive processing
