### ISSUE TITLE
`KbCheck(-3)` misses ~10ms-long keypress events from fMRI set up on Ubuntu 22.04

### ISSUE THREAD

**Issue by aalok-sathe** [Psychtoolbox-3/Psychtoolbox-3#828]
**[For commercial support for bug reports, click this link](https://www.psychtoolbox.net/license-key)**

**Describe the bug**
With ~75% probability, a while-loop using `KbCheck(-3)` fails to recognize a roughly ~10ms-long keypress trigger sent by a [Current Designs 932](https://www.curdes.com/fiu-932b.html). In an event-related fMRI design, this means we are 1 TR off from the experiment script's logs of when the events occurred. We're trying to nail down why this is happening. We don't seem to recall this happening on 2014 Matlab running on MacOS on our previous scanning set up, and this isn't as significant of a problem for block design studies, but for event-related design our modeling would be thrown off. What's worse is this happens stochastically, and we don't know why.

Here's the snippet:
```matlab
% Define keys
KbName('UnifyKeyNames');
ESCAPE_KEY = KbName('ESCAPE');
TRIGGER_KEY = [KbName('=+'),KbName('+')];

%% GET TRIGGER FROM SCANNER
fprintf('\n------------- WAITING FOR TRIGGER\n');
while 1
    [keyIsDown, seconds, keyCode] = KbCheck(-3);
    if keyCode(ESCAPE_KEY)
        Screen('CloseAll');
        error('Experiment quit by pressing ESCAPE\n');
        break;
    elseif ismember(find(keyCode,1),TRIGGER_KEY) %keyCode(KbName(TRIGGER_KEY))
        % After the trigger, get the onset of this run
        run_start_time = GetSecs;
        break
    end
end

fprintf('\n------------- TRIGGERED! STARTING RUN! Run onset %f\n', run_start_time)
```

**To Reproduce**
1. Run while-loop and wait for trigger
2. Observe the light on Current Devices 932 interface box when trigger is sent
3. Observe if script triggers at the exact same time, or at the next trigger (in our case, 1 TR = 2000ms later)

**Expected behavior**
Trigger at each pulse sent by the Current Devices 932 interface box.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3
 - Runtime: Matlab R2021b
 - Graphics: renoir
 - Hardware: AMD Ryzen 7 pro 4750u with radeon graphics; ThinkPad T14s Gen 1
 - Version: Psychtoolbox 3.0.18

cc: @gretatuckute

**Comment by dcnieho** [comment]
I'd say not a bug. Use the KbQueue functions instead. The pulse is too
short, you may simply sometimes poll just before and just after the pulse,
thus missing it.

**Comment by aalok-sathe** [comment]
I see it on the GitHub at https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/master/Psychtoolbox/PsychDocumentation/KbQueue.html
but not on the main documentation. I see there's `KbQueueCheck`, which is probably what you were pointing us to? 
http://psychtoolbox.org/docs/KbQueueCheck
Thanks!

**Comment by kleinerm** [comment]
Not a bug, in my judgement. KbCheck(-3) is inefficient, e.g., on my Ubuntu 20.04.6-LTS this will lead to a for loop inside KbCheck, KbCheck'ing 8 keyboards, some real, some virtual, some other things, which could slow things down quite a bit, and that posted code is also not efficient.

Ideally you'd pass in the deviceIndex of the fORP device to only check that, or maybe one KbCheck for that and then another one for the operator keyboard. Or better and made for this stuff, if you can do without checking the ops keyboard ESCAPE key, `KbTriggerWait`. Downside is no easy abort key and not timeout - The script will freeze until a proper trigger is received, but simple code and high precision. There are various other ways using keyboard queues and, e.g., KbEventGet with suitable timeouts to interleave high precision waiting with occasional KbChecks for an ESCAPE key, but this is about as much as I can tell you without use of the paid support.

**Comment by aalok-sathe** [comment]
RLVPMPD5-202422211549:ffc155968d623c15fae4966b834fb0dab4185239407f6a631e003e73482fa685

**Comment by aalok-sathe** [comment]
Thank you! 
Here's our key: `RLVPMPD5-202422211549:ffc155968d623c15fae4966b834fb0dab4185239407f6a631e003e73482fa685`

**Comment by kleinerm** [comment]
Your license has run out almost a year ago, so there isn't any support entitlement based on it anymore, but I'll give you a few minutes of time out of goodwill.

So first you need the device indices of your fORP and of your regular keyboard. Then you use a KbQueue for highest precision wait for triggers from the fORP, with precise timestamp, and can use conventional KbCheck to check for ESCAPE key press on the experimenter keyboard, interrupting the wait for triggers once every second to check the experimenter keyboard.

If you would not care about the ability to interrupt the trigger wait via ESCAPE key, you could simply use

`run_start_time = KbTriggerWait(TRIGGER_KEY, forpIdx);` with forpIdx from steps 1 + 2 below. Convenient and simple and accurate. Downside is you can't break out of KbTriggerWait without receiving a trigger from the fORP.

Otherwise, the following does the trick with high precision:

1. [a,b] = GetKeyboardIndices() to find the name string (in returned vector `b`) of your fORP. Assuming it is, e.g., called 'forp932'.
2. `forpIdx = GetKeyboardIndices('forp932');
3. `RestrictKeysForKbCheck(ESCAPE_KEY); % Only accept ESCAPE key for regular KbCheck`
4. `keys = zeros(1,256);`
5. `keys(TRIGGER_KEY) = 1;`
6. `KbQueueCreate(forpIdx, keys);`
7. `KbQueueStart(forpIdx);`
8. `timeoutSecs = 1; % Interrupt trigger wait every 1 second to KbCheck for ESCAPE key instead.`


````
    % While KbCheck does not register ESCAPE_KEY to trigger abort:
    evt = [];
    while ~KbCheck && isempty(evt)
        % Wait up to timeoutSecs seconds for a new trigger event:
        evt = KbEventGet(forpIdx, timeoutSecs);
    end

    if isempt(evt)
        % evt is [] ie. no trigger received, but KbCheck registered ESCAPE key.
        % END experiment code
    else
        % Trigger received, evt contains info about it - Record trigger timestamp:
        run_start_time = evt.Time;
        % Remove all pending events from queue:
        KbEventFlush(forpIdx);
        .... experiment code ...
    end
````

At the end of experiment, shutdown keyboard queue for triggers, reenable all keys for KbCheck:
`KbQueueRelease(forpIdx); `RestrictKeysForKbCheck([]);`

If you read `help KbQueueWait` you'll see yet another way to do a timed wait for key presses / trigger keys on a forp, e.g.,
``run_start_time = KbQueueWait(forpIdx, 0, GetSecs + 1);`` would also do the trick of waiting for trigger with 1 second timeout.

This should work on Linux and macOS, where the regular keyboard and fORP etc. can be distinguished by their forpIdx etc. On Windows this would also work, but could not differentiate between a '+' sent by the fORP trigger mechanism, or a + pressed on the experimenter keyboard, so a bit more fragile due to MS-Windows limitations.

Hope it helps.

**Comment by aalok-sathe** [comment]
> Your license has run out almost a year ago, so there isn't any support entitlement based on it anymore, but I'll give you a few minutes of time out of goodwill.

@kleinerm thank you very much for your response. Unfortunately we tried several times to renew it without luck due to various errors such as:
![](https://i.imgur.com/QGOGPxo.png). We tried multiple cards from different payment networks and Paypal.

In the meantime we did come up with an implementation of our own, and I'll reply in-line to compare it with your proposed solution above, to see the similarities and dissimilarities.
 
> So first you need the device indices of your fORP and of your regular keyboard. Then you use a KbQueue for highest precision wait for triggers from the fORP, with precise timestamp, and can use conventional KbCheck to check for ESCAPE key press on the experimenter keyboard, interrupting the wait for triggers once every second to check the experimenter keyboard.
>
> If you would not care about the ability to interrupt the trigger wait via ESCAPE key, you could simply use
> 
> `run_start_time = KbTriggerWait(TRIGGER_KEY, forpIdx);` with forpIdx from steps 1 + 2 below. Convenient and simple and accurate. Downside is you can't break out of KbTriggerWait without receiving a trigger from the fORP.


Our implementation:
```matlab
function dev_idx = find_device(target)
    arguments
        target = 'Current Designs';
    end

    dev_idx = -1;
    % device class '4' corresponds to keyboards
    devs = PsychHID('Devices', 4);
    
    for idx = 1:length(devs)
        prod = devs(idx).product;
        dev_idx_ = devs(idx).index;
        fprintf('\nproduct: %s; index: %d\n', prod, dev_idx_);
        
        if contains(prod, target)
            dev_idx = dev_idx_;
            % break;
        end
    end
end
```


> Otherwise, the following does the trick with high precision:
> 
> 1. [a,b] = GetKeyboardIndices() to find the name string (in returned vector `b`) of your fORP. Assuming it is, e.g., called 'forp932'.
> 2. `forpIdx = GetKeyboardIndices('forp932');
> 3. `RestrictKeysForKbCheck(ESCAPE_KEY); % Only accept ESCAPE key for regular KbCheck`
> 4. `keys = zeros(1,256);`
> 5. `keys(TRIGGER_KEY) = 1;`
> 6. `KbQueueCreate(forpIdx, keys);`
> 7. `KbQueueStart(forpIdx);`

We have overlap in this section of your proposed solution from nos. 4-7. We also create a `KbQueue` using pre-specified trigger keys. Here's our code:

```matlab
function run_start_time = wait_for_trigger_kbqueue(wait_dur)
  arguments
        wait_dur = 100
  end
  
  KbName('UnifyKeyNames')

  fprintf('--------- CALLED `wait_for_trigger_kbqueue`\n')

  % 'keyList' is an optional 256-length vector of doubles (not logicals)  
  %  with each element corresponding to a particular key (use [KbName](KbName)  
  %  to map between keys and their positions). If the double value  
  %  corresponding to a particular key is zero, events for that key  
  %  are not added to the queue and will not be reported.
  % see also: https://github.com/caomw/Psychtoolbox-3/blob/master/Psychtoolbox/PsychBasic/KbTriggerWait.m
  keyList = zeros(1, 256, 'double');
  keyList(KbName('=+')) = 1.0;
  keyList(KbName('+')) = 1.0;
  keyList(KbName('Escape')) = 1.0;
  
  dvc = find_device;

  KbQueueCreate(dvc, keyList);
  KbQueueStart(dvc);
  KbQueueFlush(dvc);

  % docs say to wait a little time before starting to record events so we don't miss any during initialization
  WaitSecs(double(wait_dur) / 1000.0);
  
  % http://psychtoolbox.org/docs/KbQueueWait
  run_start_time = KbQueueWait(dvc);
  
end
```


> 8. `timeoutSecs = 1; % Interrupt trigger wait every 1 second to KbCheck for ESCAPE key instead.`
> 
> ```
>     % While KbCheck does not register ESCAPE_KEY to trigger abort:
>     evt = [];
>     while ~KbCheck && isempty(evt)
>         % Wait up to timeoutSecs seconds for a new trigger event:
>         evt = KbEventGet(forpIdx, timeoutSecs);
>     end
> 
>     if isempty(evt)
>         % evt is [] ie. no trigger received, but KbCheck registered ESCAPE key.
>         % END experiment code
>     else
>         % Trigger received, evt contains info about it - Record trigger timestamp:
>         run_start_time = evt.Time;
>         % Remove all pending events from queue:
>         KbEventFlush(forpIdx);
>         .... experiment code ...
>     end
> ```

This is where we diverge, and where I'm confused: does this not add potentially 1 second of latency to the trigger pulse? Or is the `KbEventGet` routine non-blocking and will monitor in the background events for up to 1 second but terminate if no events are found during that 1 second? And if it does find events, they will get added to the queue async and the `while ~KbCheck && isempty(evt)` will catch them anyway? I just want to make sure of what the latencies are here.
Your code checks for an ESC key whereas ours doesn't. It would be nice, but I'm trying to understand the rest of it before using it.

> 
> At the end of experiment, shutdown keyboard queue for triggers, reenable all keys for KbCheck: `KbQueueRelease(forpIdx); `RestrictKeysForKbCheck([]);`
> 

Good tip! Maybe we should add this in.

> If you read `help KbQueueWait` you'll see yet another way to do a timed wait for key presses / trigger keys on a forp, e.g., `run_start_time = KbQueueWait(forpIdx, 0, GetSecs + 1);` would also do the trick of waiting for trigger with 1 second timeout.
> 

Again I don't understand what the timeout is for.

> This should work on Linux and macOS, where the regular keyboard and fORP etc. can be distinguished by their forpIdx etc. On Windows this would also work, but could not differentiate between a '+' sent by the fORP trigger mechanism, or a + pressed on the experimenter keyboard, so a bit more fragile due to MS-Windows limitations.
> 
> Hope it helps.

Thanks, very helpful.
cc: @gretatuckute @selenashe

**Comment by aalok-sathe** [comment]
p.s. `KbTriggerWait.m` diverges also from what you've mentioned above: https://github.com/Psychtoolbox-3/Psychtoolbox-3/pull/829 (that file is also last edited 9 years ago, so not sure if that has already been fixed elsewhere).

**Comment by aalok-sathe** [comment]
All makes sense, thanks a ton!
