### ISSUE TITLE
PsychImaging (line 2470)             [win, winRect] = Screen('OpenWindow', screenid, clearcolor, winRect, pixelSize, numbuffers, stereomode, multiSample, imagingMode, specialFlags, clientRect, fbOverrideRect, vrrParams);

### ISSUE THREAD

**Issue by yayahoho555** [Psychtoolbox-3/Psychtoolbox-3#833]
PTB-WARNING: Created onscreen window on screenid 2 will probably not be able to use GPU pageflipping for
PTB-WARNING: Screen('Flip')! May cause tearing artifacts and unreliable or wrong visual stimulus onset timestamping!
PTB-WARNING: Could not bind wglChoosePixelFormat - Extension. Some features will be unavailable, e.g., Anti-Aliasing and high precision framebuffers.
PTB-WARNING: Created onscreen window on screenid 2 will probably not be able to use GPU pageflipping for
PTB-WARNING: Screen('Flip')! May cause tearing artifacts and unreliable or wrong visual stimulus onset timestamping!
PTB-WARNING: Your graphics driver doesn't allow me to control if bufferswaps should be synchronized to the vertical retrace!
PTB-WARNING: This can cause massive stimulus timing problems, failure of the sync tests and calibrations and severe visual tearing artifacts!
PTB-WARNING: Please update your display graphics driver as soon as possible to fix this and make sure this functionality is not disabled in
PTB-WARNING: the display settings control panel of your graphics card.
PTB-WARNING: If everything else fails, you can usually manually enable synchronization to vertical retrace somewhere in the display settings
PTB-WARNING: control panel of your machine.

PTB-WARNING: Seems that Microsofts OpenGL software renderer is active! This will likely cause miserable
PTB-WARNING: performance, lack of functionality and severe timing and synchronization problems.
PTB-WARNING: Most likely you do not have native OpenGL vendor supplied drivers (ICD's) for your graphics hardware
PTB-WARNING: installed on your system.Many Windows machines (and especially Windows Vista) come without these preinstalled.
PTB-WARNING: Go to the webpage of your computer vendor or directly to the webpage of NVidia/AMD/ATI/3DLabs/Intel
PTB-WARNING: and make sure that you've download and install their latest driver for your graphics card.
PTB-WARNING: Other causes, after you've ruled out the above:
PTB-WARNING: Maybe you run at a too high display resolution, or the system is running out of ressources for some other reason.
PTB-WARNING: Another reason could be that you disabled hardware acceleration in the display settings panel: Make sure that
PTB-WARNING: in Display settings panel -> Settings -> Advanced -> Troubleshoot -> The hardware acceleration slider is
PTB-WARNING: set to 'Full' (rightmost position).

PTB-WARNING: Actually, it is pointless to continue with the software renderer, as that will cause more trouble than good.
PTB-WARNING: I will abort now. Read the troubleshooting tips above to fix the problem. You can override this if you add the following
PTB-WARNING: command: Screen('Preference', 'ConserveVRAM', 64); to get a functional, but close to useless window up and running

**Comment by yayahoho555** [comment]
> This is not a bug, please use the forum for support requests

User
错误使用 Screen
See error message printed above.

出错 PsychImaging (line 2470)
            [win, winRect] = Screen('OpenWindow', screenid, clearcolor, winRect, pixelSize, numbuffers, stereomode, multiSample, imagingMode, specialFlags, clientRect, fbOverrideRect, vrrParams);

出错 Untitled (line 7)
[window, ~] = PsychImaging('OpenWindow', screenNumber, 0);

**Comment by dcnieho** [comment]
https://psychtoolbox.discourse.group/
