### ISSUE TITLE
Error using screen

### ISSUE THREAD

**Issue by ghazalt93** [Psychtoolbox-3/Psychtoolbox-3#834]
Hello,

I meet almost the same message as the one others described when I try to run Demos on macOS:

and here are the error messages :

DrawSomeTextDemo
PTB-WARNING: This is a Apple silicon based ARM M1 SoC or later with Apple proprietary gpu.
PTB-WARNING: All of Psychtoolbox own timing and timestamping mechanisms will not work on
PTB-WARNING: such a machine, leading to disastrously bad visual stimulus presentation timing
PTB-WARNING: and timestamping. Do not trust or use this machine if timing is of any concern!
PTB-WARNING: You may want to try enabling Psychtoolbox Vulkan display backend, after proper
PTB-WARNING: configuration. See 'help PsychImaging' the section about the 'UseVulkanDisplay'
PTB-WARNING: task, and 'help PsychHDR' for some more setup instructions for MoltenVK on macOS.
PTB-WARNING: Note that this approach is completely unsupported by us in case of any problems, and
PTB-WARNING: may just be as bad performance and timing-wise. It is completely untested on M1.
PTB-WARNING: A simple test case would be running SimpleHDRDemo. If it wouldn't flood the command
PTB-WARNING: window with error and warning messages, that would be mildly encouraging. Let us know.

PTB-INFO: Retina display. Enabling panel fitter for scaled Retina compatibility mode.

PTB-INFO: This is Psychtoolbox-3 for Apple macOS, under Matlab 64-Bit (Version 3.0.19 - Build date: Dec 16 2023).
PTB-INFO: OS support status: macOS version 14 ARM M1+ SoC is not yet tested or supported at all for this Psychtoolbox release..
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: For information about paid support, support memberships and other commercial services, please type
PTB-INFO: 'PsychPaidSupportAndServices'.

PTB-INFO: Using Cocoa + No display capture / compositor lockout for fullscreen window. Timing will be disastrous.
PTB-INFO: Installation of the PsychtoolboxKernelDriver is strongly recommended if you care about precise visual
PTB-INFO: onset timestamping or timing. See 'help PsychtoolboxKernelDriver' for installation instructions.
PTB-WARNING: Couldn't even collect one single valid flip interval sample! Sanity range checks failed!
PTB-WARNING: Could be a system bug, or a temporary timing problem. Retrying the procedure might help if
PTB-WARNING: the latter is the culprit.

WARNING: VBL Calibration run No. 1 failed. Retrying...

PTB-INFO: OpenGL-Renderer is Apple :: Apple M1 Pro :: 2.1 Metal - 88
PTB-INFO: Renderer has 10922 MB of VRAM and a maximum 10922 MB of texture memory.
PTB-INFO: VBL startline = 2234 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback.
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 7.080458 ms [141.233794 Hz]. (5 valid samples taken, stddev=0.272855 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 8.333333 ms [120.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.

WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

WARNING: Mismatch between measured monitor refresh interval and interval reported by operating system.
This indicates massive problems with VBL sync.

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! -----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

Error using DrawSomeTextDemo (line 21)
Error using Screen
See error message printed above.

What do you suggest ?
( my system info. : MacBookPro 2021 16 inch: macOS Sonoma 14.2.1 (23C71))

Thanks a lot

**Comment by kleinerm** [comment]
What a surprise. It's not supported yet on Apple Silicon. News about Apple Silicon in a few days:

https://psychtoolbox.discourse.group/t/vss-2024-satellite-on-psychophysics-software-with-matlab-next-monday/5352
