### ISSUE TITLE
Compilation issues in PyPsychToolbox break import (Apple M1, Conda environment)

### ISSUE THREAD

**Issue by berkgercek** [Psychtoolbox-3/Psychtoolbox-3#836]
**Describe the bug**
This error occurs on MacOS 14.4.1, and while I know this is an unsupported distribution I'm writing a bug report in case future support for the platform is planned. I'd like to be able to at least test scripts on this platform before running in production on Windows.

Upon first install of Psychtoolbox via `pip install psychtoolbox` attempting to import the package results in an import error stemming from a failed call to `dlopen` for a C extension:

```
In [1]: import psychtoolbox as ptb
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 1
----> 1 import psychtoolbox as ptb

File ~/mambaforge/envs/intermod/lib/python3.10/site-packages/psychtoolbox/__init__.py:28
     26 from .WaitSecs import WaitSecs
     27 from .GetSecs import GetSecs
---> 28 from .PsychHID import PsychHID
     29 from .IOPort import IOPort
     30 if is_64bits:

ImportError: dlopen(/Users/MYUSER/mambaforge/envs/intermod/lib/python3.10/site-packages/psychtoolbox/PsychHID.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_AllocateHIDObjectFromIOHIDDeviceRef'
```

I've tried omitting the various imports in the `__init__.py` and found that this error only occurs on `PsychHID` and `PsychPortAudio`. `GetSecs` and `WaitSecs` are not affected.

**To Reproduce**
Using MacOS 14 (M1 silicon) and conda as an environment manager:

1. Generate a fresh environment `conda create -n psychtest python=3.10`
2. Install Psychtoolbox `pip install psychtoolbox`
3. Attempt to import psychtoolbox in a python process via `import psychtoolbox as ptb`

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1
 - Runtime: Python 3.10 via conda forge
 - Hardware: Apple M1 Max
 - Version 3.0.19.10

**Comment by kleinerm** [comment]
It's not supported yet on Apple Silicon. News about Apple Silicon in a few days:

https://psychtoolbox.discourse.group/t/vss-2024-satellite-on-psychophysics-software-with-matlab-next-monday/5352
