### ISSUE TITLE
Integration with game engines like Unreal

### ISSUE THREAD

**Issue by fspinar** [Psychtoolbox-3/Psychtoolbox-3#837]
Hi all,

I have been looking for ways to use game building tools like Unreal, Unity, etc. to build experiments. I recently found out that it was indeed possible to use Unreal through Matlab: https://www.mathworks.com/help/sl3d/create-3d-simulation-in-unreal-engine-environment.html

I wonder if it would be possible to use engines like this in Psychtoolbox to create game-like experiments. Is this possible already, or are there any efforts for this? I feel like this could potentially be a really valuable feature.

Thanks a lot,
Fatih

**Comment by kleinerm** [comment]
Answered on forum, closing:
https://psychtoolbox.discourse.group/t/using-game-engines-unity-unreal-etc-with-psychtoolbox/5357/3
