### ISSUE TITLE
SetMouseHelper Bug

### ISSUE THREAD

**Issue by ALevitsky23** [Psychtoolbox-3/Psychtoolbox-3#842]
**Describe the bug**
We are running a two-laptop experiment where the "control" laptop (Windows 11 Enterprise) is running Matlab (2023b), while the "stimulus" computer is connected to a Medoc Pathway heat stimulator. We have been trying to complete a 100-trial run of the experiment, but it has aborted twice thus far- once on the 35th trial, and then again on the 25th. Both times, it has thrown a SetCursorPos() error:

```
Error in SetMouse (line 92)
Screen('SetMouseHelper', windowPtrOrScreenNumber, round(x), round(y), mouseid, detachFromMouse);

…

INTERNAL PSYCHTOOLBOX ERROR
	error:                PsychError_internal
	general description:  Unspecified error, probably a Psychtoolbox bug
	specific description: Couldn't position the mouse cursor! (SetCursorPos() failed).
	module name:          Screen
	subfunction call:     SetMouseHelper
	file name:            C:\Users\Mario Kleiner\Documents\GitHub\Psychtoolbox-3\PsychSourceGL\Source\Windows\Screen\PsychScreenGlue.c
	function name:        PsychPositionCursor
	line number:          1142
```

This is similar to the problem that dcnieho ran into here (https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/650), but this is not due to a Linux-specific stretch of code like that one was.

**Expected behavior**
The error occurred during the rating period of our script- where we display a 0-10 numerical scale with a red cursor on the number 5 in the middle of the screen. Subjects use the keyboard to control the cursor and input numerical responses to questions that we ask them. The cursor moves on the rating scale in discrete steps- to 4 from 5 if you press down, to 6 from 5 if you press up, etc. After 8 seconds, the screen flips and we save the last location of the cursor as the response.

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise for control laptop, Microsoft XP Professional (2002) for the stimulus laptop
 - Runtime: Matlab R2023b, Medoc Main Station 6.4.0.26.12
 - Hardware: Laptops connected via ethernet, stimulus computer using Medoc Pathway system
 - Version: Psychtoolbox 3.0.19.11

Please let me know if there is any other information that I can provide.

**Comment by dcnieho** [comment]
If the rating scale is controlled by the keyboard, why are you calling `SetMouse` at all?
And to be clear, the failing code is running on the Windows 11 laptop, right?

**Comment by ALevitsky23** [comment]
Hi Diederick,

That is an excellent point. This is a script I inherited from a previous version of the experiment, so I assumed that it was necessary for the placement of the red cursor. I commented it out and not only did the rating screen work without issue, but the script ran its course without any errors. Thank you very much!

-Andrew
