### ISSUE TITLE
win11 unbale to display movie

### ISSUE THREAD

**Issue by chongyangat** [Psychtoolbox-3/Psychtoolbox-3#844]
**[For commercial support for bug reports, click this link](https://www.psychtoolbox.net/license-key)**

**Describe the bug**
**psychtoolbox was successfully installed and it could display the image. But it could display the movie, the display window crashed with out error report. Below is the output log:**
PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.19 - Build date: Dec 14 2023).
PTB-INFO: OS support status: Windows 11 (Version 11.0) is not supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: For information about paid support, support memberships and other commercial services, please type
PTB-INFO: 'PsychPaidSupportAndServices'.

PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2 :: 4.6.0 NVIDIA 536.40
PTB-INFO: VBL startline = 1440 , VBL Endline = 1439
PTB-INFO: Measured monitor refresh interval from beamposition = 16.678784 ms [59.956410 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.679802 ms [59.952750 Hz]. (50 valid samples taken, stddev=0.087971 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.949153 ms [59.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: Support for OpenGL 3D graphics rendering enabled: depth-buffer and stencil buffer attached.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================

WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 1).
WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11 (23H2)]
 - Runtime: [ Matlab R2022b]
 - Hardware [13th Gen Intel(R) Core(TM) i7-13700F  NVIDIA GeForce RTX 4060 Ti]
 - Version [Psychtoolbox 3.0.19.13]

**Additional context**

**Comment by iandol** [comment]
You need to provide the sample code and an example video (how are you loading video, what format is it), and more log information with an actual error to better understand what your issue is...

**Comment by chongyangat** [comment]
**below is my sample code,this code was designed to display a movie**
% Clear the workspace
clear;
close all;
sca;

% Here we call some default settings for setting up Psychtoolbox
PsychDefaultSetup(2);

%--------------------------------------------------------------------------
%                       Screen initialisation
%--------------------------------------------------------------------------

% Find the screen to use for displaying the stimuli. By using "max" this
% will display on an external monitor if one is connected.
screenid = max(Screen('Screens'));

% Determine the values of black and white
black = BlackIndex(screenid);
white = WhiteIndex(screenid);

% Set up our screen
[window, windowRect] = PsychImaging('OpenWindow', screenid, black, [], 32, 2);

% Get the vertical refresh rate of the monitor
ifi = Screen('GetFlipInterval', window);

% Get the width and height of the window in pixels
[screenXpix, screenYpix] = Screen('WindowSize', window);

% Determine the center of the screen. We will need this later when we draw
% our dots.
[center(1), center(2)] = RectCenter(windowRect);

% Queries the display size in mm as reported by the operating system. Note
% that there are some complexities here. See Screen DisplaySize? for
% information. So always measure your screen size directly. We just use the
% reported value for the purposes of this demo.
[widthMM, heightMM] = Screen('DisplaySize', screenid);

% We assume some screen dimensions here so that the stimulus will fit
% nicely on the screen. Obviously this means that the dimensions we state
% here will only be correct if you screen happens to be the same size.
screenYcm = heightMM / 10;
screenXcm = widthMM / 10;
pixPerCm = mean([screenXpix / screenXcm screenYpix/ screenYcm]);

% Set the blend function so that we get nice antialised edges to the dots
% defining our cyliner
Screen('BlendFunction', window, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);


%--------------------------------------------------------------------------
%                   Stimulus information
%--------------------------------------------------------------------------

% Cylinder height, width and radius
cylHeight = 14;
cylHalfHeight = cylHeight / 2;
cylWidth = 4;
cylRadius = cylWidth / 2;

% Numer of dots to place over the surface of the cylinder
numDots = 250;

% Dot track centres over the height of the cylinder
ypos = (rand(1, numDots) .* 2 - 1) .* cylHalfHeight .* pixPerCm;

% Randomly assign the dots angles. This determines their X position on the
% screen. We are using ortographic projection, so the dots do not have a Z
% position.
angles = rand(1, numDots) .* 360;

% Set the dot size in pixels
dotSizePixels = 7;

% We will update the stimulus on each frame
waitframes = 1;

% Get a flip to sync our timing
vbl = Screen(window, 'Flip');


%--------------------------------------------------------------------------
%                           Drawing Loop
%--------------------------------------------------------------------------

% Stimulus drawing loop (exits when any button is pressed)
while ~KbCheck

    % Calculate the X screen position of the dots (note we have to convert
    % from degrees to radians here.
    xpos = cos(angles .* (pi / 180)) * cylWidth.* pixPerCm;

    % Draw the dots. Here we set them to white, determine the point at
    % which the dots are drawn relative to, in this case our screen center.
    % And set anti-aliasing to 1. This gives use smooth dots. If you use 0
    % instead you will get squares. And if you use 2 you will get nicer
    % anti-aliasing of the dots.
    Screen('DrawDots', window, [xpos; ypos], dotSizePixels, white, center, 1);

    % Flip to the screen
    vbl = Screen('Flip', window, vbl + (waitframes - 0.5) * ifi);

    % Increment the angle of the dots by one degree per frame
    angles = angles + 1;

end

% Clean up and leave the building
sca;

**Comment by chongyangat** [comment]
PTB-INFO: Automatic startup test of beamposition queries couldn't detect any beamposition problems on your system,
PTB-INFO: but by setting the special flag Screen('Preference', 'ConserveVRAM', 4096); somewhere in your script,
PTB-INFO: you requested that the workaround for beamposition problems is always unconditionally enabled.
PTB-INFO: Therefore i will enable the work-around: This should satisfy the timing needs of most applications, ie.
PTB-INFO: robust and jitter-free deterministic timestamps. However, all reported timestamps may have a
PTB-INFO: constant offset of up to the duration of the vertical blanking interval (max 1 msec worst case)
PTB-INFO: of your display. Read 'help BeampositionQueries' on how you can remove that bias by some manual
PTB-INFO: intervention, should you need that last bit of accuracy. A second drawback is increased cpu load,
PTB-INFO: which may cause louder air-fan noise due to heat production and lower battery runtime of laptops.


PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.19 - Build date: Dec 14 2023).
PTB-INFO: OS support status: Windows 11 (Version 11.0) is not supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: For information about paid support, support memberships and other commercial services, please type
PTB-INFO: 'PsychPaidSupportAndServices'.

PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.


PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2 :: 4.6.0 NVIDIA 536.40
PTB-INFO: VBL startline = 1440 , VBL Endline = 1439
PTB-INFO: Measured monitor refresh interval from beamposition = 16.679737 ms [59.952985 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.670736 ms [59.985354 Hz]. (50 valid samples taken, stddev=0.142146 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.949153 ms [59.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: Support for OpenGL 3D graphics rendering enabled: depth-buffer and stencil buffer attached.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================


WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 1).
WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.

**Comment by iandol** [comment]
Yes, you are using Windows and an NVidia GPU which ensures a poor timing control. Your code works perfectly on Linux+AMD6800:

```
PTB-INFO: OpenGL-Renderer is AMD :: AMD Radeon RX 6800 (navi21, LLVM 15.0.7, DRM 3.57, 6.5.0-44-generic) :: 4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
PTB-INFO: VBL startline = 1080 , VBL Endline = -1
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.668382 ms [59.993827 Hz]. (50 valid samples taken, stddev=0.000536 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
```

Note my VBLSync standard deviation `0.000536 ms` is 400X smaller than yours for the same code. The temporary solution is provided by the PTB error:

> Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

The better solution is dual-boot Linux and exchange your NVidia GPU for an AMD or even Intel GPU to use for your experiments.

**Comment by chongyangat** [comment]
That sounds terrible. I have to prepare another computer because Iots of softwares was already installed in this computer. Besides, are you going to develop new version of PTB based on cuda support?

**Comment by iandol** [comment]
You can dual-boot easily, no need to lose any system or use a second computer. All my lab computers have Ubuntu 22.04 and Windows (though we never use Windows unless sftware depends on it). Blame Nvidia and Microsoft for this, they do not fix timing bugs as they mostly care about gaming and max FPS not reliability or fidelity (which are critical for Neuroscience experiments).

I am not a PTB developer but CUDA is not relevant for PTB, which uses graphics APIs (OpenGL and parially Vulkan) not compute APIs (like CUDA or ROCm).

**Comment by qx1147** [comment]
I wouldn't jump to conclusions yet. A VBLSync standard deviation of 0.2ms is still good and no indication of severe problems in that department. The confusing PTB messages left aside, which don't really fit the sample code (which doesn't seem to modify beamposition preferences or alike, as suggested by the PTB output), what should this sample code have to do with a movie not being played? I assume the sample code still runs on your machine (despite PTB warnings), so what's needed is the code (and video) that crashes PTB.

**Comment by chongyangat** [comment]
> I wouldn't jump to conclusions yet. A VBLSync standard deviation of 0.2ms is still good and no indication of severe problems in that department. The confusing PTB messages left aside, which don't really fit the sample code (which doesn't seem to modify beamposition preferences or alike, as suggested by the PTB output), what should this sample code have to do with a movie not being played? I assume the sample code still runs on your machine (despite PTB warnings), so what's needed is the code (and video) that crashes PTB.

I don't what you mean since I provide the code. this code was intended to display a movie. maybe iandol is right, i should try linux + AMD card

**Comment by iandol** [comment]
After the OP posted the drawdots example explicitly, and his screenshot is just showing the sync warning at startup, I assumed he is translating "Video" to mean "animation".

@chongyangat -- did you try to add `Screen('Preference', 'SkipSyncTests', 1)` to the start of your script? Do you see the dot animation?

**Comment by qx1147** [comment]
Google-translate, I guess. I have a different understanding of "movie" and "crash" then.

**Comment by chongyangat** [comment]
yes, I think it is better to use animation instead of movie.
I have tried to add Screen('Preference', 'SkipSyncTests', 1) to the start,  the warning is gone but no animation is displayed.
below is the output dialog
```
>> SFMD

ans =

     1

PTB-INFO: Automatic startup test of beamposition queries couldn't detect any beamposition problems on your system,
PTB-INFO: but by setting the special flag Screen('Preference', 'ConserveVRAM', 4096); somewhere in your script,
PTB-INFO: you requested that the workaround for beamposition problems is always unconditionally enabled.
PTB-INFO: Therefore i will enable the work-around: This should satisfy the timing needs of most applications, ie.
PTB-INFO: robust and jitter-free deterministic timestamps. However, all reported timestamps may have a
PTB-INFO: constant offset of up to the duration of the vertical blanking interval (max 1 msec worst case)
PTB-INFO: of your display. Read 'help BeampositionQueries' on how you can remove that bias by some manual
PTB-INFO: intervention, should you need that last bit of accuracy. A second drawback is increased cpu load,
PTB-INFO: which may cause louder air-fan noise due to heat production and lower battery runtime of laptops.


PTB-INFO: This is Psychtoolbox-3 for Microsoft Windows, under Matlab 64-Bit (Version 3.0.19 - Build date: Dec 14 2023).
PTB-INFO: OS support status: Windows 11 (Version 11.0) is not supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: For information about paid support, support memberships and other commercial services, please type
PTB-INFO: 'PsychPaidSupportAndServices'.


PTB-WARNING: Couldn't determine end-line of vertical blanking interval for your display! Trouble with beamposition queries?!?
PTB-WARNING: Detected end-line is 1438, which is either lower or more than 1.250000 times higher than vbl startline 1440 --> Out of sane range!


PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2 :: 4.6.0 NVIDIA 536.40
PTB-INFO: VBL startline = 1440 , VBL Endline = 1438
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback.
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.675826 ms [59.967045 Hz]. (50 valid samples taken, stddev=0.193830 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.949153 ms [59.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-INFO: Support for OpenGL 3D graphics rendering enabled: depth-buffer and stencil buffer attached.
PTB-INFO: ==============================================================================================================================
PTB-INFO: WINDOWS DWM DESKTOP COMPOSITOR IS ACTIVE. On this Windows-10 or later system, Psychtoolbox can no longer reliably detect if
PTB-INFO: this will cause trouble for timing and integrity of visual stimuli or not. You might be just fine, or you could be in trouble.
PTB-INFO: Use external measurement equipment and independent procedures to verify reliability of timing if you care about proper timing.
PTB-INFO: ==============================================================================================================================


----- ! PTB - WARNING: SYNCHRONIZATION TROUBLE ! -----

One or more internal checks (see Warnings above) indicate that
queries of rasterbeam position are not properly working for your setup.

Psychtoolbox will work around this by using a different timing algorithm, 
but it will cause Screen('Flip') to report less accurate/robust timestamps
for stimulus timing.
Read 'help BeampositionQueries' for more info and troubleshooting tips.




WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 1).
WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.
```

**Comment by chongyangat** [comment]
dual-boot is not a good choice. I have to use other softwares on this computer, like unity3D, motion capture software(commercial version)

**Comment by dcnieho** [comment]
I do not understand the problem. There is no error in any of the logs you
post, no indication that running of the code was in some way interrupted.
What exactly happens instead of "no animation is displayed"?

**Comment by chongyangat** [comment]
https://github.com/user-attachments/assets/faaae3e2-8337-47c3-ad88-99b6ab4daf87

It seems that the problem I encountered is not common, I added a recorded video

**Comment by chongyangat** [comment]
As you see in this video, no animation was displayed as i expected.

**Comment by iandol** [comment]
Right this is unexpected, normally if PTB window crashes you get feedback. Can you also add:

`Screen('Preference','Verbosity',10)` to the top of the script and see you you get any log info that looks like it can explain this silent window closure. What happens with other PTB demos (like `SimpleMovieDemo` or `GratingDemo`)?

**Comment by chongyangat** [comment]
Very strange, i tried another demo and it worked:[Draw Image Demo](https://peterscarfe.com/drawImage.html)

https://github.com/user-attachments/assets/5bbff0a7-78aa-4ec1-b727-bfb7fcc8b65b

I add` Screen('Preference','Verbosity',10)` to the top and post the log on the dialog
[debug.txt](https://github.com/user-attachments/files/16389721/debug.txt)

**Comment by chongyangat** [comment]
that really hurts
```
WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?

----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! -----

One or more internal checks (see Warnings above) indicate that synchronization
of Psychtoolbox to the vertical retrace (VBL) is not working on your setup.

This will seriously impair proper stimulus presentation and stimulus presentation timing!
Please read 'help SyncTrouble' for information about how to solve or work-around the problem.
You can force Psychtoolbox to continue, despite the severe problems, by adding the command
Screen('Preference', 'SkipSyncTests', 1); at the top of your script, if you really know what you are doing.

```

**Comment by iandol** [comment]
`SYNCHRONIZATION FAILURE` is common on Windows/NVidia systems -- you can see the VBL samples go from 0.0155ms to 0.0178ms (the std dev seems low at 0.2ms but the min and max are significant, nearly 2ms range as measured). You can ignore these warnings completely with `Screen('Preference', 'SkipSyncTests', 2)`. But that is not what is causing the silent crash. You need to edit your script until the line that causes the crash. 

Can you try to edit this line:

```
PsychImaging('OpenWindow', screenid, [0 0 0])
```

...maybe specifying the pixelSize (the 32) triggers some sort problem for your GPU etc.

**Comment by dcnieho** [comment]
Looking at your code, i guess KbCheck just returns something immediately so
we break out of the while loop immediately and nothing is drawn.
can you replace while ~KbCheck with something else, e.g. loop for 2 seconds
or x frames, to see if it works then?

**Comment by chongyangat** [comment]
> Looking at your code, i guess KbCheck just returns something immediately so we break out of the while loop immediately and nothing is drawn. can you replace while ~KbCheck with something else, e.g. loop for 2 seconds or x frames, to see if it works then?
> […](#)
> Message ID: ***@***.*** com>

I guess you are right. I executed the code in the debug mode and i found that KbCheck=1, which means it skipped the loop. Then I comment out the `while loop`, the dot pattern was successfully draw in my screen. Could you please explain the reason why KbCheck could be different value in different computer?

**Comment by chongyangat** [comment]
> `SYNCHRONIZATION FAILURE` is common on Windows/NVidia systems -- you can see the VBL samples go from 0.0155ms to 0.0178ms (the std dev seems low at 0.2ms but the min and max are significant, nearly 2ms range as measured). You can ignore these warnings completely with `Screen('Preference', 'SkipSyncTests', 2)`. But that is not what is causing the silent crash. You need to edit your script until the line that causes the crash.
> 
> Can you try to edit this line:
> 
> ```
> [window, windowRect] = PsychImaging('OpenWindow', screenid, [0 0 0])
> ```
> 
> ...maybe specifying the pixelSize (the 32) triggers some sort problem for your GPU etc.

many thanks for your warm responds, but i found the reason is the `KbCheck vaule`. It equal to 1 on my computer which means it skipped to execute the code in the `while loop`. I don't know why it happens in this way. Maybe win11 + nvidia could still run psychtoolbox with some modifications on the code. btw, how should i modify my code to realize the similar animation demonstrated on your computer?

**Comment by chongyangat** [comment]
KbCheck is the keyboard input. Is it means the psychtoolbox has no responds to my keyboard? I don't know what wrong with the interaction between keyboard and psychtoolbox since I could type normally using my keyboard.

**Comment by dcnieho** [comment]
See the help of KbCheck:

  Some users of Laptops experienced the problem of "stuck keys": Some keys
  are always reported as "down", so KbWait returns immediately and KbCheck
  always reports keyIsDown == 1. This is often due to special function keys.
  These keys or system functionality are assigned vendor specific
  key codes, e.g., the status of the Laptop lid (opened/closed) could be
  reported by some special keycode. Whenever the Laptop lid is open, this
key
  will be reported as pressed. You can work around this problem by passing
  a list of keycodes to be ignored by KbCheck and KbWait. See
  "help DisableKeysForKbCheck" on how to do this.

Even if this isn't a laptop (I'm not sure what you have), that may be it.

**Comment by chongyangat** [comment]
I am not using laptop. The desktop computer is **ideacentre geekpro-17irb**.
 Other configurations are as follows:
13th Gen Intel(R) Core(TM) i7-13700F   2.10 GHz
RAM:16.0 GB 
win11
nvidia 4060Ti

**Comment by dcnieho** [comment]
try those instructions anyway

**Comment by chongyangat** [comment]
here is the output 
 ```
olddisabledkeys = DisableKeysForKbCheck([disablekeys])
 
  Specify a vector of keycodes for keys which should be
  ignored by KbCheck and KbWait. This is useful to
  disable specific keys, e.g., if they are stuck. The function
  returns the old set of disabled keys.
 
  Example: To disable the keys with keycodes 4, 6 and 7, do
  DisableKeysForKbCheck([4, 6, 7]);
 
  Caution: This setting is reset to "empty" during a "clear all" command!
 
  Background info:
 
  Some users of Laptops experienced the problem of "stuck keys": Some keys
  are always reported as "down", so KbWait returns immediately and KbCheck
  always reports keyIsDown == 1. This is often due to special function keys.
  These keys or system functionality are assigned vendor specific
  key codes, e.g., the status of the Laptop lid (opened/closed) could be
  reported by some special keycode. Whenever the Laptop lid is open, this key
  will be reported as pressed. You can work around this problem by passing
  a list of keycodes to be ignored by KbCheck and KbWait.
  _________________________________________________________________________
  
```

**Comment by chongyangat** [comment]
One more question, how should I use `olddisabledkeys = DisableKeysForKbCheck([disablekeys])` in the code above? could you please teach me how to modify the code so that it could perform the same function. I am an entry-level user of psychtoolbox

**Comment by chongyangat** [comment]
it works!
```
% Stimulus drawing loop (exits when any button is pressed)
while true

    % Calculate the X screen position of the dots (note we have to convert
    % from degrees to radians here.
    xpos = cos(angles .* (pi / 180)) * cylWidth.* pixPerCm;

    % Draw the dots. Here we set them to white, determine the point at
    % which the dots are drawn relative to, in this case our screen center.
    % And set anti-aliasing to 1. This gives use smooth dots. If you use 0
    % instead you will get squares. And if you use 2 you will get nicer
    % anti-aliasing of the dots.
    Screen('DrawDots', window, [xpos; ypos], dotSizePixels, white, center, 1);

    % Flip to the screen
    vbl = Screen('Flip', window, vbl + (waitframes - 0.5) * ifi);

    % Increment the angle of the dots by one degree per frame
    angles = angles + 1;
        % Check for keyboard input
    [keyIsDown, ~, keyCode] = KbCheck;
    if keyIsDown
        if keyCode(KbName('ESCAPE')) || keyCode(KbName('q'))
            break;
        end
    end

end
```

**Comment by kleinerm** [comment]
You can also use RestrictKeysForKbCheck() to only allow certain keys to be reported by KbCheck. E.g.,
``RestrictKeysForKbCheck([KbName('ESCAPE')), keyCode(KbName('q')]); would only allow KbCheck to respond to ESCAPE and q, but ignore any other - potentially stuck and unwanted or accidentally pressed - keys.

Closing this as resolved.
