### ISSUE TITLE
Codecs in VideoRecordingDemo not working on Linux

### ISSUE THREAD

**Issue by inichoso** [Psychtoolbox-3/Psychtoolbox-3#845]
**Comercial support token: 6R7X549H-202481111018:8517f9148012534acf6ae04e29b2b28cd5325a8e4a6cd5177b90073e7fc10268

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 22.04 
 - Runtime: Matlab R2022b
 - Hardware: Radeon RX 6900 XT
 - Version: Psychtoolbox 3.0.19

**Describe the bug**
I am trying to run the VideoRecordingDemo script on a Linux PC but every codec I've tried produces an unplayable video. I have tried to run this script with both a USB MR safe camera (MRC systems 12M camera [https://www.mrc-systems.de/en/products/mr-compatible-cameras]) and a Logitech webcam. Both cameras can provide a video feed and record videos with no issue using VLC. However with the VideoRecordingDemo script, regardless of the camera used, when I run the script without specifying a codec (i.e. using the Linux system default), the script quits out immediately without displaying a camera feed or saving a video. When I run the script while specifying one of the “good” codecs (i.e. avenc_mpeg4, x264enc, VideoCodec=x264enc speed-preset=1, Keyframe=60 Videobitrate=8192), I get a video feed and a video is saved. However when I try to play back the video I recorded, I get the error message “The playback of the movie requires a ITU H.264 (High 4:2:2 Profile) recorder plugin which is not installed”. Linux then directs me to download GStreamer which I already have downloaded on the system and have already tried updating and reinstalling  multiple times as a trouble-shooting measure.

**Additional context**
I have also tried running this script on two difference Linux PC's running Ubuntu 20.04 as well as a Linux laptop also running Ubuntu 20.04 and run into the same errors listed above regardless. I also get the same exact issues regardless of using the MRC systems camera or the Logitech camera and both camera's can successfully record playable video through VLC.

**Comment by kleinerm** [comment]
Handled on user forum, see:
https://psychtoolbox.discourse.group/t/codecs-in-videorecordingdemo-not-working-on-linux/5441/2?u=mariokleiner

Closing here.
