### ISSUE TITLE
`DrawFormattedText` does not display unicode character

### ISSUE THREAD

**Issue by chanyca** [Psychtoolbox-3/Psychtoolbox-3#847]
I tried to draw an up-pointing triangle (unicode: 9651) using `DrawFormattedText` and encountered the following error:

> PTB-INFO: ==============================================================================================================================
INTERNAL PSYCHTOOLBOX ERROR
	error:                PsychError_internal
	general description:  Unspecified error, probably a Psychtoolbox bug
	specific description: mxGetString failed to get the string
	module name:          Screen
	subfunction call:     TextBounds
	file name:            C:\Users\Mario Kleiner\Documents\GitHub\Psychtoolbox-3\PsychSourceGL\Source\Common\Base\PsychScriptingGlueMatlab.c
	function name:        PsychAllocInCharArg
	line number:          1596
>  
> WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 1).
WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.
WARNING: This session of your experiment was run by you with the setting Screen('Preference', 'SkipSyncTests', 1).
WARNING: This means that some internal self-tests and calibrations were skipped. Your stimulus presentation timing
WARNING: may have been wrong. This is fine for development and debugging of your experiment, but for running the real
WARNING: study, please make sure to set Screen('Preference', 'SkipSyncTests', 0) for maximum accuracy and reliability.
>
> Error using Screen
> See error message printed above.
> 
> Error in DrawFormattedText (line 293)
>     theight = RectHeight(Screen('TextBounds', win, tstring));
> 
> Error in draw_bs_flash (line 56)
>     DrawFormattedText(window, target, flashes(f,1)-deg.half, flashes(f,2)+deg.half, lineColor);`

Where I defined my target as `target = char(9651);`

**Desktop:**
 - OS: Windows 11 23H2
 - Runtime: Matlab R2023b
 - Hardware: AMD Radeon RX 6700 XT
 - Version: Psychtoolbox 3.0.19

**Comment by dcnieho** [comment]
non-ascii characters should be passed a double() of the character (array).
As shown in the demos
