### ISSUE TITLE
Error On Psychtoolbox on R20204b 

### ISSUE THREAD

**Issue by hturroserrano** [Psychtoolbox-3/Psychtoolbox-3#853]
**[For commercial support for bug reports, click this link](https://www.psychtoolbox.net/license-key)**

**Describe the bug**
When Installing apple sillicon version of MATLAB, it prevents access from using psychtoolbox with this error:

In place of the expected mex file this placeholder file was executed:

  Screen

This mex file seems to be missing or inaccessible on your Matlab path or it is dysfunctional:

  Screen.mexmaca64

Hmm. I cannot find the file on your Matlab path?!?

One reason could be that your Matlab path is wrong or not up to date
for the current Psychtoolbox. You may want to run SetupPsychtoolbox to 
fix possible path problems.

NOTE: You may want to acquire paid support for future issues like this.
Please type 'PsychPaidSupportAndServices' to learn more.

There is also this error that happens:

Error using SetupPsychtoolbox
You need to change your working directory to the Psychtoolbox folder before running
this routine!

I believe that this is an issue with the new update with the macOS Sequoia 15.1 cause I believe everyone is having the same issue with Psychtoolbox

**Comment by kleinerm** [comment]
Psychtoolbox is not supposed to work on Apple Silicon Macs, so this behavior is exactly as intended.

We will soon, within weeks from now, release Psychtoolbox 3.0.20, which will have proper Apple Silicon Support, but will require a yearly paid license. Watch the user forum or news section of our website for updates.
