### ISSUE TITLE
Full compatibility with Apple Silicon MacBooks

### ISSUE THREAD

**Issue by desy329** [Psychtoolbox-3/Psychtoolbox-3#854]
Dear developers,

I have just tried to install Psychtoolbox-3 following the guidelines provided on our website. However, I got the following error _Psychtoolbox does not yet work on native Matlab or Octave for Apple Silicon Macs with 64-Bit ARM architecture._ Considering that Matlab is now fully compatible with Apple Silicon MacBooks, can you please tell me if and when Psychtoolbox will be compatible with Apple Silicon MacBooks?

Thank you in advance for your help.

Best wishes,
Desi

**Comment by kleinerm** [comment]
Dear Desi

Now! At least as a beta.  https://psychtoolbox.discourse.group/t/psychtoolbox-3-0-20-0-release-appletizer/5590
